import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { stripTypeScriptTypes } from "node:module";
import test from "node:test";

import ts from "typescript";

import { hardenGeneratedParams } from "./harden-generated-params.mjs";

const upstream =
  "// This file is auto-generated by @hey-api/openapi-ts\n\n" +
  readFileSync(
    new URL(
      "../node_modules/@hey-api/openapi-ts/dist/clients/core/params.ts",
      import.meta.url,
    ),
    "utf8",
  ).replaceAll("\r\n", "\n");
const generated = readFileSync(
  new URL("../generated/typescript/core/params.gen.ts", import.meta.url),
  "utf8",
).replaceAll("\r\n", "\n");
const { buildClientParams } = await loadRuntime(generated);
const baseline = (await loadRuntime(upstream)).buildClientParams;
const slots = ["body", "headers", "path", "query"];
const dangerousKeys = ["__proto__", "constructor", "prototype"];

async function loadRuntime(source) {
  const javascript = stripTypeScriptTypes(source);
  return import(
    `data:text/javascript;base64,${Buffer.from(javascript).toString("base64")}`
  );
}

test("the pinned generator template is hardened reproducibly and fails closed on drift", () => {
  const manifest = JSON.parse(
    readFileSync(new URL("../package.json", import.meta.url), "utf8"),
  );
  assert.equal(manifest.devDependencies["@hey-api/openapi-ts"], "0.99.0");
  assert.equal(generated, hardenGeneratedParams(upstream));
  assert.equal(
    generated,
    hardenGeneratedParams(upstream.replaceAll("\n", "\r\n")),
  );
  for (const mutated of [
    upstream + "\n",
    upstream.replace("record[key] = value;", "record[key] ??= value;"),
    upstream.replace(
      "params[field.map] = value;",
      "params[field.map] = { value };",
    ),
    upstream.replace("Object.create(null)", "{}"),
    generated,
  ]) {
    assert.throws(
      () => hardenGeneratedParams(mutated),
      /security review required/,
    );
  }
});

for (const slot of slots) {
  test(`${slot}: reproduced upstream aggregate substitution is rejected without caller mutation`, () => {
    const input = JSON.parse(
      `{"payload":{"safe":"original"},"$${slot}___proto__":{"fixtureMarker":true}}`,
    );
    const config = [{ args: [{ key: "payload", map: slot }] }];
    const result = baseline([input], config);
    assert.equal(Object.getPrototypeOf(result[slot]).fixtureMarker, true);
    assert.equal(result[slot], input.payload);
    assert.equal(Object.prototype.fixtureMarker, undefined);

    const clean = JSON.parse(
      `{"payload":{"safe":"original"},"$${slot}_safe":"modified","$${slot}___proto__":{"fixtureMarker":true}}`,
    );
    assert.throws(
      () => buildClientParams([clean], config),
      /Invalid client parameter key/,
    );
    assert.equal(Object.getPrototypeOf(clean.payload), Object.prototype);
    assert.deepEqual(clean.payload, { safe: "original" });
    assert.equal(Object.prototype.fixtureMarker, undefined);
  });

  test(`${slot}: fresh and mapped records reject every dangerous destination and JSON value shape`, () => {
    for (const key of dangerousKeys) {
      for (const value of [
        { fixtureMarker: true },
        "literal JSON data",
        null,
      ]) {
        for (const mapped of [false, true]) {
          const caller = { keep: "original" };
          const input = JSON.parse(
            JSON.stringify({ [`$${slot}_${key}`]: value }),
          );
          if (mapped) input.payload = caller;
          // Aggregate assignment must precede the extra key, as it would for a
          // whole-body/slot object followed by ordinary caller options.
          const ordered = mapped ? { payload: caller, ...input } : input;
          assert.throws(
            () =>
              buildClientParams(
                [ordered],
                [{ args: mapped ? [{ key: "payload", map: slot }] : [] }],
              ),
            /Invalid client parameter key/,
          );
          assert.deepEqual(caller, { keep: "original" });
          assert.equal(Object.getPrototypeOf(caller), Object.prototype);
          assert.equal(Object.prototype.fixtureMarker, undefined);
        }
        assert.throws(
          () => buildClientParams([value], [{ in: slot, key }]),
          /Invalid client parameter key/,
        );
        assert.throws(
          () =>
            buildClientParams([value], [{ in: slot, key: "safe", map: key }]),
          /Invalid client parameter key/,
        );
        const rawKeyInput = JSON.parse(`{"${key}":"literal JSON data"}`);
        assert.throws(
          () =>
            buildClientParams(
              [rawKeyInput],
              [{ allowExtra: { [slot]: true } }],
            ),
          /Invalid client parameter key/,
        );
      }
    }
  });

  test(`${slot}: ordinary field writes use owned null-prototype records`, () => {
    for (const caller of [
      { keep: "original" },
      Object.assign(Object.create(null), { keep: "original" }),
    ]) {
      const prototype = Object.getPrototypeOf(caller);
      const result = buildClientParams(
        [{ payload: caller, [`$${slot}_extra`]: "new" }],
        [{ args: [{ key: "payload", map: slot }] }],
      );
      assert.equal(Object.getPrototypeOf(result[slot]), null);
      assert.notEqual(result[slot], caller);
      assert.equal(result[slot].keep, "original");
      assert.equal(result[slot].extra, "new");
      assert.deepEqual(Object.keys(caller), ["keep"]);
      assert.equal(Object.getPrototypeOf(caller), prototype);
    }
    const fresh = buildClientParams(
      [{ [`$${slot}_safe`]: "value" }],
      [{ args: [] }],
    );
    assert.equal(Object.getPrototypeOf(fresh[slot]), null);
    assert.equal(fresh[slot].safe, "value");
  });
}

test("actual slot names are checked before aggregate and field writes", () => {
  for (const slot of [...dangerousKeys, "other", "toString", "", null, 7]) {
    const caller = { keep: "original" };
    const attempts = [
      () =>
        buildClientParams(
          [{ payload: caller }],
          [{ args: [{ key: "payload", map: slot }] }],
        ),
      () =>
        buildClientParams(
          [{ safe: "value" }],
          [{ allowExtra: { [slot]: true } }],
        ),
    ];
    // A falsy malformed `in` produces no field write in upstream dispatch.
    if (slot)
      attempts.push(() =>
        buildClientParams(["value"], [{ in: slot, key: "safe" }]),
      );
    for (const run of attempts) {
      assert.throws(run, /Invalid client parameter slot/);
      assert.deepEqual(caller, { keep: "original" });
      assert.equal(Object.getPrototypeOf(caller), Object.prototype);
    }
  }
  const caller = { keep: "original" };
  assert.throws(
    () =>
      buildClientParams(
        [{ body: caller, $body_safe: "new", bad: "value" }],
        [
          {
            args: [
              { key: "body", map: "body" },
              { key: "bad", map: "__proto__" },
            ],
          },
        ],
      ),
    /Invalid client parameter slot/,
  );
  assert.deepEqual(caller, { keep: "original" });
});

test("slot selectors never perform computed reads or writes on the outer params object", () => {
  const source = ts.createSourceFile(
    "params.gen.ts",
    generated,
    ts.ScriptTarget.Latest,
    true,
  );
  const computedAccesses = [];
  function visit(node) {
    if (
      ts.isElementAccessExpression(node) &&
      ts.isIdentifier(node.expression) &&
      node.expression.text === "params" &&
      !ts.isDeleteExpression(node.parent)
    ) {
      computedAccesses.push(node.getStart(source));
    }
    ts.forEachChild(node, visit);
  }
  visit(source);
  // stripEmptySlots may delete an enumerated own property; library selectors
  // must only reach the explicit literal read/replacement switches.
  assert.deepEqual(computedAccesses, []);
});

test("literal slot access preserves outer descriptors and repeated aggregate ownership", () => {
  for (const slot of slots) {
    const first = { first: "original" };
    const second = { second: "original" };
    const result = buildClientParams(
      [
        { payload: first, [`$${slot}_extra`]: "discarded" },
        { payload: second, [`$${slot}_extra`]: "kept" },
      ],
      [{ args: [{ key: "payload", map: slot }] }],
    );
    assert.equal(Object.getPrototypeOf(result), Object.prototype);
    assert.deepEqual(Object.keys(result), [slot]);
    const descriptor = Object.getOwnPropertyDescriptor(result, slot);
    assert.equal(descriptor.enumerable, true);
    assert.equal(descriptor.writable, true);
    assert.equal(descriptor.configurable, true);
    assert.equal(descriptor.value, result[slot]);
    assert.equal(Object.getPrototypeOf(result[slot]), null);
    assert.deepEqual(Object.entries(result[slot]), [
      ["second", "original"],
      ["extra", "kept"],
    ]);
    assert.deepEqual(first, { first: "original" });
    assert.deepEqual(second, { second: "original" });
  }
});

test("runtime slot validation never coerces a non-string selector", () => {
  let coercions = 0;
  const invalidSlot = {
    [Symbol.toPrimitive]() {
      coercions += 1;
      return "body";
    },
  };
  const caller = { safe: "original" };
  assert.throws(
    () =>
      buildClientParams(
        [{ payload: caller }],
        [{ args: [{ key: "payload", map: invalidSlot }] }],
      ),
    /Invalid client parameter slot/,
  );
  assert.throws(
    () => buildClientParams(["value"], [{ in: invalidSlot, key: "safe" }]),
    /Invalid client parameter slot/,
  );
  assert.equal(coercions, 0);
  assert.deepEqual(caller, { safe: "original" });
});

test("whole-body values remain untouched without per-field writes", () => {
  const form = new FormData();
  form.set("safe", "value");
  for (const body of [
    null,
    false,
    42,
    "body",
    [1, 2],
    { safe: "value" },
    form,
  ]) {
    assert.equal(buildClientParams([body], [{ in: "body" }]).body, body);
    assert.equal(
      buildClientParams(
        [{ payload: body }],
        [{ args: [{ key: "payload", map: "body" }] }],
      ).body,
      body,
    );
    if (
      body === null ||
      typeof body !== "object" ||
      Array.isArray(body) ||
      body === form
    ) {
      assert.throws(
        () =>
          buildClientParams(
            [body, { $body_extra: "new" }],
            [{ in: "body" }, { args: [] }],
          ),
        /plain record/,
      );
    }
  }
});

test("ordinary aliases, extra slots and body JSON retain serialization semantics", () => {
  const fields = [
    {
      args: [
        { key: "body", map: "body" },
        { in: "headers", key: "contentType", map: "Content-Type" },
        { in: "path", key: "identifier", map: "id" },
        { in: "query", key: "page" },
      ],
    },
  ];
  const input = {
    body: { title: "value" },
    contentType: "application/json",
    identifier: "fixture",
    page: 2,
    $query_sort: "asc",
  };
  assert.equal(
    JSON.stringify(buildClientParams([input], fields)),
    JSON.stringify(baseline([input], fields)),
  );
  const ordinaryJSON = JSON.parse(
    '{"__proto__":"literal data","constructor":"field","prototype":"field"}',
  );
  assert.equal(
    buildClientParams([ordinaryJSON], [{ in: "body" }]).body,
    ordinaryJSON,
  );
  assert.equal(Object.getPrototypeOf(ordinaryJSON), Object.prototype);
  assert.deepEqual(buildClientParams([], []), {});
});
