// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alerts.sql

package dbsql

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTenantAlertAsHuman = `-- name: CreateTenantAlertAsHuman :one
SELECT created.id::uuid AS id,
       created.number::text AS number,
       created.workflow_id::uuid AS workflow_id,
       created.workflow_version::integer AS workflow_version,
       created.state_key::text AS state_key,
       created.customer_visible::boolean AS customer_visible,
       (created.external_id IS NOT NULL)::boolean AS has_external_id,
       coalesce(created.external_id::text, '')::text AS external_id,
       (created.deduplication_key IS NOT NULL)::boolean AS has_deduplication_key,
       coalesce(created.deduplication_key::text, '')::text AS deduplication_key,
       created.title::text AS title,
       (created.description IS NOT NULL)::boolean AS has_description,
       coalesce(created.description::text, '')::text AS description,
       created.status::text AS status,
       created.severity::text AS severity,
       created.priority::text AS priority,
       created.category::text AS category,
       (created.classification IS NOT NULL)::boolean AS has_classification,
       coalesce(created.classification::text, '')::text AS classification,
       created.source::text AS source,
       created.source_type::text AS source_type,
       created.tags::text[] AS tags,
       created.custom_fields::jsonb AS custom_fields,
       created.customer_custom_fields::jsonb AS customer_custom_fields,
       created.raw_payload::jsonb AS raw_payload,
       created.assigned_team_id::uuid AS assigned_team_id,
       created.assignee_user_id::uuid AS assignee_user_id,
       created.claimed_by_user_id::uuid AS claimed_by_user_id,
       created.created_by_user_id::uuid AS created_by_user_id,
       created.created_by_membership_id::uuid AS created_by_membership_id,
       created.created_by_service_account_id::uuid AS created_by_service_account_id,
       created.detected_at::timestamptz AS detected_at,
       created.received_at::timestamptz AS received_at,
       created.acknowledged_at::timestamptz AS acknowledged_at,
       created.closed_at::timestamptz AS closed_at,
       created.assigned_at::timestamptz AS assigned_at,
       created.first_response_at::timestamptz AS first_response_at,
       created.resolved_at::timestamptz AS resolved_at,
       created.claimed_at::timestamptz AS claimed_at,
       created.created_at::timestamptz AS created_at,
       created.updated_at::timestamptz AS updated_at,
       created.version::integer AS version,
       created.replayed::boolean AS replayed
FROM app.create_tenant_alert_as_human_v3(
  $1::text,
  $2::text,
  $3::text,
  $4::alert_severity,
  $5::text,
  $6::text,
  $7::text,
  $8::jsonb,
  $9::text,
  $10::text,
  $11::text,
  $12::timestamptz,
  $13::boolean,
  $14::text[],
  $15::jsonb,
  $16::uuid,
  $17::uuid,
  $18::uuid,
  $19::bytea,
  $20::bytea,
  $21::uuid,
  $22::uuid,
  $23::inet,
  nullif($24::text, ''),
  $25::text,
  $26::text,
  $27::text
) AS created(
  id, number, workflow_id, workflow_version, state_key, customer_visible,
  external_id, deduplication_key, title, description, status, severity,
  priority, category, classification, source, source_type, tags, custom_fields,
  customer_custom_fields, raw_payload, assigned_team_id, assignee_user_id,
  claimed_by_user_id, created_by_user_id, created_by_membership_id,
  created_by_service_account_id, detected_at, received_at, acknowledged_at,
  closed_at, assigned_at, first_response_at, resolved_at, claimed_at,
  created_at, updated_at, version, replayed
)
`

type CreateTenantAlertAsHumanParams struct {
	Title                string             `db:"title" json:"title"`
	Description          *string            `db:"description" json:"description"`
	ExternalID           *string            `db:"external_id" json:"external_id"`
	Severity             AlertSeverity      `db:"severity" json:"severity"`
	Source               string             `db:"source" json:"source"`
	SourceType           string             `db:"source_type" json:"source_type"`
	DeduplicationKey     *string            `db:"deduplication_key" json:"deduplication_key"`
	RawPayload           []byte             `db:"raw_payload" json:"raw_payload"`
	Priority             string             `db:"priority" json:"priority"`
	Category             string             `db:"category" json:"category"`
	Classification       *string            `db:"classification" json:"classification"`
	DetectedAt           pgtype.Timestamptz `db:"detected_at" json:"detected_at"`
	CustomerVisible      bool               `db:"customer_visible" json:"customer_visible"`
	Tags                 []string           `db:"tags" json:"tags"`
	CustomFields         []byte             `db:"custom_fields" json:"custom_fields"`
	WorkflowID           pgtype.UUID        `db:"workflow_id" json:"workflow_id"`
	AssignedTeamID       pgtype.UUID        `db:"assigned_team_id" json:"assigned_team_id"`
	AssigneeUserID       pgtype.UUID        `db:"assignee_user_id" json:"assignee_user_id"`
	KeyDigest            []byte             `db:"key_digest" json:"key_digest"`
	RequestDigest        []byte             `db:"request_digest" json:"request_digest"`
	RequestID            pgtype.UUID        `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID        `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr         `db:"ip_address" json:"ip_address"`
	UserAgent            string             `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string             `db:"authentication_method" json:"authentication_method"`
	Traceparent          *string            `db:"traceparent" json:"traceparent"`
	Tracestate           *string            `db:"tracestate" json:"tracestate"`
}

type CreateTenantAlertAsHumanRow struct {
	ID                        pgtype.UUID        `db:"id" json:"id"`
	Number                    string             `db:"number" json:"number"`
	WorkflowID                pgtype.UUID        `db:"workflow_id" json:"workflow_id"`
	WorkflowVersion           int32              `db:"workflow_version" json:"workflow_version"`
	StateKey                  string             `db:"state_key" json:"state_key"`
	CustomerVisible           bool               `db:"customer_visible" json:"customer_visible"`
	HasExternalID             bool               `db:"has_external_id" json:"has_external_id"`
	ExternalID                string             `db:"external_id" json:"external_id"`
	HasDeduplicationKey       bool               `db:"has_deduplication_key" json:"has_deduplication_key"`
	DeduplicationKey          string             `db:"deduplication_key" json:"deduplication_key"`
	Title                     string             `db:"title" json:"title"`
	HasDescription            bool               `db:"has_description" json:"has_description"`
	Description               string             `db:"description" json:"description"`
	Status                    string             `db:"status" json:"status"`
	Severity                  string             `db:"severity" json:"severity"`
	Priority                  string             `db:"priority" json:"priority"`
	Category                  string             `db:"category" json:"category"`
	HasClassification         bool               `db:"has_classification" json:"has_classification"`
	Classification            string             `db:"classification" json:"classification"`
	Source                    string             `db:"source" json:"source"`
	SourceType                string             `db:"source_type" json:"source_type"`
	Tags                      []string           `db:"tags" json:"tags"`
	CustomFields              []byte             `db:"custom_fields" json:"custom_fields"`
	CustomerCustomFields      []byte             `db:"customer_custom_fields" json:"customer_custom_fields"`
	RawPayload                []byte             `db:"raw_payload" json:"raw_payload"`
	AssignedTeamID            pgtype.UUID        `db:"assigned_team_id" json:"assigned_team_id"`
	AssigneeUserID            pgtype.UUID        `db:"assignee_user_id" json:"assignee_user_id"`
	ClaimedByUserID           pgtype.UUID        `db:"claimed_by_user_id" json:"claimed_by_user_id"`
	CreatedByUserID           pgtype.UUID        `db:"created_by_user_id" json:"created_by_user_id"`
	CreatedByMembershipID     pgtype.UUID        `db:"created_by_membership_id" json:"created_by_membership_id"`
	CreatedByServiceAccountID pgtype.UUID        `db:"created_by_service_account_id" json:"created_by_service_account_id"`
	DetectedAt                pgtype.Timestamptz `db:"detected_at" json:"detected_at"`
	ReceivedAt                pgtype.Timestamptz `db:"received_at" json:"received_at"`
	AcknowledgedAt            pgtype.Timestamptz `db:"acknowledged_at" json:"acknowledged_at"`
	ClosedAt                  pgtype.Timestamptz `db:"closed_at" json:"closed_at"`
	AssignedAt                pgtype.Timestamptz `db:"assigned_at" json:"assigned_at"`
	FirstResponseAt           pgtype.Timestamptz `db:"first_response_at" json:"first_response_at"`
	ResolvedAt                pgtype.Timestamptz `db:"resolved_at" json:"resolved_at"`
	ClaimedAt                 pgtype.Timestamptz `db:"claimed_at" json:"claimed_at"`
	CreatedAt                 pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Version                   int32              `db:"version" json:"version"`
	Replayed                  bool               `db:"replayed" json:"replayed"`
}

func (q *Queries) CreateTenantAlertAsHuman(ctx context.Context, arg CreateTenantAlertAsHumanParams) (*CreateTenantAlertAsHumanRow, error) {
	row := q.db.QueryRow(ctx, createTenantAlertAsHuman,
		arg.Title,
		arg.Description,
		arg.ExternalID,
		arg.Severity,
		arg.Source,
		arg.SourceType,
		arg.DeduplicationKey,
		arg.RawPayload,
		arg.Priority,
		arg.Category,
		arg.Classification,
		arg.DetectedAt,
		arg.CustomerVisible,
		arg.Tags,
		arg.CustomFields,
		arg.WorkflowID,
		arg.AssignedTeamID,
		arg.AssigneeUserID,
		arg.KeyDigest,
		arg.RequestDigest,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
		arg.Traceparent,
		arg.Tracestate,
	)
	var i CreateTenantAlertAsHumanRow
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.WorkflowID,
		&i.WorkflowVersion,
		&i.StateKey,
		&i.CustomerVisible,
		&i.HasExternalID,
		&i.ExternalID,
		&i.HasDeduplicationKey,
		&i.DeduplicationKey,
		&i.Title,
		&i.HasDescription,
		&i.Description,
		&i.Status,
		&i.Severity,
		&i.Priority,
		&i.Category,
		&i.HasClassification,
		&i.Classification,
		&i.Source,
		&i.SourceType,
		&i.Tags,
		&i.CustomFields,
		&i.CustomerCustomFields,
		&i.RawPayload,
		&i.AssignedTeamID,
		&i.AssigneeUserID,
		&i.ClaimedByUserID,
		&i.CreatedByUserID,
		&i.CreatedByMembershipID,
		&i.CreatedByServiceAccountID,
		&i.DetectedAt,
		&i.ReceivedAt,
		&i.AcknowledgedAt,
		&i.ClosedAt,
		&i.AssignedAt,
		&i.FirstResponseAt,
		&i.ResolvedAt,
		&i.ClaimedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.Replayed,
	)
	return &i, err
}

const createTenantAlertAsServiceAccount = `-- name: CreateTenantAlertAsServiceAccount :one
SELECT created.id::uuid AS id,
       created.number::text AS number,
       created.workflow_id::uuid AS workflow_id,
       created.workflow_version::integer AS workflow_version,
       created.state_key::text AS state_key,
       created.customer_visible::boolean AS customer_visible,
       (created.external_id IS NOT NULL)::boolean AS has_external_id,
       coalesce(created.external_id::text, '')::text AS external_id,
       (created.deduplication_key IS NOT NULL)::boolean AS has_deduplication_key,
       coalesce(created.deduplication_key::text, '')::text AS deduplication_key,
       created.title::text AS title,
       (created.description IS NOT NULL)::boolean AS has_description,
       coalesce(created.description::text, '')::text AS description,
       created.status::text AS status,
       created.severity::text AS severity,
       created.priority::text AS priority,
       created.category::text AS category,
       (created.classification IS NOT NULL)::boolean AS has_classification,
       coalesce(created.classification::text, '')::text AS classification,
       created.source::text AS source,
       created.source_type::text AS source_type,
       created.tags::text[] AS tags,
       created.custom_fields::jsonb AS custom_fields,
       created.customer_custom_fields::jsonb AS customer_custom_fields,
       created.raw_payload::jsonb AS raw_payload,
       created.assigned_team_id::uuid AS assigned_team_id,
       created.assignee_user_id::uuid AS assignee_user_id,
       created.claimed_by_user_id::uuid AS claimed_by_user_id,
       created.created_by_user_id::uuid AS created_by_user_id,
       created.created_by_membership_id::uuid AS created_by_membership_id,
       created.created_by_service_account_id::uuid AS created_by_service_account_id,
       created.detected_at::timestamptz AS detected_at,
       created.received_at::timestamptz AS received_at,
       created.acknowledged_at::timestamptz AS acknowledged_at,
       created.closed_at::timestamptz AS closed_at,
       created.assigned_at::timestamptz AS assigned_at,
       created.first_response_at::timestamptz AS first_response_at,
       created.resolved_at::timestamptz AS resolved_at,
       created.claimed_at::timestamptz AS claimed_at,
       created.created_at::timestamptz AS created_at,
       created.updated_at::timestamptz AS updated_at,
       created.version::integer AS version,
       created.replayed::boolean AS replayed
FROM app.create_tenant_alert_as_service_account_v3(
  $1::uuid,
  $2::bytea,
  $3::integer,
  $4::bytea,
  $5::inet,
  $6::text,
  $7::text,
  $8::text,
  $9::alert_severity,
  $10::text,
  $11::text,
  $12::text,
  $13::jsonb,
  $14::text,
  $15::text,
  $16::text,
  $17::timestamptz,
  $18::boolean,
  $19::text[],
  $20::jsonb,
  $21::uuid,
  $22::uuid,
  $23::uuid,
  $24::bytea,
  $25::bytea,
  $26::uuid,
  $27::uuid,
  nullif($28::text, ''),
  $29::text,
  $30::text
) AS created(
  id, number, workflow_id, workflow_version, state_key, customer_visible,
  external_id, deduplication_key, title, description, status, severity,
  priority, category, classification, source, source_type, tags, custom_fields,
  customer_custom_fields, raw_payload, assigned_team_id, assignee_user_id,
  claimed_by_user_id, created_by_user_id, created_by_membership_id,
  created_by_service_account_id, detected_at, received_at, acknowledged_at,
  closed_at, assigned_at, first_response_at, resolved_at, claimed_at,
  created_at, updated_at, version, replayed
)
`

type CreateTenantAlertAsServiceAccountParams struct {
	TenantID           pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	Locator            []byte             `db:"locator" json:"locator"`
	EnvelopeKeyVersion int32              `db:"envelope_key_version" json:"envelope_key_version"`
	SecretDigest       []byte             `db:"secret_digest" json:"secret_digest"`
	ClientAddress      netip.Addr         `db:"client_address" json:"client_address"`
	Title              string             `db:"title" json:"title"`
	Description        *string            `db:"description" json:"description"`
	ExternalID         *string            `db:"external_id" json:"external_id"`
	Severity           AlertSeverity      `db:"severity" json:"severity"`
	Source             string             `db:"source" json:"source"`
	SourceType         string             `db:"source_type" json:"source_type"`
	DeduplicationKey   *string            `db:"deduplication_key" json:"deduplication_key"`
	RawPayload         []byte             `db:"raw_payload" json:"raw_payload"`
	Priority           string             `db:"priority" json:"priority"`
	Category           string             `db:"category" json:"category"`
	Classification     *string            `db:"classification" json:"classification"`
	DetectedAt         pgtype.Timestamptz `db:"detected_at" json:"detected_at"`
	CustomerVisible    bool               `db:"customer_visible" json:"customer_visible"`
	Tags               []string           `db:"tags" json:"tags"`
	CustomFields       []byte             `db:"custom_fields" json:"custom_fields"`
	WorkflowID         pgtype.UUID        `db:"workflow_id" json:"workflow_id"`
	AssignedTeamID     pgtype.UUID        `db:"assigned_team_id" json:"assigned_team_id"`
	AssigneeUserID     pgtype.UUID        `db:"assignee_user_id" json:"assignee_user_id"`
	KeyDigest          []byte             `db:"key_digest" json:"key_digest"`
	RequestDigest      []byte             `db:"request_digest" json:"request_digest"`
	RequestID          pgtype.UUID        `db:"request_id" json:"request_id"`
	CorrelationID      pgtype.UUID        `db:"correlation_id" json:"correlation_id"`
	UserAgent          string             `db:"user_agent" json:"user_agent"`
	Traceparent        *string            `db:"traceparent" json:"traceparent"`
	Tracestate         *string            `db:"tracestate" json:"tracestate"`
}

type CreateTenantAlertAsServiceAccountRow struct {
	ID                        pgtype.UUID        `db:"id" json:"id"`
	Number                    string             `db:"number" json:"number"`
	WorkflowID                pgtype.UUID        `db:"workflow_id" json:"workflow_id"`
	WorkflowVersion           int32              `db:"workflow_version" json:"workflow_version"`
	StateKey                  string             `db:"state_key" json:"state_key"`
	CustomerVisible           bool               `db:"customer_visible" json:"customer_visible"`
	HasExternalID             bool               `db:"has_external_id" json:"has_external_id"`
	ExternalID                string             `db:"external_id" json:"external_id"`
	HasDeduplicationKey       bool               `db:"has_deduplication_key" json:"has_deduplication_key"`
	DeduplicationKey          string             `db:"deduplication_key" json:"deduplication_key"`
	Title                     string             `db:"title" json:"title"`
	HasDescription            bool               `db:"has_description" json:"has_description"`
	Description               string             `db:"description" json:"description"`
	Status                    string             `db:"status" json:"status"`
	Severity                  string             `db:"severity" json:"severity"`
	Priority                  string             `db:"priority" json:"priority"`
	Category                  string             `db:"category" json:"category"`
	HasClassification         bool               `db:"has_classification" json:"has_classification"`
	Classification            string             `db:"classification" json:"classification"`
	Source                    string             `db:"source" json:"source"`
	SourceType                string             `db:"source_type" json:"source_type"`
	Tags                      []string           `db:"tags" json:"tags"`
	CustomFields              []byte             `db:"custom_fields" json:"custom_fields"`
	CustomerCustomFields      []byte             `db:"customer_custom_fields" json:"customer_custom_fields"`
	RawPayload                []byte             `db:"raw_payload" json:"raw_payload"`
	AssignedTeamID            pgtype.UUID        `db:"assigned_team_id" json:"assigned_team_id"`
	AssigneeUserID            pgtype.UUID        `db:"assignee_user_id" json:"assignee_user_id"`
	ClaimedByUserID           pgtype.UUID        `db:"claimed_by_user_id" json:"claimed_by_user_id"`
	CreatedByUserID           pgtype.UUID        `db:"created_by_user_id" json:"created_by_user_id"`
	CreatedByMembershipID     pgtype.UUID        `db:"created_by_membership_id" json:"created_by_membership_id"`
	CreatedByServiceAccountID pgtype.UUID        `db:"created_by_service_account_id" json:"created_by_service_account_id"`
	DetectedAt                pgtype.Timestamptz `db:"detected_at" json:"detected_at"`
	ReceivedAt                pgtype.Timestamptz `db:"received_at" json:"received_at"`
	AcknowledgedAt            pgtype.Timestamptz `db:"acknowledged_at" json:"acknowledged_at"`
	ClosedAt                  pgtype.Timestamptz `db:"closed_at" json:"closed_at"`
	AssignedAt                pgtype.Timestamptz `db:"assigned_at" json:"assigned_at"`
	FirstResponseAt           pgtype.Timestamptz `db:"first_response_at" json:"first_response_at"`
	ResolvedAt                pgtype.Timestamptz `db:"resolved_at" json:"resolved_at"`
	ClaimedAt                 pgtype.Timestamptz `db:"claimed_at" json:"claimed_at"`
	CreatedAt                 pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Version                   int32              `db:"version" json:"version"`
	Replayed                  bool               `db:"replayed" json:"replayed"`
}

func (q *Queries) CreateTenantAlertAsServiceAccount(ctx context.Context, arg CreateTenantAlertAsServiceAccountParams) (*CreateTenantAlertAsServiceAccountRow, error) {
	row := q.db.QueryRow(ctx, createTenantAlertAsServiceAccount,
		arg.TenantID,
		arg.Locator,
		arg.EnvelopeKeyVersion,
		arg.SecretDigest,
		arg.ClientAddress,
		arg.Title,
		arg.Description,
		arg.ExternalID,
		arg.Severity,
		arg.Source,
		arg.SourceType,
		arg.DeduplicationKey,
		arg.RawPayload,
		arg.Priority,
		arg.Category,
		arg.Classification,
		arg.DetectedAt,
		arg.CustomerVisible,
		arg.Tags,
		arg.CustomFields,
		arg.WorkflowID,
		arg.AssignedTeamID,
		arg.AssigneeUserID,
		arg.KeyDigest,
		arg.RequestDigest,
		arg.RequestID,
		arg.CorrelationID,
		arg.UserAgent,
		arg.Traceparent,
		arg.Tracestate,
	)
	var i CreateTenantAlertAsServiceAccountRow
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.WorkflowID,
		&i.WorkflowVersion,
		&i.StateKey,
		&i.CustomerVisible,
		&i.HasExternalID,
		&i.ExternalID,
		&i.HasDeduplicationKey,
		&i.DeduplicationKey,
		&i.Title,
		&i.HasDescription,
		&i.Description,
		&i.Status,
		&i.Severity,
		&i.Priority,
		&i.Category,
		&i.HasClassification,
		&i.Classification,
		&i.Source,
		&i.SourceType,
		&i.Tags,
		&i.CustomFields,
		&i.CustomerCustomFields,
		&i.RawPayload,
		&i.AssignedTeamID,
		&i.AssigneeUserID,
		&i.ClaimedByUserID,
		&i.CreatedByUserID,
		&i.CreatedByMembershipID,
		&i.CreatedByServiceAccountID,
		&i.DetectedAt,
		&i.ReceivedAt,
		&i.AcknowledgedAt,
		&i.ClosedAt,
		&i.AssignedAt,
		&i.FirstResponseAt,
		&i.ResolvedAt,
		&i.ClaimedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.Replayed,
	)
	return &i, err
}

const getAlert = `-- name: GetAlert :one
SELECT
  id,
  tenant_id,
  external_id,
  title,
  description,
  status,
  severity,
  created_by,
  created_at,
  updated_at,
  version
FROM alerts
WHERE tenant_id = $1::uuid
  AND id = $2::uuid
  AND deleted_at IS NULL
`

type GetAlertParams struct {
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	ID       pgtype.UUID `db:"id" json:"id"`
}

type GetAlertRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	TenantID    pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	ExternalID  *string            `db:"external_id" json:"external_id"`
	Title       string             `db:"title" json:"title"`
	Description *string            `db:"description" json:"description"`
	Status      AlertStatus        `db:"status" json:"status"`
	Severity    AlertSeverity      `db:"severity" json:"severity"`
	CreatedBy   pgtype.UUID        `db:"created_by" json:"created_by"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Version     int32              `db:"version" json:"version"`
}

func (q *Queries) GetAlert(ctx context.Context, arg GetAlertParams) (*GetAlertRow, error) {
	row := q.db.QueryRow(ctx, getAlert, arg.TenantID, arg.ID)
	var i GetAlertRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExternalID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Severity,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return &i, err
}

const listAlerts = `-- name: ListAlerts :many
SELECT
  id,
  tenant_id,
  external_id,
  title,
  description,
  status,
  severity,
  created_by,
  created_at,
  updated_at,
  version
FROM alerts
WHERE tenant_id = $1::uuid
  AND deleted_at IS NULL
  AND (
    $2::uuid IS NULL
    OR id > $2::uuid
  )
ORDER BY id ASC
LIMIT $3
`

type ListAlertsParams struct {
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	AfterID  pgtype.UUID `db:"after_id" json:"after_id"`
	PageSize int32       `db:"page_size" json:"page_size"`
}

type ListAlertsRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	TenantID    pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	ExternalID  *string            `db:"external_id" json:"external_id"`
	Title       string             `db:"title" json:"title"`
	Description *string            `db:"description" json:"description"`
	Status      AlertStatus        `db:"status" json:"status"`
	Severity    AlertSeverity      `db:"severity" json:"severity"`
	CreatedBy   pgtype.UUID        `db:"created_by" json:"created_by"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Version     int32              `db:"version" json:"version"`
}

func (q *Queries) ListAlerts(ctx context.Context, arg ListAlertsParams) ([]*ListAlertsRow, error) {
	rows, err := q.db.Query(ctx, listAlerts, arg.TenantID, arg.AfterID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListAlertsRow
	for rows.Next() {
		var i ListAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ExternalID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Severity,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
