// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_operations.sql

package dbsql

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const authorizePlatformAuditExportDownload = `-- name: AuthorizePlatformAuditExportDownload :one
SELECT result.artifact_id::uuid AS artifact_id,
       result.object_key::text AS object_key,
       result.digest::bytea AS digest,
       result.rows::bigint AS rows,
       result.bytes::bigint AS bytes,
       result.expires_at::timestamptz AS expires_at,
       result.filename::text AS filename
FROM app.authorize_platform_audit_export_download_v1(
  $1::uuid,
  'platform.audit.export'::text,
  'platform.audit.read'::text,
  $2::uuid,
  $3::uuid,
  $4::uuid,
  $5::uuid,
  $6::inet,
  $7::text
) AS result(artifact_id,object_key,digest,rows,bytes,expires_at,filename)
`

type AuthorizePlatformAuditExportDownloadParams struct {
	SessionID     pgtype.UUID `db:"session_id" json:"session_id"`
	ExportID      pgtype.UUID `db:"export_id" json:"export_id"`
	AuditID       pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID     pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress     netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent     string      `db:"user_agent" json:"user_agent"`
}

type AuthorizePlatformAuditExportDownloadRow struct {
	ArtifactID pgtype.UUID        `db:"artifact_id" json:"artifact_id"`
	ObjectKey  string             `db:"object_key" json:"object_key"`
	Digest     []byte             `db:"digest" json:"digest"`
	Rows       int64              `db:"rows" json:"rows"`
	Bytes      int64              `db:"bytes" json:"bytes"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	Filename   string             `db:"filename" json:"filename"`
}

func (q *Queries) AuthorizePlatformAuditExportDownload(ctx context.Context, arg AuthorizePlatformAuditExportDownloadParams) (*AuthorizePlatformAuditExportDownloadRow, error) {
	row := q.db.QueryRow(ctx, authorizePlatformAuditExportDownload,
		arg.SessionID,
		arg.ExportID,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i AuthorizePlatformAuditExportDownloadRow
	err := row.Scan(
		&i.ArtifactID,
		&i.ObjectKey,
		&i.Digest,
		&i.Rows,
		&i.Bytes,
		&i.ExpiresAt,
		&i.Filename,
	)
	return &i, err
}

const authorizeTenantAuditExportDownload = `-- name: AuthorizeTenantAuditExportDownload :one
SELECT result.artifact_id::uuid AS artifact_id,
       result.object_key::text AS object_key,
       result.digest::bytea AS digest,
       result.rows::bigint AS rows,
       result.bytes::bigint AS bytes,
       result.expires_at::timestamptz AS expires_at,
       result.filename::text AS filename
FROM app.authorize_tenant_audit_export_download_v1(
  $1::uuid,
  'audit.export'::text,
  'audit.read'::text,
  $2::uuid,
  $3::uuid,
  $4::uuid,
  $5::uuid,
  $6::inet,
  $7::text
) AS result(artifact_id,object_key,digest,rows,bytes,expires_at,filename)
`

type AuthorizeTenantAuditExportDownloadParams struct {
	SessionID     pgtype.UUID `db:"session_id" json:"session_id"`
	ExportID      pgtype.UUID `db:"export_id" json:"export_id"`
	AuditID       pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID     pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress     netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent     string      `db:"user_agent" json:"user_agent"`
}

type AuthorizeTenantAuditExportDownloadRow struct {
	ArtifactID pgtype.UUID        `db:"artifact_id" json:"artifact_id"`
	ObjectKey  string             `db:"object_key" json:"object_key"`
	Digest     []byte             `db:"digest" json:"digest"`
	Rows       int64              `db:"rows" json:"rows"`
	Bytes      int64              `db:"bytes" json:"bytes"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	Filename   string             `db:"filename" json:"filename"`
}

func (q *Queries) AuthorizeTenantAuditExportDownload(ctx context.Context, arg AuthorizeTenantAuditExportDownloadParams) (*AuthorizeTenantAuditExportDownloadRow, error) {
	row := q.db.QueryRow(ctx, authorizeTenantAuditExportDownload,
		arg.SessionID,
		arg.ExportID,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i AuthorizeTenantAuditExportDownloadRow
	err := row.Scan(
		&i.ArtifactID,
		&i.ObjectKey,
		&i.Digest,
		&i.Rows,
		&i.Bytes,
		&i.ExpiresAt,
		&i.Filename,
	)
	return &i, err
}

const cancelPlatformAuditExportOperation = `-- name: CancelPlatformAuditExportOperation :one
SELECT app.cancel_platform_audit_export_v1(
  $1::uuid,
  'platform.audit.export'::text,
  'platform.audit.read'::text,
  $2::uuid,
  $3::bigint,
  $4::bytea,
  sha256(convert_to(jsonb_build_object(
    'exportId',$2::uuid,
    'expectedRevision',$3::bigint,
    'reason',$5::text
  )::text,'UTF8')),
  $5::text,
  $6::uuid,
  $7::uuid,
  $8::uuid,
  $9::inet,
  $10::text
)::jsonb AS document
`

type CancelPlatformAuditExportOperationParams struct {
	SessionID            pgtype.UUID `db:"session_id" json:"session_id"`
	ExportID             pgtype.UUID `db:"export_id" json:"export_id"`
	ExpectedRevision     int64       `db:"expected_revision" json:"expected_revision"`
	IdempotencyKeyDigest []byte      `db:"idempotency_key_digest" json:"idempotency_key_digest"`
	Reason               string      `db:"reason" json:"reason"`
	AuditID              pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
}

func (q *Queries) CancelPlatformAuditExportOperation(ctx context.Context, arg CancelPlatformAuditExportOperationParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, cancelPlatformAuditExportOperation,
		arg.SessionID,
		arg.ExportID,
		arg.ExpectedRevision,
		arg.IdempotencyKeyDigest,
		arg.Reason,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
	)
	var document []byte
	err := row.Scan(&document)
	return document, err
}

const cancelTenantAuditExportOperation = `-- name: CancelTenantAuditExportOperation :one
SELECT app.cancel_tenant_audit_export_v1(
  $1::uuid,
  'audit.export'::text,
  'audit.read'::text,
  $2::uuid,
  $3::bigint,
  $4::bytea,
  sha256(convert_to(jsonb_build_object(
    'exportId',$2::uuid,
    'expectedRevision',$3::bigint,
    'reason',$5::text
  )::text,'UTF8')),
  $5::text,
  $6::uuid,
  $7::uuid,
  $8::uuid,
  $9::inet,
  $10::text
)::jsonb AS document
`

type CancelTenantAuditExportOperationParams struct {
	SessionID            pgtype.UUID `db:"session_id" json:"session_id"`
	ExportID             pgtype.UUID `db:"export_id" json:"export_id"`
	ExpectedRevision     int64       `db:"expected_revision" json:"expected_revision"`
	IdempotencyKeyDigest []byte      `db:"idempotency_key_digest" json:"idempotency_key_digest"`
	Reason               string      `db:"reason" json:"reason"`
	AuditID              pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
}

func (q *Queries) CancelTenantAuditExportOperation(ctx context.Context, arg CancelTenantAuditExportOperationParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, cancelTenantAuditExportOperation,
		arg.SessionID,
		arg.ExportID,
		arg.ExpectedRevision,
		arg.IdempotencyKeyDigest,
		arg.Reason,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
	)
	var document []byte
	err := row.Scan(&document)
	return document, err
}

const createPlatformAuditExportOperation = `-- name: CreatePlatformAuditExportOperation :one
SELECT app.create_platform_audit_export_v1(
  $1::uuid,
  'platform.audit.export'::text,
  'platform.audit.read'::text,
  $2::bytea,
  sha256(convert_to(jsonb_build_object(
    'filter',$3::jsonb,
    'retentionSeconds',$4::bigint,
    'projectionVersion',1,
    'format','jsonl',
    'reason',$5::text
  )::text,'UTF8')),
  $6::uuid,
  $3::jsonb,
  sha256(convert_to($3::jsonb::text,'UTF8')),
  $4::bigint,
  $5::text,
  $7::uuid,
  $8::uuid,
  $9::uuid,
  $10::inet,
  $11::text
)::jsonb AS document
`

type CreatePlatformAuditExportOperationParams struct {
	SessionID            pgtype.UUID `db:"session_id" json:"session_id"`
	IdempotencyKeyDigest []byte      `db:"idempotency_key_digest" json:"idempotency_key_digest"`
	NormalizedFilter     []byte      `db:"normalized_filter" json:"normalized_filter"`
	RetentionSeconds     int64       `db:"retention_seconds" json:"retention_seconds"`
	Reason               string      `db:"reason" json:"reason"`
	JobID                pgtype.UUID `db:"job_id" json:"job_id"`
	AuditID              pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
}

func (q *Queries) CreatePlatformAuditExportOperation(ctx context.Context, arg CreatePlatformAuditExportOperationParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, createPlatformAuditExportOperation,
		arg.SessionID,
		arg.IdempotencyKeyDigest,
		arg.NormalizedFilter,
		arg.RetentionSeconds,
		arg.Reason,
		arg.JobID,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
	)
	var document []byte
	err := row.Scan(&document)
	return document, err
}

const createTenantAuditExportOperation = `-- name: CreateTenantAuditExportOperation :one

SELECT app.create_tenant_audit_export_v1(
  $1::uuid,
  'audit.export'::text,
  'audit.read'::text,
  $2::bytea,
  sha256(convert_to(jsonb_build_object(
    'filter',$3::jsonb,
    'retentionSeconds',$4::bigint,
    'projectionVersion',1,
    'format','jsonl',
    'reason',$5::text
  )::text,'UTF8')),
  $6::uuid,
  $3::jsonb,
  sha256(convert_to($3::jsonb::text,'UTF8')),
  $4::bigint,
  $5::text,
  $7::uuid,
  $8::uuid,
  $9::uuid,
  $10::inet,
  $11::text
)::jsonb AS document
`

type CreateTenantAuditExportOperationParams struct {
	SessionID            pgtype.UUID `db:"session_id" json:"session_id"`
	IdempotencyKeyDigest []byte      `db:"idempotency_key_digest" json:"idempotency_key_digest"`
	NormalizedFilter     []byte      `db:"normalized_filter" json:"normalized_filter"`
	RetentionSeconds     int64       `db:"retention_seconds" json:"retention_seconds"`
	Reason               string      `db:"reason" json:"reason"`
	JobID                pgtype.UUID `db:"job_id" json:"job_id"`
	AuditID              pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
}

// Audit operation mutations intentionally calculate their payload digests from
// PostgreSQL's canonical jsonb representation. The database ABI verifies the
// same representation before admitting an idempotency receipt.
func (q *Queries) CreateTenantAuditExportOperation(ctx context.Context, arg CreateTenantAuditExportOperationParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, createTenantAuditExportOperation,
		arg.SessionID,
		arg.IdempotencyKeyDigest,
		arg.NormalizedFilter,
		arg.RetentionSeconds,
		arg.Reason,
		arg.JobID,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
	)
	var document []byte
	err := row.Scan(&document)
	return document, err
}

const getPlatformAuditExportOperation = `-- name: GetPlatformAuditExportOperation :one
SELECT app.get_platform_audit_export_v1(
  $1::uuid,
  'platform.audit.export'::text,
  'platform.audit.read'::text,
  $2::uuid,
  $3::uuid,
  $4::uuid,
  $5::uuid,
  $6::inet,
  $7::text
)::jsonb AS document
`

type GetPlatformAuditExportOperationParams struct {
	SessionID     pgtype.UUID `db:"session_id" json:"session_id"`
	ExportID      pgtype.UUID `db:"export_id" json:"export_id"`
	AuditID       pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID     pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress     netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent     string      `db:"user_agent" json:"user_agent"`
}

func (q *Queries) GetPlatformAuditExportOperation(ctx context.Context, arg GetPlatformAuditExportOperationParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getPlatformAuditExportOperation,
		arg.SessionID,
		arg.ExportID,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
	)
	var document []byte
	err := row.Scan(&document)
	return document, err
}

const getPlatformAuditRetentionOperation = `-- name: GetPlatformAuditRetentionOperation :one
SELECT app.get_platform_audit_retention_v1(
  $1::uuid,
  'platform.audit.retention.manage'::text,
  $2::uuid,
  $3::uuid,
  $4::uuid,
  $5::inet,
  $6::text
)::jsonb AS document
`

type GetPlatformAuditRetentionOperationParams struct {
	SessionID     pgtype.UUID `db:"session_id" json:"session_id"`
	AuditID       pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID     pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress     netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent     string      `db:"user_agent" json:"user_agent"`
}

func (q *Queries) GetPlatformAuditRetentionOperation(ctx context.Context, arg GetPlatformAuditRetentionOperationParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getPlatformAuditRetentionOperation,
		arg.SessionID,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
	)
	var document []byte
	err := row.Scan(&document)
	return document, err
}

const getTenantAuditExportOperation = `-- name: GetTenantAuditExportOperation :one
SELECT app.get_tenant_audit_export_v1(
  $1::uuid,
  'audit.export'::text,
  'audit.read'::text,
  $2::uuid,
  $3::uuid,
  $4::uuid,
  $5::uuid,
  $6::inet,
  $7::text
)::jsonb AS document
`

type GetTenantAuditExportOperationParams struct {
	SessionID     pgtype.UUID `db:"session_id" json:"session_id"`
	ExportID      pgtype.UUID `db:"export_id" json:"export_id"`
	AuditID       pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID     pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress     netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent     string      `db:"user_agent" json:"user_agent"`
}

func (q *Queries) GetTenantAuditExportOperation(ctx context.Context, arg GetTenantAuditExportOperationParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getTenantAuditExportOperation,
		arg.SessionID,
		arg.ExportID,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
	)
	var document []byte
	err := row.Scan(&document)
	return document, err
}

const getTenantAuditRetentionOperation = `-- name: GetTenantAuditRetentionOperation :one
SELECT app.get_tenant_audit_retention_v1(
  $1::uuid,
  'audit.retention.manage'::text,
  $2::uuid,
  $3::uuid,
  $4::uuid,
  $5::inet,
  $6::text
)::jsonb AS document
`

type GetTenantAuditRetentionOperationParams struct {
	SessionID     pgtype.UUID `db:"session_id" json:"session_id"`
	AuditID       pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID     pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress     netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent     string      `db:"user_agent" json:"user_agent"`
}

func (q *Queries) GetTenantAuditRetentionOperation(ctx context.Context, arg GetTenantAuditRetentionOperationParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getTenantAuditRetentionOperation,
		arg.SessionID,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
	)
	var document []byte
	err := row.Scan(&document)
	return document, err
}

const placePlatformAuditLegalHoldOperation = `-- name: PlacePlatformAuditLegalHoldOperation :one
SELECT app.place_platform_audit_legal_hold_v1(
  $1::uuid,
  'platform.audit.retention.manage'::text,
  $2::uuid,
  $3::bytea,
  sha256(convert_to(jsonb_build_object('reason',$4::text)::text,'UTF8')),
  $4::text,
  $5::uuid,
  $6::uuid,
  $7::uuid,
  $8::inet,
  $9::text
)::jsonb AS document
`

type PlacePlatformAuditLegalHoldOperationParams struct {
	SessionID            pgtype.UUID `db:"session_id" json:"session_id"`
	HoldID               pgtype.UUID `db:"hold_id" json:"hold_id"`
	IdempotencyKeyDigest []byte      `db:"idempotency_key_digest" json:"idempotency_key_digest"`
	Reason               string      `db:"reason" json:"reason"`
	AuditID              pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
}

func (q *Queries) PlacePlatformAuditLegalHoldOperation(ctx context.Context, arg PlacePlatformAuditLegalHoldOperationParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, placePlatformAuditLegalHoldOperation,
		arg.SessionID,
		arg.HoldID,
		arg.IdempotencyKeyDigest,
		arg.Reason,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
	)
	var document []byte
	err := row.Scan(&document)
	return document, err
}

const placeTenantAuditLegalHoldOperation = `-- name: PlaceTenantAuditLegalHoldOperation :one
SELECT app.place_tenant_audit_legal_hold_v1(
  $1::uuid,
  'audit.retention.manage'::text,
  $2::uuid,
  $3::bytea,
  sha256(convert_to(jsonb_build_object('reason',$4::text)::text,'UTF8')),
  $4::text,
  $5::uuid,
  $6::uuid,
  $7::uuid,
  $8::inet,
  $9::text
)::jsonb AS document
`

type PlaceTenantAuditLegalHoldOperationParams struct {
	SessionID            pgtype.UUID `db:"session_id" json:"session_id"`
	HoldID               pgtype.UUID `db:"hold_id" json:"hold_id"`
	IdempotencyKeyDigest []byte      `db:"idempotency_key_digest" json:"idempotency_key_digest"`
	Reason               string      `db:"reason" json:"reason"`
	AuditID              pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
}

func (q *Queries) PlaceTenantAuditLegalHoldOperation(ctx context.Context, arg PlaceTenantAuditLegalHoldOperationParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, placeTenantAuditLegalHoldOperation,
		arg.SessionID,
		arg.HoldID,
		arg.IdempotencyKeyDigest,
		arg.Reason,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
	)
	var document []byte
	err := row.Scan(&document)
	return document, err
}

const releasePlatformAuditLegalHoldOperation = `-- name: ReleasePlatformAuditLegalHoldOperation :one
SELECT app.release_platform_audit_legal_hold_v1(
  $1::uuid,
  'platform.audit.retention.manage'::text,
  $2::uuid,
  $3::bigint,
  $4::bytea,
  sha256(convert_to(jsonb_build_object(
    'holdId',$2::uuid,
    'expectedRevision',$3::bigint,
    'reason',$5::text
  )::text,'UTF8')),
  $5::text,
  $6::uuid,
  $7::uuid,
  $8::uuid,
  $9::inet,
  $10::text
)::jsonb AS document
`

type ReleasePlatformAuditLegalHoldOperationParams struct {
	SessionID            pgtype.UUID `db:"session_id" json:"session_id"`
	HoldID               pgtype.UUID `db:"hold_id" json:"hold_id"`
	ExpectedRevision     int64       `db:"expected_revision" json:"expected_revision"`
	IdempotencyKeyDigest []byte      `db:"idempotency_key_digest" json:"idempotency_key_digest"`
	Reason               string      `db:"reason" json:"reason"`
	AuditID              pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
}

func (q *Queries) ReleasePlatformAuditLegalHoldOperation(ctx context.Context, arg ReleasePlatformAuditLegalHoldOperationParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, releasePlatformAuditLegalHoldOperation,
		arg.SessionID,
		arg.HoldID,
		arg.ExpectedRevision,
		arg.IdempotencyKeyDigest,
		arg.Reason,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
	)
	var document []byte
	err := row.Scan(&document)
	return document, err
}

const releaseTenantAuditLegalHoldOperation = `-- name: ReleaseTenantAuditLegalHoldOperation :one
SELECT app.release_tenant_audit_legal_hold_v1(
  $1::uuid,
  'audit.retention.manage'::text,
  $2::uuid,
  $3::bigint,
  $4::bytea,
  sha256(convert_to(jsonb_build_object(
    'holdId',$2::uuid,
    'expectedRevision',$3::bigint,
    'reason',$5::text
  )::text,'UTF8')),
  $5::text,
  $6::uuid,
  $7::uuid,
  $8::uuid,
  $9::inet,
  $10::text
)::jsonb AS document
`

type ReleaseTenantAuditLegalHoldOperationParams struct {
	SessionID            pgtype.UUID `db:"session_id" json:"session_id"`
	HoldID               pgtype.UUID `db:"hold_id" json:"hold_id"`
	ExpectedRevision     int64       `db:"expected_revision" json:"expected_revision"`
	IdempotencyKeyDigest []byte      `db:"idempotency_key_digest" json:"idempotency_key_digest"`
	Reason               string      `db:"reason" json:"reason"`
	AuditID              pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
}

func (q *Queries) ReleaseTenantAuditLegalHoldOperation(ctx context.Context, arg ReleaseTenantAuditLegalHoldOperationParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, releaseTenantAuditLegalHoldOperation,
		arg.SessionID,
		arg.HoldID,
		arg.ExpectedRevision,
		arg.IdempotencyKeyDigest,
		arg.Reason,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
	)
	var document []byte
	err := row.Scan(&document)
	return document, err
}

const updatePlatformAuditRetentionOperation = `-- name: UpdatePlatformAuditRetentionOperation :one
SELECT app.update_platform_audit_retention_v1(
  $1::uuid,
  'platform.audit.retention.manage'::text,
  $2::bigint,
  $3::integer,
  $4::bytea,
  sha256(convert_to(jsonb_build_object(
    'expectedRevision',$2::bigint,
    'retentionDays',$3::integer,
    'reason',$5::text
  )::text,'UTF8')),
  $5::text,
  $6::uuid,
  $7::uuid,
  $8::uuid,
  $9::inet,
  $10::text
)::jsonb AS document
`

type UpdatePlatformAuditRetentionOperationParams struct {
	SessionID            pgtype.UUID `db:"session_id" json:"session_id"`
	ExpectedRevision     int64       `db:"expected_revision" json:"expected_revision"`
	RetentionDays        int32       `db:"retention_days" json:"retention_days"`
	IdempotencyKeyDigest []byte      `db:"idempotency_key_digest" json:"idempotency_key_digest"`
	Reason               string      `db:"reason" json:"reason"`
	AuditID              pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
}

func (q *Queries) UpdatePlatformAuditRetentionOperation(ctx context.Context, arg UpdatePlatformAuditRetentionOperationParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, updatePlatformAuditRetentionOperation,
		arg.SessionID,
		arg.ExpectedRevision,
		arg.RetentionDays,
		arg.IdempotencyKeyDigest,
		arg.Reason,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
	)
	var document []byte
	err := row.Scan(&document)
	return document, err
}

const updateTenantAuditRetentionOperation = `-- name: UpdateTenantAuditRetentionOperation :one
SELECT app.update_tenant_audit_retention_v1(
  $1::uuid,
  'audit.retention.manage'::text,
  $2::bigint,
  $3::integer,
  $4::bytea,
  sha256(convert_to(jsonb_build_object(
    'expectedRevision',$2::bigint,
    'retentionDays',$3::integer,
    'reason',$5::text
  )::text,'UTF8')),
  $5::text,
  $6::uuid,
  $7::uuid,
  $8::uuid,
  $9::inet,
  $10::text
)::jsonb AS document
`

type UpdateTenantAuditRetentionOperationParams struct {
	SessionID            pgtype.UUID `db:"session_id" json:"session_id"`
	ExpectedRevision     int64       `db:"expected_revision" json:"expected_revision"`
	RetentionDays        int32       `db:"retention_days" json:"retention_days"`
	IdempotencyKeyDigest []byte      `db:"idempotency_key_digest" json:"idempotency_key_digest"`
	Reason               string      `db:"reason" json:"reason"`
	AuditID              pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
}

func (q *Queries) UpdateTenantAuditRetentionOperation(ctx context.Context, arg UpdateTenantAuditRetentionOperationParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, updateTenantAuditRetentionOperation,
		arg.SessionID,
		arg.ExpectedRevision,
		arg.RetentionDays,
		arg.IdempotencyKeyDigest,
		arg.Reason,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
	)
	var document []byte
	err := row.Scan(&document)
	return document, err
}
