// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authentication.sql

package dbsql

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const admitAuthAttempts = `-- name: AdmitAuthAttempts :one
SELECT admission.admitted::boolean AS admitted,
       admission.maximum_attempt_count::integer AS maximum_attempt_count,
       admission.blocked_until::timestamptz AS blocked_until
FROM app.admit_auth_attempts(
  $1::text[]::auth_rate_limit_scope[],
  $2::bytea[],
  $3::integer[],
  $4::integer[],
  $5::integer[]
) AS admission(admitted, maximum_attempt_count, blocked_until)
`

type AdmitAuthAttemptsParams struct {
	Scopes        []string `db:"scopes" json:"scopes"`
	KeyDigests    [][]byte `db:"key_digests" json:"key_digests"`
	WindowSeconds []int32  `db:"window_seconds" json:"window_seconds"`
	MaxAttempts   []int32  `db:"max_attempts" json:"max_attempts"`
	BlockSeconds  []int32  `db:"block_seconds" json:"block_seconds"`
}

type AdmitAuthAttemptsRow struct {
	Admitted            bool               `db:"admitted" json:"admitted"`
	MaximumAttemptCount int32              `db:"maximum_attempt_count" json:"maximum_attempt_count"`
	BlockedUntil        pgtype.Timestamptz `db:"blocked_until" json:"blocked_until"`
}

func (q *Queries) AdmitAuthAttempts(ctx context.Context, arg AdmitAuthAttemptsParams) (*AdmitAuthAttemptsRow, error) {
	row := q.db.QueryRow(ctx, admitAuthAttempts,
		arg.Scopes,
		arg.KeyDigests,
		arg.WindowSeconds,
		arg.MaxAttempts,
		arg.BlockSeconds,
	)
	var i AdmitAuthAttemptsRow
	err := row.Scan(&i.Admitted, &i.MaximumAttemptCount, &i.BlockedUntil)
	return &i, err
}

const completeMFALogin = `-- name: CompleteMFALogin :one
SELECT completion.session_id::uuid AS session_id,
       completion.failure_recorded::boolean AS failure_recorded,
       completion.blocked_until::timestamptz AS blocked_until
FROM app.complete_mfa_login(
  $1::bytea,
  $2::text,
  $3::bigint,
  $4::bytea,
  $5::uuid,
  $6::uuid,
  NULL::uuid,
  $7::bytea,
  $8::bytea,
  $9::timestamptz,
  $10::timestamptz,
  $11::text[]::auth_rate_limit_scope[],
  $12::bytea[],
  $13::integer[],
  $14::integer[],
  $15::integer[],
  $16::text[]::auth_rate_limit_scope[],
  $17::bytea[],
  $18::uuid,
  $19::uuid,
  $20::uuid,
  $21::inet,
  $22::text
) AS completion(session_id, failure_recorded, blocked_until)
`

type CompleteMFALoginParams struct {
	ChallengeDigest      []byte             `db:"challenge_digest" json:"challenge_digest"`
	AuthenticationMethod string             `db:"authentication_method" json:"authentication_method"`
	TotpCounter          *int64             `db:"totp_counter" json:"totp_counter"`
	RecoveryCodeDigest   []byte             `db:"recovery_code_digest" json:"recovery_code_digest"`
	SessionID            pgtype.UUID        `db:"session_id" json:"session_id"`
	RotationFamilyID     pgtype.UUID        `db:"rotation_family_id" json:"rotation_family_id"`
	SessionTokenDigest   []byte             `db:"session_token_digest" json:"session_token_digest"`
	CsrfDigest           []byte             `db:"csrf_digest" json:"csrf_digest"`
	IdleExpiresAt        pgtype.Timestamptz `db:"idle_expires_at" json:"idle_expires_at"`
	AbsoluteExpiresAt    pgtype.Timestamptz `db:"absolute_expires_at" json:"absolute_expires_at"`
	FailureScopes        []string           `db:"failure_scopes" json:"failure_scopes"`
	FailureKeyDigests    [][]byte           `db:"failure_key_digests" json:"failure_key_digests"`
	FailureWindowSeconds []int32            `db:"failure_window_seconds" json:"failure_window_seconds"`
	FailureMaxAttempts   []int32            `db:"failure_max_attempts" json:"failure_max_attempts"`
	FailureBlockSeconds  []int32            `db:"failure_block_seconds" json:"failure_block_seconds"`
	ClearScopes          []string           `db:"clear_scopes" json:"clear_scopes"`
	ClearKeyDigests      [][]byte           `db:"clear_key_digests" json:"clear_key_digests"`
	AuditID              pgtype.UUID        `db:"audit_id" json:"audit_id"`
	RequestID            pgtype.UUID        `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID        `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr         `db:"ip_address" json:"ip_address"`
	UserAgent            string             `db:"user_agent" json:"user_agent"`
}

type CompleteMFALoginRow struct {
	SessionID       pgtype.UUID        `db:"session_id" json:"session_id"`
	FailureRecorded bool               `db:"failure_recorded" json:"failure_recorded"`
	BlockedUntil    pgtype.Timestamptz `db:"blocked_until" json:"blocked_until"`
}

func (q *Queries) CompleteMFALogin(ctx context.Context, arg CompleteMFALoginParams) (*CompleteMFALoginRow, error) {
	row := q.db.QueryRow(ctx, completeMFALogin,
		arg.ChallengeDigest,
		arg.AuthenticationMethod,
		arg.TotpCounter,
		arg.RecoveryCodeDigest,
		arg.SessionID,
		arg.RotationFamilyID,
		arg.SessionTokenDigest,
		arg.CsrfDigest,
		arg.IdleExpiresAt,
		arg.AbsoluteExpiresAt,
		arg.FailureScopes,
		arg.FailureKeyDigests,
		arg.FailureWindowSeconds,
		arg.FailureMaxAttempts,
		arg.FailureBlockSeconds,
		arg.ClearScopes,
		arg.ClearKeyDigests,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i CompleteMFALoginRow
	err := row.Scan(&i.SessionID, &i.FailureRecorded, &i.BlockedUntil)
	return &i, err
}

const confirmBootstrap = `-- name: ConfirmBootstrap :one
SELECT app.confirm_platform_bootstrap(
  $1::bytea,
  $2::bytea,
  $3::uuid,
  $4::uuid,
  $5::uuid,
  $6::bytea,
  $7::bytea,
  $8::bytea,
  $9::integer,
  $10::uuid,
  $11::text,
  $12::text,
  $13::text,
  1::integer,
  $14::bigint,
  $15::uuid[],
  $16::bytea[],
  1::integer,
  $17::uuid,
  $18::uuid,
  $19::bytea,
  $20::bytea,
  $21::timestamptz,
  $22::timestamptz,
  $23::uuid,
  $24::uuid,
  $25::uuid,
  $26::inet,
  $27::text
) AS session_id
`

type ConfirmBootstrapParams struct {
	AuthorityDigest     []byte             `db:"authority_digest" json:"authority_digest"`
	EnrollmentDigest    []byte             `db:"enrollment_digest" json:"enrollment_digest"`
	UserID              pgtype.UUID        `db:"user_id" json:"user_id"`
	LocalCredentialID   pgtype.UUID        `db:"local_credential_id" json:"local_credential_id"`
	TotpCredentialID    pgtype.UUID        `db:"totp_credential_id" json:"totp_credential_id"`
	TotpCiphertext      []byte             `db:"totp_ciphertext" json:"totp_ciphertext"`
	TotpNonce           []byte             `db:"totp_nonce" json:"totp_nonce"`
	TotpAad             []byte             `db:"totp_aad" json:"totp_aad"`
	TotpKeyVersion      int32              `db:"totp_key_version" json:"totp_key_version"`
	PlatformRoleGrantID pgtype.UUID        `db:"platform_role_grant_id" json:"platform_role_grant_id"`
	CanonicalEmail      string             `db:"canonical_email" json:"canonical_email"`
	DisplayName         string             `db:"display_name" json:"display_name"`
	PasswordPhc         string             `db:"password_phc" json:"password_phc"`
	InitialTotpCounter  int64              `db:"initial_totp_counter" json:"initial_totp_counter"`
	RecoveryCodeIds     []pgtype.UUID      `db:"recovery_code_ids" json:"recovery_code_ids"`
	RecoveryCodeDigests [][]byte           `db:"recovery_code_digests" json:"recovery_code_digests"`
	SessionID           pgtype.UUID        `db:"session_id" json:"session_id"`
	RotationFamilyID    pgtype.UUID        `db:"rotation_family_id" json:"rotation_family_id"`
	SessionTokenDigest  []byte             `db:"session_token_digest" json:"session_token_digest"`
	CsrfDigest          []byte             `db:"csrf_digest" json:"csrf_digest"`
	IdleExpiresAt       pgtype.Timestamptz `db:"idle_expires_at" json:"idle_expires_at"`
	AbsoluteExpiresAt   pgtype.Timestamptz `db:"absolute_expires_at" json:"absolute_expires_at"`
	AuditID             pgtype.UUID        `db:"audit_id" json:"audit_id"`
	RequestID           pgtype.UUID        `db:"request_id" json:"request_id"`
	CorrelationID       pgtype.UUID        `db:"correlation_id" json:"correlation_id"`
	IpAddress           netip.Addr         `db:"ip_address" json:"ip_address"`
	UserAgent           string             `db:"user_agent" json:"user_agent"`
}

func (q *Queries) ConfirmBootstrap(ctx context.Context, arg ConfirmBootstrapParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, confirmBootstrap,
		arg.AuthorityDigest,
		arg.EnrollmentDigest,
		arg.UserID,
		arg.LocalCredentialID,
		arg.TotpCredentialID,
		arg.TotpCiphertext,
		arg.TotpNonce,
		arg.TotpAad,
		arg.TotpKeyVersion,
		arg.PlatformRoleGrantID,
		arg.CanonicalEmail,
		arg.DisplayName,
		arg.PasswordPhc,
		arg.InitialTotpCounter,
		arg.RecoveryCodeIds,
		arg.RecoveryCodeDigests,
		arg.SessionID,
		arg.RotationFamilyID,
		arg.SessionTokenDigest,
		arg.CsrfDigest,
		arg.IdleExpiresAt,
		arg.AbsoluteExpiresAt,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
	)
	var session_id pgtype.UUID
	err := row.Scan(&session_id)
	return session_id, err
}

const createMFAChallenge = `-- name: CreateMFAChallenge :one
SELECT app.create_auth_challenge(
  $1::uuid,
  $2::uuid,
  $3::bytea,
  $4::bytea,
  $5::bytea,
  $6::bytea,
  'mfa_login'::auth_challenge_purpose,
  $7::timestamptz,
  $8::integer,
  $9::uuid,
  $10::uuid,
  $11::uuid,
  $12::inet,
  $13::text,
  'local_password'::text
) AS challenge_id
`

type CreateMFAChallengeParams struct {
	ChallengeID               pgtype.UUID        `db:"challenge_id" json:"challenge_id"`
	UserID                    pgtype.UUID        `db:"user_id" json:"user_id"`
	ChallengeRateKeyDigest    []byte             `db:"challenge_rate_key_digest" json:"challenge_rate_key_digest"`
	MfaRateKeyDigest          []byte             `db:"mfa_rate_key_digest" json:"mfa_rate_key_digest"`
	LoginAccountRateKeyDigest []byte             `db:"login_account_rate_key_digest" json:"login_account_rate_key_digest"`
	TokenDigest               []byte             `db:"token_digest" json:"token_digest"`
	ExpiresAt                 pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	MaxAttempts               int32              `db:"max_attempts" json:"max_attempts"`
	AuditID                   pgtype.UUID        `db:"audit_id" json:"audit_id"`
	RequestID                 pgtype.UUID        `db:"request_id" json:"request_id"`
	CorrelationID             pgtype.UUID        `db:"correlation_id" json:"correlation_id"`
	IpAddress                 netip.Addr         `db:"ip_address" json:"ip_address"`
	UserAgent                 string             `db:"user_agent" json:"user_agent"`
}

func (q *Queries) CreateMFAChallenge(ctx context.Context, arg CreateMFAChallengeParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createMFAChallenge,
		arg.ChallengeID,
		arg.UserID,
		arg.ChallengeRateKeyDigest,
		arg.MfaRateKeyDigest,
		arg.LoginAccountRateKeyDigest,
		arg.TokenDigest,
		arg.ExpiresAt,
		arg.MaxAttempts,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
	)
	var challenge_id pgtype.UUID
	err := row.Scan(&challenge_id)
	return challenge_id, err
}

const getAuthRateLimit = `-- name: GetAuthRateLimit :one
SELECT rate.attempt_count::integer AS attempt_count,
       rate.window_expires_at::timestamptz AS window_expires_at,
       rate.blocked_until::timestamptz AS blocked_until
FROM app.get_auth_rate_limit(
  $1::auth_rate_limit_scope,
  $2::bytea
) AS rate(attempt_count, window_expires_at, blocked_until)
`

type GetAuthRateLimitParams struct {
	Scope     AuthRateLimitScope `db:"scope" json:"scope"`
	KeyDigest []byte             `db:"key_digest" json:"key_digest"`
}

type GetAuthRateLimitRow struct {
	AttemptCount    int32              `db:"attempt_count" json:"attempt_count"`
	WindowExpiresAt pgtype.Timestamptz `db:"window_expires_at" json:"window_expires_at"`
	BlockedUntil    pgtype.Timestamptz `db:"blocked_until" json:"blocked_until"`
}

func (q *Queries) GetAuthRateLimit(ctx context.Context, arg GetAuthRateLimitParams) (*GetAuthRateLimitRow, error) {
	row := q.db.QueryRow(ctx, getAuthRateLimit, arg.Scope, arg.KeyDigest)
	var i GetAuthRateLimitRow
	err := row.Scan(&i.AttemptCount, &i.WindowExpiresAt, &i.BlockedUntil)
	return &i, err
}

const getBootstrapEnrollment = `-- name: GetBootstrapEnrollment :one
SELECT enrollment.enrollment_id::uuid AS enrollment_id,
       enrollment.canonical_email::text AS canonical_email,
       enrollment.totp_secret_ciphertext::bytea AS totp_secret_ciphertext,
       enrollment.totp_secret_nonce::bytea AS totp_secret_nonce,
       enrollment.totp_secret_aad::bytea AS totp_secret_aad,
       enrollment.totp_key_version::integer AS totp_key_version,
       enrollment.expires_at::timestamptz AS expires_at,
       enrollment.attempts::integer AS attempts,
       enrollment.max_attempts::integer AS max_attempts
FROM app.get_platform_bootstrap_enrollment(
  $1::bytea,
  $2::bytea
) AS enrollment(
  enrollment_id, canonical_email, totp_secret_ciphertext, totp_secret_nonce,
  totp_secret_aad, totp_key_version, expires_at, attempts, max_attempts
)
`

type GetBootstrapEnrollmentParams struct {
	AuthorityDigest  []byte `db:"authority_digest" json:"authority_digest"`
	EnrollmentDigest []byte `db:"enrollment_digest" json:"enrollment_digest"`
}

type GetBootstrapEnrollmentRow struct {
	EnrollmentID         pgtype.UUID        `db:"enrollment_id" json:"enrollment_id"`
	CanonicalEmail       string             `db:"canonical_email" json:"canonical_email"`
	TotpSecretCiphertext []byte             `db:"totp_secret_ciphertext" json:"totp_secret_ciphertext"`
	TotpSecretNonce      []byte             `db:"totp_secret_nonce" json:"totp_secret_nonce"`
	TotpSecretAad        []byte             `db:"totp_secret_aad" json:"totp_secret_aad"`
	TotpKeyVersion       int32              `db:"totp_key_version" json:"totp_key_version"`
	ExpiresAt            pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	Attempts             int32              `db:"attempts" json:"attempts"`
	MaxAttempts          int32              `db:"max_attempts" json:"max_attempts"`
}

func (q *Queries) GetBootstrapEnrollment(ctx context.Context, arg GetBootstrapEnrollmentParams) (*GetBootstrapEnrollmentRow, error) {
	row := q.db.QueryRow(ctx, getBootstrapEnrollment, arg.AuthorityDigest, arg.EnrollmentDigest)
	var i GetBootstrapEnrollmentRow
	err := row.Scan(
		&i.EnrollmentID,
		&i.CanonicalEmail,
		&i.TotpSecretCiphertext,
		&i.TotpSecretNonce,
		&i.TotpSecretAad,
		&i.TotpKeyVersion,
		&i.ExpiresAt,
		&i.Attempts,
		&i.MaxAttempts,
	)
	return &i, err
}

const getLocalCredential = `-- name: GetLocalCredential :one
SELECT credential.user_id::uuid AS user_id,
       credential.password_phc::text AS password_phc,
       credential.password_algorithm::text AS password_algorithm,
       credential.password_version::integer AS password_version,
       credential.must_rotate::boolean AS must_rotate
FROM app.get_local_break_glass_credential($1::text)
  AS credential(user_id, password_phc, password_algorithm, password_version, must_rotate)
`

type GetLocalCredentialParams struct {
	CanonicalEmail string `db:"canonical_email" json:"canonical_email"`
}

type GetLocalCredentialRow struct {
	UserID            pgtype.UUID `db:"user_id" json:"user_id"`
	PasswordPhc       string      `db:"password_phc" json:"password_phc"`
	PasswordAlgorithm string      `db:"password_algorithm" json:"password_algorithm"`
	PasswordVersion   int32       `db:"password_version" json:"password_version"`
	MustRotate        bool        `db:"must_rotate" json:"must_rotate"`
}

func (q *Queries) GetLocalCredential(ctx context.Context, arg GetLocalCredentialParams) (*GetLocalCredentialRow, error) {
	row := q.db.QueryRow(ctx, getLocalCredential, arg.CanonicalEmail)
	var i GetLocalCredentialRow
	err := row.Scan(
		&i.UserID,
		&i.PasswordPhc,
		&i.PasswordAlgorithm,
		&i.PasswordVersion,
		&i.MustRotate,
	)
	return &i, err
}

const getMFAChallenge = `-- name: GetMFAChallenge :one
SELECT challenge.challenge_id::uuid AS challenge_id,
       challenge.user_id::uuid AS user_id,
       challenge.attempts::integer AS attempts,
       challenge.max_attempts::integer AS max_attempts,
       challenge.expires_at::timestamptz AS expires_at,
       credential.credential_id::uuid AS credential_id,
       credential.secret_ciphertext::bytea AS secret_ciphertext,
       credential.secret_nonce::bytea AS secret_nonce,
       credential.secret_aad::bytea AS secret_aad,
       credential.key_version::integer AS key_version,
       credential.last_accepted_counter::bigint AS last_accepted_counter
FROM app.get_auth_challenge(
  $1::bytea,
  'mfa_login'::auth_challenge_purpose
) AS challenge(challenge_id, user_id, purpose, attempts, max_attempts, expires_at)
CROSS JOIN LATERAL app.get_totp_credential(challenge.user_id::uuid) AS credential(
  credential_id, secret_ciphertext, secret_nonce, secret_aad, key_version,
  encryption_algorithm, otp_algorithm, digits, period_seconds, last_accepted_counter
)
`

type GetMFAChallengeParams struct {
	ChallengeDigest []byte `db:"challenge_digest" json:"challenge_digest"`
}

type GetMFAChallengeRow struct {
	ChallengeID         pgtype.UUID        `db:"challenge_id" json:"challenge_id"`
	UserID              pgtype.UUID        `db:"user_id" json:"user_id"`
	Attempts            int32              `db:"attempts" json:"attempts"`
	MaxAttempts         int32              `db:"max_attempts" json:"max_attempts"`
	ExpiresAt           pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CredentialID        pgtype.UUID        `db:"credential_id" json:"credential_id"`
	SecretCiphertext    []byte             `db:"secret_ciphertext" json:"secret_ciphertext"`
	SecretNonce         []byte             `db:"secret_nonce" json:"secret_nonce"`
	SecretAad           []byte             `db:"secret_aad" json:"secret_aad"`
	KeyVersion          int32              `db:"key_version" json:"key_version"`
	LastAcceptedCounter int64              `db:"last_accepted_counter" json:"last_accepted_counter"`
}

func (q *Queries) GetMFAChallenge(ctx context.Context, arg GetMFAChallengeParams) (*GetMFAChallengeRow, error) {
	row := q.db.QueryRow(ctx, getMFAChallenge, arg.ChallengeDigest)
	var i GetMFAChallengeRow
	err := row.Scan(
		&i.ChallengeID,
		&i.UserID,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.CredentialID,
		&i.SecretCiphertext,
		&i.SecretNonce,
		&i.SecretAad,
		&i.KeyVersion,
		&i.LastAcceptedCounter,
	)
	return &i, err
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT session.session_id::uuid AS session_id,
       session.current::boolean AS current,
       session.authentication_method::text AS authentication_method,
       session.last_seen_at::timestamptz AS last_seen_at,
       session.idle_expires_at::timestamptz AS idle_expires_at,
       session.absolute_expires_at::timestamptz AS absolute_expires_at,
       session.revoked_at::timestamptz AS revoked_at,
       session.created_at::timestamptz AS created_at
FROM app.list_user_sessions(
  $1::uuid,
  $2::uuid,
  $3::integer
) AS session(
  session_id, current, active_tenant_id, authentication_method, mfa_satisfied_at,
  last_seen_at, idle_expires_at, absolute_expires_at, revoked_at, revoke_reason, created_at
)
`

type ListUserSessionsParams struct {
	CurrentSessionID pgtype.UUID `db:"current_session_id" json:"current_session_id"`
	AfterSessionID   pgtype.UUID `db:"after_session_id" json:"after_session_id"`
	PageSize         int32       `db:"page_size" json:"page_size"`
}

type ListUserSessionsRow struct {
	SessionID            pgtype.UUID        `db:"session_id" json:"session_id"`
	Current              bool               `db:"current" json:"current"`
	AuthenticationMethod string             `db:"authentication_method" json:"authentication_method"`
	LastSeenAt           pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	IdleExpiresAt        pgtype.Timestamptz `db:"idle_expires_at" json:"idle_expires_at"`
	AbsoluteExpiresAt    pgtype.Timestamptz `db:"absolute_expires_at" json:"absolute_expires_at"`
	RevokedAt            pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) ListUserSessions(ctx context.Context, arg ListUserSessionsParams) ([]*ListUserSessionsRow, error) {
	rows, err := q.db.Query(ctx, listUserSessions, arg.CurrentSessionID, arg.AfterSessionID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListUserSessionsRow
	for rows.Next() {
		var i ListUserSessionsRow
		if err := rows.Scan(
			&i.SessionID,
			&i.Current,
			&i.AuthenticationMethod,
			&i.LastSeenAt,
			&i.IdleExpiresAt,
			&i.AbsoluteExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTenantMemberships = `-- name: ListUserTenantMemberships :many
SELECT membership.membership_id::uuid AS membership_id,
       membership.tenant_id::uuid AS tenant_id,
       membership.tenant_slug::text AS tenant_slug,
       membership.tenant_name::text AS tenant_name,
       membership.membership_role::text AS membership_role,
       membership.tenant_status::text AS tenant_status,
       membership.timezone::text AS timezone,
       membership.locale::text AS locale,
       membership.created_at::timestamptz AS created_at,
       membership.updated_at::timestamptz AS updated_at
FROM app.list_user_tenant_memberships(
  $1::uuid,
  $2::integer
) AS membership(
  membership_id, tenant_id, tenant_slug, tenant_name, membership_role,
  membership_status, tenant_status, timezone, locale, created_at, updated_at
)
`

type ListUserTenantMembershipsParams struct {
	AfterMembershipID pgtype.UUID `db:"after_membership_id" json:"after_membership_id"`
	PageSize          int32       `db:"page_size" json:"page_size"`
}

type ListUserTenantMembershipsRow struct {
	MembershipID   pgtype.UUID        `db:"membership_id" json:"membership_id"`
	TenantID       pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	TenantSlug     string             `db:"tenant_slug" json:"tenant_slug"`
	TenantName     string             `db:"tenant_name" json:"tenant_name"`
	MembershipRole string             `db:"membership_role" json:"membership_role"`
	TenantStatus   string             `db:"tenant_status" json:"tenant_status"`
	Timezone       string             `db:"timezone" json:"timezone"`
	Locale         string             `db:"locale" json:"locale"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListUserTenantMemberships(ctx context.Context, arg ListUserTenantMembershipsParams) ([]*ListUserTenantMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listUserTenantMemberships, arg.AfterMembershipID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListUserTenantMembershipsRow
	for rows.Next() {
		var i ListUserTenantMembershipsRow
		if err := rows.Scan(
			&i.MembershipID,
			&i.TenantID,
			&i.TenantSlug,
			&i.TenantName,
			&i.MembershipRole,
			&i.TenantStatus,
			&i.Timezone,
			&i.Locale,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAuthRateLimitFailure = `-- name: RecordAuthRateLimitFailure :one
SELECT failure.maximum_attempt_count::integer AS maximum_attempt_count,
       failure.blocked_until::timestamptz AS blocked_until
FROM app.record_auth_rate_limit_failure(
  $1::text[]::auth_rate_limit_scope[],
  $2::bytea[],
  $3::integer[],
  $4::integer[],
  $5::integer[],
  $6::uuid,
  $7::text,
  $8::uuid,
  $9::uuid,
  $10::inet,
  $11::text,
  $12::text
) AS failure(maximum_attempt_count, blocked_until)
`

type RecordAuthRateLimitFailureParams struct {
	Scopes               []string    `db:"scopes" json:"scopes"`
	KeyDigests           [][]byte    `db:"key_digests" json:"key_digests"`
	WindowSeconds        []int32     `db:"window_seconds" json:"window_seconds"`
	MaxAttempts          []int32     `db:"max_attempts" json:"max_attempts"`
	BlockSeconds         []int32     `db:"block_seconds" json:"block_seconds"`
	AuditID              pgtype.UUID `db:"audit_id" json:"audit_id"`
	Reason               string      `db:"reason" json:"reason"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
}

type RecordAuthRateLimitFailureRow struct {
	MaximumAttemptCount int32              `db:"maximum_attempt_count" json:"maximum_attempt_count"`
	BlockedUntil        pgtype.Timestamptz `db:"blocked_until" json:"blocked_until"`
}

func (q *Queries) RecordAuthRateLimitFailure(ctx context.Context, arg RecordAuthRateLimitFailureParams) (*RecordAuthRateLimitFailureRow, error) {
	row := q.db.QueryRow(ctx, recordAuthRateLimitFailure,
		arg.Scopes,
		arg.KeyDigests,
		arg.WindowSeconds,
		arg.MaxAttempts,
		arg.BlockSeconds,
		arg.AuditID,
		arg.Reason,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
	)
	var i RecordAuthRateLimitFailureRow
	err := row.Scan(&i.MaximumAttemptCount, &i.BlockedUntil)
	return &i, err
}

const recordAuthenticationFailure = `-- name: RecordAuthenticationFailure :one
SELECT app.record_authentication_failure(
  'local_login'::auth_rate_limit_scope,
  $1::bytea,
  $2::uuid,
  $3::uuid,
  'invalid_credentials'::text,
  $4::uuid,
  $5::uuid,
  $6::inet,
  $7::text,
  'local_password'::text
) AS recorded
`

type RecordAuthenticationFailureParams struct {
	MeteredKeyDigest []byte      `db:"metered_key_digest" json:"metered_key_digest"`
	UserID           pgtype.UUID `db:"user_id" json:"user_id"`
	AuditID          pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID        pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID    pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress        netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent        string      `db:"user_agent" json:"user_agent"`
}

func (q *Queries) RecordAuthenticationFailure(ctx context.Context, arg RecordAuthenticationFailureParams) (bool, error) {
	row := q.db.QueryRow(ctx, recordAuthenticationFailure,
		arg.MeteredKeyDigest,
		arg.UserID,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
	)
	var recorded bool
	err := row.Scan(&recorded)
	return recorded, err
}

const recordBootstrapFailure = `-- name: RecordBootstrapFailure :one
SELECT failure.enrollment_attempts::integer AS enrollment_attempts,
       failure.enrollment_exhausted::boolean AS enrollment_exhausted,
       failure.maximum_rate_attempt_count::integer AS maximum_rate_attempt_count,
       failure.blocked_until::timestamptz AS blocked_until
FROM app.record_platform_bootstrap_failure(
  $1::bytea,
  $2::bytea,
  $3::text[]::auth_rate_limit_scope[],
  $4::bytea[],
  $5::integer[],
  $6::integer[],
  $7::integer[],
  $8::uuid,
  'invalid_totp_proof'::text,
  $9::uuid,
  $10::uuid,
  $11::inet,
  $12::text
) AS failure(
  enrollment_attempts, enrollment_exhausted, maximum_rate_attempt_count, blocked_until
)
`

type RecordBootstrapFailureParams struct {
	AuthorityDigest  []byte      `db:"authority_digest" json:"authority_digest"`
	EnrollmentDigest []byte      `db:"enrollment_digest" json:"enrollment_digest"`
	Scopes           []string    `db:"scopes" json:"scopes"`
	KeyDigests       [][]byte    `db:"key_digests" json:"key_digests"`
	WindowSeconds    []int32     `db:"window_seconds" json:"window_seconds"`
	MaxAttempts      []int32     `db:"max_attempts" json:"max_attempts"`
	BlockSeconds     []int32     `db:"block_seconds" json:"block_seconds"`
	AuditID          pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID        pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID    pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress        netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent        string      `db:"user_agent" json:"user_agent"`
}

type RecordBootstrapFailureRow struct {
	EnrollmentAttempts      int32              `db:"enrollment_attempts" json:"enrollment_attempts"`
	EnrollmentExhausted     bool               `db:"enrollment_exhausted" json:"enrollment_exhausted"`
	MaximumRateAttemptCount int32              `db:"maximum_rate_attempt_count" json:"maximum_rate_attempt_count"`
	BlockedUntil            pgtype.Timestamptz `db:"blocked_until" json:"blocked_until"`
}

func (q *Queries) RecordBootstrapFailure(ctx context.Context, arg RecordBootstrapFailureParams) (*RecordBootstrapFailureRow, error) {
	row := q.db.QueryRow(ctx, recordBootstrapFailure,
		arg.AuthorityDigest,
		arg.EnrollmentDigest,
		arg.Scopes,
		arg.KeyDigests,
		arg.WindowSeconds,
		arg.MaxAttempts,
		arg.BlockSeconds,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i RecordBootstrapFailureRow
	err := row.Scan(
		&i.EnrollmentAttempts,
		&i.EnrollmentExhausted,
		&i.MaximumRateAttemptCount,
		&i.BlockedUntil,
	)
	return &i, err
}

const recordMFAFailure = `-- name: RecordMFAFailure :one
SELECT failure.challenge_attempts::integer AS challenge_attempts,
       failure.challenge_exhausted::boolean AS challenge_exhausted,
       failure.maximum_rate_attempt_count::integer AS maximum_rate_attempt_count,
       failure.blocked_until::timestamptz AS blocked_until
FROM app.record_mfa_challenge_failure(
  $1::bytea,
  $2::text[]::auth_rate_limit_scope[],
  $3::bytea[],
  $4::integer[],
  $5::integer[],
  $6::integer[],
  $7::uuid,
  'invalid_mfa_proof'::text,
  $8::uuid,
  $9::uuid,
  $10::inet,
  $11::text,
  $12::text
) AS failure(
  challenge_attempts, challenge_exhausted, maximum_rate_attempt_count, blocked_until
)
`

type RecordMFAFailureParams struct {
	ChallengeDigest      []byte      `db:"challenge_digest" json:"challenge_digest"`
	Scopes               []string    `db:"scopes" json:"scopes"`
	KeyDigests           [][]byte    `db:"key_digests" json:"key_digests"`
	WindowSeconds        []int32     `db:"window_seconds" json:"window_seconds"`
	MaxAttempts          []int32     `db:"max_attempts" json:"max_attempts"`
	BlockSeconds         []int32     `db:"block_seconds" json:"block_seconds"`
	AuditID              pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
}

type RecordMFAFailureRow struct {
	ChallengeAttempts       int32              `db:"challenge_attempts" json:"challenge_attempts"`
	ChallengeExhausted      bool               `db:"challenge_exhausted" json:"challenge_exhausted"`
	MaximumRateAttemptCount int32              `db:"maximum_rate_attempt_count" json:"maximum_rate_attempt_count"`
	BlockedUntil            pgtype.Timestamptz `db:"blocked_until" json:"blocked_until"`
}

func (q *Queries) RecordMFAFailure(ctx context.Context, arg RecordMFAFailureParams) (*RecordMFAFailureRow, error) {
	row := q.db.QueryRow(ctx, recordMFAFailure,
		arg.ChallengeDigest,
		arg.Scopes,
		arg.KeyDigests,
		arg.WindowSeconds,
		arg.MaxAttempts,
		arg.BlockSeconds,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
	)
	var i RecordMFAFailureRow
	err := row.Scan(
		&i.ChallengeAttempts,
		&i.ChallengeExhausted,
		&i.MaximumRateAttemptCount,
		&i.BlockedUntil,
	)
	return &i, err
}

const reserveBootstrap = `-- name: ReserveBootstrap :one
SELECT app.reserve_platform_bootstrap(
  $1::uuid,
  $2::bytea,
  $3::bytea,
  $4::bytea,
  $5::text,
  $6::bytea,
  $7::bytea,
  $8::bytea,
  $9::integer,
  $10::timestamptz,
  $11::integer,
  $12::uuid,
  $13::uuid,
  $14::inet,
  $15::text
) AS enrollment_id
`

type ReserveBootstrapParams struct {
	EnrollmentID            pgtype.UUID        `db:"enrollment_id" json:"enrollment_id"`
	AuthorityDigest         []byte             `db:"authority_digest" json:"authority_digest"`
	EnrollmentDigest        []byte             `db:"enrollment_digest" json:"enrollment_digest"`
	EnrollmentRateKeyDigest []byte             `db:"enrollment_rate_key_digest" json:"enrollment_rate_key_digest"`
	CanonicalEmail          string             `db:"canonical_email" json:"canonical_email"`
	TotpCiphertext          []byte             `db:"totp_ciphertext" json:"totp_ciphertext"`
	TotpNonce               []byte             `db:"totp_nonce" json:"totp_nonce"`
	TotpAad                 []byte             `db:"totp_aad" json:"totp_aad"`
	TotpKeyVersion          int32              `db:"totp_key_version" json:"totp_key_version"`
	ExpiresAt               pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	MaxAttempts             int32              `db:"max_attempts" json:"max_attempts"`
	RequestID               pgtype.UUID        `db:"request_id" json:"request_id"`
	CorrelationID           pgtype.UUID        `db:"correlation_id" json:"correlation_id"`
	IpAddress               netip.Addr         `db:"ip_address" json:"ip_address"`
	UserAgent               string             `db:"user_agent" json:"user_agent"`
}

func (q *Queries) ReserveBootstrap(ctx context.Context, arg ReserveBootstrapParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, reserveBootstrap,
		arg.EnrollmentID,
		arg.AuthorityDigest,
		arg.EnrollmentDigest,
		arg.EnrollmentRateKeyDigest,
		arg.CanonicalEmail,
		arg.TotpCiphertext,
		arg.TotpNonce,
		arg.TotpAad,
		arg.TotpKeyVersion,
		arg.ExpiresAt,
		arg.MaxAttempts,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
	)
	var enrollment_id pgtype.UUID
	err := row.Scan(&enrollment_id)
	return enrollment_id, err
}

const resolveSession = `-- name: ResolveSession :one
SELECT session.session_id::uuid AS session_id,
       session.user_id::uuid AS user_id,
       session.rotation_family_id::uuid AS rotation_family_id,
       COALESCE(session.email::text, '')::text AS email,
       session.display_name::text AS display_name,
       session.active_tenant_id::uuid AS active_tenant_id,
       session.csrf_secret_digest::bytea AS csrf_secret_digest,
       session.authentication_method::text AS authentication_method,
       session.created_at::timestamptz AS created_at,
       session.last_seen_at::timestamptz AS last_seen_at,
       session.idle_expires_at::timestamptz AS idle_expires_at,
       session.absolute_expires_at::timestamptz AS absolute_expires_at,
       session.platform_permissions::text[] AS platform_permissions
FROM app.get_auth_session_v3($1::bytea) AS session(
  session_id, user_id, rotation_family_id, email, display_name, active_tenant_id,
  csrf_secret_digest, authentication_method, mfa_satisfied_at, created_at,
  last_seen_at, idle_expires_at, absolute_expires_at, platform_permissions
)
`

type ResolveSessionParams struct {
	TokenDigest []byte `db:"token_digest" json:"token_digest"`
}

type ResolveSessionRow struct {
	SessionID            pgtype.UUID        `db:"session_id" json:"session_id"`
	UserID               pgtype.UUID        `db:"user_id" json:"user_id"`
	RotationFamilyID     pgtype.UUID        `db:"rotation_family_id" json:"rotation_family_id"`
	Email                string             `db:"email" json:"email"`
	DisplayName          string             `db:"display_name" json:"display_name"`
	ActiveTenantID       pgtype.UUID        `db:"active_tenant_id" json:"active_tenant_id"`
	CsrfSecretDigest     []byte             `db:"csrf_secret_digest" json:"csrf_secret_digest"`
	AuthenticationMethod string             `db:"authentication_method" json:"authentication_method"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	LastSeenAt           pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	IdleExpiresAt        pgtype.Timestamptz `db:"idle_expires_at" json:"idle_expires_at"`
	AbsoluteExpiresAt    pgtype.Timestamptz `db:"absolute_expires_at" json:"absolute_expires_at"`
	PlatformPermissions  []string           `db:"platform_permissions" json:"platform_permissions"`
}

func (q *Queries) ResolveSession(ctx context.Context, arg ResolveSessionParams) (*ResolveSessionRow, error) {
	row := q.db.QueryRow(ctx, resolveSession, arg.TokenDigest)
	var i ResolveSessionRow
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.RotationFamilyID,
		&i.Email,
		&i.DisplayName,
		&i.ActiveTenantID,
		&i.CsrfSecretDigest,
		&i.AuthenticationMethod,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.PlatformPermissions,
	)
	return &i, err
}

const revokeUserSession = `-- name: RevokeUserSession :one
SELECT app.revoke_user_session(
  $1::uuid,
  $2::text,
  $3::uuid,
  $4::uuid,
  $5::uuid,
  $6::inet,
  $7::text
) AS revoked
`

type RevokeUserSessionParams struct {
	SessionID     pgtype.UUID `db:"session_id" json:"session_id"`
	Reason        string      `db:"reason" json:"reason"`
	AuditID       pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID     pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress     netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent     string      `db:"user_agent" json:"user_agent"`
}

func (q *Queries) RevokeUserSession(ctx context.Context, arg RevokeUserSessionParams) (bool, error) {
	row := q.db.QueryRow(ctx, revokeUserSession,
		arg.SessionID,
		arg.Reason,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
	)
	var revoked bool
	err := row.Scan(&revoked)
	return revoked, err
}

const rotateSession = `-- name: RotateSession :one
SELECT app.rotate_auth_session(
  $1::bytea,
  $2::uuid,
  $3::bytea,
  $4::bytea,
  $5::timestamptz,
  $6::timestamptz,
  $7::uuid,
  $8::uuid,
  $9::uuid,
  $10::inet,
  $11::text
) AS session_id
`

type RotateSessionParams struct {
	CurrentTokenDigest []byte             `db:"current_token_digest" json:"current_token_digest"`
	NewSessionID       pgtype.UUID        `db:"new_session_id" json:"new_session_id"`
	NewTokenDigest     []byte             `db:"new_token_digest" json:"new_token_digest"`
	NewCsrfDigest      []byte             `db:"new_csrf_digest" json:"new_csrf_digest"`
	IdleExpiresAt      pgtype.Timestamptz `db:"idle_expires_at" json:"idle_expires_at"`
	AbsoluteExpiresAt  pgtype.Timestamptz `db:"absolute_expires_at" json:"absolute_expires_at"`
	AuditID            pgtype.UUID        `db:"audit_id" json:"audit_id"`
	RequestID          pgtype.UUID        `db:"request_id" json:"request_id"`
	CorrelationID      pgtype.UUID        `db:"correlation_id" json:"correlation_id"`
	IpAddress          netip.Addr         `db:"ip_address" json:"ip_address"`
	UserAgent          string             `db:"user_agent" json:"user_agent"`
}

func (q *Queries) RotateSession(ctx context.Context, arg RotateSessionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, rotateSession,
		arg.CurrentTokenDigest,
		arg.NewSessionID,
		arg.NewTokenDigest,
		arg.NewCsrfDigest,
		arg.IdleExpiresAt,
		arg.AbsoluteExpiresAt,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
	)
	var session_id pgtype.UUID
	err := row.Scan(&session_id)
	return session_id, err
}

const rotateSessionTenant = `-- name: RotateSessionTenant :one
SELECT app.rotate_auth_session_tenant(
  $1::bytea,
  $2::uuid,
  $3::bytea,
  $4::bytea,
  $5::uuid,
  $6::timestamptz,
  $7::timestamptz,
  $8::uuid,
  $9::uuid,
  $10::uuid,
  $11::inet,
  $12::text
) AS session_id
`

type RotateSessionTenantParams struct {
	CurrentTokenDigest []byte             `db:"current_token_digest" json:"current_token_digest"`
	NewSessionID       pgtype.UUID        `db:"new_session_id" json:"new_session_id"`
	NewTokenDigest     []byte             `db:"new_token_digest" json:"new_token_digest"`
	NewCsrfDigest      []byte             `db:"new_csrf_digest" json:"new_csrf_digest"`
	TenantID           pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	IdleExpiresAt      pgtype.Timestamptz `db:"idle_expires_at" json:"idle_expires_at"`
	AbsoluteExpiresAt  pgtype.Timestamptz `db:"absolute_expires_at" json:"absolute_expires_at"`
	AuditID            pgtype.UUID        `db:"audit_id" json:"audit_id"`
	RequestID          pgtype.UUID        `db:"request_id" json:"request_id"`
	CorrelationID      pgtype.UUID        `db:"correlation_id" json:"correlation_id"`
	IpAddress          netip.Addr         `db:"ip_address" json:"ip_address"`
	UserAgent          string             `db:"user_agent" json:"user_agent"`
}

func (q *Queries) RotateSessionTenant(ctx context.Context, arg RotateSessionTenantParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, rotateSessionTenant,
		arg.CurrentTokenDigest,
		arg.NewSessionID,
		arg.NewTokenDigest,
		arg.NewCsrfDigest,
		arg.TenantID,
		arg.IdleExpiresAt,
		arg.AbsoluteExpiresAt,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
	)
	var session_id pgtype.UUID
	err := row.Scan(&session_id)
	return session_id, err
}

const setUserContext = `-- name: SetUserContext :one
SELECT set_config('app.user_id', $1::uuid::text, true)::text AS user_id
`

type SetUserContextParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) SetUserContext(ctx context.Context, arg SetUserContextParams) (string, error) {
	row := q.db.QueryRow(ctx, setUserContext, arg.UserID)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const touchSession = `-- name: TouchSession :one
SELECT app.touch_auth_session(
  $1::bytea,
  $2::timestamptz
) AS touched
`

type TouchSessionParams struct {
	TokenDigest   []byte             `db:"token_digest" json:"token_digest"`
	IdleExpiresAt pgtype.Timestamptz `db:"idle_expires_at" json:"idle_expires_at"`
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) (bool, error) {
	row := q.db.QueryRow(ctx, touchSession, arg.TokenDigest, arg.IdleExpiresAt)
	var touched bool
	err := row.Scan(&touched)
	return touched, err
}

const verifyProtectedConfiguration = `-- name: VerifyProtectedConfiguration :one
SELECT app.verify_protected_configuration(
  $1::bytea,
  $2::bytea
) AS bootstrap_available
`

type VerifyProtectedConfigurationParams struct {
	AuthorityDigest   []byte `db:"authority_digest" json:"authority_digest"`
	MasterKeyVerifier []byte `db:"master_key_verifier" json:"master_key_verifier"`
}

func (q *Queries) VerifyProtectedConfiguration(ctx context.Context, arg VerifyProtectedConfigurationParams) (bool, error) {
	row := q.db.QueryRow(ctx, verifyProtectedConfiguration, arg.AuthorityDigest, arg.MasterKeyVerifier)
	var bootstrap_available bool
	err := row.Scan(&bootstrap_available)
	return bootstrap_available, err
}
