// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authorization.sql

package dbsql

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTenantAuthorizationSecurityGroupMember = `-- name: AddTenantAuthorizationSecurityGroupMember :one
SELECT result.result_resource_id::uuid AS result_resource_id,
       result.result_version::integer AS result_version,
       result.replayed::boolean AS replayed
FROM app.add_tenant_security_group_member(
  $1::uuid,
  $2::bytea,
  $3::uuid,
  $4::uuid,
  $5::text,
  $6::timestamptz,
  $7::uuid,
  $8::uuid,
  $9::uuid,
  $10::inet,
  nullif($11::text, ''),
  $12::text
) AS result(result_resource_id, result_version, replayed)
`

type AddTenantAuthorizationSecurityGroupMemberParams struct {
	GroupMembershipID    pgtype.UUID        `db:"group_membership_id" json:"group_membership_id"`
	IdempotencyKeyDigest []byte             `db:"idempotency_key_digest" json:"idempotency_key_digest"`
	GroupID              pgtype.UUID        `db:"group_id" json:"group_id"`
	TargetUserID         pgtype.UUID        `db:"target_user_id" json:"target_user_id"`
	Reason               string             `db:"reason" json:"reason"`
	ExpiresAt            pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	AuditID              pgtype.UUID        `db:"audit_id" json:"audit_id"`
	RequestID            pgtype.UUID        `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID        `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr         `db:"ip_address" json:"ip_address"`
	UserAgent            string             `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string             `db:"authentication_method" json:"authentication_method"`
}

type AddTenantAuthorizationSecurityGroupMemberRow struct {
	ResultResourceID pgtype.UUID `db:"result_resource_id" json:"result_resource_id"`
	ResultVersion    int32       `db:"result_version" json:"result_version"`
	Replayed         bool        `db:"replayed" json:"replayed"`
}

func (q *Queries) AddTenantAuthorizationSecurityGroupMember(ctx context.Context, arg AddTenantAuthorizationSecurityGroupMemberParams) (*AddTenantAuthorizationSecurityGroupMemberRow, error) {
	row := q.db.QueryRow(ctx, addTenantAuthorizationSecurityGroupMember,
		arg.GroupMembershipID,
		arg.IdempotencyKeyDigest,
		arg.GroupID,
		arg.TargetUserID,
		arg.Reason,
		arg.ExpiresAt,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
	)
	var i AddTenantAuthorizationSecurityGroupMemberRow
	err := row.Scan(&i.ResultResourceID, &i.ResultVersion, &i.Replayed)
	return &i, err
}

const archiveTenantAuthorizationRole = `-- name: ArchiveTenantAuthorizationRole :one
SELECT app.archive_tenant_role(
  $1::uuid,
  $2::integer,
  $3::uuid,
  $4::uuid,
  $5::uuid,
  $6::inet,
  nullif($7::text, ''),
  $8::text
) AS version
`

type ArchiveTenantAuthorizationRoleParams struct {
	RoleID               pgtype.UUID `db:"role_id" json:"role_id"`
	ExpectedVersion      int32       `db:"expected_version" json:"expected_version"`
	AuditID              pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
}

func (q *Queries) ArchiveTenantAuthorizationRole(ctx context.Context, arg ArchiveTenantAuthorizationRoleParams) (int32, error) {
	row := q.db.QueryRow(ctx, archiveTenantAuthorizationRole,
		arg.RoleID,
		arg.ExpectedVersion,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const archiveTenantAuthorizationSecurityGroup = `-- name: ArchiveTenantAuthorizationSecurityGroup :one
SELECT app.archive_tenant_security_group(
  $1::uuid,
  $2::integer,
  $3::uuid,
  $4::uuid,
  $5::uuid,
  $6::inet,
  nullif($7::text, ''),
  $8::text
) AS version
`

type ArchiveTenantAuthorizationSecurityGroupParams struct {
	GroupID              pgtype.UUID `db:"group_id" json:"group_id"`
	ExpectedVersion      int32       `db:"expected_version" json:"expected_version"`
	AuditID              pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
}

func (q *Queries) ArchiveTenantAuthorizationSecurityGroup(ctx context.Context, arg ArchiveTenantAuthorizationSecurityGroupParams) (int32, error) {
	row := q.db.QueryRow(ctx, archiveTenantAuthorizationSecurityGroup,
		arg.GroupID,
		arg.ExpectedVersion,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const changeTenantMembershipLifecycle = `-- name: ChangeTenantMembershipLifecycle :one
SELECT result.tenant_id::uuid AS tenant_id,
       result.membership_id::uuid AS membership_id,
       result.target_user_id::uuid AS target_user_id,
       result.previous_status::text AS previous_status,
       result.status::text AS status,
       result.lifecycle_revision::integer AS lifecycle_revision,
       result.updated_at::timestamptz AS updated_at,
       result.revoked_session_count::integer AS revoked_session_count,
       result.revoked_continuation_count::integer AS revoked_continuation_count,
       result.replayed::boolean AS replayed
FROM app.change_tenant_membership_lifecycle_v1(
  $1::uuid,
  $2::uuid,
  $3::text::membership_status,
  $4::integer,
  $5::text,
  $6::bytea,
  $7::uuid,
  $8::uuid,
  $9::uuid,
  $10::inet,
  nullif($11::text, ''),
  $12::text
) AS result(
  tenant_id, membership_id, target_user_id, previous_status, status,
  lifecycle_revision, updated_at, revoked_session_count,
  revoked_continuation_count, replayed
)
`

type ChangeTenantMembershipLifecycleParams struct {
	ActorSessionID       pgtype.UUID `db:"actor_session_id" json:"actor_session_id"`
	TargetUserID         pgtype.UUID `db:"target_user_id" json:"target_user_id"`
	TargetStatus         string      `db:"target_status" json:"target_status"`
	ExpectedRevision     int32       `db:"expected_revision" json:"expected_revision"`
	Reason               string      `db:"reason" json:"reason"`
	IdempotencyKeyDigest []byte      `db:"idempotency_key_digest" json:"idempotency_key_digest"`
	AuditID              pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
}

type ChangeTenantMembershipLifecycleRow struct {
	TenantID                 pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	MembershipID             pgtype.UUID        `db:"membership_id" json:"membership_id"`
	TargetUserID             pgtype.UUID        `db:"target_user_id" json:"target_user_id"`
	PreviousStatus           string             `db:"previous_status" json:"previous_status"`
	Status                   string             `db:"status" json:"status"`
	LifecycleRevision        int32              `db:"lifecycle_revision" json:"lifecycle_revision"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	RevokedSessionCount      int32              `db:"revoked_session_count" json:"revoked_session_count"`
	RevokedContinuationCount int32              `db:"revoked_continuation_count" json:"revoked_continuation_count"`
	Replayed                 bool               `db:"replayed" json:"replayed"`
}

func (q *Queries) ChangeTenantMembershipLifecycle(ctx context.Context, arg ChangeTenantMembershipLifecycleParams) (*ChangeTenantMembershipLifecycleRow, error) {
	row := q.db.QueryRow(ctx, changeTenantMembershipLifecycle,
		arg.ActorSessionID,
		arg.TargetUserID,
		arg.TargetStatus,
		arg.ExpectedRevision,
		arg.Reason,
		arg.IdempotencyKeyDigest,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
	)
	var i ChangeTenantMembershipLifecycleRow
	err := row.Scan(
		&i.TenantID,
		&i.MembershipID,
		&i.TargetUserID,
		&i.PreviousStatus,
		&i.Status,
		&i.LifecycleRevision,
		&i.UpdatedAt,
		&i.RevokedSessionCount,
		&i.RevokedContinuationCount,
		&i.Replayed,
	)
	return &i, err
}

const createTenantAuthorizationRole = `-- name: CreateTenantAuthorizationRole :one
SELECT result.result_resource_id::uuid AS result_resource_id,
       result.result_version::integer AS result_version,
       result.replayed::boolean AS replayed
FROM app.create_tenant_role(
  $1::uuid,
  $2::bytea,
  $3::text,
  $4::text,
  $5::text,
  $6::text[],
  $7::text[]::authorization_scope[],
  $8::text[],
  $9::text[]::authorization_scope[],
  $10::uuid,
  $11::uuid,
  $12::uuid,
  $13::inet,
  nullif($14::text, ''),
  $15::text
) AS result(result_resource_id, result_version, replayed)
`

type CreateTenantAuthorizationRoleParams struct {
	RoleID                   pgtype.UUID `db:"role_id" json:"role_id"`
	IdempotencyKeyDigest     []byte      `db:"idempotency_key_digest" json:"idempotency_key_digest"`
	RoleKey                  string      `db:"role_key" json:"role_key"`
	RoleName                 string      `db:"role_name" json:"role_name"`
	RoleDescription          string      `db:"role_description" json:"role_description"`
	PermissionKeys           []string    `db:"permission_keys" json:"permission_keys"`
	PermissionScopes         []string    `db:"permission_scopes" json:"permission_scopes"`
	DelegationPermissionKeys []string    `db:"delegation_permission_keys" json:"delegation_permission_keys"`
	DelegationScopes         []string    `db:"delegation_scopes" json:"delegation_scopes"`
	AuditID                  pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID                pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID            pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress                netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent                string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod     string      `db:"authentication_method" json:"authentication_method"`
}

type CreateTenantAuthorizationRoleRow struct {
	ResultResourceID pgtype.UUID `db:"result_resource_id" json:"result_resource_id"`
	ResultVersion    int32       `db:"result_version" json:"result_version"`
	Replayed         bool        `db:"replayed" json:"replayed"`
}

func (q *Queries) CreateTenantAuthorizationRole(ctx context.Context, arg CreateTenantAuthorizationRoleParams) (*CreateTenantAuthorizationRoleRow, error) {
	row := q.db.QueryRow(ctx, createTenantAuthorizationRole,
		arg.RoleID,
		arg.IdempotencyKeyDigest,
		arg.RoleKey,
		arg.RoleName,
		arg.RoleDescription,
		arg.PermissionKeys,
		arg.PermissionScopes,
		arg.DelegationPermissionKeys,
		arg.DelegationScopes,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
	)
	var i CreateTenantAuthorizationRoleRow
	err := row.Scan(&i.ResultResourceID, &i.ResultVersion, &i.Replayed)
	return &i, err
}

const createTenantAuthorizationSecurityGroup = `-- name: CreateTenantAuthorizationSecurityGroup :one
SELECT result.result_resource_id::uuid AS result_resource_id,
       result.result_version::integer AS result_version,
       result.replayed::boolean AS replayed
FROM app.create_tenant_security_group(
  $1::uuid,
  $2::bytea,
  $3::text,
  $4::text,
  $5::text,
  $6::uuid,
  $7::uuid,
  $8::uuid,
  $9::inet,
  nullif($10::text, ''),
  $11::text
) AS result(result_resource_id, result_version, replayed)
`

type CreateTenantAuthorizationSecurityGroupParams struct {
	GroupID              pgtype.UUID `db:"group_id" json:"group_id"`
	IdempotencyKeyDigest []byte      `db:"idempotency_key_digest" json:"idempotency_key_digest"`
	GroupKey             string      `db:"group_key" json:"group_key"`
	GroupName            string      `db:"group_name" json:"group_name"`
	GroupDescription     string      `db:"group_description" json:"group_description"`
	AuditID              pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
}

type CreateTenantAuthorizationSecurityGroupRow struct {
	ResultResourceID pgtype.UUID `db:"result_resource_id" json:"result_resource_id"`
	ResultVersion    int32       `db:"result_version" json:"result_version"`
	Replayed         bool        `db:"replayed" json:"replayed"`
}

func (q *Queries) CreateTenantAuthorizationSecurityGroup(ctx context.Context, arg CreateTenantAuthorizationSecurityGroupParams) (*CreateTenantAuthorizationSecurityGroupRow, error) {
	row := q.db.QueryRow(ctx, createTenantAuthorizationSecurityGroup,
		arg.GroupID,
		arg.IdempotencyKeyDigest,
		arg.GroupKey,
		arg.GroupName,
		arg.GroupDescription,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
	)
	var i CreateTenantAuthorizationSecurityGroupRow
	err := row.Scan(&i.ResultResourceID, &i.ResultVersion, &i.Replayed)
	return &i, err
}

const getCurrentTenantAuthorizationContext = `-- name: GetCurrentTenantAuthorizationContext :one
SELECT authority.tenant_id::uuid AS tenant_id,
       authority.membership_id::uuid AS membership_id,
       authority.authorization_revision::bigint AS authorization_revision,
       authority.membership_status::text AS membership_status,
       authority.compatibility_role::text AS compatibility_role,
       authority.evaluated_at::timestamptz AS evaluated_at
FROM app.get_current_tenant_authorization_context() AS authority(
  tenant_id, membership_id, authorization_revision, membership_status,
  compatibility_role, evaluated_at
)
`

type GetCurrentTenantAuthorizationContextRow struct {
	TenantID              pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	MembershipID          pgtype.UUID        `db:"membership_id" json:"membership_id"`
	AuthorizationRevision int64              `db:"authorization_revision" json:"authorization_revision"`
	MembershipStatus      string             `db:"membership_status" json:"membership_status"`
	CompatibilityRole     string             `db:"compatibility_role" json:"compatibility_role"`
	EvaluatedAt           pgtype.Timestamptz `db:"evaluated_at" json:"evaluated_at"`
}

func (q *Queries) GetCurrentTenantAuthorizationContext(ctx context.Context) (*GetCurrentTenantAuthorizationContextRow, error) {
	row := q.db.QueryRow(ctx, getCurrentTenantAuthorizationContext)
	var i GetCurrentTenantAuthorizationContextRow
	err := row.Scan(
		&i.TenantID,
		&i.MembershipID,
		&i.AuthorizationRevision,
		&i.MembershipStatus,
		&i.CompatibilityRole,
		&i.EvaluatedAt,
	)
	return &i, err
}

const getTenantAuthorizationRole = `-- name: GetTenantAuthorizationRole :one
SELECT role.role_id::uuid AS role_id,
       role.role_key::text AS role_key,
       role.display_name::text AS display_name,
       role.description::text AS description,
       role.principal_kind::text AS principal_kind,
       role.system_role::boolean AS system_role,
       role.protected_role::boolean AS protected_role,
       role.version::integer AS version,
       role.archived_at::timestamptz AS archived_at,
       role.created_at::timestamptz AS created_at,
       role.updated_at::timestamptz AS updated_at
FROM app.get_tenant_role_v3($1::uuid) AS role(
  role_id, role_key, display_name, description, principal_kind, system_role, protected_role,
  version, archived_at, created_at, updated_at
)
`

type GetTenantAuthorizationRoleParams struct {
	RoleID pgtype.UUID `db:"role_id" json:"role_id"`
}

type GetTenantAuthorizationRoleRow struct {
	RoleID        pgtype.UUID        `db:"role_id" json:"role_id"`
	RoleKey       string             `db:"role_key" json:"role_key"`
	DisplayName   string             `db:"display_name" json:"display_name"`
	Description   string             `db:"description" json:"description"`
	PrincipalKind string             `db:"principal_kind" json:"principal_kind"`
	SystemRole    bool               `db:"system_role" json:"system_role"`
	ProtectedRole bool               `db:"protected_role" json:"protected_role"`
	Version       int32              `db:"version" json:"version"`
	ArchivedAt    pgtype.Timestamptz `db:"archived_at" json:"archived_at"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetTenantAuthorizationRole(ctx context.Context, arg GetTenantAuthorizationRoleParams) (*GetTenantAuthorizationRoleRow, error) {
	row := q.db.QueryRow(ctx, getTenantAuthorizationRole, arg.RoleID)
	var i GetTenantAuthorizationRoleRow
	err := row.Scan(
		&i.RoleID,
		&i.RoleKey,
		&i.DisplayName,
		&i.Description,
		&i.PrincipalKind,
		&i.SystemRole,
		&i.ProtectedRole,
		&i.Version,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getTenantAuthorizationRolePolicy = `-- name: GetTenantAuthorizationRolePolicy :many
SELECT policy.permission_key::text AS permission_key,
       policy.scope::text AS scope,
       policy.delegable::boolean AS delegable
FROM app.get_tenant_role_policy_v3(
  $1::uuid
) AS policy(permission_key, scope, delegable)
`

type GetTenantAuthorizationRolePolicyParams struct {
	RoleID pgtype.UUID `db:"role_id" json:"role_id"`
}

type GetTenantAuthorizationRolePolicyRow struct {
	PermissionKey string `db:"permission_key" json:"permission_key"`
	Scope         string `db:"scope" json:"scope"`
	Delegable     bool   `db:"delegable" json:"delegable"`
}

func (q *Queries) GetTenantAuthorizationRolePolicy(ctx context.Context, arg GetTenantAuthorizationRolePolicyParams) ([]*GetTenantAuthorizationRolePolicyRow, error) {
	rows, err := q.db.Query(ctx, getTenantAuthorizationRolePolicy, arg.RoleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetTenantAuthorizationRolePolicyRow
	for rows.Next() {
		var i GetTenantAuthorizationRolePolicyRow
		if err := rows.Scan(&i.PermissionKey, &i.Scope, &i.Delegable); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTenantAuthorizationSecurityGroup = `-- name: GetTenantAuthorizationSecurityGroup :one
SELECT security_group.group_id::uuid AS group_id,
       security_group.group_key::text AS group_key,
       security_group.group_name::text AS group_name,
       security_group.group_description::text AS group_description,
       security_group.archived_at::timestamptz AS archived_at,
       security_group.version::integer AS version,
       security_group.created_at::timestamptz AS created_at,
       security_group.updated_at::timestamptz AS updated_at
FROM app.get_tenant_security_group(
  $1::uuid
) AS security_group(
  group_id, group_key, group_name, group_description,
  created_by_membership_id, created_by_user_id, archived_at, version,
  created_at, updated_at
)
`

type GetTenantAuthorizationSecurityGroupParams struct {
	GroupID pgtype.UUID `db:"group_id" json:"group_id"`
}

type GetTenantAuthorizationSecurityGroupRow struct {
	GroupID          pgtype.UUID        `db:"group_id" json:"group_id"`
	GroupKey         string             `db:"group_key" json:"group_key"`
	GroupName        string             `db:"group_name" json:"group_name"`
	GroupDescription string             `db:"group_description" json:"group_description"`
	ArchivedAt       pgtype.Timestamptz `db:"archived_at" json:"archived_at"`
	Version          int32              `db:"version" json:"version"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetTenantAuthorizationSecurityGroup(ctx context.Context, arg GetTenantAuthorizationSecurityGroupParams) (*GetTenantAuthorizationSecurityGroupRow, error) {
	row := q.db.QueryRow(ctx, getTenantAuthorizationSecurityGroup, arg.GroupID)
	var i GetTenantAuthorizationSecurityGroupRow
	err := row.Scan(
		&i.GroupID,
		&i.GroupKey,
		&i.GroupName,
		&i.GroupDescription,
		&i.ArchivedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getTenantAuthorizationSecurityGroupMembership = `-- name: GetTenantAuthorizationSecurityGroupMembership :one
SELECT edge.group_membership_id::uuid AS group_membership_id,
       edge.group_id::uuid AS group_id,
       edge.group_key::text AS group_key,
       edge.group_name::text AS group_name,
       edge.group_description::text AS group_description,
       edge.group_archived_at::timestamptz AS group_archived_at,
       edge.group_version::integer AS group_version,
       edge.group_created_at::timestamptz AS group_created_at,
       edge.group_updated_at::timestamptz AS group_updated_at,
       edge.membership_id::uuid AS membership_id,
       edge.target_user_id::uuid AS target_user_id,
       coalesce(edge.email, '')::text AS email,
       edge.display_name::text AS display_name,
       edge.membership_status::text AS membership_status,
       edge.compatibility_role::text AS compatibility_role,
       edge.user_active::boolean AS user_active,
       edge.membership_created_at::timestamptz AS membership_created_at,
       edge.membership_updated_at::timestamptz AS membership_updated_at,
       edge.source_id::uuid AS source_id,
       edge.source_kind::text AS source_kind,
       edge.source_authoritative::boolean AS source_authoritative,
       edge.source_retired_at::timestamptz AS source_retired_at,
       edge.granted_by_user_id::uuid AS granted_by_user_id,
       edge.grant_reason::text AS grant_reason,
       edge.granted_at::timestamptz AS granted_at,
       edge.expires_at::timestamptz AS expires_at,
       edge.revoked_at::timestamptz AS revoked_at,
       edge.revoked_by_user_id::uuid AS revoked_by_user_id,
       coalesce(edge.revoke_reason::text, '')::text AS revoke_reason,
       edge.grant_state::text AS grant_state,
       edge.version::integer AS version,
       edge.updated_at::timestamptz AS updated_at,
       edge.managed_by_authorization_api::boolean AS managed_by_authorization_api,
       edge.membership_lifecycle_revision::integer AS membership_lifecycle_revision
FROM app.get_tenant_security_group_membership_v4(
  $1::uuid,
  $2::uuid
) AS edge(
  group_membership_id, group_id, group_key, group_name, group_description,
  group_archived_at, group_version, group_created_at, group_updated_at,
  membership_id, target_user_id, email, display_name, membership_status,
  compatibility_role, user_active, membership_created_at,
  membership_updated_at, source_id, source_kind, source_authoritative,
  source_retired_at, granted_by_membership_id, granted_by_user_id,
  grant_reason, granted_at, expires_at, revoked_at,
  revoked_by_membership_id, revoked_by_user_id, revoke_reason, grant_state,
  version, updated_at, managed_by_authorization_api, membership_lifecycle_revision
)
`

type GetTenantAuthorizationSecurityGroupMembershipParams struct {
	GroupID           pgtype.UUID `db:"group_id" json:"group_id"`
	GroupMembershipID pgtype.UUID `db:"group_membership_id" json:"group_membership_id"`
}

type GetTenantAuthorizationSecurityGroupMembershipRow struct {
	GroupMembershipID           pgtype.UUID        `db:"group_membership_id" json:"group_membership_id"`
	GroupID                     pgtype.UUID        `db:"group_id" json:"group_id"`
	GroupKey                    string             `db:"group_key" json:"group_key"`
	GroupName                   string             `db:"group_name" json:"group_name"`
	GroupDescription            string             `db:"group_description" json:"group_description"`
	GroupArchivedAt             pgtype.Timestamptz `db:"group_archived_at" json:"group_archived_at"`
	GroupVersion                int32              `db:"group_version" json:"group_version"`
	GroupCreatedAt              pgtype.Timestamptz `db:"group_created_at" json:"group_created_at"`
	GroupUpdatedAt              pgtype.Timestamptz `db:"group_updated_at" json:"group_updated_at"`
	MembershipID                pgtype.UUID        `db:"membership_id" json:"membership_id"`
	TargetUserID                pgtype.UUID        `db:"target_user_id" json:"target_user_id"`
	Email                       string             `db:"email" json:"email"`
	DisplayName                 string             `db:"display_name" json:"display_name"`
	MembershipStatus            string             `db:"membership_status" json:"membership_status"`
	CompatibilityRole           string             `db:"compatibility_role" json:"compatibility_role"`
	UserActive                  bool               `db:"user_active" json:"user_active"`
	MembershipCreatedAt         pgtype.Timestamptz `db:"membership_created_at" json:"membership_created_at"`
	MembershipUpdatedAt         pgtype.Timestamptz `db:"membership_updated_at" json:"membership_updated_at"`
	SourceID                    pgtype.UUID        `db:"source_id" json:"source_id"`
	SourceKind                  string             `db:"source_kind" json:"source_kind"`
	SourceAuthoritative         bool               `db:"source_authoritative" json:"source_authoritative"`
	SourceRetiredAt             pgtype.Timestamptz `db:"source_retired_at" json:"source_retired_at"`
	GrantedByUserID             pgtype.UUID        `db:"granted_by_user_id" json:"granted_by_user_id"`
	GrantReason                 string             `db:"grant_reason" json:"grant_reason"`
	GrantedAt                   pgtype.Timestamptz `db:"granted_at" json:"granted_at"`
	ExpiresAt                   pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt                   pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RevokedByUserID             pgtype.UUID        `db:"revoked_by_user_id" json:"revoked_by_user_id"`
	RevokeReason                string             `db:"revoke_reason" json:"revoke_reason"`
	GrantState                  string             `db:"grant_state" json:"grant_state"`
	Version                     int32              `db:"version" json:"version"`
	UpdatedAt                   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ManagedByAuthorizationApi   bool               `db:"managed_by_authorization_api" json:"managed_by_authorization_api"`
	MembershipLifecycleRevision int32              `db:"membership_lifecycle_revision" json:"membership_lifecycle_revision"`
}

func (q *Queries) GetTenantAuthorizationSecurityGroupMembership(ctx context.Context, arg GetTenantAuthorizationSecurityGroupMembershipParams) (*GetTenantAuthorizationSecurityGroupMembershipRow, error) {
	row := q.db.QueryRow(ctx, getTenantAuthorizationSecurityGroupMembership, arg.GroupID, arg.GroupMembershipID)
	var i GetTenantAuthorizationSecurityGroupMembershipRow
	err := row.Scan(
		&i.GroupMembershipID,
		&i.GroupID,
		&i.GroupKey,
		&i.GroupName,
		&i.GroupDescription,
		&i.GroupArchivedAt,
		&i.GroupVersion,
		&i.GroupCreatedAt,
		&i.GroupUpdatedAt,
		&i.MembershipID,
		&i.TargetUserID,
		&i.Email,
		&i.DisplayName,
		&i.MembershipStatus,
		&i.CompatibilityRole,
		&i.UserActive,
		&i.MembershipCreatedAt,
		&i.MembershipUpdatedAt,
		&i.SourceID,
		&i.SourceKind,
		&i.SourceAuthoritative,
		&i.SourceRetiredAt,
		&i.GrantedByUserID,
		&i.GrantReason,
		&i.GrantedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedByUserID,
		&i.RevokeReason,
		&i.GrantState,
		&i.Version,
		&i.UpdatedAt,
		&i.ManagedByAuthorizationApi,
		&i.MembershipLifecycleRevision,
	)
	return &i, err
}

const getTenantAuthorizationSecurityGroupRoleGrant = `-- name: GetTenantAuthorizationSecurityGroupRoleGrant :one
SELECT edge.group_role_grant_id::uuid AS group_role_grant_id,
       edge.group_id::uuid AS group_id,
       edge.group_key::text AS group_key,
       edge.group_name::text AS group_name,
       edge.group_description::text AS group_description,
       edge.group_archived_at::timestamptz AS group_archived_at,
       edge.group_version::integer AS group_version,
       edge.group_created_at::timestamptz AS group_created_at,
       edge.group_updated_at::timestamptz AS group_updated_at,
       edge.role_id::uuid AS role_id,
       edge.role_key::text AS role_key,
       edge.role_name::text AS role_name,
       edge.role_description::text AS role_description,
       edge.role_system::boolean AS role_system,
       edge.role_protected::boolean AS role_protected,
       edge.role_archived_at::timestamptz AS role_archived_at,
       edge.role_version::integer AS role_version,
       edge.role_created_at::timestamptz AS role_created_at,
       edge.role_updated_at::timestamptz AS role_updated_at,
       edge.source_id::uuid AS source_id,
       edge.source_kind::text AS source_kind,
       edge.source_authoritative::boolean AS source_authoritative,
       edge.source_retired_at::timestamptz AS source_retired_at,
       edge.granted_by_user_id::uuid AS granted_by_user_id,
       edge.grant_reason::text AS grant_reason,
       edge.granted_at::timestamptz AS granted_at,
       edge.expires_at::timestamptz AS expires_at,
       edge.revoked_at::timestamptz AS revoked_at,
       edge.revoked_by_user_id::uuid AS revoked_by_user_id,
       coalesce(edge.revoke_reason::text, '')::text AS revoke_reason,
       edge.grant_state::text AS grant_state,
       edge.version::integer AS version,
       edge.updated_at::timestamptz AS updated_at,
       edge.managed_by_authorization_api::boolean AS managed_by_authorization_api
FROM app.get_tenant_security_group_role_grant_v2(
  $1::uuid,
  $2::uuid
) AS edge(
  group_role_grant_id, group_id, group_key, group_name, group_description,
  group_archived_at, group_version, group_created_at, group_updated_at,
  role_id, role_key, role_name, role_description, role_system,
  role_protected, role_archived_at, role_version, role_created_at,
  role_updated_at, source_id, source_kind, source_authoritative,
  source_retired_at, granted_by_membership_id, granted_by_user_id,
  grant_reason, granted_at, expires_at, revoked_at,
  revoked_by_membership_id, revoked_by_user_id, revoke_reason, grant_state,
  version, updated_at, managed_by_authorization_api
)
`

type GetTenantAuthorizationSecurityGroupRoleGrantParams struct {
	GroupID          pgtype.UUID `db:"group_id" json:"group_id"`
	GroupRoleGrantID pgtype.UUID `db:"group_role_grant_id" json:"group_role_grant_id"`
}

type GetTenantAuthorizationSecurityGroupRoleGrantRow struct {
	GroupRoleGrantID          pgtype.UUID        `db:"group_role_grant_id" json:"group_role_grant_id"`
	GroupID                   pgtype.UUID        `db:"group_id" json:"group_id"`
	GroupKey                  string             `db:"group_key" json:"group_key"`
	GroupName                 string             `db:"group_name" json:"group_name"`
	GroupDescription          string             `db:"group_description" json:"group_description"`
	GroupArchivedAt           pgtype.Timestamptz `db:"group_archived_at" json:"group_archived_at"`
	GroupVersion              int32              `db:"group_version" json:"group_version"`
	GroupCreatedAt            pgtype.Timestamptz `db:"group_created_at" json:"group_created_at"`
	GroupUpdatedAt            pgtype.Timestamptz `db:"group_updated_at" json:"group_updated_at"`
	RoleID                    pgtype.UUID        `db:"role_id" json:"role_id"`
	RoleKey                   string             `db:"role_key" json:"role_key"`
	RoleName                  string             `db:"role_name" json:"role_name"`
	RoleDescription           string             `db:"role_description" json:"role_description"`
	RoleSystem                bool               `db:"role_system" json:"role_system"`
	RoleProtected             bool               `db:"role_protected" json:"role_protected"`
	RoleArchivedAt            pgtype.Timestamptz `db:"role_archived_at" json:"role_archived_at"`
	RoleVersion               int32              `db:"role_version" json:"role_version"`
	RoleCreatedAt             pgtype.Timestamptz `db:"role_created_at" json:"role_created_at"`
	RoleUpdatedAt             pgtype.Timestamptz `db:"role_updated_at" json:"role_updated_at"`
	SourceID                  pgtype.UUID        `db:"source_id" json:"source_id"`
	SourceKind                string             `db:"source_kind" json:"source_kind"`
	SourceAuthoritative       bool               `db:"source_authoritative" json:"source_authoritative"`
	SourceRetiredAt           pgtype.Timestamptz `db:"source_retired_at" json:"source_retired_at"`
	GrantedByUserID           pgtype.UUID        `db:"granted_by_user_id" json:"granted_by_user_id"`
	GrantReason               string             `db:"grant_reason" json:"grant_reason"`
	GrantedAt                 pgtype.Timestamptz `db:"granted_at" json:"granted_at"`
	ExpiresAt                 pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt                 pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RevokedByUserID           pgtype.UUID        `db:"revoked_by_user_id" json:"revoked_by_user_id"`
	RevokeReason              string             `db:"revoke_reason" json:"revoke_reason"`
	GrantState                string             `db:"grant_state" json:"grant_state"`
	Version                   int32              `db:"version" json:"version"`
	UpdatedAt                 pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ManagedByAuthorizationApi bool               `db:"managed_by_authorization_api" json:"managed_by_authorization_api"`
}

func (q *Queries) GetTenantAuthorizationSecurityGroupRoleGrant(ctx context.Context, arg GetTenantAuthorizationSecurityGroupRoleGrantParams) (*GetTenantAuthorizationSecurityGroupRoleGrantRow, error) {
	row := q.db.QueryRow(ctx, getTenantAuthorizationSecurityGroupRoleGrant, arg.GroupID, arg.GroupRoleGrantID)
	var i GetTenantAuthorizationSecurityGroupRoleGrantRow
	err := row.Scan(
		&i.GroupRoleGrantID,
		&i.GroupID,
		&i.GroupKey,
		&i.GroupName,
		&i.GroupDescription,
		&i.GroupArchivedAt,
		&i.GroupVersion,
		&i.GroupCreatedAt,
		&i.GroupUpdatedAt,
		&i.RoleID,
		&i.RoleKey,
		&i.RoleName,
		&i.RoleDescription,
		&i.RoleSystem,
		&i.RoleProtected,
		&i.RoleArchivedAt,
		&i.RoleVersion,
		&i.RoleCreatedAt,
		&i.RoleUpdatedAt,
		&i.SourceID,
		&i.SourceKind,
		&i.SourceAuthoritative,
		&i.SourceRetiredAt,
		&i.GrantedByUserID,
		&i.GrantReason,
		&i.GrantedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedByUserID,
		&i.RevokeReason,
		&i.GrantState,
		&i.Version,
		&i.UpdatedAt,
		&i.ManagedByAuthorizationApi,
	)
	return &i, err
}

const getTenantMembershipRoleGrant = `-- name: GetTenantMembershipRoleGrant :one
SELECT role_grant.grant_id::uuid AS grant_id,
       role_grant.membership_id::uuid AS membership_id,
       role_grant.target_user_id::uuid AS target_user_id,
       role_grant.role_id::uuid AS role_id,
       role_grant.role_key::text AS role_key,
       role_grant.role_name::text AS role_name,
       role_grant.role_description::text AS role_description,
       role_grant.role_system::boolean AS role_system,
       role_grant.role_archived_at::timestamptz AS role_archived_at,
       role_grant.role_version::integer AS role_version,
       role_grant.role_created_at::timestamptz AS role_created_at,
       role_grant.role_updated_at::timestamptz AS role_updated_at,
       role_grant.source_id::uuid AS source_id,
       role_grant.source_kind::text AS source_kind,
       role_grant.source_authoritative::boolean AS source_authoritative,
       role_grant.source_retired_at::timestamptz AS source_retired_at,
       role_grant.managed_by_authorization_api::boolean AS managed_by_authorization_api,
       role_grant.source_type::text AS source_type,
       role_grant.granted_by_membership_id::uuid AS granted_by_membership_id,
       role_grant.granted_by_user_id::uuid AS granted_by_user_id,
       role_grant.grant_reason::text AS grant_reason,
       role_grant.granted_at::timestamptz AS granted_at,
       role_grant.expires_at::timestamptz AS expires_at,
       role_grant.revoked_at::timestamptz AS revoked_at,
       role_grant.revoked_by_membership_id::uuid AS revoked_by_membership_id,
       role_grant.revoked_by_user_id::uuid AS revoked_by_user_id,
       coalesce(role_grant.revoke_reason::text, '')::text AS revoke_reason,
       role_grant.grant_state::text AS grant_state,
       role_grant.version::integer AS version,
       role_grant.updated_at::timestamptz AS updated_at
FROM app.get_tenant_membership_role_grant_v2(
  $1::uuid
) AS role_grant(
  grant_id, membership_id, target_user_id, role_id, role_key, role_name,
  role_description, role_system, role_archived_at, role_version,
  role_created_at, role_updated_at, source_id, source_kind,
  source_authoritative, source_retired_at, managed_by_authorization_api,
  source_type,
  granted_by_membership_id, granted_by_user_id, grant_reason, granted_at,
  expires_at, revoked_at, revoked_by_membership_id, revoked_by_user_id,
  revoke_reason, grant_state, version, updated_at
)
`

type GetTenantMembershipRoleGrantParams struct {
	GrantID pgtype.UUID `db:"grant_id" json:"grant_id"`
}

type GetTenantMembershipRoleGrantRow struct {
	GrantID                   pgtype.UUID        `db:"grant_id" json:"grant_id"`
	MembershipID              pgtype.UUID        `db:"membership_id" json:"membership_id"`
	TargetUserID              pgtype.UUID        `db:"target_user_id" json:"target_user_id"`
	RoleID                    pgtype.UUID        `db:"role_id" json:"role_id"`
	RoleKey                   string             `db:"role_key" json:"role_key"`
	RoleName                  string             `db:"role_name" json:"role_name"`
	RoleDescription           string             `db:"role_description" json:"role_description"`
	RoleSystem                bool               `db:"role_system" json:"role_system"`
	RoleArchivedAt            pgtype.Timestamptz `db:"role_archived_at" json:"role_archived_at"`
	RoleVersion               int32              `db:"role_version" json:"role_version"`
	RoleCreatedAt             pgtype.Timestamptz `db:"role_created_at" json:"role_created_at"`
	RoleUpdatedAt             pgtype.Timestamptz `db:"role_updated_at" json:"role_updated_at"`
	SourceID                  pgtype.UUID        `db:"source_id" json:"source_id"`
	SourceKind                string             `db:"source_kind" json:"source_kind"`
	SourceAuthoritative       bool               `db:"source_authoritative" json:"source_authoritative"`
	SourceRetiredAt           pgtype.Timestamptz `db:"source_retired_at" json:"source_retired_at"`
	ManagedByAuthorizationApi bool               `db:"managed_by_authorization_api" json:"managed_by_authorization_api"`
	SourceType                string             `db:"source_type" json:"source_type"`
	GrantedByMembershipID     pgtype.UUID        `db:"granted_by_membership_id" json:"granted_by_membership_id"`
	GrantedByUserID           pgtype.UUID        `db:"granted_by_user_id" json:"granted_by_user_id"`
	GrantReason               string             `db:"grant_reason" json:"grant_reason"`
	GrantedAt                 pgtype.Timestamptz `db:"granted_at" json:"granted_at"`
	ExpiresAt                 pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt                 pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RevokedByMembershipID     pgtype.UUID        `db:"revoked_by_membership_id" json:"revoked_by_membership_id"`
	RevokedByUserID           pgtype.UUID        `db:"revoked_by_user_id" json:"revoked_by_user_id"`
	RevokeReason              string             `db:"revoke_reason" json:"revoke_reason"`
	GrantState                string             `db:"grant_state" json:"grant_state"`
	Version                   int32              `db:"version" json:"version"`
	UpdatedAt                 pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetTenantMembershipRoleGrant(ctx context.Context, arg GetTenantMembershipRoleGrantParams) (*GetTenantMembershipRoleGrantRow, error) {
	row := q.db.QueryRow(ctx, getTenantMembershipRoleGrant, arg.GrantID)
	var i GetTenantMembershipRoleGrantRow
	err := row.Scan(
		&i.GrantID,
		&i.MembershipID,
		&i.TargetUserID,
		&i.RoleID,
		&i.RoleKey,
		&i.RoleName,
		&i.RoleDescription,
		&i.RoleSystem,
		&i.RoleArchivedAt,
		&i.RoleVersion,
		&i.RoleCreatedAt,
		&i.RoleUpdatedAt,
		&i.SourceID,
		&i.SourceKind,
		&i.SourceAuthoritative,
		&i.SourceRetiredAt,
		&i.ManagedByAuthorizationApi,
		&i.SourceType,
		&i.GrantedByMembershipID,
		&i.GrantedByUserID,
		&i.GrantReason,
		&i.GrantedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedByMembershipID,
		&i.RevokedByUserID,
		&i.RevokeReason,
		&i.GrantState,
		&i.Version,
		&i.UpdatedAt,
	)
	return &i, err
}

const grantTenantAuthorizationSecurityGroupRole = `-- name: GrantTenantAuthorizationSecurityGroupRole :one
SELECT result.result_resource_id::uuid AS result_resource_id,
       result.result_version::integer AS result_version,
       result.replayed::boolean AS replayed
FROM app.grant_tenant_human_security_group_role_v1(
  $1::uuid,
  $2::bytea,
  $3::uuid,
  $4::uuid,
  $5::text,
  $6::timestamptz,
  $7::uuid,
  $8::uuid,
  $9::uuid,
  $10::inet,
  nullif($11::text, ''),
  $12::text
) AS result(result_resource_id, result_version, replayed)
`

type GrantTenantAuthorizationSecurityGroupRoleParams struct {
	GroupRoleGrantID     pgtype.UUID        `db:"group_role_grant_id" json:"group_role_grant_id"`
	IdempotencyKeyDigest []byte             `db:"idempotency_key_digest" json:"idempotency_key_digest"`
	GroupID              pgtype.UUID        `db:"group_id" json:"group_id"`
	RoleID               pgtype.UUID        `db:"role_id" json:"role_id"`
	Reason               string             `db:"reason" json:"reason"`
	ExpiresAt            pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	AuditID              pgtype.UUID        `db:"audit_id" json:"audit_id"`
	RequestID            pgtype.UUID        `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID        `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr         `db:"ip_address" json:"ip_address"`
	UserAgent            string             `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string             `db:"authentication_method" json:"authentication_method"`
}

type GrantTenantAuthorizationSecurityGroupRoleRow struct {
	ResultResourceID pgtype.UUID `db:"result_resource_id" json:"result_resource_id"`
	ResultVersion    int32       `db:"result_version" json:"result_version"`
	Replayed         bool        `db:"replayed" json:"replayed"`
}

func (q *Queries) GrantTenantAuthorizationSecurityGroupRole(ctx context.Context, arg GrantTenantAuthorizationSecurityGroupRoleParams) (*GrantTenantAuthorizationSecurityGroupRoleRow, error) {
	row := q.db.QueryRow(ctx, grantTenantAuthorizationSecurityGroupRole,
		arg.GroupRoleGrantID,
		arg.IdempotencyKeyDigest,
		arg.GroupID,
		arg.RoleID,
		arg.Reason,
		arg.ExpiresAt,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
	)
	var i GrantTenantAuthorizationSecurityGroupRoleRow
	err := row.Scan(&i.ResultResourceID, &i.ResultVersion, &i.Replayed)
	return &i, err
}

const grantTenantUserRole = `-- name: GrantTenantUserRole :one
SELECT result.result_resource_id::uuid AS result_resource_id,
       result.result_version::integer AS result_version,
       result.replayed::boolean AS replayed
FROM app.grant_tenant_human_user_role_v1(
  $1::uuid,
  $2::bytea,
  $3::uuid,
  $4::uuid,
  $5::text,
  $6::timestamptz,
  $7::uuid,
  $8::uuid,
  $9::uuid,
  $10::inet,
  nullif($11::text, ''),
  $12::text
) AS result(result_resource_id, result_version, replayed)
`

type GrantTenantUserRoleParams struct {
	GrantID              pgtype.UUID        `db:"grant_id" json:"grant_id"`
	IdempotencyKeyDigest []byte             `db:"idempotency_key_digest" json:"idempotency_key_digest"`
	TargetUserID         pgtype.UUID        `db:"target_user_id" json:"target_user_id"`
	RoleID               pgtype.UUID        `db:"role_id" json:"role_id"`
	Reason               string             `db:"reason" json:"reason"`
	ExpiresAt            pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	AuditID              pgtype.UUID        `db:"audit_id" json:"audit_id"`
	RequestID            pgtype.UUID        `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID        `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr         `db:"ip_address" json:"ip_address"`
	UserAgent            string             `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string             `db:"authentication_method" json:"authentication_method"`
}

type GrantTenantUserRoleRow struct {
	ResultResourceID pgtype.UUID `db:"result_resource_id" json:"result_resource_id"`
	ResultVersion    int32       `db:"result_version" json:"result_version"`
	Replayed         bool        `db:"replayed" json:"replayed"`
}

func (q *Queries) GrantTenantUserRole(ctx context.Context, arg GrantTenantUserRoleParams) (*GrantTenantUserRoleRow, error) {
	row := q.db.QueryRow(ctx, grantTenantUserRole,
		arg.GrantID,
		arg.IdempotencyKeyDigest,
		arg.TargetUserID,
		arg.RoleID,
		arg.Reason,
		arg.ExpiresAt,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
	)
	var i GrantTenantUserRoleRow
	err := row.Scan(&i.ResultResourceID, &i.ResultVersion, &i.Replayed)
	return &i, err
}

const listTenantAuthorizationRoles = `-- name: ListTenantAuthorizationRoles :many
SELECT role.role_id::uuid AS role_id,
       role.role_key::text AS role_key,
       role.display_name::text AS display_name,
       role.description::text AS description,
       role.principal_kind::text AS principal_kind,
       role.system_role::boolean AS system_role,
       role.protected_role::boolean AS protected_role,
       role.version::integer AS version,
       role.archived_at::timestamptz AS archived_at,
       role.created_at::timestamptz AS created_at,
       role.updated_at::timestamptz AS updated_at
FROM app.list_tenant_roles_v3(
  $1::uuid,
  $2::boolean,
  $3::integer
) AS role(
  role_id, role_key, display_name, description, principal_kind, system_role, protected_role,
  version, archived_at, created_at, updated_at
)
`

type ListTenantAuthorizationRolesParams struct {
	AfterID         pgtype.UUID `db:"after_id" json:"after_id"`
	IncludeArchived bool        `db:"include_archived" json:"include_archived"`
	PageSize        int32       `db:"page_size" json:"page_size"`
}

type ListTenantAuthorizationRolesRow struct {
	RoleID        pgtype.UUID        `db:"role_id" json:"role_id"`
	RoleKey       string             `db:"role_key" json:"role_key"`
	DisplayName   string             `db:"display_name" json:"display_name"`
	Description   string             `db:"description" json:"description"`
	PrincipalKind string             `db:"principal_kind" json:"principal_kind"`
	SystemRole    bool               `db:"system_role" json:"system_role"`
	ProtectedRole bool               `db:"protected_role" json:"protected_role"`
	Version       int32              `db:"version" json:"version"`
	ArchivedAt    pgtype.Timestamptz `db:"archived_at" json:"archived_at"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListTenantAuthorizationRoles(ctx context.Context, arg ListTenantAuthorizationRolesParams) ([]*ListTenantAuthorizationRolesRow, error) {
	rows, err := q.db.Query(ctx, listTenantAuthorizationRoles, arg.AfterID, arg.IncludeArchived, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListTenantAuthorizationRolesRow
	for rows.Next() {
		var i ListTenantAuthorizationRolesRow
		if err := rows.Scan(
			&i.RoleID,
			&i.RoleKey,
			&i.DisplayName,
			&i.Description,
			&i.PrincipalKind,
			&i.SystemRole,
			&i.ProtectedRole,
			&i.Version,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantAuthorizationSecurityGroupMemberships = `-- name: ListTenantAuthorizationSecurityGroupMemberships :many
SELECT edge.group_membership_id::uuid AS group_membership_id,
       edge.group_id::uuid AS group_id,
       edge.group_key::text AS group_key,
       edge.group_name::text AS group_name,
       edge.group_description::text AS group_description,
       edge.group_archived_at::timestamptz AS group_archived_at,
       edge.group_version::integer AS group_version,
       edge.group_created_at::timestamptz AS group_created_at,
       edge.group_updated_at::timestamptz AS group_updated_at,
       edge.membership_id::uuid AS membership_id,
       edge.target_user_id::uuid AS target_user_id,
       coalesce(edge.email, '')::text AS email,
       edge.display_name::text AS display_name,
       edge.membership_status::text AS membership_status,
       edge.compatibility_role::text AS compatibility_role,
       edge.user_active::boolean AS user_active,
       edge.membership_created_at::timestamptz AS membership_created_at,
       edge.membership_updated_at::timestamptz AS membership_updated_at,
       edge.source_id::uuid AS source_id,
       edge.source_kind::text AS source_kind,
       edge.source_authoritative::boolean AS source_authoritative,
       edge.source_retired_at::timestamptz AS source_retired_at,
       edge.granted_by_user_id::uuid AS granted_by_user_id,
       edge.grant_reason::text AS grant_reason,
       edge.granted_at::timestamptz AS granted_at,
       edge.expires_at::timestamptz AS expires_at,
       edge.revoked_at::timestamptz AS revoked_at,
       edge.revoked_by_user_id::uuid AS revoked_by_user_id,
       coalesce(edge.revoke_reason::text, '')::text AS revoke_reason,
       edge.grant_state::text AS grant_state,
       edge.version::integer AS version,
       edge.updated_at::timestamptz AS updated_at,
       edge.managed_by_authorization_api::boolean AS managed_by_authorization_api,
       edge.membership_lifecycle_revision::integer AS membership_lifecycle_revision
FROM app.list_tenant_security_group_memberships_v4(
  $1::uuid,
  $2::uuid,
  $3::boolean,
  $4::integer
) AS edge(
  group_membership_id, group_id, group_key, group_name, group_description,
  group_archived_at, group_version, group_created_at, group_updated_at,
  membership_id, target_user_id, email, display_name, membership_status,
  compatibility_role, user_active, membership_created_at,
  membership_updated_at, source_id, source_kind, source_authoritative,
  source_retired_at, granted_by_membership_id, granted_by_user_id,
  grant_reason, granted_at, expires_at, revoked_at,
  revoked_by_membership_id, revoked_by_user_id, revoke_reason, grant_state,
  version, updated_at, managed_by_authorization_api, membership_lifecycle_revision
)
`

type ListTenantAuthorizationSecurityGroupMembershipsParams struct {
	GroupID                pgtype.UUID `db:"group_id" json:"group_id"`
	AfterGroupMembershipID pgtype.UUID `db:"after_group_membership_id" json:"after_group_membership_id"`
	IncludeRevoked         bool        `db:"include_revoked" json:"include_revoked"`
	PageSize               int32       `db:"page_size" json:"page_size"`
}

type ListTenantAuthorizationSecurityGroupMembershipsRow struct {
	GroupMembershipID           pgtype.UUID        `db:"group_membership_id" json:"group_membership_id"`
	GroupID                     pgtype.UUID        `db:"group_id" json:"group_id"`
	GroupKey                    string             `db:"group_key" json:"group_key"`
	GroupName                   string             `db:"group_name" json:"group_name"`
	GroupDescription            string             `db:"group_description" json:"group_description"`
	GroupArchivedAt             pgtype.Timestamptz `db:"group_archived_at" json:"group_archived_at"`
	GroupVersion                int32              `db:"group_version" json:"group_version"`
	GroupCreatedAt              pgtype.Timestamptz `db:"group_created_at" json:"group_created_at"`
	GroupUpdatedAt              pgtype.Timestamptz `db:"group_updated_at" json:"group_updated_at"`
	MembershipID                pgtype.UUID        `db:"membership_id" json:"membership_id"`
	TargetUserID                pgtype.UUID        `db:"target_user_id" json:"target_user_id"`
	Email                       string             `db:"email" json:"email"`
	DisplayName                 string             `db:"display_name" json:"display_name"`
	MembershipStatus            string             `db:"membership_status" json:"membership_status"`
	CompatibilityRole           string             `db:"compatibility_role" json:"compatibility_role"`
	UserActive                  bool               `db:"user_active" json:"user_active"`
	MembershipCreatedAt         pgtype.Timestamptz `db:"membership_created_at" json:"membership_created_at"`
	MembershipUpdatedAt         pgtype.Timestamptz `db:"membership_updated_at" json:"membership_updated_at"`
	SourceID                    pgtype.UUID        `db:"source_id" json:"source_id"`
	SourceKind                  string             `db:"source_kind" json:"source_kind"`
	SourceAuthoritative         bool               `db:"source_authoritative" json:"source_authoritative"`
	SourceRetiredAt             pgtype.Timestamptz `db:"source_retired_at" json:"source_retired_at"`
	GrantedByUserID             pgtype.UUID        `db:"granted_by_user_id" json:"granted_by_user_id"`
	GrantReason                 string             `db:"grant_reason" json:"grant_reason"`
	GrantedAt                   pgtype.Timestamptz `db:"granted_at" json:"granted_at"`
	ExpiresAt                   pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt                   pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RevokedByUserID             pgtype.UUID        `db:"revoked_by_user_id" json:"revoked_by_user_id"`
	RevokeReason                string             `db:"revoke_reason" json:"revoke_reason"`
	GrantState                  string             `db:"grant_state" json:"grant_state"`
	Version                     int32              `db:"version" json:"version"`
	UpdatedAt                   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ManagedByAuthorizationApi   bool               `db:"managed_by_authorization_api" json:"managed_by_authorization_api"`
	MembershipLifecycleRevision int32              `db:"membership_lifecycle_revision" json:"membership_lifecycle_revision"`
}

func (q *Queries) ListTenantAuthorizationSecurityGroupMemberships(ctx context.Context, arg ListTenantAuthorizationSecurityGroupMembershipsParams) ([]*ListTenantAuthorizationSecurityGroupMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listTenantAuthorizationSecurityGroupMemberships,
		arg.GroupID,
		arg.AfterGroupMembershipID,
		arg.IncludeRevoked,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListTenantAuthorizationSecurityGroupMembershipsRow
	for rows.Next() {
		var i ListTenantAuthorizationSecurityGroupMembershipsRow
		if err := rows.Scan(
			&i.GroupMembershipID,
			&i.GroupID,
			&i.GroupKey,
			&i.GroupName,
			&i.GroupDescription,
			&i.GroupArchivedAt,
			&i.GroupVersion,
			&i.GroupCreatedAt,
			&i.GroupUpdatedAt,
			&i.MembershipID,
			&i.TargetUserID,
			&i.Email,
			&i.DisplayName,
			&i.MembershipStatus,
			&i.CompatibilityRole,
			&i.UserActive,
			&i.MembershipCreatedAt,
			&i.MembershipUpdatedAt,
			&i.SourceID,
			&i.SourceKind,
			&i.SourceAuthoritative,
			&i.SourceRetiredAt,
			&i.GrantedByUserID,
			&i.GrantReason,
			&i.GrantedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RevokedByUserID,
			&i.RevokeReason,
			&i.GrantState,
			&i.Version,
			&i.UpdatedAt,
			&i.ManagedByAuthorizationApi,
			&i.MembershipLifecycleRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantAuthorizationSecurityGroupRoleGrants = `-- name: ListTenantAuthorizationSecurityGroupRoleGrants :many
SELECT edge.group_role_grant_id::uuid AS group_role_grant_id,
       edge.group_id::uuid AS group_id,
       edge.group_key::text AS group_key,
       edge.group_name::text AS group_name,
       edge.group_description::text AS group_description,
       edge.group_archived_at::timestamptz AS group_archived_at,
       edge.group_version::integer AS group_version,
       edge.group_created_at::timestamptz AS group_created_at,
       edge.group_updated_at::timestamptz AS group_updated_at,
       edge.role_id::uuid AS role_id,
       edge.role_key::text AS role_key,
       edge.role_name::text AS role_name,
       edge.role_description::text AS role_description,
       edge.role_system::boolean AS role_system,
       edge.role_protected::boolean AS role_protected,
       edge.role_archived_at::timestamptz AS role_archived_at,
       edge.role_version::integer AS role_version,
       edge.role_created_at::timestamptz AS role_created_at,
       edge.role_updated_at::timestamptz AS role_updated_at,
       edge.source_id::uuid AS source_id,
       edge.source_kind::text AS source_kind,
       edge.source_authoritative::boolean AS source_authoritative,
       edge.source_retired_at::timestamptz AS source_retired_at,
       edge.granted_by_user_id::uuid AS granted_by_user_id,
       edge.grant_reason::text AS grant_reason,
       edge.granted_at::timestamptz AS granted_at,
       edge.expires_at::timestamptz AS expires_at,
       edge.revoked_at::timestamptz AS revoked_at,
       edge.revoked_by_user_id::uuid AS revoked_by_user_id,
       coalesce(edge.revoke_reason::text, '')::text AS revoke_reason,
       edge.grant_state::text AS grant_state,
       edge.version::integer AS version,
       edge.updated_at::timestamptz AS updated_at,
       edge.managed_by_authorization_api::boolean AS managed_by_authorization_api
FROM app.list_tenant_security_group_role_grants_v2(
  $1::uuid,
  $2::uuid,
  $3::boolean,
  $4::integer
) AS edge(
  group_role_grant_id, group_id, group_key, group_name, group_description,
  group_archived_at, group_version, group_created_at, group_updated_at,
  role_id, role_key, role_name, role_description, role_system,
  role_protected, role_archived_at, role_version, role_created_at,
  role_updated_at, source_id, source_kind, source_authoritative,
  source_retired_at, granted_by_membership_id, granted_by_user_id,
  grant_reason, granted_at, expires_at, revoked_at,
  revoked_by_membership_id, revoked_by_user_id, revoke_reason, grant_state,
  version, updated_at, managed_by_authorization_api
)
`

type ListTenantAuthorizationSecurityGroupRoleGrantsParams struct {
	GroupID               pgtype.UUID `db:"group_id" json:"group_id"`
	AfterGroupRoleGrantID pgtype.UUID `db:"after_group_role_grant_id" json:"after_group_role_grant_id"`
	IncludeRevoked        bool        `db:"include_revoked" json:"include_revoked"`
	PageSize              int32       `db:"page_size" json:"page_size"`
}

type ListTenantAuthorizationSecurityGroupRoleGrantsRow struct {
	GroupRoleGrantID          pgtype.UUID        `db:"group_role_grant_id" json:"group_role_grant_id"`
	GroupID                   pgtype.UUID        `db:"group_id" json:"group_id"`
	GroupKey                  string             `db:"group_key" json:"group_key"`
	GroupName                 string             `db:"group_name" json:"group_name"`
	GroupDescription          string             `db:"group_description" json:"group_description"`
	GroupArchivedAt           pgtype.Timestamptz `db:"group_archived_at" json:"group_archived_at"`
	GroupVersion              int32              `db:"group_version" json:"group_version"`
	GroupCreatedAt            pgtype.Timestamptz `db:"group_created_at" json:"group_created_at"`
	GroupUpdatedAt            pgtype.Timestamptz `db:"group_updated_at" json:"group_updated_at"`
	RoleID                    pgtype.UUID        `db:"role_id" json:"role_id"`
	RoleKey                   string             `db:"role_key" json:"role_key"`
	RoleName                  string             `db:"role_name" json:"role_name"`
	RoleDescription           string             `db:"role_description" json:"role_description"`
	RoleSystem                bool               `db:"role_system" json:"role_system"`
	RoleProtected             bool               `db:"role_protected" json:"role_protected"`
	RoleArchivedAt            pgtype.Timestamptz `db:"role_archived_at" json:"role_archived_at"`
	RoleVersion               int32              `db:"role_version" json:"role_version"`
	RoleCreatedAt             pgtype.Timestamptz `db:"role_created_at" json:"role_created_at"`
	RoleUpdatedAt             pgtype.Timestamptz `db:"role_updated_at" json:"role_updated_at"`
	SourceID                  pgtype.UUID        `db:"source_id" json:"source_id"`
	SourceKind                string             `db:"source_kind" json:"source_kind"`
	SourceAuthoritative       bool               `db:"source_authoritative" json:"source_authoritative"`
	SourceRetiredAt           pgtype.Timestamptz `db:"source_retired_at" json:"source_retired_at"`
	GrantedByUserID           pgtype.UUID        `db:"granted_by_user_id" json:"granted_by_user_id"`
	GrantReason               string             `db:"grant_reason" json:"grant_reason"`
	GrantedAt                 pgtype.Timestamptz `db:"granted_at" json:"granted_at"`
	ExpiresAt                 pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt                 pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RevokedByUserID           pgtype.UUID        `db:"revoked_by_user_id" json:"revoked_by_user_id"`
	RevokeReason              string             `db:"revoke_reason" json:"revoke_reason"`
	GrantState                string             `db:"grant_state" json:"grant_state"`
	Version                   int32              `db:"version" json:"version"`
	UpdatedAt                 pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ManagedByAuthorizationApi bool               `db:"managed_by_authorization_api" json:"managed_by_authorization_api"`
}

func (q *Queries) ListTenantAuthorizationSecurityGroupRoleGrants(ctx context.Context, arg ListTenantAuthorizationSecurityGroupRoleGrantsParams) ([]*ListTenantAuthorizationSecurityGroupRoleGrantsRow, error) {
	rows, err := q.db.Query(ctx, listTenantAuthorizationSecurityGroupRoleGrants,
		arg.GroupID,
		arg.AfterGroupRoleGrantID,
		arg.IncludeRevoked,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListTenantAuthorizationSecurityGroupRoleGrantsRow
	for rows.Next() {
		var i ListTenantAuthorizationSecurityGroupRoleGrantsRow
		if err := rows.Scan(
			&i.GroupRoleGrantID,
			&i.GroupID,
			&i.GroupKey,
			&i.GroupName,
			&i.GroupDescription,
			&i.GroupArchivedAt,
			&i.GroupVersion,
			&i.GroupCreatedAt,
			&i.GroupUpdatedAt,
			&i.RoleID,
			&i.RoleKey,
			&i.RoleName,
			&i.RoleDescription,
			&i.RoleSystem,
			&i.RoleProtected,
			&i.RoleArchivedAt,
			&i.RoleVersion,
			&i.RoleCreatedAt,
			&i.RoleUpdatedAt,
			&i.SourceID,
			&i.SourceKind,
			&i.SourceAuthoritative,
			&i.SourceRetiredAt,
			&i.GrantedByUserID,
			&i.GrantReason,
			&i.GrantedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RevokedByUserID,
			&i.RevokeReason,
			&i.GrantState,
			&i.Version,
			&i.UpdatedAt,
			&i.ManagedByAuthorizationApi,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantAuthorizationSecurityGroups = `-- name: ListTenantAuthorizationSecurityGroups :many
SELECT security_group.group_id::uuid AS group_id,
       security_group.group_key::text AS group_key,
       security_group.group_name::text AS group_name,
       security_group.group_description::text AS group_description,
       security_group.archived_at::timestamptz AS archived_at,
       security_group.version::integer AS version,
       security_group.created_at::timestamptz AS created_at,
       security_group.updated_at::timestamptz AS updated_at
FROM app.list_tenant_security_groups(
  $1::uuid,
  $2::boolean,
  $3::integer
) AS security_group(
  group_id, group_key, group_name, group_description,
  created_by_membership_id, created_by_user_id, archived_at, version,
  created_at, updated_at
)
`

type ListTenantAuthorizationSecurityGroupsParams struct {
	AfterGroupID    pgtype.UUID `db:"after_group_id" json:"after_group_id"`
	IncludeArchived bool        `db:"include_archived" json:"include_archived"`
	PageSize        int32       `db:"page_size" json:"page_size"`
}

type ListTenantAuthorizationSecurityGroupsRow struct {
	GroupID          pgtype.UUID        `db:"group_id" json:"group_id"`
	GroupKey         string             `db:"group_key" json:"group_key"`
	GroupName        string             `db:"group_name" json:"group_name"`
	GroupDescription string             `db:"group_description" json:"group_description"`
	ArchivedAt       pgtype.Timestamptz `db:"archived_at" json:"archived_at"`
	Version          int32              `db:"version" json:"version"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListTenantAuthorizationSecurityGroups(ctx context.Context, arg ListTenantAuthorizationSecurityGroupsParams) ([]*ListTenantAuthorizationSecurityGroupsRow, error) {
	rows, err := q.db.Query(ctx, listTenantAuthorizationSecurityGroups, arg.AfterGroupID, arg.IncludeArchived, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListTenantAuthorizationSecurityGroupsRow
	for rows.Next() {
		var i ListTenantAuthorizationSecurityGroupsRow
		if err := rows.Scan(
			&i.GroupID,
			&i.GroupKey,
			&i.GroupName,
			&i.GroupDescription,
			&i.ArchivedAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantAuthorizationUsers = `-- name: ListTenantAuthorizationUsers :many
SELECT tenant_user.membership_id::uuid AS membership_id,
       tenant_user.user_id::uuid AS user_id,
       coalesce(tenant_user.email, '')::text AS email,
       tenant_user.display_name::text AS display_name,
       tenant_user.membership_status::text AS membership_status,
       tenant_user.compatibility_role::text AS compatibility_role,
       tenant_user.user_active::boolean AS user_active,
       tenant_user.lifecycle_revision::integer AS lifecycle_revision,
       tenant_user.created_at::timestamptz AS created_at,
       tenant_user.updated_at::timestamptz AS updated_at
FROM app.list_tenant_users_v3(
  $1::uuid,
  $2::integer
) AS tenant_user(
  membership_id, user_id, email, display_name, membership_status,
  compatibility_role, user_active, lifecycle_revision, created_at, updated_at
)
`

type ListTenantAuthorizationUsersParams struct {
	AfterMembershipID pgtype.UUID `db:"after_membership_id" json:"after_membership_id"`
	PageSize          int32       `db:"page_size" json:"page_size"`
}

type ListTenantAuthorizationUsersRow struct {
	MembershipID      pgtype.UUID        `db:"membership_id" json:"membership_id"`
	UserID            pgtype.UUID        `db:"user_id" json:"user_id"`
	Email             string             `db:"email" json:"email"`
	DisplayName       string             `db:"display_name" json:"display_name"`
	MembershipStatus  string             `db:"membership_status" json:"membership_status"`
	CompatibilityRole string             `db:"compatibility_role" json:"compatibility_role"`
	UserActive        bool               `db:"user_active" json:"user_active"`
	LifecycleRevision int32              `db:"lifecycle_revision" json:"lifecycle_revision"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListTenantAuthorizationUsers(ctx context.Context, arg ListTenantAuthorizationUsersParams) ([]*ListTenantAuthorizationUsersRow, error) {
	rows, err := q.db.Query(ctx, listTenantAuthorizationUsers, arg.AfterMembershipID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListTenantAuthorizationUsersRow
	for rows.Next() {
		var i ListTenantAuthorizationUsersRow
		if err := rows.Scan(
			&i.MembershipID,
			&i.UserID,
			&i.Email,
			&i.DisplayName,
			&i.MembershipStatus,
			&i.CompatibilityRole,
			&i.UserActive,
			&i.LifecycleRevision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantMembershipRoleGrants = `-- name: ListTenantMembershipRoleGrants :many
SELECT role_grant.grant_id::uuid AS grant_id,
       role_grant.membership_id::uuid AS membership_id,
       role_grant.role_id::uuid AS role_id,
       role_grant.role_key::text AS role_key,
       role_grant.role_name::text AS role_name,
       role_grant.role_description::text AS role_description,
       role_grant.role_system::boolean AS role_system,
       role_grant.role_archived_at::timestamptz AS role_archived_at,
       role_grant.role_version::integer AS role_version,
       role_grant.role_created_at::timestamptz AS role_created_at,
       role_grant.role_updated_at::timestamptz AS role_updated_at,
       role_grant.source_id::uuid AS source_id,
       role_grant.source_kind::text AS source_kind,
       role_grant.source_authoritative::boolean AS source_authoritative,
       role_grant.source_retired_at::timestamptz AS source_retired_at,
       role_grant.managed_by_authorization_api::boolean AS managed_by_authorization_api,
       role_grant.source_type::text AS source_type,
       role_grant.granted_by_membership_id::uuid AS granted_by_membership_id,
       role_grant.granted_by_user_id::uuid AS granted_by_user_id,
       role_grant.grant_reason::text AS grant_reason,
       role_grant.granted_at::timestamptz AS granted_at,
       role_grant.expires_at::timestamptz AS expires_at,
       role_grant.revoked_at::timestamptz AS revoked_at,
       role_grant.revoked_by_membership_id::uuid AS revoked_by_membership_id,
       role_grant.revoked_by_user_id::uuid AS revoked_by_user_id,
       coalesce(role_grant.revoke_reason::text, '')::text AS revoke_reason,
       role_grant.grant_state::text AS grant_state,
       role_grant.version::integer AS version,
       role_grant.updated_at::timestamptz AS updated_at
FROM app.list_tenant_membership_role_grants_v2(
  $1::uuid,
  $2::uuid,
  $3::boolean,
  $4::integer
) AS role_grant(
  grant_id, membership_id, role_id, role_key, role_name, role_description,
  role_system, role_archived_at, role_version, role_created_at, role_updated_at,
  source_id, source_kind, source_authoritative, source_retired_at,
  managed_by_authorization_api, source_type,
  granted_by_membership_id,
  granted_by_user_id, grant_reason, granted_at, expires_at, revoked_at,
  revoked_by_membership_id, revoked_by_user_id, revoke_reason, grant_state,
  version, updated_at
)
`

type ListTenantMembershipRoleGrantsParams struct {
	TargetUserID   pgtype.UUID `db:"target_user_id" json:"target_user_id"`
	AfterGrantID   pgtype.UUID `db:"after_grant_id" json:"after_grant_id"`
	IncludeRevoked bool        `db:"include_revoked" json:"include_revoked"`
	PageSize       int32       `db:"page_size" json:"page_size"`
}

type ListTenantMembershipRoleGrantsRow struct {
	GrantID                   pgtype.UUID        `db:"grant_id" json:"grant_id"`
	MembershipID              pgtype.UUID        `db:"membership_id" json:"membership_id"`
	RoleID                    pgtype.UUID        `db:"role_id" json:"role_id"`
	RoleKey                   string             `db:"role_key" json:"role_key"`
	RoleName                  string             `db:"role_name" json:"role_name"`
	RoleDescription           string             `db:"role_description" json:"role_description"`
	RoleSystem                bool               `db:"role_system" json:"role_system"`
	RoleArchivedAt            pgtype.Timestamptz `db:"role_archived_at" json:"role_archived_at"`
	RoleVersion               int32              `db:"role_version" json:"role_version"`
	RoleCreatedAt             pgtype.Timestamptz `db:"role_created_at" json:"role_created_at"`
	RoleUpdatedAt             pgtype.Timestamptz `db:"role_updated_at" json:"role_updated_at"`
	SourceID                  pgtype.UUID        `db:"source_id" json:"source_id"`
	SourceKind                string             `db:"source_kind" json:"source_kind"`
	SourceAuthoritative       bool               `db:"source_authoritative" json:"source_authoritative"`
	SourceRetiredAt           pgtype.Timestamptz `db:"source_retired_at" json:"source_retired_at"`
	ManagedByAuthorizationApi bool               `db:"managed_by_authorization_api" json:"managed_by_authorization_api"`
	SourceType                string             `db:"source_type" json:"source_type"`
	GrantedByMembershipID     pgtype.UUID        `db:"granted_by_membership_id" json:"granted_by_membership_id"`
	GrantedByUserID           pgtype.UUID        `db:"granted_by_user_id" json:"granted_by_user_id"`
	GrantReason               string             `db:"grant_reason" json:"grant_reason"`
	GrantedAt                 pgtype.Timestamptz `db:"granted_at" json:"granted_at"`
	ExpiresAt                 pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt                 pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RevokedByMembershipID     pgtype.UUID        `db:"revoked_by_membership_id" json:"revoked_by_membership_id"`
	RevokedByUserID           pgtype.UUID        `db:"revoked_by_user_id" json:"revoked_by_user_id"`
	RevokeReason              string             `db:"revoke_reason" json:"revoke_reason"`
	GrantState                string             `db:"grant_state" json:"grant_state"`
	Version                   int32              `db:"version" json:"version"`
	UpdatedAt                 pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListTenantMembershipRoleGrants(ctx context.Context, arg ListTenantMembershipRoleGrantsParams) ([]*ListTenantMembershipRoleGrantsRow, error) {
	rows, err := q.db.Query(ctx, listTenantMembershipRoleGrants,
		arg.TargetUserID,
		arg.AfterGrantID,
		arg.IncludeRevoked,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListTenantMembershipRoleGrantsRow
	for rows.Next() {
		var i ListTenantMembershipRoleGrantsRow
		if err := rows.Scan(
			&i.GrantID,
			&i.MembershipID,
			&i.RoleID,
			&i.RoleKey,
			&i.RoleName,
			&i.RoleDescription,
			&i.RoleSystem,
			&i.RoleArchivedAt,
			&i.RoleVersion,
			&i.RoleCreatedAt,
			&i.RoleUpdatedAt,
			&i.SourceID,
			&i.SourceKind,
			&i.SourceAuthoritative,
			&i.SourceRetiredAt,
			&i.ManagedByAuthorizationApi,
			&i.SourceType,
			&i.GrantedByMembershipID,
			&i.GrantedByUserID,
			&i.GrantReason,
			&i.GrantedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RevokedByMembershipID,
			&i.RevokedByUserID,
			&i.RevokeReason,
			&i.GrantState,
			&i.Version,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantPermissionCatalog = `-- name: ListTenantPermissionCatalog :many
SELECT permission.permission_id::uuid AS permission_id,
       permission.permission_key::text AS permission_key,
       permission.display_name::text AS display_name,
       permission.description::text AS description,
       permission.allowed_scopes::text[] AS allowed_scopes,
       permission.principal_kinds::text[] AS principal_kinds
FROM app.list_tenant_permission_catalog_v3(
  $1::uuid,
  $2::integer
) AS permission(
  permission_id, permission_key, display_name, description, allowed_scopes,
  principal_kinds
)
`

type ListTenantPermissionCatalogParams struct {
	AfterID  pgtype.UUID `db:"after_id" json:"after_id"`
	PageSize int32       `db:"page_size" json:"page_size"`
}

type ListTenantPermissionCatalogRow struct {
	PermissionID   pgtype.UUID `db:"permission_id" json:"permission_id"`
	PermissionKey  string      `db:"permission_key" json:"permission_key"`
	DisplayName    string      `db:"display_name" json:"display_name"`
	Description    string      `db:"description" json:"description"`
	AllowedScopes  []string    `db:"allowed_scopes" json:"allowed_scopes"`
	PrincipalKinds []string    `db:"principal_kinds" json:"principal_kinds"`
}

func (q *Queries) ListTenantPermissionCatalog(ctx context.Context, arg ListTenantPermissionCatalogParams) ([]*ListTenantPermissionCatalogRow, error) {
	rows, err := q.db.Query(ctx, listTenantPermissionCatalog, arg.AfterID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListTenantPermissionCatalogRow
	for rows.Next() {
		var i ListTenantPermissionCatalogRow
		if err := rows.Scan(
			&i.PermissionID,
			&i.PermissionKey,
			&i.DisplayName,
			&i.Description,
			&i.AllowedScopes,
			&i.PrincipalKinds,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceTenantAuthorizationRolePolicy = `-- name: ReplaceTenantAuthorizationRolePolicy :one
SELECT result.role_id::uuid AS role_id,
       result.role_key::text AS role_key,
       result.display_name::text AS display_name,
       result.description::text AS description,
       result.system_role::boolean AS system_role,
       result.protected_role::boolean AS protected_role,
       result.version::integer AS version,
       result.archived_at::timestamptz AS archived_at,
       result.created_at::timestamptz AS created_at,
       result.updated_at::timestamptz AS updated_at,
       result.permission_keys::text[] AS permission_keys,
       result.permission_scopes::text[] AS permission_scopes,
       result.delegation_permission_keys::text[] AS delegation_permission_keys,
       result.delegation_scopes::text[] AS delegation_scopes
FROM app.replace_tenant_role_policy_with_result_v2(
  $1::uuid,
  $2::integer,
  $3::text[],
  $4::text[]::authorization_scope[],
  $5::text[],
  $6::text[]::authorization_scope[],
  $7::uuid,
  $8::uuid,
  $9::uuid,
  $10::inet,
  nullif($11::text, ''),
  $12::text
) AS result(
  role_id, role_key, display_name, description, system_role, protected_role,
  version, archived_at, created_at, updated_at, permission_keys,
  permission_scopes, delegation_permission_keys, delegation_scopes
)
`

type ReplaceTenantAuthorizationRolePolicyParams struct {
	RoleID                   pgtype.UUID `db:"role_id" json:"role_id"`
	ExpectedVersion          int32       `db:"expected_version" json:"expected_version"`
	PermissionKeys           []string    `db:"permission_keys" json:"permission_keys"`
	PermissionScopes         []string    `db:"permission_scopes" json:"permission_scopes"`
	DelegationPermissionKeys []string    `db:"delegation_permission_keys" json:"delegation_permission_keys"`
	DelegationScopes         []string    `db:"delegation_scopes" json:"delegation_scopes"`
	AuditID                  pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID                pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID            pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress                netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent                string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod     string      `db:"authentication_method" json:"authentication_method"`
}

type ReplaceTenantAuthorizationRolePolicyRow struct {
	RoleID                   pgtype.UUID        `db:"role_id" json:"role_id"`
	RoleKey                  string             `db:"role_key" json:"role_key"`
	DisplayName              string             `db:"display_name" json:"display_name"`
	Description              string             `db:"description" json:"description"`
	SystemRole               bool               `db:"system_role" json:"system_role"`
	ProtectedRole            bool               `db:"protected_role" json:"protected_role"`
	Version                  int32              `db:"version" json:"version"`
	ArchivedAt               pgtype.Timestamptz `db:"archived_at" json:"archived_at"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	PermissionKeys           []string           `db:"permission_keys" json:"permission_keys"`
	PermissionScopes         []string           `db:"permission_scopes" json:"permission_scopes"`
	DelegationPermissionKeys []string           `db:"delegation_permission_keys" json:"delegation_permission_keys"`
	DelegationScopes         []string           `db:"delegation_scopes" json:"delegation_scopes"`
}

func (q *Queries) ReplaceTenantAuthorizationRolePolicy(ctx context.Context, arg ReplaceTenantAuthorizationRolePolicyParams) (*ReplaceTenantAuthorizationRolePolicyRow, error) {
	row := q.db.QueryRow(ctx, replaceTenantAuthorizationRolePolicy,
		arg.RoleID,
		arg.ExpectedVersion,
		arg.PermissionKeys,
		arg.PermissionScopes,
		arg.DelegationPermissionKeys,
		arg.DelegationScopes,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
	)
	var i ReplaceTenantAuthorizationRolePolicyRow
	err := row.Scan(
		&i.RoleID,
		&i.RoleKey,
		&i.DisplayName,
		&i.Description,
		&i.SystemRole,
		&i.ProtectedRole,
		&i.Version,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PermissionKeys,
		&i.PermissionScopes,
		&i.DelegationPermissionKeys,
		&i.DelegationScopes,
	)
	return &i, err
}

const resolveCurrentTenantHumanAuthority = `-- name: ResolveCurrentTenantHumanAuthority :many
SELECT authority.permission_key::text AS permission_key,
       authority.scope::text AS scope,
       authority.delegable::boolean AS delegable,
       authority.delegation_expires_at::timestamptz AS delegation_expires_at
FROM app.resolve_current_tenant_human_authority_v3(
  $1::integer
) AS authority(permission_key, scope, delegable, delegation_expires_at)
`

type ResolveCurrentTenantHumanAuthorityParams struct {
	PageSize int32 `db:"page_size" json:"page_size"`
}

type ResolveCurrentTenantHumanAuthorityRow struct {
	PermissionKey       string             `db:"permission_key" json:"permission_key"`
	Scope               string             `db:"scope" json:"scope"`
	Delegable           bool               `db:"delegable" json:"delegable"`
	DelegationExpiresAt pgtype.Timestamptz `db:"delegation_expires_at" json:"delegation_expires_at"`
}

func (q *Queries) ResolveCurrentTenantHumanAuthority(ctx context.Context, arg ResolveCurrentTenantHumanAuthorityParams) ([]*ResolveCurrentTenantHumanAuthorityRow, error) {
	rows, err := q.db.Query(ctx, resolveCurrentTenantHumanAuthority, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ResolveCurrentTenantHumanAuthorityRow
	for rows.Next() {
		var i ResolveCurrentTenantHumanAuthorityRow
		if err := rows.Scan(
			&i.PermissionKey,
			&i.Scope,
			&i.Delegable,
			&i.DelegationExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveCurrentTenantHumanRoleGrantPaths = `-- name: ResolveCurrentTenantHumanRoleGrantPaths :many
SELECT role_path.path_type::text AS path_type,
       role_path.source_type::text AS source_type,
       role_path.effective_expires_at::timestamptz AS effective_expires_at,
       role_path.role_id::uuid AS role_id,
       role_path.role_key::text AS role_key,
       role_path.role_name::text AS role_name,
       role_path.role_grant_id::uuid AS role_grant_id,
       role_path.role_source_id::uuid AS role_source_id,
       role_path.role_source_kind::text AS role_source_kind,
       role_path.role_source_authoritative::boolean AS role_source_authoritative,
       role_path.role_source_retired_at::timestamptz AS role_source_retired_at,
       role_path.role_granted_by_user_id::uuid AS role_granted_by_user_id,
       role_path.role_grant_reason::text AS role_grant_reason,
       role_path.role_granted_at::timestamptz AS role_granted_at,
       role_path.role_grant_expires_at::timestamptz AS role_grant_expires_at,
       role_path.role_grant_version::integer AS role_grant_version,
       role_path.group_id::uuid AS group_id,
       coalesce(role_path.group_key::text, '')::text AS group_key,
       coalesce(role_path.group_name::text, '')::text AS group_name,
       role_path.group_membership_id::uuid AS group_membership_id,
       role_path.membership_source_id::uuid AS membership_source_id,
       coalesce(role_path.membership_source_kind::text, '')::text AS membership_source_kind,
       coalesce(role_path.membership_source_authoritative::boolean, false)::boolean AS membership_source_authoritative,
       role_path.membership_source_retired_at::timestamptz AS membership_source_retired_at,
       role_path.membership_granted_by_user_id::uuid AS membership_granted_by_user_id,
       coalesce(role_path.membership_grant_reason::text, '')::text AS membership_grant_reason,
       role_path.membership_granted_at::timestamptz AS membership_granted_at,
       role_path.membership_expires_at::timestamptz AS membership_expires_at,
       coalesce(role_path.membership_version::integer, 0)::integer AS membership_version
FROM app.resolve_current_tenant_human_role_grant_paths(
  $1::integer
) AS role_path(
  path_type, source_type, effective_expires_at, role_id, role_key, role_name,
  role_grant_id, role_source_id, role_source_kind, role_source_authoritative,
  role_source_retired_at, role_granted_by_user_id, role_grant_reason,
  role_granted_at, role_grant_expires_at, role_grant_version, group_id,
  group_key, group_name, group_membership_id, membership_source_id,
  membership_source_kind, membership_source_authoritative,
  membership_source_retired_at, membership_granted_by_user_id,
  membership_grant_reason, membership_granted_at, membership_expires_at,
  membership_version
)
`

type ResolveCurrentTenantHumanRoleGrantPathsParams struct {
	PageSize int32 `db:"page_size" json:"page_size"`
}

type ResolveCurrentTenantHumanRoleGrantPathsRow struct {
	PathType                      string             `db:"path_type" json:"path_type"`
	SourceType                    string             `db:"source_type" json:"source_type"`
	EffectiveExpiresAt            pgtype.Timestamptz `db:"effective_expires_at" json:"effective_expires_at"`
	RoleID                        pgtype.UUID        `db:"role_id" json:"role_id"`
	RoleKey                       string             `db:"role_key" json:"role_key"`
	RoleName                      string             `db:"role_name" json:"role_name"`
	RoleGrantID                   pgtype.UUID        `db:"role_grant_id" json:"role_grant_id"`
	RoleSourceID                  pgtype.UUID        `db:"role_source_id" json:"role_source_id"`
	RoleSourceKind                string             `db:"role_source_kind" json:"role_source_kind"`
	RoleSourceAuthoritative       bool               `db:"role_source_authoritative" json:"role_source_authoritative"`
	RoleSourceRetiredAt           pgtype.Timestamptz `db:"role_source_retired_at" json:"role_source_retired_at"`
	RoleGrantedByUserID           pgtype.UUID        `db:"role_granted_by_user_id" json:"role_granted_by_user_id"`
	RoleGrantReason               string             `db:"role_grant_reason" json:"role_grant_reason"`
	RoleGrantedAt                 pgtype.Timestamptz `db:"role_granted_at" json:"role_granted_at"`
	RoleGrantExpiresAt            pgtype.Timestamptz `db:"role_grant_expires_at" json:"role_grant_expires_at"`
	RoleGrantVersion              int32              `db:"role_grant_version" json:"role_grant_version"`
	GroupID                       pgtype.UUID        `db:"group_id" json:"group_id"`
	GroupKey                      string             `db:"group_key" json:"group_key"`
	GroupName                     string             `db:"group_name" json:"group_name"`
	GroupMembershipID             pgtype.UUID        `db:"group_membership_id" json:"group_membership_id"`
	MembershipSourceID            pgtype.UUID        `db:"membership_source_id" json:"membership_source_id"`
	MembershipSourceKind          string             `db:"membership_source_kind" json:"membership_source_kind"`
	MembershipSourceAuthoritative bool               `db:"membership_source_authoritative" json:"membership_source_authoritative"`
	MembershipSourceRetiredAt     pgtype.Timestamptz `db:"membership_source_retired_at" json:"membership_source_retired_at"`
	MembershipGrantedByUserID     pgtype.UUID        `db:"membership_granted_by_user_id" json:"membership_granted_by_user_id"`
	MembershipGrantReason         string             `db:"membership_grant_reason" json:"membership_grant_reason"`
	MembershipGrantedAt           pgtype.Timestamptz `db:"membership_granted_at" json:"membership_granted_at"`
	MembershipExpiresAt           pgtype.Timestamptz `db:"membership_expires_at" json:"membership_expires_at"`
	MembershipVersion             int32              `db:"membership_version" json:"membership_version"`
}

func (q *Queries) ResolveCurrentTenantHumanRoleGrantPaths(ctx context.Context, arg ResolveCurrentTenantHumanRoleGrantPathsParams) ([]*ResolveCurrentTenantHumanRoleGrantPathsRow, error) {
	rows, err := q.db.Query(ctx, resolveCurrentTenantHumanRoleGrantPaths, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ResolveCurrentTenantHumanRoleGrantPathsRow
	for rows.Next() {
		var i ResolveCurrentTenantHumanRoleGrantPathsRow
		if err := rows.Scan(
			&i.PathType,
			&i.SourceType,
			&i.EffectiveExpiresAt,
			&i.RoleID,
			&i.RoleKey,
			&i.RoleName,
			&i.RoleGrantID,
			&i.RoleSourceID,
			&i.RoleSourceKind,
			&i.RoleSourceAuthoritative,
			&i.RoleSourceRetiredAt,
			&i.RoleGrantedByUserID,
			&i.RoleGrantReason,
			&i.RoleGrantedAt,
			&i.RoleGrantExpiresAt,
			&i.RoleGrantVersion,
			&i.GroupID,
			&i.GroupKey,
			&i.GroupName,
			&i.GroupMembershipID,
			&i.MembershipSourceID,
			&i.MembershipSourceKind,
			&i.MembershipSourceAuthoritative,
			&i.MembershipSourceRetiredAt,
			&i.MembershipGrantedByUserID,
			&i.MembershipGrantReason,
			&i.MembershipGrantedAt,
			&i.MembershipExpiresAt,
			&i.MembershipVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeTenantAuthorizationSecurityGroupMembership = `-- name: RevokeTenantAuthorizationSecurityGroupMembership :one
SELECT app.revoke_tenant_security_group_membership(
  $1::uuid,
  $2::uuid,
  $3::integer,
  $4::text,
  $5::uuid,
  $6::uuid,
  $7::uuid,
  $8::inet,
  nullif($9::text, ''),
  $10::text
) AS version
`

type RevokeTenantAuthorizationSecurityGroupMembershipParams struct {
	GroupID              pgtype.UUID `db:"group_id" json:"group_id"`
	GroupMembershipID    pgtype.UUID `db:"group_membership_id" json:"group_membership_id"`
	ExpectedVersion      int32       `db:"expected_version" json:"expected_version"`
	Reason               string      `db:"reason" json:"reason"`
	AuditID              pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
}

func (q *Queries) RevokeTenantAuthorizationSecurityGroupMembership(ctx context.Context, arg RevokeTenantAuthorizationSecurityGroupMembershipParams) (int32, error) {
	row := q.db.QueryRow(ctx, revokeTenantAuthorizationSecurityGroupMembership,
		arg.GroupID,
		arg.GroupMembershipID,
		arg.ExpectedVersion,
		arg.Reason,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const revokeTenantAuthorizationSecurityGroupRoleGrant = `-- name: RevokeTenantAuthorizationSecurityGroupRoleGrant :one
SELECT app.revoke_tenant_human_security_group_role_grant_v1(
  $1::uuid,
  $2::uuid,
  $3::integer,
  $4::text,
  $5::uuid,
  $6::uuid,
  $7::uuid,
  $8::inet,
  nullif($9::text, ''),
  $10::text
) AS version
`

type RevokeTenantAuthorizationSecurityGroupRoleGrantParams struct {
	GroupID              pgtype.UUID `db:"group_id" json:"group_id"`
	GroupRoleGrantID     pgtype.UUID `db:"group_role_grant_id" json:"group_role_grant_id"`
	ExpectedVersion      int32       `db:"expected_version" json:"expected_version"`
	Reason               string      `db:"reason" json:"reason"`
	AuditID              pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
}

func (q *Queries) RevokeTenantAuthorizationSecurityGroupRoleGrant(ctx context.Context, arg RevokeTenantAuthorizationSecurityGroupRoleGrantParams) (int32, error) {
	row := q.db.QueryRow(ctx, revokeTenantAuthorizationSecurityGroupRoleGrant,
		arg.GroupID,
		arg.GroupRoleGrantID,
		arg.ExpectedVersion,
		arg.Reason,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const revokeTenantUserRoleGrant = `-- name: RevokeTenantUserRoleGrant :one
SELECT app.revoke_tenant_human_user_role_grant_v1(
  $1::uuid,
  $2::integer,
  $3::text,
  $4::uuid,
  $5::uuid,
  $6::uuid,
  $7::inet,
  nullif($8::text, ''),
  $9::text
) AS version
`

type RevokeTenantUserRoleGrantParams struct {
	GrantID              pgtype.UUID `db:"grant_id" json:"grant_id"`
	ExpectedVersion      int32       `db:"expected_version" json:"expected_version"`
	Reason               string      `db:"reason" json:"reason"`
	AuditID              pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
}

func (q *Queries) RevokeTenantUserRoleGrant(ctx context.Context, arg RevokeTenantUserRoleGrantParams) (int32, error) {
	row := q.db.QueryRow(ctx, revokeTenantUserRoleGrant,
		arg.GrantID,
		arg.ExpectedVersion,
		arg.Reason,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const updateTenantAuthorizationRoleMetadata = `-- name: UpdateTenantAuthorizationRoleMetadata :one
SELECT app.update_tenant_role_metadata(
  $1::uuid,
  $2::integer,
  $3::text,
  $4::text,
  $5::uuid,
  $6::uuid,
  $7::uuid,
  $8::inet,
  nullif($9::text, ''),
  $10::text
) AS version
`

type UpdateTenantAuthorizationRoleMetadataParams struct {
	RoleID               pgtype.UUID `db:"role_id" json:"role_id"`
	ExpectedVersion      int32       `db:"expected_version" json:"expected_version"`
	RoleName             *string     `db:"role_name" json:"role_name"`
	RoleDescription      *string     `db:"role_description" json:"role_description"`
	AuditID              pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
}

func (q *Queries) UpdateTenantAuthorizationRoleMetadata(ctx context.Context, arg UpdateTenantAuthorizationRoleMetadataParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateTenantAuthorizationRoleMetadata,
		arg.RoleID,
		arg.ExpectedVersion,
		arg.RoleName,
		arg.RoleDescription,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const updateTenantAuthorizationSecurityGroupMetadata = `-- name: UpdateTenantAuthorizationSecurityGroupMetadata :one
SELECT app.update_tenant_security_group_metadata(
  $1::uuid,
  $2::integer,
  $3::text,
  $4::text,
  $5::uuid,
  $6::uuid,
  $7::uuid,
  $8::inet,
  nullif($9::text, ''),
  $10::text
) AS version
`

type UpdateTenantAuthorizationSecurityGroupMetadataParams struct {
	GroupID              pgtype.UUID `db:"group_id" json:"group_id"`
	ExpectedVersion      int32       `db:"expected_version" json:"expected_version"`
	GroupName            *string     `db:"group_name" json:"group_name"`
	GroupDescription     *string     `db:"group_description" json:"group_description"`
	AuditID              pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
}

func (q *Queries) UpdateTenantAuthorizationSecurityGroupMetadata(ctx context.Context, arg UpdateTenantAuthorizationSecurityGroupMetadataParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateTenantAuthorizationSecurityGroupMetadata,
		arg.GroupID,
		arg.ExpectedVersion,
		arg.GroupName,
		arg.GroupDescription,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}
