// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: context.sql

package dbsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const setTenantContext = `-- name: SetTenantContext :one
SELECT
  set_config('app.tenant_id', $1::uuid::text, true)::text AS tenant_id,
  set_config('app.user_id', $2::uuid::text, true)::text AS user_id
`

type SetTenantContextParams struct {
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	UserID   pgtype.UUID `db:"user_id" json:"user_id"`
}

type SetTenantContextRow struct {
	TenantID string `db:"tenant_id" json:"tenant_id"`
	UserID   string `db:"user_id" json:"user_id"`
}

func (q *Queries) SetTenantContext(ctx context.Context, arg SetTenantContextParams) (*SetTenantContextRow, error) {
	row := q.db.QueryRow(ctx, setTenantContext, arg.TenantID, arg.UserID)
	var i SetTenantContextRow
	err := row.Scan(&i.TenantID, &i.UserID)
	return &i, err
}
