// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ldap_directory_inspections.sql

package dbsql

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const beginTenantLDAPAdministrativeDirectoryInspection = `-- name: BeginTenantLDAPAdministrativeDirectoryInspection :one
SELECT snapshot.operation_run_id::uuid AS operation_run_id,
       snapshot.tenant_id::uuid AS tenant_id,
       snapshot.provider_id::uuid AS provider_id,
       snapshot.provider_version::integer AS provider_version,
       snapshot.configuration_version::integer AS configuration_version,
       snapshot.endpoint_snapshot_digest::bytea AS endpoint_snapshot_digest,
       snapshot.configuration::jsonb AS configuration,
       snapshot.endpoints::jsonb AS endpoints,
       snapshot.bind_secret_id::uuid AS bind_secret_id,
       snapshot.bind_secret_ciphertext::bytea AS bind_secret_ciphertext,
       snapshot.bind_secret_nonce::bytea AS bind_secret_nonce,
       snapshot.bind_secret_version::integer AS bind_secret_version,
       snapshot.bind_secret_key_version::integer AS bind_secret_key_version,
       snapshot.bind_secret_algorithm::text AS bind_secret_algorithm,
       snapshot.started_at::timestamptz AS started_at,
       snapshot.expires_at::timestamptz AS expires_at
FROM app.begin_tenant_ldap_administrative_search_v1(
  $1::uuid,
  $2::uuid,
  $3::text::ldap_directory_operation_kind,
  $4::text,
  $5::uuid,
  $6::uuid,
  $7::uuid,
  $8::inet,
  nullif($9::text, ''),
  $10::text
) AS snapshot
`

type BeginTenantLDAPAdministrativeDirectoryInspectionParams struct {
	OperationRunID       pgtype.UUID `db:"operation_run_id" json:"operation_run_id"`
	ProviderID           pgtype.UUID `db:"provider_id" json:"provider_id"`
	OperationKind        string      `db:"operation_kind" json:"operation_kind"`
	Reason               string      `db:"reason" json:"reason"`
	AuditEventID         pgtype.UUID `db:"audit_event_id" json:"audit_event_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
}

type BeginTenantLDAPAdministrativeDirectoryInspectionRow struct {
	OperationRunID         pgtype.UUID        `db:"operation_run_id" json:"operation_run_id"`
	TenantID               pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	ProviderID             pgtype.UUID        `db:"provider_id" json:"provider_id"`
	ProviderVersion        int32              `db:"provider_version" json:"provider_version"`
	ConfigurationVersion   int32              `db:"configuration_version" json:"configuration_version"`
	EndpointSnapshotDigest []byte             `db:"endpoint_snapshot_digest" json:"endpoint_snapshot_digest"`
	Configuration          []byte             `db:"configuration" json:"configuration"`
	Endpoints              []byte             `db:"endpoints" json:"endpoints"`
	BindSecretID           pgtype.UUID        `db:"bind_secret_id" json:"bind_secret_id"`
	BindSecretCiphertext   []byte             `db:"bind_secret_ciphertext" json:"bind_secret_ciphertext"`
	BindSecretNonce        []byte             `db:"bind_secret_nonce" json:"bind_secret_nonce"`
	BindSecretVersion      int32              `db:"bind_secret_version" json:"bind_secret_version"`
	BindSecretKeyVersion   int32              `db:"bind_secret_key_version" json:"bind_secret_key_version"`
	BindSecretAlgorithm    string             `db:"bind_secret_algorithm" json:"bind_secret_algorithm"`
	StartedAt              pgtype.Timestamptz `db:"started_at" json:"started_at"`
	ExpiresAt              pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) BeginTenantLDAPAdministrativeDirectoryInspection(ctx context.Context, arg BeginTenantLDAPAdministrativeDirectoryInspectionParams) (*BeginTenantLDAPAdministrativeDirectoryInspectionRow, error) {
	row := q.db.QueryRow(ctx, beginTenantLDAPAdministrativeDirectoryInspection,
		arg.OperationRunID,
		arg.ProviderID,
		arg.OperationKind,
		arg.Reason,
		arg.AuditEventID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
	)
	var i BeginTenantLDAPAdministrativeDirectoryInspectionRow
	err := row.Scan(
		&i.OperationRunID,
		&i.TenantID,
		&i.ProviderID,
		&i.ProviderVersion,
		&i.ConfigurationVersion,
		&i.EndpointSnapshotDigest,
		&i.Configuration,
		&i.Endpoints,
		&i.BindSecretID,
		&i.BindSecretCiphertext,
		&i.BindSecretNonce,
		&i.BindSecretVersion,
		&i.BindSecretKeyVersion,
		&i.BindSecretAlgorithm,
		&i.StartedAt,
		&i.ExpiresAt,
	)
	return &i, err
}

const beginTenantLDAPMappingDryRun = `-- name: BeginTenantLDAPMappingDryRun :one
SELECT snapshot.operation_run_id::uuid AS operation_run_id,
       snapshot.tenant_id::uuid AS tenant_id,
       snapshot.provider_id::uuid AS provider_id,
       snapshot.provider_version::integer AS provider_version,
       snapshot.configuration_version::integer AS configuration_version,
       snapshot.endpoint_snapshot_digest::bytea AS endpoint_snapshot_digest,
       snapshot.configuration::jsonb AS configuration,
       snapshot.endpoints::jsonb AS endpoints,
       snapshot.bind_secret_id::uuid AS bind_secret_id,
       snapshot.bind_secret_ciphertext::bytea AS bind_secret_ciphertext,
       snapshot.bind_secret_nonce::bytea AS bind_secret_nonce,
       snapshot.bind_secret_version::integer AS bind_secret_version,
       snapshot.bind_secret_key_version::integer AS bind_secret_key_version,
       snapshot.bind_secret_algorithm::text AS bind_secret_algorithm,
       snapshot.binding_id::uuid AS binding_id,
       snapshot.binding_version::integer AS binding_version,
       snapshot.binding_auth_revision::integer AS binding_auth_revision,
       snapshot.binding_access_epoch_id::uuid AS binding_access_epoch_id,
       snapshot.rule_set_revision::bigint AS rule_set_revision,
       snapshot.authorization_revision::bigint AS authorization_revision,
       snapshot.mapping_revisions::jsonb AS mapping_revisions,
       snapshot.started_at::timestamptz AS started_at,
       snapshot.expires_at::timestamptz AS expires_at
FROM app.begin_tenant_ldap_mapping_dry_run_v1(
  $1::uuid,
  $2::uuid,
  $3::uuid[],
  $4::text,
  $5::uuid,
  $6::uuid,
  $7::uuid,
  $8::inet,
  nullif($9::text, ''),
  $10::text
) AS snapshot
`

type BeginTenantLDAPMappingDryRunParams struct {
	OperationRunID            pgtype.UUID   `db:"operation_run_id" json:"operation_run_id"`
	BindingID                 pgtype.UUID   `db:"binding_id" json:"binding_id"`
	IncludeDisabledMappingIds []pgtype.UUID `db:"include_disabled_mapping_ids" json:"include_disabled_mapping_ids"`
	Reason                    string        `db:"reason" json:"reason"`
	AuditEventID              pgtype.UUID   `db:"audit_event_id" json:"audit_event_id"`
	RequestID                 pgtype.UUID   `db:"request_id" json:"request_id"`
	CorrelationID             pgtype.UUID   `db:"correlation_id" json:"correlation_id"`
	IpAddress                 netip.Addr    `db:"ip_address" json:"ip_address"`
	UserAgent                 string        `db:"user_agent" json:"user_agent"`
	AuthenticationMethod      string        `db:"authentication_method" json:"authentication_method"`
}

type BeginTenantLDAPMappingDryRunRow struct {
	OperationRunID         pgtype.UUID        `db:"operation_run_id" json:"operation_run_id"`
	TenantID               pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	ProviderID             pgtype.UUID        `db:"provider_id" json:"provider_id"`
	ProviderVersion        int32              `db:"provider_version" json:"provider_version"`
	ConfigurationVersion   int32              `db:"configuration_version" json:"configuration_version"`
	EndpointSnapshotDigest []byte             `db:"endpoint_snapshot_digest" json:"endpoint_snapshot_digest"`
	Configuration          []byte             `db:"configuration" json:"configuration"`
	Endpoints              []byte             `db:"endpoints" json:"endpoints"`
	BindSecretID           pgtype.UUID        `db:"bind_secret_id" json:"bind_secret_id"`
	BindSecretCiphertext   []byte             `db:"bind_secret_ciphertext" json:"bind_secret_ciphertext"`
	BindSecretNonce        []byte             `db:"bind_secret_nonce" json:"bind_secret_nonce"`
	BindSecretVersion      int32              `db:"bind_secret_version" json:"bind_secret_version"`
	BindSecretKeyVersion   int32              `db:"bind_secret_key_version" json:"bind_secret_key_version"`
	BindSecretAlgorithm    string             `db:"bind_secret_algorithm" json:"bind_secret_algorithm"`
	BindingID              pgtype.UUID        `db:"binding_id" json:"binding_id"`
	BindingVersion         int32              `db:"binding_version" json:"binding_version"`
	BindingAuthRevision    int32              `db:"binding_auth_revision" json:"binding_auth_revision"`
	BindingAccessEpochID   pgtype.UUID        `db:"binding_access_epoch_id" json:"binding_access_epoch_id"`
	RuleSetRevision        int64              `db:"rule_set_revision" json:"rule_set_revision"`
	AuthorizationRevision  int64              `db:"authorization_revision" json:"authorization_revision"`
	MappingRevisions       []byte             `db:"mapping_revisions" json:"mapping_revisions"`
	StartedAt              pgtype.Timestamptz `db:"started_at" json:"started_at"`
	ExpiresAt              pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) BeginTenantLDAPMappingDryRun(ctx context.Context, arg BeginTenantLDAPMappingDryRunParams) (*BeginTenantLDAPMappingDryRunRow, error) {
	row := q.db.QueryRow(ctx, beginTenantLDAPMappingDryRun,
		arg.OperationRunID,
		arg.BindingID,
		arg.IncludeDisabledMappingIds,
		arg.Reason,
		arg.AuditEventID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
	)
	var i BeginTenantLDAPMappingDryRunRow
	err := row.Scan(
		&i.OperationRunID,
		&i.TenantID,
		&i.ProviderID,
		&i.ProviderVersion,
		&i.ConfigurationVersion,
		&i.EndpointSnapshotDigest,
		&i.Configuration,
		&i.Endpoints,
		&i.BindSecretID,
		&i.BindSecretCiphertext,
		&i.BindSecretNonce,
		&i.BindSecretVersion,
		&i.BindSecretKeyVersion,
		&i.BindSecretAlgorithm,
		&i.BindingID,
		&i.BindingVersion,
		&i.BindingAuthRevision,
		&i.BindingAccessEpochID,
		&i.RuleSetRevision,
		&i.AuthorizationRevision,
		&i.MappingRevisions,
		&i.StartedAt,
		&i.ExpiresAt,
	)
	return &i, err
}

const completeTenantLDAPDirectoryInspection = `-- name: CompleteTenantLDAPDirectoryInspection :one
SELECT result.operation_run_id::uuid AS operation_run_id,
       result.outcome::text AS outcome,
       result.category::text AS category,
       coalesce(result.endpoint_priority, 0)::integer AS endpoint_priority,
       result.duration_ms::integer AS duration_ms,
       result.matched_entry_count::integer AS matched_entry_count,
       result.truncated::boolean AS truncated,
       result.stale::boolean AS stale,
       result.completed_at::timestamptz AS completed_at
FROM app.complete_tenant_ldap_directory_operation_v1(
  $1::uuid,
  $2::text::ldap_provider_test_outcome,
  $3::text::ldap_provider_test_category,
  $4::integer,
  $5::integer,
  $6::integer,
  $7::boolean,
  $8::uuid,
  $9::uuid,
  $10::uuid,
  $11::inet,
  nullif($12::text, ''),
  $13::text
) AS result
`

type CompleteTenantLDAPDirectoryInspectionParams struct {
	OperationRunID       pgtype.UUID `db:"operation_run_id" json:"operation_run_id"`
	ReportedOutcome      string      `db:"reported_outcome" json:"reported_outcome"`
	ReportedCategory     string      `db:"reported_category" json:"reported_category"`
	EndpointPriority     *int32      `db:"endpoint_priority" json:"endpoint_priority"`
	DurationMs           int32       `db:"duration_ms" json:"duration_ms"`
	MatchedEntryCount    int32       `db:"matched_entry_count" json:"matched_entry_count"`
	Truncated            bool        `db:"truncated" json:"truncated"`
	AuditEventID         pgtype.UUID `db:"audit_event_id" json:"audit_event_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
}

type CompleteTenantLDAPDirectoryInspectionRow struct {
	OperationRunID    pgtype.UUID        `db:"operation_run_id" json:"operation_run_id"`
	Outcome           string             `db:"outcome" json:"outcome"`
	Category          string             `db:"category" json:"category"`
	EndpointPriority  int32              `db:"endpoint_priority" json:"endpoint_priority"`
	DurationMs        int32              `db:"duration_ms" json:"duration_ms"`
	MatchedEntryCount int32              `db:"matched_entry_count" json:"matched_entry_count"`
	Truncated         bool               `db:"truncated" json:"truncated"`
	Stale             bool               `db:"stale" json:"stale"`
	CompletedAt       pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
}

func (q *Queries) CompleteTenantLDAPDirectoryInspection(ctx context.Context, arg CompleteTenantLDAPDirectoryInspectionParams) (*CompleteTenantLDAPDirectoryInspectionRow, error) {
	row := q.db.QueryRow(ctx, completeTenantLDAPDirectoryInspection,
		arg.OperationRunID,
		arg.ReportedOutcome,
		arg.ReportedCategory,
		arg.EndpointPriority,
		arg.DurationMs,
		arg.MatchedEntryCount,
		arg.Truncated,
		arg.AuditEventID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
	)
	var i CompleteTenantLDAPDirectoryInspectionRow
	err := row.Scan(
		&i.OperationRunID,
		&i.Outcome,
		&i.Category,
		&i.EndpointPriority,
		&i.DurationMs,
		&i.MatchedEntryCount,
		&i.Truncated,
		&i.Stale,
		&i.CompletedAt,
	)
	return &i, err
}

const getTenantLDAPMappingDryRunPlanningSnapshot = `-- name: GetTenantLDAPMappingDryRunPlanningSnapshot :one
SELECT snapshot.operation_run_id::uuid AS operation_run_id,
       snapshot.tenant_id::uuid AS tenant_id,
       snapshot.provider_id::uuid AS provider_id,
       snapshot.provider_version::integer AS provider_version,
       snapshot.binding_id::uuid AS binding_id,
       snapshot.binding_version::integer AS binding_version,
       snapshot.binding_auth_revision::integer AS binding_auth_revision,
       snapshot.binding_access_epoch_id::uuid AS binding_access_epoch_id,
       snapshot.configuration_revision::integer AS configuration_revision,
       snapshot.rule_set_revision::bigint AS rule_set_revision,
       snapshot.authorization_revision::bigint AS authorization_revision,
       snapshot.jit_mode::text AS jit_mode,
       snapshot.no_match_policy::text AS no_match_policy,
       snapshot.effective_until::timestamptz AS effective_until,
       snapshot.provider_access_source_id::uuid AS provider_access_source_id,
       snapshot.provider_access_epoch_id::uuid AS provider_access_epoch_id,
       snapshot.external_identity_id::uuid AS external_identity_id,
       snapshot.user_id::uuid AS user_id,
       snapshot.membership_id::uuid AS membership_id,
       snapshot.external_identity_exists::boolean AS external_identity_exists,
       snapshot.user_active::boolean AS user_active,
       snapshot.tenant_membership_exists::boolean AS tenant_membership_exists,
       snapshot.tenant_membership_active::boolean AS tenant_membership_active,
       snapshot.access_grant_live::boolean AS access_grant_live,
       snapshot.rules::jsonb AS rules,
       snapshot.security_groups::jsonb AS security_groups,
       snapshot.live_assignments::jsonb AS live_assignments,
       snapshot.role_policies::jsonb AS role_policies,
       snapshot.existing_effective_role_ids::uuid[] AS existing_effective_role_ids,
       snapshot.delegation::jsonb AS delegation,
       snapshot.live_owned_edges::jsonb AS live_owned_edges
FROM app.get_tenant_ldap_dry_run_planning_snapshot_v1(
  $1::uuid,
  $2::integer[],
  $3::bytea[]
) AS snapshot
`

type GetTenantLDAPMappingDryRunPlanningSnapshotParams struct {
	OperationRunID    pgtype.UUID `db:"operation_run_id" json:"operation_run_id"`
	DigestKeyVersions []int32     `db:"digest_key_versions" json:"digest_key_versions"`
	SubjectDigests    [][]byte    `db:"subject_digests" json:"subject_digests"`
}

type GetTenantLDAPMappingDryRunPlanningSnapshotRow struct {
	OperationRunID           pgtype.UUID        `db:"operation_run_id" json:"operation_run_id"`
	TenantID                 pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	ProviderID               pgtype.UUID        `db:"provider_id" json:"provider_id"`
	ProviderVersion          int32              `db:"provider_version" json:"provider_version"`
	BindingID                pgtype.UUID        `db:"binding_id" json:"binding_id"`
	BindingVersion           int32              `db:"binding_version" json:"binding_version"`
	BindingAuthRevision      int32              `db:"binding_auth_revision" json:"binding_auth_revision"`
	BindingAccessEpochID     pgtype.UUID        `db:"binding_access_epoch_id" json:"binding_access_epoch_id"`
	ConfigurationRevision    int32              `db:"configuration_revision" json:"configuration_revision"`
	RuleSetRevision          int64              `db:"rule_set_revision" json:"rule_set_revision"`
	AuthorizationRevision    int64              `db:"authorization_revision" json:"authorization_revision"`
	JitMode                  string             `db:"jit_mode" json:"jit_mode"`
	NoMatchPolicy            string             `db:"no_match_policy" json:"no_match_policy"`
	EffectiveUntil           pgtype.Timestamptz `db:"effective_until" json:"effective_until"`
	ProviderAccessSourceID   pgtype.UUID        `db:"provider_access_source_id" json:"provider_access_source_id"`
	ProviderAccessEpochID    pgtype.UUID        `db:"provider_access_epoch_id" json:"provider_access_epoch_id"`
	ExternalIdentityID       pgtype.UUID        `db:"external_identity_id" json:"external_identity_id"`
	UserID                   pgtype.UUID        `db:"user_id" json:"user_id"`
	MembershipID             pgtype.UUID        `db:"membership_id" json:"membership_id"`
	ExternalIdentityExists   bool               `db:"external_identity_exists" json:"external_identity_exists"`
	UserActive               bool               `db:"user_active" json:"user_active"`
	TenantMembershipExists   bool               `db:"tenant_membership_exists" json:"tenant_membership_exists"`
	TenantMembershipActive   bool               `db:"tenant_membership_active" json:"tenant_membership_active"`
	AccessGrantLive          bool               `db:"access_grant_live" json:"access_grant_live"`
	Rules                    []byte             `db:"rules" json:"rules"`
	SecurityGroups           []byte             `db:"security_groups" json:"security_groups"`
	LiveAssignments          []byte             `db:"live_assignments" json:"live_assignments"`
	RolePolicies             []byte             `db:"role_policies" json:"role_policies"`
	ExistingEffectiveRoleIds []pgtype.UUID      `db:"existing_effective_role_ids" json:"existing_effective_role_ids"`
	Delegation               []byte             `db:"delegation" json:"delegation"`
	LiveOwnedEdges           []byte             `db:"live_owned_edges" json:"live_owned_edges"`
}

func (q *Queries) GetTenantLDAPMappingDryRunPlanningSnapshot(ctx context.Context, arg GetTenantLDAPMappingDryRunPlanningSnapshotParams) (*GetTenantLDAPMappingDryRunPlanningSnapshotRow, error) {
	row := q.db.QueryRow(ctx, getTenantLDAPMappingDryRunPlanningSnapshot, arg.OperationRunID, arg.DigestKeyVersions, arg.SubjectDigests)
	var i GetTenantLDAPMappingDryRunPlanningSnapshotRow
	err := row.Scan(
		&i.OperationRunID,
		&i.TenantID,
		&i.ProviderID,
		&i.ProviderVersion,
		&i.BindingID,
		&i.BindingVersion,
		&i.BindingAuthRevision,
		&i.BindingAccessEpochID,
		&i.ConfigurationRevision,
		&i.RuleSetRevision,
		&i.AuthorizationRevision,
		&i.JitMode,
		&i.NoMatchPolicy,
		&i.EffectiveUntil,
		&i.ProviderAccessSourceID,
		&i.ProviderAccessEpochID,
		&i.ExternalIdentityID,
		&i.UserID,
		&i.MembershipID,
		&i.ExternalIdentityExists,
		&i.UserActive,
		&i.TenantMembershipExists,
		&i.TenantMembershipActive,
		&i.AccessGrantLive,
		&i.Rules,
		&i.SecurityGroups,
		&i.LiveAssignments,
		&i.RolePolicies,
		&i.ExistingEffectiveRoleIds,
		&i.Delegation,
		&i.LiveOwnedEdges,
	)
	return &i, err
}
