// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mfa_policy_administration.sql

package dbsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPlatformMFAPolicy = `-- name: GetPlatformMFAPolicy :one
SELECT app.get_platform_mfa_policy_v1(
  $1::uuid,
  $2::text,
  $3::uuid,
  $4::bigint
)::jsonb AS document
`

type GetPlatformMFAPolicyParams struct {
	SessionID            pgtype.UUID `db:"session_id" json:"session_id"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
	PolicyID             pgtype.UUID `db:"policy_id" json:"policy_id"`
	Revision             *int64      `db:"revision" json:"revision"`
}

func (q *Queries) GetPlatformMFAPolicy(ctx context.Context, arg GetPlatformMFAPolicyParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getPlatformMFAPolicy,
		arg.SessionID,
		arg.AuthenticationMethod,
		arg.PolicyID,
		arg.Revision,
	)
	var document []byte
	err := row.Scan(&document)
	return document, err
}

const getTenantMFAPolicy = `-- name: GetTenantMFAPolicy :one
SELECT app.get_tenant_mfa_policy_v1(
  $1::uuid,
  $2::uuid,
  $3::text,
  $4::uuid,
  $5::bigint
)::jsonb AS document
`

type GetTenantMFAPolicyParams struct {
	SessionID            pgtype.UUID `db:"session_id" json:"session_id"`
	TenantID             pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
	PolicyID             pgtype.UUID `db:"policy_id" json:"policy_id"`
	Revision             *int64      `db:"revision" json:"revision"`
}

func (q *Queries) GetTenantMFAPolicy(ctx context.Context, arg GetTenantMFAPolicyParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getTenantMFAPolicy,
		arg.SessionID,
		arg.TenantID,
		arg.AuthenticationMethod,
		arg.PolicyID,
		arg.Revision,
	)
	var document []byte
	err := row.Scan(&document)
	return document, err
}

const listPlatformMFAPolicies = `-- name: ListPlatformMFAPolicies :many
SELECT policy.document::jsonb AS document
FROM app.list_platform_mfa_policies_v1(
  $1::uuid,
  $2::text,
  $3::uuid,
  $4::bigint,
  $5::integer,
  $6::boolean
) AS policy(document)
`

type ListPlatformMFAPoliciesParams struct {
	SessionID            pgtype.UUID `db:"session_id" json:"session_id"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
	AfterPolicyID        pgtype.UUID `db:"after_policy_id" json:"after_policy_id"`
	AfterRevision        *int64      `db:"after_revision" json:"after_revision"`
	PageSize             int32       `db:"page_size" json:"page_size"`
	IncludeRetired       bool        `db:"include_retired" json:"include_retired"`
}

func (q *Queries) ListPlatformMFAPolicies(ctx context.Context, arg ListPlatformMFAPoliciesParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listPlatformMFAPolicies,
		arg.SessionID,
		arg.AuthenticationMethod,
		arg.AfterPolicyID,
		arg.AfterRevision,
		arg.PageSize,
		arg.IncludeRetired,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var document []byte
		if err := rows.Scan(&document); err != nil {
			return nil, err
		}
		items = append(items, document)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantMFAPolicies = `-- name: ListTenantMFAPolicies :many
SELECT policy.document::jsonb AS document
FROM app.list_tenant_mfa_policies_v1(
  $1::uuid,
  $2::uuid,
  $3::text,
  $4::uuid,
  $5::bigint,
  $6::integer,
  $7::boolean
) AS policy(document)
`

type ListTenantMFAPoliciesParams struct {
	SessionID            pgtype.UUID `db:"session_id" json:"session_id"`
	TenantID             pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
	AfterPolicyID        pgtype.UUID `db:"after_policy_id" json:"after_policy_id"`
	AfterRevision        *int64      `db:"after_revision" json:"after_revision"`
	PageSize             int32       `db:"page_size" json:"page_size"`
	IncludeRetired       bool        `db:"include_retired" json:"include_retired"`
}

func (q *Queries) ListTenantMFAPolicies(ctx context.Context, arg ListTenantMFAPoliciesParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listTenantMFAPolicies,
		arg.SessionID,
		arg.TenantID,
		arg.AuthenticationMethod,
		arg.AfterPolicyID,
		arg.AfterRevision,
		arg.PageSize,
		arg.IncludeRetired,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var document []byte
		if err := rows.Scan(&document); err != nil {
			return nil, err
		}
		items = append(items, document)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishPlatformMFAPolicy = `-- name: PublishPlatformMFAPolicy :one
SELECT app.publish_platform_mfa_policy_v1(
  $1::uuid,
  $2::text,
  $3::jsonb
)::jsonb AS document
`

type PublishPlatformMFAPolicyParams struct {
	SessionID            pgtype.UUID `db:"session_id" json:"session_id"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
	Command              []byte      `db:"command" json:"command"`
}

func (q *Queries) PublishPlatformMFAPolicy(ctx context.Context, arg PublishPlatformMFAPolicyParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, publishPlatformMFAPolicy, arg.SessionID, arg.AuthenticationMethod, arg.Command)
	var document []byte
	err := row.Scan(&document)
	return document, err
}

const publishTenantMFAPolicy = `-- name: PublishTenantMFAPolicy :one
SELECT app.publish_tenant_mfa_policy_v1(
  $1::uuid,
  $2::uuid,
  $3::text,
  $4::jsonb
)::jsonb AS document
`

type PublishTenantMFAPolicyParams struct {
	SessionID            pgtype.UUID `db:"session_id" json:"session_id"`
	TenantID             pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
	Command              []byte      `db:"command" json:"command"`
}

func (q *Queries) PublishTenantMFAPolicy(ctx context.Context, arg PublishTenantMFAPolicyParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, publishTenantMFAPolicy,
		arg.SessionID,
		arg.TenantID,
		arg.AuthenticationMethod,
		arg.Command,
	)
	var document []byte
	err := row.Scan(&document)
	return document, err
}

const retirePlatformMFAPolicy = `-- name: RetirePlatformMFAPolicy :one
SELECT app.retire_platform_mfa_policy_v1(
  $1::uuid,
  $2::text,
  $3::jsonb
)::jsonb AS document
`

type RetirePlatformMFAPolicyParams struct {
	SessionID            pgtype.UUID `db:"session_id" json:"session_id"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
	Command              []byte      `db:"command" json:"command"`
}

func (q *Queries) RetirePlatformMFAPolicy(ctx context.Context, arg RetirePlatformMFAPolicyParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, retirePlatformMFAPolicy, arg.SessionID, arg.AuthenticationMethod, arg.Command)
	var document []byte
	err := row.Scan(&document)
	return document, err
}

const retireTenantMFAPolicy = `-- name: RetireTenantMFAPolicy :one
SELECT app.retire_tenant_mfa_policy_v1(
  $1::uuid,
  $2::uuid,
  $3::text,
  $4::jsonb
)::jsonb AS document
`

type RetireTenantMFAPolicyParams struct {
	SessionID            pgtype.UUID `db:"session_id" json:"session_id"`
	TenantID             pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
	Command              []byte      `db:"command" json:"command"`
}

func (q *Queries) RetireTenantMFAPolicy(ctx context.Context, arg RetireTenantMFAPolicyParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, retireTenantMFAPolicy,
		arg.SessionID,
		arg.TenantID,
		arg.AuthenticationMethod,
		arg.Command,
	)
	var document []byte
	err := row.Scan(&document)
	return document, err
}

const simulatePlatformMFAPolicyChange = `-- name: SimulatePlatformMFAPolicyChange :one
SELECT app.simulate_platform_mfa_policy_change_v1(
  $1::uuid,
  $2::text,
  $3::jsonb
)::jsonb AS document
`

type SimulatePlatformMFAPolicyChangeParams struct {
	SessionID            pgtype.UUID `db:"session_id" json:"session_id"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
	Request              []byte      `db:"request" json:"request"`
}

func (q *Queries) SimulatePlatformMFAPolicyChange(ctx context.Context, arg SimulatePlatformMFAPolicyChangeParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, simulatePlatformMFAPolicyChange, arg.SessionID, arg.AuthenticationMethod, arg.Request)
	var document []byte
	err := row.Scan(&document)
	return document, err
}

const simulateTenantMFAPolicyChange = `-- name: SimulateTenantMFAPolicyChange :one
SELECT app.simulate_tenant_mfa_policy_change_v1(
  $1::uuid,
  $2::uuid,
  $3::text,
  $4::jsonb
)::jsonb AS document
`

type SimulateTenantMFAPolicyChangeParams struct {
	SessionID            pgtype.UUID `db:"session_id" json:"session_id"`
	TenantID             pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
	Request              []byte      `db:"request" json:"request"`
}

func (q *Queries) SimulateTenantMFAPolicyChange(ctx context.Context, arg SimulateTenantMFAPolicyChangeParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, simulateTenantMFAPolicyChange,
		arg.SessionID,
		arg.TenantID,
		arg.AuthenticationMethod,
		arg.Request,
	)
	var document []byte
	err := row.Scan(&document)
	return document, err
}
