// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operator_teams.sql

package dbsql

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTenantOperatorTeamRosterEntry = `-- name: AddTenantOperatorTeamRosterEntry :one
SELECT result.result_resource_id::uuid AS result_resource_id,
       result.result_version::integer AS result_version,
       result.replayed::boolean AS replayed
FROM app.add_tenant_operator_team_roster_entry(
  $1::uuid,
  $2::bytea,
  $3::uuid,
  $4::uuid,
  $5::uuid,
  $6::text,
  $7::timestamptz,
  $8::uuid,
  $9::uuid,
  $10::uuid,
  $11::inet,
  nullif($12::text, ''),
  $13::text
) AS result(result_resource_id, result_version, replayed)
`

type AddTenantOperatorTeamRosterEntryParams struct {
	RosterEntryID        pgtype.UUID        `db:"roster_entry_id" json:"roster_entry_id"`
	IdempotencyKeyDigest []byte             `db:"idempotency_key_digest" json:"idempotency_key_digest"`
	OperatorTeamID       pgtype.UUID        `db:"operator_team_id" json:"operator_team_id"`
	AssignmentEpochID    pgtype.UUID        `db:"assignment_epoch_id" json:"assignment_epoch_id"`
	MembershipID         pgtype.UUID        `db:"membership_id" json:"membership_id"`
	Reason               string             `db:"reason" json:"reason"`
	ExpiresAt            pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	AuditID              pgtype.UUID        `db:"audit_id" json:"audit_id"`
	RequestID            pgtype.UUID        `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID        `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr         `db:"ip_address" json:"ip_address"`
	UserAgent            string             `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string             `db:"authentication_method" json:"authentication_method"`
}

type AddTenantOperatorTeamRosterEntryRow struct {
	ResultResourceID pgtype.UUID `db:"result_resource_id" json:"result_resource_id"`
	ResultVersion    int32       `db:"result_version" json:"result_version"`
	Replayed         bool        `db:"replayed" json:"replayed"`
}

func (q *Queries) AddTenantOperatorTeamRosterEntry(ctx context.Context, arg AddTenantOperatorTeamRosterEntryParams) (*AddTenantOperatorTeamRosterEntryRow, error) {
	row := q.db.QueryRow(ctx, addTenantOperatorTeamRosterEntry,
		arg.RosterEntryID,
		arg.IdempotencyKeyDigest,
		arg.OperatorTeamID,
		arg.AssignmentEpochID,
		arg.MembershipID,
		arg.Reason,
		arg.ExpiresAt,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
	)
	var i AddTenantOperatorTeamRosterEntryRow
	err := row.Scan(&i.ResultResourceID, &i.ResultVersion, &i.Replayed)
	return &i, err
}

const archivePlatformOperatorTeam = `-- name: ArchivePlatformOperatorTeam :one
SELECT app.archive_platform_operator_team(
  $1::uuid,
  $2::integer,
  $3::text,
  $4::uuid,
  $5::uuid,
  $6::uuid,
  $7::inet,
  nullif($8::text, ''),
  $9::text
) AS version
`

type ArchivePlatformOperatorTeamParams struct {
	OperatorTeamID       pgtype.UUID `db:"operator_team_id" json:"operator_team_id"`
	ExpectedVersion      int32       `db:"expected_version" json:"expected_version"`
	Reason               string      `db:"reason" json:"reason"`
	AuditID              pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
}

func (q *Queries) ArchivePlatformOperatorTeam(ctx context.Context, arg ArchivePlatformOperatorTeamParams) (int32, error) {
	row := q.db.QueryRow(ctx, archivePlatformOperatorTeam,
		arg.OperatorTeamID,
		arg.ExpectedVersion,
		arg.Reason,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const createPlatformOperatorTeam = `-- name: CreatePlatformOperatorTeam :one
SELECT result.result_resource_id::uuid AS result_resource_id,
       result.result_version::integer AS result_version,
       result.replayed::boolean AS replayed
FROM app.create_platform_operator_team(
  $1::uuid,
  $2::bytea,
  $3::text,
  $4::text,
  $5::text,
  $6::uuid,
  $7::uuid,
  $8::uuid,
  $9::inet,
  nullif($10::text, ''),
  $11::text
) AS result(result_resource_id, result_version, replayed)
`

type CreatePlatformOperatorTeamParams struct {
	OperatorTeamID       pgtype.UUID `db:"operator_team_id" json:"operator_team_id"`
	IdempotencyKeyDigest []byte      `db:"idempotency_key_digest" json:"idempotency_key_digest"`
	TeamKey              string      `db:"team_key" json:"team_key"`
	DisplayName          string      `db:"display_name" json:"display_name"`
	Description          string      `db:"description" json:"description"`
	AuditID              pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
}

type CreatePlatformOperatorTeamRow struct {
	ResultResourceID pgtype.UUID `db:"result_resource_id" json:"result_resource_id"`
	ResultVersion    int32       `db:"result_version" json:"result_version"`
	Replayed         bool        `db:"replayed" json:"replayed"`
}

func (q *Queries) CreatePlatformOperatorTeam(ctx context.Context, arg CreatePlatformOperatorTeamParams) (*CreatePlatformOperatorTeamRow, error) {
	row := q.db.QueryRow(ctx, createPlatformOperatorTeam,
		arg.OperatorTeamID,
		arg.IdempotencyKeyDigest,
		arg.TeamKey,
		arg.DisplayName,
		arg.Description,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
	)
	var i CreatePlatformOperatorTeamRow
	err := row.Scan(&i.ResultResourceID, &i.ResultVersion, &i.Replayed)
	return &i, err
}

const endTenantOperatorTeamAssignment = `-- name: EndTenantOperatorTeamAssignment :one
SELECT app.end_tenant_operator_team_assignment(
  $1::uuid,
  $2::uuid,
  $3::integer,
  $4::text,
  $5::uuid,
  $6::uuid,
  $7::uuid,
  $8::uuid,
  $9::inet,
  nullif($10::text, ''),
  $11::text
) AS version
`

type EndTenantOperatorTeamAssignmentParams struct {
	OperatorTeamID       pgtype.UUID `db:"operator_team_id" json:"operator_team_id"`
	AssignmentEpochID    pgtype.UUID `db:"assignment_epoch_id" json:"assignment_epoch_id"`
	ExpectedVersion      int32       `db:"expected_version" json:"expected_version"`
	Reason               string      `db:"reason" json:"reason"`
	TenantAuditID        pgtype.UUID `db:"tenant_audit_id" json:"tenant_audit_id"`
	PlatformAuditID      pgtype.UUID `db:"platform_audit_id" json:"platform_audit_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
}

func (q *Queries) EndTenantOperatorTeamAssignment(ctx context.Context, arg EndTenantOperatorTeamAssignmentParams) (int32, error) {
	row := q.db.QueryRow(ctx, endTenantOperatorTeamAssignment,
		arg.OperatorTeamID,
		arg.AssignmentEpochID,
		arg.ExpectedVersion,
		arg.Reason,
		arg.TenantAuditID,
		arg.PlatformAuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const getPlatformOperatorTeam = `-- name: GetPlatformOperatorTeam :one
SELECT team.operator_team_id::uuid AS operator_team_id,
       team.team_key::text AS team_key,
       team.display_name::text AS display_name,
       team.description::text AS description,
       team.version::integer AS version,
       team.created_by_user_id::uuid AS created_by_user_id,
       team.archived_at::timestamptz AS archived_at,
       team.archived_by_user_id::uuid AS archived_by_user_id,
       coalesce(team.archive_reason::text, '')::text AS archive_reason,
       team.active_assignment_count::bigint AS active_assignment_count,
       team.created_at::timestamptz AS created_at,
       team.updated_at::timestamptz AS updated_at
FROM app.get_platform_operator_team(
  $1::uuid
) AS team(
  operator_team_id, team_key, display_name, description, version,
  created_by_user_id, archived_at, archived_by_user_id, archive_reason,
  active_assignment_count, created_at, updated_at
)
`

type GetPlatformOperatorTeamParams struct {
	OperatorTeamID pgtype.UUID `db:"operator_team_id" json:"operator_team_id"`
}

type GetPlatformOperatorTeamRow struct {
	OperatorTeamID        pgtype.UUID        `db:"operator_team_id" json:"operator_team_id"`
	TeamKey               string             `db:"team_key" json:"team_key"`
	DisplayName           string             `db:"display_name" json:"display_name"`
	Description           string             `db:"description" json:"description"`
	Version               int32              `db:"version" json:"version"`
	CreatedByUserID       pgtype.UUID        `db:"created_by_user_id" json:"created_by_user_id"`
	ArchivedAt            pgtype.Timestamptz `db:"archived_at" json:"archived_at"`
	ArchivedByUserID      pgtype.UUID        `db:"archived_by_user_id" json:"archived_by_user_id"`
	ArchiveReason         string             `db:"archive_reason" json:"archive_reason"`
	ActiveAssignmentCount int64              `db:"active_assignment_count" json:"active_assignment_count"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetPlatformOperatorTeam(ctx context.Context, arg GetPlatformOperatorTeamParams) (*GetPlatformOperatorTeamRow, error) {
	row := q.db.QueryRow(ctx, getPlatformOperatorTeam, arg.OperatorTeamID)
	var i GetPlatformOperatorTeamRow
	err := row.Scan(
		&i.OperatorTeamID,
		&i.TeamKey,
		&i.DisplayName,
		&i.Description,
		&i.Version,
		&i.CreatedByUserID,
		&i.ArchivedAt,
		&i.ArchivedByUserID,
		&i.ArchiveReason,
		&i.ActiveAssignmentCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getTenantOperatorTeamAssignment = `-- name: GetTenantOperatorTeamAssignment :one
SELECT assignment.assignment_epoch_id::uuid AS assignment_epoch_id,
       assignment.operator_team_id::uuid AS operator_team_id,
       assignment.team_key::text AS team_key,
       assignment.team_display_name::text AS team_display_name,
       assignment.team_archived_at::timestamptz AS team_archived_at,
       assignment.assigned_by_membership_id::uuid AS assigned_by_membership_id,
       assignment.assigned_by_user_id::uuid AS assigned_by_user_id,
       assignment.assignment_reason::text AS assignment_reason,
       assignment.assigned_at::timestamptz AS assigned_at,
       assignment.ended_at::timestamptz AS ended_at,
       assignment.ended_by_membership_id::uuid AS ended_by_membership_id,
       assignment.ended_by_user_id::uuid AS ended_by_user_id,
       coalesce(assignment.end_reason::text, '')::text AS end_reason,
       assignment.version::integer AS version,
       assignment.updated_at::timestamptz AS updated_at
FROM app.get_tenant_operator_team_assignment_epoch(
  $1::uuid,
  $2::uuid
) AS assignment(
  assignment_epoch_id, operator_team_id, team_key, team_display_name,
  team_archived_at, assigned_by_membership_id, assigned_by_user_id,
  assignment_reason, assigned_at, ended_at, ended_by_membership_id,
  ended_by_user_id, end_reason, version, updated_at
)
`

type GetTenantOperatorTeamAssignmentParams struct {
	OperatorTeamID    pgtype.UUID `db:"operator_team_id" json:"operator_team_id"`
	AssignmentEpochID pgtype.UUID `db:"assignment_epoch_id" json:"assignment_epoch_id"`
}

type GetTenantOperatorTeamAssignmentRow struct {
	AssignmentEpochID      pgtype.UUID        `db:"assignment_epoch_id" json:"assignment_epoch_id"`
	OperatorTeamID         pgtype.UUID        `db:"operator_team_id" json:"operator_team_id"`
	TeamKey                string             `db:"team_key" json:"team_key"`
	TeamDisplayName        string             `db:"team_display_name" json:"team_display_name"`
	TeamArchivedAt         pgtype.Timestamptz `db:"team_archived_at" json:"team_archived_at"`
	AssignedByMembershipID pgtype.UUID        `db:"assigned_by_membership_id" json:"assigned_by_membership_id"`
	AssignedByUserID       pgtype.UUID        `db:"assigned_by_user_id" json:"assigned_by_user_id"`
	AssignmentReason       string             `db:"assignment_reason" json:"assignment_reason"`
	AssignedAt             pgtype.Timestamptz `db:"assigned_at" json:"assigned_at"`
	EndedAt                pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	EndedByMembershipID    pgtype.UUID        `db:"ended_by_membership_id" json:"ended_by_membership_id"`
	EndedByUserID          pgtype.UUID        `db:"ended_by_user_id" json:"ended_by_user_id"`
	EndReason              string             `db:"end_reason" json:"end_reason"`
	Version                int32              `db:"version" json:"version"`
	UpdatedAt              pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetTenantOperatorTeamAssignment(ctx context.Context, arg GetTenantOperatorTeamAssignmentParams) (*GetTenantOperatorTeamAssignmentRow, error) {
	row := q.db.QueryRow(ctx, getTenantOperatorTeamAssignment, arg.OperatorTeamID, arg.AssignmentEpochID)
	var i GetTenantOperatorTeamAssignmentRow
	err := row.Scan(
		&i.AssignmentEpochID,
		&i.OperatorTeamID,
		&i.TeamKey,
		&i.TeamDisplayName,
		&i.TeamArchivedAt,
		&i.AssignedByMembershipID,
		&i.AssignedByUserID,
		&i.AssignmentReason,
		&i.AssignedAt,
		&i.EndedAt,
		&i.EndedByMembershipID,
		&i.EndedByUserID,
		&i.EndReason,
		&i.Version,
		&i.UpdatedAt,
	)
	return &i, err
}

const getTenantOperatorTeamRosterEntry = `-- name: GetTenantOperatorTeamRosterEntry :one
SELECT roster.roster_entry_id::uuid AS roster_entry_id,
       roster.operator_team_id::uuid AS operator_team_id,
       roster.team_key::text AS team_key,
       roster.team_display_name::text AS team_display_name,
       roster.team_archived_at::timestamptz AS team_archived_at,
       roster.assignment_epoch_id::uuid AS assignment_epoch_id,
       roster.assignment_ended_at::timestamptz AS assignment_ended_at,
       roster.membership_id::uuid AS membership_id,
       roster.target_user_id::uuid AS target_user_id,
       roster.email::text AS email,
       roster.display_name::text AS display_name,
       roster.membership_status::text AS membership_status,
       roster.compatibility_role::text AS compatibility_role,
       roster.user_active::boolean AS user_active,
       roster.source_id::uuid AS source_id,
       roster.source_kind::text AS source_kind,
       roster.source_key::text AS source_key,
       roster.source_authoritative::boolean AS source_authoritative,
       roster.source_retired_at::timestamptz AS source_retired_at,
       roster.granted_by_membership_id::uuid AS granted_by_membership_id,
       roster.granted_by_user_id::uuid AS granted_by_user_id,
       roster.grant_reason::text AS grant_reason,
       roster.granted_at::timestamptz AS granted_at,
       roster.expires_at::timestamptz AS expires_at,
       roster.revoked_at::timestamptz AS revoked_at,
       roster.revoked_by_membership_id::uuid AS revoked_by_membership_id,
       roster.revoked_by_user_id::uuid AS revoked_by_user_id,
       coalesce(roster.revoke_reason::text, '')::text AS revoke_reason,
       roster.roster_state::text AS roster_state,
       roster.version::integer AS version,
       roster.updated_at::timestamptz AS updated_at
FROM app.get_tenant_operator_team_roster_entry(
  $1::uuid,
  $2::uuid,
  $3::uuid
) AS roster(
  roster_entry_id, operator_team_id, team_key, team_display_name,
  team_archived_at, assignment_epoch_id, assignment_ended_at, membership_id,
  target_user_id, email, display_name, membership_status, compatibility_role,
  user_active, source_id, source_kind, source_key, source_authoritative,
  source_retired_at, granted_by_membership_id, granted_by_user_id,
  grant_reason, granted_at, expires_at, revoked_at, revoked_by_membership_id,
  revoked_by_user_id, revoke_reason, roster_state, version, updated_at
)
`

type GetTenantOperatorTeamRosterEntryParams struct {
	OperatorTeamID    pgtype.UUID `db:"operator_team_id" json:"operator_team_id"`
	AssignmentEpochID pgtype.UUID `db:"assignment_epoch_id" json:"assignment_epoch_id"`
	RosterEntryID     pgtype.UUID `db:"roster_entry_id" json:"roster_entry_id"`
}

type GetTenantOperatorTeamRosterEntryRow struct {
	RosterEntryID         pgtype.UUID        `db:"roster_entry_id" json:"roster_entry_id"`
	OperatorTeamID        pgtype.UUID        `db:"operator_team_id" json:"operator_team_id"`
	TeamKey               string             `db:"team_key" json:"team_key"`
	TeamDisplayName       string             `db:"team_display_name" json:"team_display_name"`
	TeamArchivedAt        pgtype.Timestamptz `db:"team_archived_at" json:"team_archived_at"`
	AssignmentEpochID     pgtype.UUID        `db:"assignment_epoch_id" json:"assignment_epoch_id"`
	AssignmentEndedAt     pgtype.Timestamptz `db:"assignment_ended_at" json:"assignment_ended_at"`
	MembershipID          pgtype.UUID        `db:"membership_id" json:"membership_id"`
	TargetUserID          pgtype.UUID        `db:"target_user_id" json:"target_user_id"`
	Email                 string             `db:"email" json:"email"`
	DisplayName           string             `db:"display_name" json:"display_name"`
	MembershipStatus      string             `db:"membership_status" json:"membership_status"`
	CompatibilityRole     string             `db:"compatibility_role" json:"compatibility_role"`
	UserActive            bool               `db:"user_active" json:"user_active"`
	SourceID              pgtype.UUID        `db:"source_id" json:"source_id"`
	SourceKind            string             `db:"source_kind" json:"source_kind"`
	SourceKey             string             `db:"source_key" json:"source_key"`
	SourceAuthoritative   bool               `db:"source_authoritative" json:"source_authoritative"`
	SourceRetiredAt       pgtype.Timestamptz `db:"source_retired_at" json:"source_retired_at"`
	GrantedByMembershipID pgtype.UUID        `db:"granted_by_membership_id" json:"granted_by_membership_id"`
	GrantedByUserID       pgtype.UUID        `db:"granted_by_user_id" json:"granted_by_user_id"`
	GrantReason           string             `db:"grant_reason" json:"grant_reason"`
	GrantedAt             pgtype.Timestamptz `db:"granted_at" json:"granted_at"`
	ExpiresAt             pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt             pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RevokedByMembershipID pgtype.UUID        `db:"revoked_by_membership_id" json:"revoked_by_membership_id"`
	RevokedByUserID       pgtype.UUID        `db:"revoked_by_user_id" json:"revoked_by_user_id"`
	RevokeReason          string             `db:"revoke_reason" json:"revoke_reason"`
	RosterState           string             `db:"roster_state" json:"roster_state"`
	Version               int32              `db:"version" json:"version"`
	UpdatedAt             pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetTenantOperatorTeamRosterEntry(ctx context.Context, arg GetTenantOperatorTeamRosterEntryParams) (*GetTenantOperatorTeamRosterEntryRow, error) {
	row := q.db.QueryRow(ctx, getTenantOperatorTeamRosterEntry, arg.OperatorTeamID, arg.AssignmentEpochID, arg.RosterEntryID)
	var i GetTenantOperatorTeamRosterEntryRow
	err := row.Scan(
		&i.RosterEntryID,
		&i.OperatorTeamID,
		&i.TeamKey,
		&i.TeamDisplayName,
		&i.TeamArchivedAt,
		&i.AssignmentEpochID,
		&i.AssignmentEndedAt,
		&i.MembershipID,
		&i.TargetUserID,
		&i.Email,
		&i.DisplayName,
		&i.MembershipStatus,
		&i.CompatibilityRole,
		&i.UserActive,
		&i.SourceID,
		&i.SourceKind,
		&i.SourceKey,
		&i.SourceAuthoritative,
		&i.SourceRetiredAt,
		&i.GrantedByMembershipID,
		&i.GrantedByUserID,
		&i.GrantReason,
		&i.GrantedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedByMembershipID,
		&i.RevokedByUserID,
		&i.RevokeReason,
		&i.RosterState,
		&i.Version,
		&i.UpdatedAt,
	)
	return &i, err
}

const listPlatformOperatorTeams = `-- name: ListPlatformOperatorTeams :many
SELECT team.operator_team_id::uuid AS operator_team_id,
       team.team_key::text AS team_key,
       team.display_name::text AS display_name,
       team.description::text AS description,
       team.version::integer AS version,
       team.created_by_user_id::uuid AS created_by_user_id,
       team.archived_at::timestamptz AS archived_at,
       team.archived_by_user_id::uuid AS archived_by_user_id,
       coalesce(team.archive_reason::text, '')::text AS archive_reason,
       team.active_assignment_count::bigint AS active_assignment_count,
       team.created_at::timestamptz AS created_at,
       team.updated_at::timestamptz AS updated_at
FROM app.list_platform_operator_teams(
  $1::uuid,
  $2::boolean,
  $3::integer
) AS team(
  operator_team_id, team_key, display_name, description, version,
  created_by_user_id, archived_at, archived_by_user_id, archive_reason,
  active_assignment_count, created_at, updated_at
)
`

type ListPlatformOperatorTeamsParams struct {
	AfterID         pgtype.UUID `db:"after_id" json:"after_id"`
	IncludeArchived bool        `db:"include_archived" json:"include_archived"`
	PageSize        int32       `db:"page_size" json:"page_size"`
}

type ListPlatformOperatorTeamsRow struct {
	OperatorTeamID        pgtype.UUID        `db:"operator_team_id" json:"operator_team_id"`
	TeamKey               string             `db:"team_key" json:"team_key"`
	DisplayName           string             `db:"display_name" json:"display_name"`
	Description           string             `db:"description" json:"description"`
	Version               int32              `db:"version" json:"version"`
	CreatedByUserID       pgtype.UUID        `db:"created_by_user_id" json:"created_by_user_id"`
	ArchivedAt            pgtype.Timestamptz `db:"archived_at" json:"archived_at"`
	ArchivedByUserID      pgtype.UUID        `db:"archived_by_user_id" json:"archived_by_user_id"`
	ArchiveReason         string             `db:"archive_reason" json:"archive_reason"`
	ActiveAssignmentCount int64              `db:"active_assignment_count" json:"active_assignment_count"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListPlatformOperatorTeams(ctx context.Context, arg ListPlatformOperatorTeamsParams) ([]*ListPlatformOperatorTeamsRow, error) {
	rows, err := q.db.Query(ctx, listPlatformOperatorTeams, arg.AfterID, arg.IncludeArchived, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListPlatformOperatorTeamsRow
	for rows.Next() {
		var i ListPlatformOperatorTeamsRow
		if err := rows.Scan(
			&i.OperatorTeamID,
			&i.TeamKey,
			&i.DisplayName,
			&i.Description,
			&i.Version,
			&i.CreatedByUserID,
			&i.ArchivedAt,
			&i.ArchivedByUserID,
			&i.ArchiveReason,
			&i.ActiveAssignmentCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantOperatorTeamAssignments = `-- name: ListTenantOperatorTeamAssignments :many
SELECT assignment.assignment_epoch_id::uuid AS assignment_epoch_id,
       assignment.operator_team_id::uuid AS operator_team_id,
       assignment.team_key::text AS team_key,
       assignment.team_display_name::text AS team_display_name,
       assignment.team_archived_at::timestamptz AS team_archived_at,
       assignment.assigned_by_membership_id::uuid AS assigned_by_membership_id,
       assignment.assigned_by_user_id::uuid AS assigned_by_user_id,
       assignment.assignment_reason::text AS assignment_reason,
       assignment.assigned_at::timestamptz AS assigned_at,
       assignment.ended_at::timestamptz AS ended_at,
       assignment.ended_by_membership_id::uuid AS ended_by_membership_id,
       assignment.ended_by_user_id::uuid AS ended_by_user_id,
       coalesce(assignment.end_reason::text, '')::text AS end_reason,
       assignment.version::integer AS version,
       assignment.updated_at::timestamptz AS updated_at
FROM app.list_tenant_operator_team_assignment_epochs(
  $1::uuid,
  $2::uuid,
  $3::boolean,
  $4::integer
) AS assignment(
  assignment_epoch_id, operator_team_id, team_key, team_display_name,
  team_archived_at, assigned_by_membership_id, assigned_by_user_id,
  assignment_reason, assigned_at, ended_at, ended_by_membership_id,
  ended_by_user_id, end_reason, version, updated_at
)
`

type ListTenantOperatorTeamAssignmentsParams struct {
	OperatorTeamID pgtype.UUID `db:"operator_team_id" json:"operator_team_id"`
	AfterEpochID   pgtype.UUID `db:"after_epoch_id" json:"after_epoch_id"`
	IncludeEnded   bool        `db:"include_ended" json:"include_ended"`
	PageSize       int32       `db:"page_size" json:"page_size"`
}

type ListTenantOperatorTeamAssignmentsRow struct {
	AssignmentEpochID      pgtype.UUID        `db:"assignment_epoch_id" json:"assignment_epoch_id"`
	OperatorTeamID         pgtype.UUID        `db:"operator_team_id" json:"operator_team_id"`
	TeamKey                string             `db:"team_key" json:"team_key"`
	TeamDisplayName        string             `db:"team_display_name" json:"team_display_name"`
	TeamArchivedAt         pgtype.Timestamptz `db:"team_archived_at" json:"team_archived_at"`
	AssignedByMembershipID pgtype.UUID        `db:"assigned_by_membership_id" json:"assigned_by_membership_id"`
	AssignedByUserID       pgtype.UUID        `db:"assigned_by_user_id" json:"assigned_by_user_id"`
	AssignmentReason       string             `db:"assignment_reason" json:"assignment_reason"`
	AssignedAt             pgtype.Timestamptz `db:"assigned_at" json:"assigned_at"`
	EndedAt                pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	EndedByMembershipID    pgtype.UUID        `db:"ended_by_membership_id" json:"ended_by_membership_id"`
	EndedByUserID          pgtype.UUID        `db:"ended_by_user_id" json:"ended_by_user_id"`
	EndReason              string             `db:"end_reason" json:"end_reason"`
	Version                int32              `db:"version" json:"version"`
	UpdatedAt              pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListTenantOperatorTeamAssignments(ctx context.Context, arg ListTenantOperatorTeamAssignmentsParams) ([]*ListTenantOperatorTeamAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listTenantOperatorTeamAssignments,
		arg.OperatorTeamID,
		arg.AfterEpochID,
		arg.IncludeEnded,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListTenantOperatorTeamAssignmentsRow
	for rows.Next() {
		var i ListTenantOperatorTeamAssignmentsRow
		if err := rows.Scan(
			&i.AssignmentEpochID,
			&i.OperatorTeamID,
			&i.TeamKey,
			&i.TeamDisplayName,
			&i.TeamArchivedAt,
			&i.AssignedByMembershipID,
			&i.AssignedByUserID,
			&i.AssignmentReason,
			&i.AssignedAt,
			&i.EndedAt,
			&i.EndedByMembershipID,
			&i.EndedByUserID,
			&i.EndReason,
			&i.Version,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantOperatorTeamRosterEntries = `-- name: ListTenantOperatorTeamRosterEntries :many
SELECT roster.roster_entry_id::uuid AS roster_entry_id,
       roster.operator_team_id::uuid AS operator_team_id,
       roster.team_key::text AS team_key,
       roster.team_display_name::text AS team_display_name,
       roster.team_archived_at::timestamptz AS team_archived_at,
       roster.assignment_epoch_id::uuid AS assignment_epoch_id,
       roster.assignment_ended_at::timestamptz AS assignment_ended_at,
       roster.membership_id::uuid AS membership_id,
       roster.target_user_id::uuid AS target_user_id,
       roster.email::text AS email,
       roster.display_name::text AS display_name,
       roster.membership_status::text AS membership_status,
       roster.compatibility_role::text AS compatibility_role,
       roster.user_active::boolean AS user_active,
       roster.source_id::uuid AS source_id,
       roster.source_kind::text AS source_kind,
       roster.source_key::text AS source_key,
       roster.source_authoritative::boolean AS source_authoritative,
       roster.source_retired_at::timestamptz AS source_retired_at,
       roster.granted_by_membership_id::uuid AS granted_by_membership_id,
       roster.granted_by_user_id::uuid AS granted_by_user_id,
       roster.grant_reason::text AS grant_reason,
       roster.granted_at::timestamptz AS granted_at,
       roster.expires_at::timestamptz AS expires_at,
       roster.revoked_at::timestamptz AS revoked_at,
       roster.revoked_by_membership_id::uuid AS revoked_by_membership_id,
       roster.revoked_by_user_id::uuid AS revoked_by_user_id,
       coalesce(roster.revoke_reason::text, '')::text AS revoke_reason,
       roster.roster_state::text AS roster_state,
       roster.version::integer AS version,
       roster.updated_at::timestamptz AS updated_at
FROM app.list_tenant_operator_team_roster_entries(
  $1::uuid,
  $2::uuid,
  $3::uuid,
  $4::boolean,
  $5::integer
) AS roster(
  roster_entry_id, operator_team_id, team_key, team_display_name,
  team_archived_at, assignment_epoch_id, assignment_ended_at, membership_id,
  target_user_id, email, display_name, membership_status, compatibility_role,
  user_active, source_id, source_kind, source_key, source_authoritative,
  source_retired_at, granted_by_membership_id, granted_by_user_id,
  grant_reason, granted_at, expires_at, revoked_at, revoked_by_membership_id,
  revoked_by_user_id, revoke_reason, roster_state, version, updated_at
)
`

type ListTenantOperatorTeamRosterEntriesParams struct {
	OperatorTeamID    pgtype.UUID `db:"operator_team_id" json:"operator_team_id"`
	AssignmentEpochID pgtype.UUID `db:"assignment_epoch_id" json:"assignment_epoch_id"`
	AfterEntryID      pgtype.UUID `db:"after_entry_id" json:"after_entry_id"`
	IncludeRevoked    bool        `db:"include_revoked" json:"include_revoked"`
	PageSize          int32       `db:"page_size" json:"page_size"`
}

type ListTenantOperatorTeamRosterEntriesRow struct {
	RosterEntryID         pgtype.UUID        `db:"roster_entry_id" json:"roster_entry_id"`
	OperatorTeamID        pgtype.UUID        `db:"operator_team_id" json:"operator_team_id"`
	TeamKey               string             `db:"team_key" json:"team_key"`
	TeamDisplayName       string             `db:"team_display_name" json:"team_display_name"`
	TeamArchivedAt        pgtype.Timestamptz `db:"team_archived_at" json:"team_archived_at"`
	AssignmentEpochID     pgtype.UUID        `db:"assignment_epoch_id" json:"assignment_epoch_id"`
	AssignmentEndedAt     pgtype.Timestamptz `db:"assignment_ended_at" json:"assignment_ended_at"`
	MembershipID          pgtype.UUID        `db:"membership_id" json:"membership_id"`
	TargetUserID          pgtype.UUID        `db:"target_user_id" json:"target_user_id"`
	Email                 string             `db:"email" json:"email"`
	DisplayName           string             `db:"display_name" json:"display_name"`
	MembershipStatus      string             `db:"membership_status" json:"membership_status"`
	CompatibilityRole     string             `db:"compatibility_role" json:"compatibility_role"`
	UserActive            bool               `db:"user_active" json:"user_active"`
	SourceID              pgtype.UUID        `db:"source_id" json:"source_id"`
	SourceKind            string             `db:"source_kind" json:"source_kind"`
	SourceKey             string             `db:"source_key" json:"source_key"`
	SourceAuthoritative   bool               `db:"source_authoritative" json:"source_authoritative"`
	SourceRetiredAt       pgtype.Timestamptz `db:"source_retired_at" json:"source_retired_at"`
	GrantedByMembershipID pgtype.UUID        `db:"granted_by_membership_id" json:"granted_by_membership_id"`
	GrantedByUserID       pgtype.UUID        `db:"granted_by_user_id" json:"granted_by_user_id"`
	GrantReason           string             `db:"grant_reason" json:"grant_reason"`
	GrantedAt             pgtype.Timestamptz `db:"granted_at" json:"granted_at"`
	ExpiresAt             pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt             pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RevokedByMembershipID pgtype.UUID        `db:"revoked_by_membership_id" json:"revoked_by_membership_id"`
	RevokedByUserID       pgtype.UUID        `db:"revoked_by_user_id" json:"revoked_by_user_id"`
	RevokeReason          string             `db:"revoke_reason" json:"revoke_reason"`
	RosterState           string             `db:"roster_state" json:"roster_state"`
	Version               int32              `db:"version" json:"version"`
	UpdatedAt             pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListTenantOperatorTeamRosterEntries(ctx context.Context, arg ListTenantOperatorTeamRosterEntriesParams) ([]*ListTenantOperatorTeamRosterEntriesRow, error) {
	rows, err := q.db.Query(ctx, listTenantOperatorTeamRosterEntries,
		arg.OperatorTeamID,
		arg.AssignmentEpochID,
		arg.AfterEntryID,
		arg.IncludeRevoked,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListTenantOperatorTeamRosterEntriesRow
	for rows.Next() {
		var i ListTenantOperatorTeamRosterEntriesRow
		if err := rows.Scan(
			&i.RosterEntryID,
			&i.OperatorTeamID,
			&i.TeamKey,
			&i.TeamDisplayName,
			&i.TeamArchivedAt,
			&i.AssignmentEpochID,
			&i.AssignmentEndedAt,
			&i.MembershipID,
			&i.TargetUserID,
			&i.Email,
			&i.DisplayName,
			&i.MembershipStatus,
			&i.CompatibilityRole,
			&i.UserActive,
			&i.SourceID,
			&i.SourceKind,
			&i.SourceKey,
			&i.SourceAuthoritative,
			&i.SourceRetiredAt,
			&i.GrantedByMembershipID,
			&i.GrantedByUserID,
			&i.GrantReason,
			&i.GrantedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RevokedByMembershipID,
			&i.RevokedByUserID,
			&i.RevokeReason,
			&i.RosterState,
			&i.Version,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveCurrentTenantOperatorTeams = `-- name: ResolveCurrentTenantOperatorTeams :many
SELECT relationship.operator_team_id::uuid AS operator_team_id,
       relationship.assignment_epoch_id::uuid AS assignment_epoch_id
FROM app.resolve_current_tenant_operator_teams(
  $1::integer
) AS relationship(operator_team_id, assignment_epoch_id)
`

type ResolveCurrentTenantOperatorTeamsParams struct {
	PageSize int32 `db:"page_size" json:"page_size"`
}

type ResolveCurrentTenantOperatorTeamsRow struct {
	OperatorTeamID    pgtype.UUID `db:"operator_team_id" json:"operator_team_id"`
	AssignmentEpochID pgtype.UUID `db:"assignment_epoch_id" json:"assignment_epoch_id"`
}

func (q *Queries) ResolveCurrentTenantOperatorTeams(ctx context.Context, arg ResolveCurrentTenantOperatorTeamsParams) ([]*ResolveCurrentTenantOperatorTeamsRow, error) {
	rows, err := q.db.Query(ctx, resolveCurrentTenantOperatorTeams, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ResolveCurrentTenantOperatorTeamsRow
	for rows.Next() {
		var i ResolveCurrentTenantOperatorTeamsRow
		if err := rows.Scan(&i.OperatorTeamID, &i.AssignmentEpochID); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeTenantOperatorTeamRosterEntry = `-- name: RevokeTenantOperatorTeamRosterEntry :one
SELECT app.revoke_tenant_operator_team_roster_entry(
  $1::uuid,
  $2::uuid,
  $3::uuid,
  $4::integer,
  $5::text,
  $6::uuid,
  $7::uuid,
  $8::uuid,
  $9::inet,
  nullif($10::text, ''),
  $11::text
) AS version
`

type RevokeTenantOperatorTeamRosterEntryParams struct {
	OperatorTeamID       pgtype.UUID `db:"operator_team_id" json:"operator_team_id"`
	AssignmentEpochID    pgtype.UUID `db:"assignment_epoch_id" json:"assignment_epoch_id"`
	RosterEntryID        pgtype.UUID `db:"roster_entry_id" json:"roster_entry_id"`
	ExpectedVersion      int32       `db:"expected_version" json:"expected_version"`
	Reason               string      `db:"reason" json:"reason"`
	AuditID              pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
}

func (q *Queries) RevokeTenantOperatorTeamRosterEntry(ctx context.Context, arg RevokeTenantOperatorTeamRosterEntryParams) (int32, error) {
	row := q.db.QueryRow(ctx, revokeTenantOperatorTeamRosterEntry,
		arg.OperatorTeamID,
		arg.AssignmentEpochID,
		arg.RosterEntryID,
		arg.ExpectedVersion,
		arg.Reason,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const startTenantOperatorTeamAssignment = `-- name: StartTenantOperatorTeamAssignment :one
SELECT result.result_resource_id::uuid AS result_resource_id,
       result.result_version::integer AS result_version,
       result.replayed::boolean AS replayed
FROM app.start_tenant_operator_team_assignment(
  $1::uuid,
  $2::bytea,
  $3::uuid,
  $4::text,
  $5::uuid,
  $6::uuid,
  $7::uuid,
  $8::uuid,
  $9::inet,
  nullif($10::text, ''),
  $11::text
) AS result(result_resource_id, result_version, replayed)
`

type StartTenantOperatorTeamAssignmentParams struct {
	AssignmentEpochID    pgtype.UUID `db:"assignment_epoch_id" json:"assignment_epoch_id"`
	IdempotencyKeyDigest []byte      `db:"idempotency_key_digest" json:"idempotency_key_digest"`
	OperatorTeamID       pgtype.UUID `db:"operator_team_id" json:"operator_team_id"`
	Reason               string      `db:"reason" json:"reason"`
	TenantAuditID        pgtype.UUID `db:"tenant_audit_id" json:"tenant_audit_id"`
	PlatformAuditID      pgtype.UUID `db:"platform_audit_id" json:"platform_audit_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
}

type StartTenantOperatorTeamAssignmentRow struct {
	ResultResourceID pgtype.UUID `db:"result_resource_id" json:"result_resource_id"`
	ResultVersion    int32       `db:"result_version" json:"result_version"`
	Replayed         bool        `db:"replayed" json:"replayed"`
}

func (q *Queries) StartTenantOperatorTeamAssignment(ctx context.Context, arg StartTenantOperatorTeamAssignmentParams) (*StartTenantOperatorTeamAssignmentRow, error) {
	row := q.db.QueryRow(ctx, startTenantOperatorTeamAssignment,
		arg.AssignmentEpochID,
		arg.IdempotencyKeyDigest,
		arg.OperatorTeamID,
		arg.Reason,
		arg.TenantAuditID,
		arg.PlatformAuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
	)
	var i StartTenantOperatorTeamAssignmentRow
	err := row.Scan(&i.ResultResourceID, &i.ResultVersion, &i.Replayed)
	return &i, err
}

const updatePlatformOperatorTeamMetadata = `-- name: UpdatePlatformOperatorTeamMetadata :one
SELECT app.update_platform_operator_team_metadata(
  $1::uuid,
  $2::integer,
  $3::text,
  $4::text,
  $5::uuid,
  $6::uuid,
  $7::uuid,
  $8::inet,
  nullif($9::text, ''),
  $10::text
) AS version
`

type UpdatePlatformOperatorTeamMetadataParams struct {
	OperatorTeamID       pgtype.UUID `db:"operator_team_id" json:"operator_team_id"`
	ExpectedVersion      int32       `db:"expected_version" json:"expected_version"`
	DisplayName          *string     `db:"display_name" json:"display_name"`
	Description          *string     `db:"description" json:"description"`
	AuditID              pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
}

func (q *Queries) UpdatePlatformOperatorTeamMetadata(ctx context.Context, arg UpdatePlatformOperatorTeamMetadataParams) (int32, error) {
	row := q.db.QueryRow(ctx, updatePlatformOperatorTeamMetadata,
		arg.OperatorTeamID,
		arg.ExpectedVersion,
		arg.DisplayName,
		arg.Description,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}
