// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_identity_providers.sql

package dbsql

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const activatePlatformAuthProviderTenantExecution = `-- name: ActivatePlatformAuthProviderTenantExecution :one
SELECT result.version::bigint AS version,
       result.document::jsonb AS document
FROM app.activate_platform_auth_provider_tenant_execution_v1(
  $1::uuid,
  $2::uuid,
  $3::bigint,
  $4::text,
  $5::uuid,
  $6::uuid,
  $7::uuid,
  $8::inet,
  $9::text,
  $10::text,
  $11::text
) AS result(version, document)
`

type ActivatePlatformAuthProviderTenantExecutionParams struct {
	SessionID            pgtype.UUID `db:"session_id" json:"session_id"`
	ProviderID           pgtype.UUID `db:"provider_id" json:"provider_id"`
	ExpectedVersion      int64       `db:"expected_version" json:"expected_version"`
	AccountMode          string      `db:"account_mode" json:"account_mode"`
	AuditEventID         pgtype.UUID `db:"audit_event_id" json:"audit_event_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
	Reason               string      `db:"reason" json:"reason"`
}

type ActivatePlatformAuthProviderTenantExecutionRow struct {
	Version  int64  `db:"version" json:"version"`
	Document []byte `db:"document" json:"document"`
}

func (q *Queries) ActivatePlatformAuthProviderTenantExecution(ctx context.Context, arg ActivatePlatformAuthProviderTenantExecutionParams) (*ActivatePlatformAuthProviderTenantExecutionRow, error) {
	row := q.db.QueryRow(ctx, activatePlatformAuthProviderTenantExecution,
		arg.SessionID,
		arg.ProviderID,
		arg.ExpectedVersion,
		arg.AccountMode,
		arg.AuditEventID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
		arg.Reason,
	)
	var i ActivatePlatformAuthProviderTenantExecutionRow
	err := row.Scan(&i.Version, &i.Document)
	return &i, err
}

const activatePlatformOIDCDirectLogin = `-- name: ActivatePlatformOIDCDirectLogin :one
SELECT result.version::bigint AS version,
       result.document::jsonb AS document
FROM app.activate_platform_direct_login_v2(
  $1::uuid,
  $2::uuid,
  $3::bigint,
  $4::uuid,
  $5::uuid,
  $6::uuid,
  $7::inet,
  $8::text,
  $9::text,
  $10::text
) AS result(version, document)
`

type ActivatePlatformOIDCDirectLoginParams struct {
	SessionID            pgtype.UUID `db:"session_id" json:"session_id"`
	ProviderID           pgtype.UUID `db:"provider_id" json:"provider_id"`
	ExpectedVersion      int64       `db:"expected_version" json:"expected_version"`
	AuditEventID         pgtype.UUID `db:"audit_event_id" json:"audit_event_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
	Reason               string      `db:"reason" json:"reason"`
}

type ActivatePlatformOIDCDirectLoginRow struct {
	Version  int64  `db:"version" json:"version"`
	Document []byte `db:"document" json:"document"`
}

func (q *Queries) ActivatePlatformOIDCDirectLogin(ctx context.Context, arg ActivatePlatformOIDCDirectLoginParams) (*ActivatePlatformOIDCDirectLoginRow, error) {
	row := q.db.QueryRow(ctx, activatePlatformOIDCDirectLogin,
		arg.SessionID,
		arg.ProviderID,
		arg.ExpectedVersion,
		arg.AuditEventID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
		arg.Reason,
	)
	var i ActivatePlatformOIDCDirectLoginRow
	err := row.Scan(&i.Version, &i.Document)
	return &i, err
}

const archivePlatformAuthProvider = `-- name: ArchivePlatformAuthProvider :one
SELECT app.archive_platform_auth_provider_v1(
  $1::uuid,
  $2::uuid,
  $3::bigint,
  $4::uuid,
  $5::uuid,
  $6::uuid,
  $7::inet,
  $8::text,
  $9::text,
  $10::text
)::bigint AS version
`

type ArchivePlatformAuthProviderParams struct {
	SessionID            pgtype.UUID `db:"session_id" json:"session_id"`
	ProviderID           pgtype.UUID `db:"provider_id" json:"provider_id"`
	ExpectedVersion      int64       `db:"expected_version" json:"expected_version"`
	AuditEventID         pgtype.UUID `db:"audit_event_id" json:"audit_event_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
	Reason               string      `db:"reason" json:"reason"`
}

func (q *Queries) ArchivePlatformAuthProvider(ctx context.Context, arg ArchivePlatformAuthProviderParams) (int64, error) {
	row := q.db.QueryRow(ctx, archivePlatformAuthProvider,
		arg.SessionID,
		arg.ProviderID,
		arg.ExpectedVersion,
		arg.AuditEventID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
		arg.Reason,
	)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const beginPlatformLDAPTest = `-- name: BeginPlatformLDAPTest :one
SELECT app.begin_platform_ldap_test_v1(
  $1::jsonb
)::jsonb AS snapshot
`

type BeginPlatformLDAPTestParams struct {
	Request []byte `db:"request" json:"request"`
}

func (q *Queries) BeginPlatformLDAPTest(ctx context.Context, arg BeginPlatformLDAPTestParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, beginPlatformLDAPTest, arg.Request)
	var snapshot []byte
	err := row.Scan(&snapshot)
	return snapshot, err
}

const completePlatformLDAPTest = `-- name: CompletePlatformLDAPTest :one
SELECT app.complete_platform_ldap_test_v1(
  $1::jsonb
)::jsonb AS result
`

type CompletePlatformLDAPTestParams struct {
	Request []byte `db:"request" json:"request"`
}

func (q *Queries) CompletePlatformLDAPTest(ctx context.Context, arg CompletePlatformLDAPTestParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, completePlatformLDAPTest, arg.Request)
	var result []byte
	err := row.Scan(&result)
	return result, err
}

const createPlatformLDAPAuthProvider = `-- name: CreatePlatformLDAPAuthProvider :one
SELECT app.create_platform_ldap_provider_v1(
  $1::jsonb
)::jsonb AS result
`

type CreatePlatformLDAPAuthProviderParams struct {
	Request []byte `db:"request" json:"request"`
}

func (q *Queries) CreatePlatformLDAPAuthProvider(ctx context.Context, arg CreatePlatformLDAPAuthProviderParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, createPlatformLDAPAuthProvider, arg.Request)
	var result []byte
	err := row.Scan(&result)
	return result, err
}

const createPlatformOIDCAuthProvider = `-- name: CreatePlatformOIDCAuthProvider :one
SELECT result.provider_id::uuid AS provider_id,
       result.version::bigint AS version,
       result.replayed::boolean AS replayed,
       result.document::jsonb AS document
FROM app.create_platform_oidc_auth_provider_v2(
  $1::uuid,
  $2::uuid,
  $3::uuid,
  $4::text,
  $5::text,
  $6::text,
  $7::jsonb,
  $8::text,
  $9::bytea,
  $10::bytea,
  $11::uuid,
  $12::uuid,
  $13::uuid,
  $14::inet,
  $15::text,
  $16::text,
  $17::text
) AS result(provider_id, version, replayed, document)
`

type CreatePlatformOIDCAuthProviderParams struct {
	SessionID            pgtype.UUID `db:"session_id" json:"session_id"`
	CommandID            pgtype.UUID `db:"command_id" json:"command_id"`
	ProviderID           pgtype.UUID `db:"provider_id" json:"provider_id"`
	ProviderKey          string      `db:"provider_key" json:"provider_key"`
	DisplayName          string      `db:"display_name" json:"display_name"`
	Description          string      `db:"description" json:"description"`
	Configuration        []byte      `db:"configuration" json:"configuration"`
	TenantRedirectUri    string      `db:"tenant_redirect_uri" json:"tenant_redirect_uri"`
	KeyDigest            []byte      `db:"key_digest" json:"key_digest"`
	RequestDigest        []byte      `db:"request_digest" json:"request_digest"`
	AuditEventID         pgtype.UUID `db:"audit_event_id" json:"audit_event_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
	Reason               string      `db:"reason" json:"reason"`
}

type CreatePlatformOIDCAuthProviderRow struct {
	ProviderID pgtype.UUID `db:"provider_id" json:"provider_id"`
	Version    int64       `db:"version" json:"version"`
	Replayed   bool        `db:"replayed" json:"replayed"`
	Document   []byte      `db:"document" json:"document"`
}

func (q *Queries) CreatePlatformOIDCAuthProvider(ctx context.Context, arg CreatePlatformOIDCAuthProviderParams) (*CreatePlatformOIDCAuthProviderRow, error) {
	row := q.db.QueryRow(ctx, createPlatformOIDCAuthProvider,
		arg.SessionID,
		arg.CommandID,
		arg.ProviderID,
		arg.ProviderKey,
		arg.DisplayName,
		arg.Description,
		arg.Configuration,
		arg.TenantRedirectUri,
		arg.KeyDigest,
		arg.RequestDigest,
		arg.AuditEventID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
		arg.Reason,
	)
	var i CreatePlatformOIDCAuthProviderRow
	err := row.Scan(
		&i.ProviderID,
		&i.Version,
		&i.Replayed,
		&i.Document,
	)
	return &i, err
}

const createPlatformSAMLAuthProvider = `-- name: CreatePlatformSAMLAuthProvider :one
SELECT result.provider_id::uuid AS provider_id,
       result.version::bigint AS version,
       result.replayed::boolean AS replayed,
       result.document::jsonb AS document
FROM app.create_platform_saml_auth_provider_v2(
  $1::uuid,
  $2::uuid,
  $3::uuid,
  $4::text,
  $5::text,
  $6::text,
  $7::jsonb,
  $8::bytea,
  $9::bytea,
  $10::uuid,
  $11::uuid,
  $12::uuid,
  $13::inet,
  $14::text,
  $15::text,
  $16::text
) AS result(provider_id, version, replayed, document)
`

type CreatePlatformSAMLAuthProviderParams struct {
	SessionID            pgtype.UUID `db:"session_id" json:"session_id"`
	CommandID            pgtype.UUID `db:"command_id" json:"command_id"`
	ProviderID           pgtype.UUID `db:"provider_id" json:"provider_id"`
	ProviderKey          string      `db:"provider_key" json:"provider_key"`
	DisplayName          string      `db:"display_name" json:"display_name"`
	Description          string      `db:"description" json:"description"`
	Configuration        []byte      `db:"configuration" json:"configuration"`
	KeyDigest            []byte      `db:"key_digest" json:"key_digest"`
	RequestDigest        []byte      `db:"request_digest" json:"request_digest"`
	AuditEventID         pgtype.UUID `db:"audit_event_id" json:"audit_event_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
	Reason               string      `db:"reason" json:"reason"`
}

type CreatePlatformSAMLAuthProviderRow struct {
	ProviderID pgtype.UUID `db:"provider_id" json:"provider_id"`
	Version    int64       `db:"version" json:"version"`
	Replayed   bool        `db:"replayed" json:"replayed"`
	Document   []byte      `db:"document" json:"document"`
}

func (q *Queries) CreatePlatformSAMLAuthProvider(ctx context.Context, arg CreatePlatformSAMLAuthProviderParams) (*CreatePlatformSAMLAuthProviderRow, error) {
	row := q.db.QueryRow(ctx, createPlatformSAMLAuthProvider,
		arg.SessionID,
		arg.CommandID,
		arg.ProviderID,
		arg.ProviderKey,
		arg.DisplayName,
		arg.Description,
		arg.Configuration,
		arg.KeyDigest,
		arg.RequestDigest,
		arg.AuditEventID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
		arg.Reason,
	)
	var i CreatePlatformSAMLAuthProviderRow
	err := row.Scan(
		&i.ProviderID,
		&i.Version,
		&i.Replayed,
		&i.Document,
	)
	return &i, err
}

const deactivatePlatformAuthProviderTenantExecution = `-- name: DeactivatePlatformAuthProviderTenantExecution :one
SELECT result.version::bigint AS version,
       result.document::jsonb AS document
FROM app.deactivate_platform_auth_provider_tenant_execution_v1(
  $1::uuid,
  $2::uuid,
  $3::bigint,
  $4::uuid,
  $5::uuid,
  $6::uuid,
  $7::inet,
  $8::text,
  $9::text,
  $10::text
) AS result(version, document)
`

type DeactivatePlatformAuthProviderTenantExecutionParams struct {
	SessionID            pgtype.UUID `db:"session_id" json:"session_id"`
	ProviderID           pgtype.UUID `db:"provider_id" json:"provider_id"`
	ExpectedVersion      int64       `db:"expected_version" json:"expected_version"`
	AuditEventID         pgtype.UUID `db:"audit_event_id" json:"audit_event_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
	Reason               string      `db:"reason" json:"reason"`
}

type DeactivatePlatformAuthProviderTenantExecutionRow struct {
	Version  int64  `db:"version" json:"version"`
	Document []byte `db:"document" json:"document"`
}

func (q *Queries) DeactivatePlatformAuthProviderTenantExecution(ctx context.Context, arg DeactivatePlatformAuthProviderTenantExecutionParams) (*DeactivatePlatformAuthProviderTenantExecutionRow, error) {
	row := q.db.QueryRow(ctx, deactivatePlatformAuthProviderTenantExecution,
		arg.SessionID,
		arg.ProviderID,
		arg.ExpectedVersion,
		arg.AuditEventID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
		arg.Reason,
	)
	var i DeactivatePlatformAuthProviderTenantExecutionRow
	err := row.Scan(&i.Version, &i.Document)
	return &i, err
}

const deactivatePlatformOIDCDirectLogin = `-- name: DeactivatePlatformOIDCDirectLogin :one
SELECT result.version::bigint AS version,
       result.document::jsonb AS document
FROM app.deactivate_platform_direct_login_v2(
  $1::uuid,
  $2::uuid,
  $3::bigint,
  $4::uuid,
  $5::uuid,
  $6::uuid,
  $7::inet,
  $8::text,
  $9::text,
  $10::text
) AS result(version, document)
`

type DeactivatePlatformOIDCDirectLoginParams struct {
	SessionID            pgtype.UUID `db:"session_id" json:"session_id"`
	ProviderID           pgtype.UUID `db:"provider_id" json:"provider_id"`
	ExpectedVersion      int64       `db:"expected_version" json:"expected_version"`
	AuditEventID         pgtype.UUID `db:"audit_event_id" json:"audit_event_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
	Reason               string      `db:"reason" json:"reason"`
}

type DeactivatePlatformOIDCDirectLoginRow struct {
	Version  int64  `db:"version" json:"version"`
	Document []byte `db:"document" json:"document"`
}

func (q *Queries) DeactivatePlatformOIDCDirectLogin(ctx context.Context, arg DeactivatePlatformOIDCDirectLoginParams) (*DeactivatePlatformOIDCDirectLoginRow, error) {
	row := q.db.QueryRow(ctx, deactivatePlatformOIDCDirectLogin,
		arg.SessionID,
		arg.ProviderID,
		arg.ExpectedVersion,
		arg.AuditEventID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
		arg.Reason,
	)
	var i DeactivatePlatformOIDCDirectLoginRow
	err := row.Scan(&i.Version, &i.Document)
	return &i, err
}

const getPlatformAuthProvider = `-- name: GetPlatformAuthProvider :one
SELECT app.get_platform_auth_provider_v2(
  $1::uuid,
  $2::uuid,
  $3::text
)::jsonb AS document
`

type GetPlatformAuthProviderParams struct {
	SessionID            pgtype.UUID `db:"session_id" json:"session_id"`
	ProviderID           pgtype.UUID `db:"provider_id" json:"provider_id"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
}

func (q *Queries) GetPlatformAuthProvider(ctx context.Context, arg GetPlatformAuthProviderParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getPlatformAuthProvider, arg.SessionID, arg.ProviderID, arg.AuthenticationMethod)
	var document []byte
	err := row.Scan(&document)
	return document, err
}

const listPlatformAuthProviders = `-- name: ListPlatformAuthProviders :many
SELECT provider.document::jsonb AS document
FROM app.list_platform_auth_providers_v2(
  $1::uuid,
  $2::text,
  $3::uuid,
  $4::integer,
  $5::boolean
) AS provider(document)
`

type ListPlatformAuthProvidersParams struct {
	SessionID            pgtype.UUID `db:"session_id" json:"session_id"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
	AfterProviderID      pgtype.UUID `db:"after_provider_id" json:"after_provider_id"`
	PageSize             int32       `db:"page_size" json:"page_size"`
	IncludeArchived      bool        `db:"include_archived" json:"include_archived"`
}

func (q *Queries) ListPlatformAuthProviders(ctx context.Context, arg ListPlatformAuthProvidersParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listPlatformAuthProviders,
		arg.SessionID,
		arg.AuthenticationMethod,
		arg.AfterProviderID,
		arg.PageSize,
		arg.IncludeArchived,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var document []byte
		if err := rows.Scan(&document); err != nil {
			return nil, err
		}
		items = append(items, document)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putPlatformLDAPMapping = `-- name: PutPlatformLDAPMapping :one
SELECT app.put_platform_ldap_mapping_rule_v1(
  $1::jsonb
)::jsonb AS document
`

type PutPlatformLDAPMappingParams struct {
	Request []byte `db:"request" json:"request"`
}

func (q *Queries) PutPlatformLDAPMapping(ctx context.Context, arg PutPlatformLDAPMappingParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, putPlatformLDAPMapping, arg.Request)
	var document []byte
	err := row.Scan(&document)
	return document, err
}

const replacePlatformLDAPBindSecret = `-- name: ReplacePlatformLDAPBindSecret :one
SELECT app.rotate_platform_ldap_bind_secret_v1(
  $1::jsonb
)::jsonb AS result
`

type ReplacePlatformLDAPBindSecretParams struct {
	Request []byte `db:"request" json:"request"`
}

func (q *Queries) ReplacePlatformLDAPBindSecret(ctx context.Context, arg ReplacePlatformLDAPBindSecretParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, replacePlatformLDAPBindSecret, arg.Request)
	var result []byte
	err := row.Scan(&result)
	return result, err
}

const replacePlatformOIDCAuthProviderClientSecret = `-- name: ReplacePlatformOIDCAuthProviderClientSecret :one
SELECT result.version::bigint AS version,
       result.secret_revision::bigint AS secret_revision
FROM app.replace_platform_oidc_client_secret_v1(
  $1::uuid,
  $2::uuid,
  $3::uuid,
  $4::bigint,
  $5::integer,
  $6::bytea,
  $7::bytea,
  $8::uuid,
  $9::uuid,
  $10::uuid,
  $11::inet,
  $12::text,
  $13::text,
  $14::text
) AS result(version, secret_revision)
`

type ReplacePlatformOIDCAuthProviderClientSecretParams struct {
	SessionID            pgtype.UUID `db:"session_id" json:"session_id"`
	ProviderID           pgtype.UUID `db:"provider_id" json:"provider_id"`
	SecretID             pgtype.UUID `db:"secret_id" json:"secret_id"`
	ExpectedVersion      int64       `db:"expected_version" json:"expected_version"`
	KeyVersion           int32       `db:"key_version" json:"key_version"`
	Nonce                []byte      `db:"nonce" json:"nonce"`
	Ciphertext           []byte      `db:"ciphertext" json:"ciphertext"`
	AuditEventID         pgtype.UUID `db:"audit_event_id" json:"audit_event_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
	Reason               string      `db:"reason" json:"reason"`
}

type ReplacePlatformOIDCAuthProviderClientSecretRow struct {
	Version        int64 `db:"version" json:"version"`
	SecretRevision int64 `db:"secret_revision" json:"secret_revision"`
}

func (q *Queries) ReplacePlatformOIDCAuthProviderClientSecret(ctx context.Context, arg ReplacePlatformOIDCAuthProviderClientSecretParams) (*ReplacePlatformOIDCAuthProviderClientSecretRow, error) {
	row := q.db.QueryRow(ctx, replacePlatformOIDCAuthProviderClientSecret,
		arg.SessionID,
		arg.ProviderID,
		arg.SecretID,
		arg.ExpectedVersion,
		arg.KeyVersion,
		arg.Nonce,
		arg.Ciphertext,
		arg.AuditEventID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
		arg.Reason,
	)
	var i ReplacePlatformOIDCAuthProviderClientSecretRow
	err := row.Scan(&i.Version, &i.SecretRevision)
	return &i, err
}

const setPlatformLDAPLoginState = `-- name: SetPlatformLDAPLoginState :one
SELECT app.set_platform_ldap_provider_enabled_v1(
  $1::jsonb
)::jsonb AS document
`

type SetPlatformLDAPLoginStateParams struct {
	Request []byte `db:"request" json:"request"`
}

func (q *Queries) SetPlatformLDAPLoginState(ctx context.Context, arg SetPlatformLDAPLoginStateParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, setPlatformLDAPLoginState, arg.Request)
	var document []byte
	err := row.Scan(&document)
	return document, err
}

const updatePlatformAuthProvider = `-- name: UpdatePlatformAuthProvider :one
SELECT result.version::bigint AS version,
       result.document::jsonb AS document
FROM app.update_platform_auth_provider_v2(
  $1::uuid,
  $2::uuid,
  $3::bigint,
  $4::text,
  $5::text,
  $6::text,
  $7::uuid,
  $8::uuid,
  $9::uuid,
  $10::inet,
  $11::text,
  $12::text,
  $13::text
) AS result(version, document)
`

type UpdatePlatformAuthProviderParams struct {
	SessionID            pgtype.UUID `db:"session_id" json:"session_id"`
	ProviderID           pgtype.UUID `db:"provider_id" json:"provider_id"`
	ExpectedVersion      int64       `db:"expected_version" json:"expected_version"`
	ProviderKey          string      `db:"provider_key" json:"provider_key"`
	DisplayName          string      `db:"display_name" json:"display_name"`
	Description          string      `db:"description" json:"description"`
	AuditEventID         pgtype.UUID `db:"audit_event_id" json:"audit_event_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
	Reason               string      `db:"reason" json:"reason"`
}

type UpdatePlatformAuthProviderRow struct {
	Version  int64  `db:"version" json:"version"`
	Document []byte `db:"document" json:"document"`
}

func (q *Queries) UpdatePlatformAuthProvider(ctx context.Context, arg UpdatePlatformAuthProviderParams) (*UpdatePlatformAuthProviderRow, error) {
	row := q.db.QueryRow(ctx, updatePlatformAuthProvider,
		arg.SessionID,
		arg.ProviderID,
		arg.ExpectedVersion,
		arg.ProviderKey,
		arg.DisplayName,
		arg.Description,
		arg.AuditEventID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
		arg.Reason,
	)
	var i UpdatePlatformAuthProviderRow
	err := row.Scan(&i.Version, &i.Document)
	return &i, err
}

const updatePlatformLDAPAuthProvider = `-- name: UpdatePlatformLDAPAuthProvider :one
SELECT app.update_platform_ldap_provider_v1(
  $1::jsonb
)::jsonb AS document
`

type UpdatePlatformLDAPAuthProviderParams struct {
	Request []byte `db:"request" json:"request"`
}

func (q *Queries) UpdatePlatformLDAPAuthProvider(ctx context.Context, arg UpdatePlatformLDAPAuthProviderParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, updatePlatformLDAPAuthProvider, arg.Request)
	var document []byte
	err := row.Scan(&document)
	return document, err
}
