// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_operations.sql

package dbsql

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPlatformGlobalSettingsOperation = `-- name: GetPlatformGlobalSettingsOperation :one
SELECT settings.platform_name::text AS platform_name,
       settings.default_locale::text AS default_locale,
       settings.default_timezone::text AS default_timezone,
       coalesce(settings.support_url, '')::text AS support_url,
       settings.version::integer AS version,
       settings.updated_at::timestamptz AS updated_at
FROM app.get_platform_global_settings_v1(
  $1::uuid,
  $2::uuid,
  $3::uuid,
  $4::uuid,
  $5::inet,
  $6::text
) AS settings(
  platform_name, default_locale, default_timezone, support_url, version, updated_at
)
`

type GetPlatformGlobalSettingsOperationParams struct {
	SessionID     pgtype.UUID `db:"session_id" json:"session_id"`
	AuditID       pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID     pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress     netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent     string      `db:"user_agent" json:"user_agent"`
}

type GetPlatformGlobalSettingsOperationRow struct {
	PlatformName    string             `db:"platform_name" json:"platform_name"`
	DefaultLocale   string             `db:"default_locale" json:"default_locale"`
	DefaultTimezone string             `db:"default_timezone" json:"default_timezone"`
	SupportUrl      string             `db:"support_url" json:"support_url"`
	Version         int32              `db:"version" json:"version"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetPlatformGlobalSettingsOperation(ctx context.Context, arg GetPlatformGlobalSettingsOperationParams) (*GetPlatformGlobalSettingsOperationRow, error) {
	row := q.db.QueryRow(ctx, getPlatformGlobalSettingsOperation,
		arg.SessionID,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i GetPlatformGlobalSettingsOperationRow
	err := row.Scan(
		&i.PlatformName,
		&i.DefaultLocale,
		&i.DefaultTimezone,
		&i.SupportUrl,
		&i.Version,
		&i.UpdatedAt,
	)
	return &i, err
}

const getPlatformOperationHealth = `-- name: GetPlatformOperationHealth :one
SELECT app.get_platform_operation_health_v1(
  $1::uuid,
  $2::uuid,
  $3::uuid,
  $4::uuid,
  $5::inet,
  $6::text
)::jsonb AS document
`

type GetPlatformOperationHealthParams struct {
	SessionID     pgtype.UUID `db:"session_id" json:"session_id"`
	AuditID       pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID     pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress     netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent     string      `db:"user_agent" json:"user_agent"`
}

func (q *Queries) GetPlatformOperationHealth(ctx context.Context, arg GetPlatformOperationHealthParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getPlatformOperationHealth,
		arg.SessionID,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
	)
	var document []byte
	err := row.Scan(&document)
	return document, err
}

const listPlatformFailedNotifications = `-- name: ListPlatformFailedNotifications :one
SELECT app.list_platform_failed_notifications_v1(
  $1::uuid,
  $2::timestamptz,
  $3::uuid,
  $4::integer,
  $5::uuid,
  $6::uuid,
  $7::uuid,
  $8::inet,
  $9::text
)::jsonb AS document
`

type ListPlatformFailedNotificationsParams struct {
	SessionID       pgtype.UUID        `db:"session_id" json:"session_id"`
	AfterFailureAt  pgtype.Timestamptz `db:"after_failure_at" json:"after_failure_at"`
	AfterDeliveryID pgtype.UUID        `db:"after_delivery_id" json:"after_delivery_id"`
	PageLimit       int32              `db:"page_limit" json:"page_limit"`
	AuditID         pgtype.UUID        `db:"audit_id" json:"audit_id"`
	RequestID       pgtype.UUID        `db:"request_id" json:"request_id"`
	CorrelationID   pgtype.UUID        `db:"correlation_id" json:"correlation_id"`
	IpAddress       netip.Addr         `db:"ip_address" json:"ip_address"`
	UserAgent       string             `db:"user_agent" json:"user_agent"`
}

func (q *Queries) ListPlatformFailedNotifications(ctx context.Context, arg ListPlatformFailedNotificationsParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, listPlatformFailedNotifications,
		arg.SessionID,
		arg.AfterFailureAt,
		arg.AfterDeliveryID,
		arg.PageLimit,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
	)
	var document []byte
	err := row.Scan(&document)
	return document, err
}

const listPlatformFeatureFlags = `-- name: ListPlatformFeatureFlags :one
SELECT app.list_platform_feature_flags_v1(
  $1::uuid,
  $2::uuid,
  $3::uuid,
  $4::uuid,
  $5::inet,
  $6::text
)::jsonb AS document
`

type ListPlatformFeatureFlagsParams struct {
	SessionID     pgtype.UUID `db:"session_id" json:"session_id"`
	AuditID       pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID     pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress     netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent     string      `db:"user_agent" json:"user_agent"`
}

func (q *Queries) ListPlatformFeatureFlags(ctx context.Context, arg ListPlatformFeatureFlagsParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, listPlatformFeatureFlags,
		arg.SessionID,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
	)
	var document []byte
	err := row.Scan(&document)
	return document, err
}

const listPlatformOperationQueues = `-- name: ListPlatformOperationQueues :one
SELECT app.list_platform_operation_queues_v1(
  $1::uuid,
  $2::uuid,
  $3::uuid,
  $4::uuid,
  $5::inet,
  $6::text
)::jsonb AS document
`

type ListPlatformOperationQueuesParams struct {
	SessionID     pgtype.UUID `db:"session_id" json:"session_id"`
	AuditID       pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID     pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress     netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent     string      `db:"user_agent" json:"user_agent"`
}

func (q *Queries) ListPlatformOperationQueues(ctx context.Context, arg ListPlatformOperationQueuesParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, listPlatformOperationQueues,
		arg.SessionID,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
	)
	var document []byte
	err := row.Scan(&document)
	return document, err
}

const listPlatformUsersOperation = `-- name: ListPlatformUsersOperation :one
SELECT app.list_platform_users_v1(
  $1::uuid,
  $2::uuid,
  $3::integer,
  $4::uuid,
  $5::uuid,
  $6::uuid,
  $7::inet,
  $8::text
)::jsonb AS document
`

type ListPlatformUsersOperationParams struct {
	SessionID     pgtype.UUID `db:"session_id" json:"session_id"`
	AfterUserID   pgtype.UUID `db:"after_user_id" json:"after_user_id"`
	PageLimit     int32       `db:"page_limit" json:"page_limit"`
	AuditID       pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID     pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress     netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent     string      `db:"user_agent" json:"user_agent"`
}

func (q *Queries) ListPlatformUsersOperation(ctx context.Context, arg ListPlatformUsersOperationParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, listPlatformUsersOperation,
		arg.SessionID,
		arg.AfterUserID,
		arg.PageLimit,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
	)
	var document []byte
	err := row.Scan(&document)
	return document, err
}

const updatePlatformFeatureFlag = `-- name: UpdatePlatformFeatureFlag :one
SELECT flag.key::text AS key,
       flag.enabled::boolean AS enabled,
       flag.version::integer AS version,
       flag.updated_at::timestamptz AS updated_at
FROM app.update_platform_feature_flag_v1(
  $1::uuid,
  $2::text,
  $3::integer,
  $4::boolean,
  $5::text,
  $6::uuid,
  $7::uuid,
  $8::uuid,
  $9::inet,
  $10::text
) AS flag(key, enabled, version, updated_at)
`

type UpdatePlatformFeatureFlagParams struct {
	SessionID       pgtype.UUID `db:"session_id" json:"session_id"`
	FlagKey         string      `db:"flag_key" json:"flag_key"`
	ExpectedVersion int32       `db:"expected_version" json:"expected_version"`
	Enabled         bool        `db:"enabled" json:"enabled"`
	Reason          string      `db:"reason" json:"reason"`
	AuditID         pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID       pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID   pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress       netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent       string      `db:"user_agent" json:"user_agent"`
}

type UpdatePlatformFeatureFlagRow struct {
	Key       string             `db:"key" json:"key"`
	Enabled   bool               `db:"enabled" json:"enabled"`
	Version   int32              `db:"version" json:"version"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdatePlatformFeatureFlag(ctx context.Context, arg UpdatePlatformFeatureFlagParams) (*UpdatePlatformFeatureFlagRow, error) {
	row := q.db.QueryRow(ctx, updatePlatformFeatureFlag,
		arg.SessionID,
		arg.FlagKey,
		arg.ExpectedVersion,
		arg.Enabled,
		arg.Reason,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i UpdatePlatformFeatureFlagRow
	err := row.Scan(
		&i.Key,
		&i.Enabled,
		&i.Version,
		&i.UpdatedAt,
	)
	return &i, err
}

const updatePlatformGlobalSettingsOperation = `-- name: UpdatePlatformGlobalSettingsOperation :one
SELECT settings.platform_name::text AS platform_name,
       settings.default_locale::text AS default_locale,
       settings.default_timezone::text AS default_timezone,
       coalesce(settings.support_url, '')::text AS support_url,
       settings.version::integer AS version,
       settings.updated_at::timestamptz AS updated_at
FROM app.update_platform_global_settings_v1(
  $1::uuid,
  $2::integer,
  $3::text,
  $4::text,
  $5::text,
  $6::text,
  $7::text,
  $8::uuid,
  $9::uuid,
  $10::uuid,
  $11::inet,
  $12::text
) AS settings(
  platform_name, default_locale, default_timezone, support_url, version, updated_at
)
`

type UpdatePlatformGlobalSettingsOperationParams struct {
	SessionID       pgtype.UUID `db:"session_id" json:"session_id"`
	ExpectedVersion int32       `db:"expected_version" json:"expected_version"`
	PlatformName    string      `db:"platform_name" json:"platform_name"`
	DefaultLocale   string      `db:"default_locale" json:"default_locale"`
	DefaultTimezone string      `db:"default_timezone" json:"default_timezone"`
	SupportUrl      *string     `db:"support_url" json:"support_url"`
	Reason          string      `db:"reason" json:"reason"`
	AuditID         pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID       pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID   pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress       netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent       string      `db:"user_agent" json:"user_agent"`
}

type UpdatePlatformGlobalSettingsOperationRow struct {
	PlatformName    string             `db:"platform_name" json:"platform_name"`
	DefaultLocale   string             `db:"default_locale" json:"default_locale"`
	DefaultTimezone string             `db:"default_timezone" json:"default_timezone"`
	SupportUrl      string             `db:"support_url" json:"support_url"`
	Version         int32              `db:"version" json:"version"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdatePlatformGlobalSettingsOperation(ctx context.Context, arg UpdatePlatformGlobalSettingsOperationParams) (*UpdatePlatformGlobalSettingsOperationRow, error) {
	row := q.db.QueryRow(ctx, updatePlatformGlobalSettingsOperation,
		arg.SessionID,
		arg.ExpectedVersion,
		arg.PlatformName,
		arg.DefaultLocale,
		arg.DefaultTimezone,
		arg.SupportUrl,
		arg.Reason,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i UpdatePlatformGlobalSettingsOperationRow
	err := row.Scan(
		&i.PlatformName,
		&i.DefaultLocale,
		&i.DefaultTimezone,
		&i.SupportUrl,
		&i.Version,
		&i.UpdatedAt,
	)
	return &i, err
}
