// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform.sql

package dbsql

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const authorizePlatformTenantAccess = `-- name: AuthorizePlatformTenantAccess :one
SELECT access.tenant_id::uuid AS tenant_id,
       access.membership_id::uuid AS membership_id,
       access.user_id::uuid AS user_id,
       access.tenant_version::integer AS tenant_version,
       access.membership_revision::integer AS membership_revision,
       access.authorization_revision::bigint AS authorization_revision,
       access.authorized_at::timestamptz AS authorized_at,
       access.replayed::boolean AS replayed
FROM app.authorize_platform_tenant_access_v1(
  $1::uuid,
  $2::uuid,
  $3::uuid,
  $4::uuid,
  $5::integer,
  $6::text,
  $7::bytea,
  $8::uuid,
  $9::uuid,
  $10::uuid,
  $11::uuid,
  $12::inet,
  $13::text,
  $14::text
) AS access(
  tenant_id, membership_id, user_id, tenant_version, membership_revision,
  authorization_revision, authorized_at, replayed
)
`

type AuthorizePlatformTenantAccessParams struct {
	SessionID             pgtype.UUID `db:"session_id" json:"session_id"`
	TenantID              pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	MembershipID          pgtype.UUID `db:"membership_id" json:"membership_id"`
	RoleGrantID           pgtype.UUID `db:"role_grant_id" json:"role_grant_id"`
	ExpectedTenantVersion int32       `db:"expected_tenant_version" json:"expected_tenant_version"`
	Reason                string      `db:"reason" json:"reason"`
	IdempotencyKeyDigest  []byte      `db:"idempotency_key_digest" json:"idempotency_key_digest"`
	PlatformAuditEventID  pgtype.UUID `db:"platform_audit_event_id" json:"platform_audit_event_id"`
	TenantAuditEventID    pgtype.UUID `db:"tenant_audit_event_id" json:"tenant_audit_event_id"`
	RequestID             pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID         pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress             netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent             string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod  string      `db:"authentication_method" json:"authentication_method"`
}

type AuthorizePlatformTenantAccessRow struct {
	TenantID              pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	MembershipID          pgtype.UUID        `db:"membership_id" json:"membership_id"`
	UserID                pgtype.UUID        `db:"user_id" json:"user_id"`
	TenantVersion         int32              `db:"tenant_version" json:"tenant_version"`
	MembershipRevision    int32              `db:"membership_revision" json:"membership_revision"`
	AuthorizationRevision int64              `db:"authorization_revision" json:"authorization_revision"`
	AuthorizedAt          pgtype.Timestamptz `db:"authorized_at" json:"authorized_at"`
	Replayed              bool               `db:"replayed" json:"replayed"`
}

func (q *Queries) AuthorizePlatformTenantAccess(ctx context.Context, arg AuthorizePlatformTenantAccessParams) (*AuthorizePlatformTenantAccessRow, error) {
	row := q.db.QueryRow(ctx, authorizePlatformTenantAccess,
		arg.SessionID,
		arg.TenantID,
		arg.MembershipID,
		arg.RoleGrantID,
		arg.ExpectedTenantVersion,
		arg.Reason,
		arg.IdempotencyKeyDigest,
		arg.PlatformAuditEventID,
		arg.TenantAuditEventID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
	)
	var i AuthorizePlatformTenantAccessRow
	err := row.Scan(
		&i.TenantID,
		&i.MembershipID,
		&i.UserID,
		&i.TenantVersion,
		&i.MembershipRevision,
		&i.AuthorizationRevision,
		&i.AuthorizedAt,
		&i.Replayed,
	)
	return &i, err
}

const changePlatformTenantLifecycle = `-- name: ChangePlatformTenantLifecycle :one
SELECT lifecycle.tenant_id::uuid AS tenant_id,
       lifecycle.previous_status::text AS previous_status,
       lifecycle.status::text AS status,
       lifecycle.version::integer AS version,
       lifecycle.updated_at::timestamptz AS updated_at,
       lifecycle.replayed::boolean AS replayed
FROM app.change_platform_tenant_lifecycle(
  $1::uuid,
  $2::uuid,
  $3::public.tenant_status,
  $4::integer,
  $5::text,
  $6::uuid,
  $7::uuid,
  $8::uuid,
  $9::inet,
  $10::text,
  $11::text
) AS lifecycle(tenant_id, previous_status, status, version, updated_at, replayed)
`

type ChangePlatformTenantLifecycleParams struct {
	SessionID            pgtype.UUID  `db:"session_id" json:"session_id"`
	TenantID             pgtype.UUID  `db:"tenant_id" json:"tenant_id"`
	Target               TenantStatus `db:"target" json:"target"`
	ExpectedVersion      int32        `db:"expected_version" json:"expected_version"`
	Reason               string       `db:"reason" json:"reason"`
	AuditID              pgtype.UUID  `db:"audit_id" json:"audit_id"`
	RequestID            pgtype.UUID  `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID  `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr   `db:"ip_address" json:"ip_address"`
	UserAgent            string       `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string       `db:"authentication_method" json:"authentication_method"`
}

type ChangePlatformTenantLifecycleRow struct {
	TenantID       pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	PreviousStatus string             `db:"previous_status" json:"previous_status"`
	Status         string             `db:"status" json:"status"`
	Version        int32              `db:"version" json:"version"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Replayed       bool               `db:"replayed" json:"replayed"`
}

func (q *Queries) ChangePlatformTenantLifecycle(ctx context.Context, arg ChangePlatformTenantLifecycleParams) (*ChangePlatformTenantLifecycleRow, error) {
	row := q.db.QueryRow(ctx, changePlatformTenantLifecycle,
		arg.SessionID,
		arg.TenantID,
		arg.Target,
		arg.ExpectedVersion,
		arg.Reason,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
	)
	var i ChangePlatformTenantLifecycleRow
	err := row.Scan(
		&i.TenantID,
		&i.PreviousStatus,
		&i.Status,
		&i.Version,
		&i.UpdatedAt,
		&i.Replayed,
	)
	return &i, err
}

const createPlatformTenant = `-- name: CreatePlatformTenant :one
SELECT tenant.id::uuid AS id, tenant.slug::text AS slug,
       tenant.name::text AS name, tenant.status::text AS status,
       tenant.timezone::text AS timezone, tenant.locale::text AS locale,
	   tenant.version::integer AS version,
       tenant.created_at::timestamptz AS created_at,
       tenant.updated_at::timestamptz AS updated_at
FROM app.create_platform_tenant(
  $1::uuid,
  $2::uuid,
  $3::text,
  $4::text,
  $5::text,
  $6::text,
  $7::uuid,
  $8::uuid,
  $9::uuid,
  $10::inet,
  $11::text,
  $12::text
) AS tenant(id, slug, name, status, timezone, locale, version, created_at, updated_at)
`

type CreatePlatformTenantParams struct {
	TenantID             pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	MembershipID         pgtype.UUID `db:"membership_id" json:"membership_id"`
	Slug                 string      `db:"slug" json:"slug"`
	Name                 string      `db:"name" json:"name"`
	Timezone             string      `db:"timezone" json:"timezone"`
	Locale               string      `db:"locale" json:"locale"`
	AuditID              pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
}

type CreatePlatformTenantRow struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Slug      string             `db:"slug" json:"slug"`
	Name      string             `db:"name" json:"name"`
	Status    string             `db:"status" json:"status"`
	Timezone  string             `db:"timezone" json:"timezone"`
	Locale    string             `db:"locale" json:"locale"`
	Version   int32              `db:"version" json:"version"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreatePlatformTenant(ctx context.Context, arg CreatePlatformTenantParams) (*CreatePlatformTenantRow, error) {
	row := q.db.QueryRow(ctx, createPlatformTenant,
		arg.TenantID,
		arg.MembershipID,
		arg.Slug,
		arg.Name,
		arg.Timezone,
		arg.Locale,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
	)
	var i CreatePlatformTenantRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.Timezone,
		&i.Locale,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listPlatformTenants = `-- name: ListPlatformTenants :many
SELECT tenant.id::uuid AS id, tenant.slug::text AS slug,
       tenant.name::text AS name, tenant.status::text AS status,
       tenant.timezone::text AS timezone, tenant.locale::text AS locale,
	   tenant.version::integer AS version,
       tenant.created_at::timestamptz AS created_at,
       tenant.updated_at::timestamptz AS updated_at
FROM app.list_platform_tenants(
  $1::uuid,
  $2::integer
) AS tenant(id, slug, name, status, timezone, locale, version, created_at, updated_at)
`

type ListPlatformTenantsParams struct {
	AfterID  pgtype.UUID `db:"after_id" json:"after_id"`
	PageSize int32       `db:"page_size" json:"page_size"`
}

type ListPlatformTenantsRow struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Slug      string             `db:"slug" json:"slug"`
	Name      string             `db:"name" json:"name"`
	Status    string             `db:"status" json:"status"`
	Timezone  string             `db:"timezone" json:"timezone"`
	Locale    string             `db:"locale" json:"locale"`
	Version   int32              `db:"version" json:"version"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListPlatformTenants(ctx context.Context, arg ListPlatformTenantsParams) ([]*ListPlatformTenantsRow, error) {
	rows, err := q.db.Query(ctx, listPlatformTenants, arg.AfterID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListPlatformTenantsRow
	for rows.Next() {
		var i ListPlatformTenantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Status,
			&i.Timezone,
			&i.Locale,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
