// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_identity_bindings.sql

package dbsql

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateTenantPlatformAuthProviderBinding = `-- name: ActivateTenantPlatformAuthProviderBinding :one
SELECT result.version::bigint AS version,
       result.document::jsonb AS document
FROM app.activate_tenant_platform_auth_provider_binding_v1(
  $1::uuid,
  $2::uuid,
  $3::uuid,
  $4::bigint,
  $5::integer,
  $6::text,
  $7::text,
  $8::uuid,
  $9::uuid,
  $10::uuid,
  $11::uuid,
  $12::inet,
  $13::text,
  $14::text,
  $15::text
) AS result(version, document)
`

type ActivateTenantPlatformAuthProviderBindingParams struct {
	SessionID             pgtype.UUID `db:"session_id" json:"session_id"`
	PlatformProviderID    pgtype.UUID `db:"platform_provider_id" json:"platform_provider_id"`
	BindingID             pgtype.UUID `db:"binding_id" json:"binding_id"`
	ExpectedVersion       int64       `db:"expected_version" json:"expected_version"`
	ExpectedTenantVersion int32       `db:"expected_tenant_version" json:"expected_tenant_version"`
	JitMode               string      `db:"jit_mode" json:"jit_mode"`
	NoMatchPolicy         string      `db:"no_match_policy" json:"no_match_policy"`
	TenantAuditEventID    pgtype.UUID `db:"tenant_audit_event_id" json:"tenant_audit_event_id"`
	PlatformAuditEventID  pgtype.UUID `db:"platform_audit_event_id" json:"platform_audit_event_id"`
	RequestID             pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID         pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress             netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent             string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod  string      `db:"authentication_method" json:"authentication_method"`
	Reason                string      `db:"reason" json:"reason"`
}

type ActivateTenantPlatformAuthProviderBindingRow struct {
	Version  int64  `db:"version" json:"version"`
	Document []byte `db:"document" json:"document"`
}

func (q *Queries) ActivateTenantPlatformAuthProviderBinding(ctx context.Context, arg ActivateTenantPlatformAuthProviderBindingParams) (*ActivateTenantPlatformAuthProviderBindingRow, error) {
	row := q.db.QueryRow(ctx, activateTenantPlatformAuthProviderBinding,
		arg.SessionID,
		arg.PlatformProviderID,
		arg.BindingID,
		arg.ExpectedVersion,
		arg.ExpectedTenantVersion,
		arg.JitMode,
		arg.NoMatchPolicy,
		arg.TenantAuditEventID,
		arg.PlatformAuditEventID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
		arg.Reason,
	)
	var i ActivateTenantPlatformAuthProviderBindingRow
	err := row.Scan(&i.Version, &i.Document)
	return &i, err
}

const archiveTenantPlatformAuthProviderBinding = `-- name: ArchiveTenantPlatformAuthProviderBinding :one
SELECT result.version::bigint AS version,
       result.tenant_version::integer AS tenant_version
FROM app.archive_tenant_platform_auth_provider_binding_v1(
  $1::uuid,
  $2::uuid,
  $3::uuid,
  $4::bigint,
  $5::integer,
  $6::uuid,
  $7::uuid,
  $8::uuid,
  $9::uuid,
  $10::inet,
  $11::text,
  $12::text,
  $13::text
) AS result(version, tenant_version)
`

type ArchiveTenantPlatformAuthProviderBindingParams struct {
	SessionID             pgtype.UUID `db:"session_id" json:"session_id"`
	PlatformProviderID    pgtype.UUID `db:"platform_provider_id" json:"platform_provider_id"`
	BindingID             pgtype.UUID `db:"binding_id" json:"binding_id"`
	ExpectedVersion       int64       `db:"expected_version" json:"expected_version"`
	ExpectedTenantVersion int32       `db:"expected_tenant_version" json:"expected_tenant_version"`
	TenantAuditEventID    pgtype.UUID `db:"tenant_audit_event_id" json:"tenant_audit_event_id"`
	PlatformAuditEventID  pgtype.UUID `db:"platform_audit_event_id" json:"platform_audit_event_id"`
	RequestID             pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID         pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress             netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent             string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod  string      `db:"authentication_method" json:"authentication_method"`
	Reason                string      `db:"reason" json:"reason"`
}

type ArchiveTenantPlatformAuthProviderBindingRow struct {
	Version       int64 `db:"version" json:"version"`
	TenantVersion int32 `db:"tenant_version" json:"tenant_version"`
}

func (q *Queries) ArchiveTenantPlatformAuthProviderBinding(ctx context.Context, arg ArchiveTenantPlatformAuthProviderBindingParams) (*ArchiveTenantPlatformAuthProviderBindingRow, error) {
	row := q.db.QueryRow(ctx, archiveTenantPlatformAuthProviderBinding,
		arg.SessionID,
		arg.PlatformProviderID,
		arg.BindingID,
		arg.ExpectedVersion,
		arg.ExpectedTenantVersion,
		arg.TenantAuditEventID,
		arg.PlatformAuditEventID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
		arg.Reason,
	)
	var i ArchiveTenantPlatformAuthProviderBindingRow
	err := row.Scan(&i.Version, &i.TenantVersion)
	return &i, err
}

const createTenantPlatformAuthProviderBinding = `-- name: CreateTenantPlatformAuthProviderBinding :one
SELECT result.binding_id::uuid AS binding_id,
       result.version::bigint AS version,
       result.replayed::boolean AS replayed,
       result.document::jsonb AS document
FROM app.create_tenant_platform_auth_provider_binding_v1(
  $1::uuid,
  $2::uuid,
  $3::uuid,
  $4::uuid,
  $5::uuid,
  $6::text,
  $7::integer,
  $8::bytea,
  $9::bytea,
  $10::uuid,
  $11::uuid,
  $12::uuid,
  $13::uuid,
  $14::inet,
  $15::text,
  $16::text,
  $17::text
) AS result(binding_id, version, replayed, document)
`

type CreateTenantPlatformAuthProviderBindingParams struct {
	SessionID            pgtype.UUID `db:"session_id" json:"session_id"`
	CommandID            pgtype.UUID `db:"command_id" json:"command_id"`
	BindingID            pgtype.UUID `db:"binding_id" json:"binding_id"`
	PlatformProviderID   pgtype.UUID `db:"platform_provider_id" json:"platform_provider_id"`
	TenantID             pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	LoginKey             string      `db:"login_key" json:"login_key"`
	ProfilePriority      int32       `db:"profile_priority" json:"profile_priority"`
	KeyDigest            []byte      `db:"key_digest" json:"key_digest"`
	RequestDigest        []byte      `db:"request_digest" json:"request_digest"`
	TenantAuditEventID   pgtype.UUID `db:"tenant_audit_event_id" json:"tenant_audit_event_id"`
	PlatformAuditEventID pgtype.UUID `db:"platform_audit_event_id" json:"platform_audit_event_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
	Reason               string      `db:"reason" json:"reason"`
}

type CreateTenantPlatformAuthProviderBindingRow struct {
	BindingID pgtype.UUID `db:"binding_id" json:"binding_id"`
	Version   int64       `db:"version" json:"version"`
	Replayed  bool        `db:"replayed" json:"replayed"`
	Document  []byte      `db:"document" json:"document"`
}

func (q *Queries) CreateTenantPlatformAuthProviderBinding(ctx context.Context, arg CreateTenantPlatformAuthProviderBindingParams) (*CreateTenantPlatformAuthProviderBindingRow, error) {
	row := q.db.QueryRow(ctx, createTenantPlatformAuthProviderBinding,
		arg.SessionID,
		arg.CommandID,
		arg.BindingID,
		arg.PlatformProviderID,
		arg.TenantID,
		arg.LoginKey,
		arg.ProfilePriority,
		arg.KeyDigest,
		arg.RequestDigest,
		arg.TenantAuditEventID,
		arg.PlatformAuditEventID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
		arg.Reason,
	)
	var i CreateTenantPlatformAuthProviderBindingRow
	err := row.Scan(
		&i.BindingID,
		&i.Version,
		&i.Replayed,
		&i.Document,
	)
	return &i, err
}

const deactivateTenantPlatformAuthProviderBinding = `-- name: DeactivateTenantPlatformAuthProviderBinding :one
SELECT result.version::bigint AS version,
       result.document::jsonb AS document
FROM app.deactivate_tenant_platform_auth_provider_binding_v1(
  $1::uuid,
  $2::uuid,
  $3::uuid,
  $4::bigint,
  $5::integer,
  $6::uuid,
  $7::uuid,
  $8::uuid,
  $9::uuid,
  $10::inet,
  $11::text,
  $12::text,
  $13::text
) AS result(version, document)
`

type DeactivateTenantPlatformAuthProviderBindingParams struct {
	SessionID             pgtype.UUID `db:"session_id" json:"session_id"`
	PlatformProviderID    pgtype.UUID `db:"platform_provider_id" json:"platform_provider_id"`
	BindingID             pgtype.UUID `db:"binding_id" json:"binding_id"`
	ExpectedVersion       int64       `db:"expected_version" json:"expected_version"`
	ExpectedTenantVersion int32       `db:"expected_tenant_version" json:"expected_tenant_version"`
	TenantAuditEventID    pgtype.UUID `db:"tenant_audit_event_id" json:"tenant_audit_event_id"`
	PlatformAuditEventID  pgtype.UUID `db:"platform_audit_event_id" json:"platform_audit_event_id"`
	RequestID             pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID         pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress             netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent             string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod  string      `db:"authentication_method" json:"authentication_method"`
	Reason                string      `db:"reason" json:"reason"`
}

type DeactivateTenantPlatformAuthProviderBindingRow struct {
	Version  int64  `db:"version" json:"version"`
	Document []byte `db:"document" json:"document"`
}

func (q *Queries) DeactivateTenantPlatformAuthProviderBinding(ctx context.Context, arg DeactivateTenantPlatformAuthProviderBindingParams) (*DeactivateTenantPlatformAuthProviderBindingRow, error) {
	row := q.db.QueryRow(ctx, deactivateTenantPlatformAuthProviderBinding,
		arg.SessionID,
		arg.PlatformProviderID,
		arg.BindingID,
		arg.ExpectedVersion,
		arg.ExpectedTenantVersion,
		arg.TenantAuditEventID,
		arg.PlatformAuditEventID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
		arg.Reason,
	)
	var i DeactivateTenantPlatformAuthProviderBindingRow
	err := row.Scan(&i.Version, &i.Document)
	return &i, err
}

const getTenantPlatformAuthProviderBinding = `-- name: GetTenantPlatformAuthProviderBinding :one
SELECT app.get_tenant_platform_auth_provider_binding_v1(
  $1::uuid,
  $2::uuid,
  $3::uuid,
  $4::text
)::jsonb AS document
`

type GetTenantPlatformAuthProviderBindingParams struct {
	SessionID            pgtype.UUID `db:"session_id" json:"session_id"`
	PlatformProviderID   pgtype.UUID `db:"platform_provider_id" json:"platform_provider_id"`
	BindingID            pgtype.UUID `db:"binding_id" json:"binding_id"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
}

func (q *Queries) GetTenantPlatformAuthProviderBinding(ctx context.Context, arg GetTenantPlatformAuthProviderBindingParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getTenantPlatformAuthProviderBinding,
		arg.SessionID,
		arg.PlatformProviderID,
		arg.BindingID,
		arg.AuthenticationMethod,
	)
	var document []byte
	err := row.Scan(&document)
	return document, err
}

const listTenantPlatformAuthProviderBindings = `-- name: ListTenantPlatformAuthProviderBindings :many
SELECT binding.document::jsonb AS document
FROM app.list_tenant_platform_auth_provider_bindings_v1(
  $1::uuid,
  $2::uuid,
  $3::text,
  $4::uuid,
  $5::integer,
  $6::boolean
) AS binding(document)
`

type ListTenantPlatformAuthProviderBindingsParams struct {
	SessionID            pgtype.UUID `db:"session_id" json:"session_id"`
	PlatformProviderID   pgtype.UUID `db:"platform_provider_id" json:"platform_provider_id"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
	AfterBindingID       pgtype.UUID `db:"after_binding_id" json:"after_binding_id"`
	PageSize             int32       `db:"page_size" json:"page_size"`
	IncludeArchived      bool        `db:"include_archived" json:"include_archived"`
}

func (q *Queries) ListTenantPlatformAuthProviderBindings(ctx context.Context, arg ListTenantPlatformAuthProviderBindingsParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listTenantPlatformAuthProviderBindings,
		arg.SessionID,
		arg.PlatformProviderID,
		arg.AuthenticationMethod,
		arg.AfterBindingID,
		arg.PageSize,
		arg.IncludeArchived,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var document []byte
		if err := rows.Scan(&document); err != nil {
			return nil, err
		}
		items = append(items, document)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenantPlatformAuthProviderBinding = `-- name: UpdateTenantPlatformAuthProviderBinding :one
SELECT result.version::bigint AS version,
       result.document::jsonb AS document
FROM app.update_tenant_platform_auth_provider_binding_v1(
  $1::uuid,
  $2::uuid,
  $3::uuid,
  $4::bigint,
  $5::integer,
  $6::text,
  $7::integer,
  $8::uuid,
  $9::uuid,
  $10::uuid,
  $11::uuid,
  $12::inet,
  $13::text,
  $14::text,
  $15::text
) AS result(version, document)
`

type UpdateTenantPlatformAuthProviderBindingParams struct {
	SessionID             pgtype.UUID `db:"session_id" json:"session_id"`
	PlatformProviderID    pgtype.UUID `db:"platform_provider_id" json:"platform_provider_id"`
	BindingID             pgtype.UUID `db:"binding_id" json:"binding_id"`
	ExpectedVersion       int64       `db:"expected_version" json:"expected_version"`
	ExpectedTenantVersion int32       `db:"expected_tenant_version" json:"expected_tenant_version"`
	LoginKey              string      `db:"login_key" json:"login_key"`
	ProfilePriority       int32       `db:"profile_priority" json:"profile_priority"`
	TenantAuditEventID    pgtype.UUID `db:"tenant_audit_event_id" json:"tenant_audit_event_id"`
	PlatformAuditEventID  pgtype.UUID `db:"platform_audit_event_id" json:"platform_audit_event_id"`
	RequestID             pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID         pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress             netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent             string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod  string      `db:"authentication_method" json:"authentication_method"`
	Reason                string      `db:"reason" json:"reason"`
}

type UpdateTenantPlatformAuthProviderBindingRow struct {
	Version  int64  `db:"version" json:"version"`
	Document []byte `db:"document" json:"document"`
}

func (q *Queries) UpdateTenantPlatformAuthProviderBinding(ctx context.Context, arg UpdateTenantPlatformAuthProviderBindingParams) (*UpdateTenantPlatformAuthProviderBindingRow, error) {
	row := q.db.QueryRow(ctx, updateTenantPlatformAuthProviderBinding,
		arg.SessionID,
		arg.PlatformProviderID,
		arg.BindingID,
		arg.ExpectedVersion,
		arg.ExpectedTenantVersion,
		arg.LoginKey,
		arg.ProfilePriority,
		arg.TenantAuditEventID,
		arg.PlatformAuditEventID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
		arg.Reason,
	)
	var i UpdateTenantPlatformAuthProviderBindingRow
	err := row.Scan(&i.Version, &i.Document)
	return &i, err
}
