// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_saml_administration.sql

package dbsql

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearPlatformSAMLSPKey = `-- name: ClearPlatformSAMLSPKey :one
SELECT result.version::bigint AS version,
       result.key_revision::bigint AS material_revision
FROM app.clear_platform_saml_sp_key_v1(
  $1::uuid,
  $2::uuid,
  $3::bigint,
  $4::uuid,
  $5::uuid,
  $6::uuid,
  $7::inet,
  $8::text,
  $9::text,
  $10::text
) AS result(version, key_revision)
`

type ClearPlatformSAMLSPKeyParams struct {
	SessionID            pgtype.UUID `db:"session_id" json:"session_id"`
	ProviderID           pgtype.UUID `db:"provider_id" json:"provider_id"`
	ExpectedVersion      int64       `db:"expected_version" json:"expected_version"`
	AuditEventID         pgtype.UUID `db:"audit_event_id" json:"audit_event_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
	Reason               string      `db:"reason" json:"reason"`
}

type ClearPlatformSAMLSPKeyRow struct {
	Version          int64 `db:"version" json:"version"`
	MaterialRevision int64 `db:"material_revision" json:"material_revision"`
}

func (q *Queries) ClearPlatformSAMLSPKey(ctx context.Context, arg ClearPlatformSAMLSPKeyParams) (*ClearPlatformSAMLSPKeyRow, error) {
	row := q.db.QueryRow(ctx, clearPlatformSAMLSPKey,
		arg.SessionID,
		arg.ProviderID,
		arg.ExpectedVersion,
		arg.AuditEventID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
		arg.Reason,
	)
	var i ClearPlatformSAMLSPKeyRow
	err := row.Scan(&i.Version, &i.MaterialRevision)
	return &i, err
}

const loadPlatformSAMLMetadataAdmin = `-- name: LoadPlatformSAMLMetadataAdmin :one
SELECT app.load_platform_saml_metadata_admin_v1(
  $1::uuid,
  $2::uuid,
  $3::text
)::jsonb AS document
`

type LoadPlatformSAMLMetadataAdminParams struct {
	SessionID            pgtype.UUID `db:"session_id" json:"session_id"`
	ProviderID           pgtype.UUID `db:"provider_id" json:"provider_id"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
}

func (q *Queries) LoadPlatformSAMLMetadataAdmin(ctx context.Context, arg LoadPlatformSAMLMetadataAdminParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, loadPlatformSAMLMetadataAdmin, arg.SessionID, arg.ProviderID, arg.AuthenticationMethod)
	var document []byte
	err := row.Scan(&document)
	return document, err
}

const replacePlatformSAMLMetadata = `-- name: ReplacePlatformSAMLMetadata :one
SELECT result.version::bigint AS version,
       result.metadata_revision::bigint AS material_revision
FROM app.replace_platform_saml_metadata_v1(
  $1::uuid,
  $2::uuid,
  $3::bigint,
  $4::bytea,
  $5::bytea,
  $6::timestamptz,
  $7::timestamptz,
  $8::boolean,
  $9::uuid,
  $10::uuid,
  $11::uuid,
  $12::inet,
  $13::text,
  $14::text,
  $15::text
) AS result(version, metadata_revision)
`

type ReplacePlatformSAMLMetadataParams struct {
	SessionID            pgtype.UUID        `db:"session_id" json:"session_id"`
	ProviderID           pgtype.UUID        `db:"provider_id" json:"provider_id"`
	ExpectedVersion      int64              `db:"expected_version" json:"expected_version"`
	Document             []byte             `db:"document" json:"document"`
	DocumentDigest       []byte             `db:"document_digest" json:"document_digest"`
	RetrievedAt          pgtype.Timestamptz `db:"retrieved_at" json:"retrieved_at"`
	MaximumValidUntil    pgtype.Timestamptz `db:"maximum_valid_until" json:"maximum_valid_until"`
	ProtectedApproval    bool               `db:"protected_approval" json:"protected_approval"`
	AuditEventID         pgtype.UUID        `db:"audit_event_id" json:"audit_event_id"`
	RequestID            pgtype.UUID        `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID        `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr         `db:"ip_address" json:"ip_address"`
	UserAgent            string             `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string             `db:"authentication_method" json:"authentication_method"`
	Reason               string             `db:"reason" json:"reason"`
}

type ReplacePlatformSAMLMetadataRow struct {
	Version          int64 `db:"version" json:"version"`
	MaterialRevision int64 `db:"material_revision" json:"material_revision"`
}

func (q *Queries) ReplacePlatformSAMLMetadata(ctx context.Context, arg ReplacePlatformSAMLMetadataParams) (*ReplacePlatformSAMLMetadataRow, error) {
	row := q.db.QueryRow(ctx, replacePlatformSAMLMetadata,
		arg.SessionID,
		arg.ProviderID,
		arg.ExpectedVersion,
		arg.Document,
		arg.DocumentDigest,
		arg.RetrievedAt,
		arg.MaximumValidUntil,
		arg.ProtectedApproval,
		arg.AuditEventID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
		arg.Reason,
	)
	var i ReplacePlatformSAMLMetadataRow
	err := row.Scan(&i.Version, &i.MaterialRevision)
	return &i, err
}

const replacePlatformSAMLSPKey = `-- name: ReplacePlatformSAMLSPKey :one
SELECT result.version::bigint AS version,
       result.key_revision::bigint AS material_revision
FROM app.replace_platform_saml_sp_key_v1(
  $1::uuid,
  $2::uuid,
  $3::uuid,
  $4::bigint,
  $5::integer,
  $6::bytea,
  $7::bytea,
  $8::bytea[],
  $9::uuid,
  $10::uuid,
  $11::uuid,
  $12::inet,
  $13::text,
  $14::text,
  $15::text
) AS result(version, key_revision)
`

type ReplacePlatformSAMLSPKeyParams struct {
	SessionID            pgtype.UUID `db:"session_id" json:"session_id"`
	ProviderID           pgtype.UUID `db:"provider_id" json:"provider_id"`
	KeyID                pgtype.UUID `db:"key_id" json:"key_id"`
	ExpectedVersion      int64       `db:"expected_version" json:"expected_version"`
	KeyVersion           int32       `db:"key_version" json:"key_version"`
	Nonce                []byte      `db:"nonce" json:"nonce"`
	Ciphertext           []byte      `db:"ciphertext" json:"ciphertext"`
	Certificates         [][]byte    `db:"certificates" json:"certificates"`
	AuditEventID         pgtype.UUID `db:"audit_event_id" json:"audit_event_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
	Reason               string      `db:"reason" json:"reason"`
}

type ReplacePlatformSAMLSPKeyRow struct {
	Version          int64 `db:"version" json:"version"`
	MaterialRevision int64 `db:"material_revision" json:"material_revision"`
}

func (q *Queries) ReplacePlatformSAMLSPKey(ctx context.Context, arg ReplacePlatformSAMLSPKeyParams) (*ReplacePlatformSAMLSPKeyRow, error) {
	row := q.db.QueryRow(ctx, replacePlatformSAMLSPKey,
		arg.SessionID,
		arg.ProviderID,
		arg.KeyID,
		arg.ExpectedVersion,
		arg.KeyVersion,
		arg.Nonce,
		arg.Ciphertext,
		arg.Certificates,
		arg.AuditEventID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
		arg.Reason,
	)
	var i ReplacePlatformSAMLSPKeyRow
	err := row.Scan(&i.Version, &i.MaterialRevision)
	return &i, err
}
