// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: service_accounts.sql

package dbsql

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveTenantServiceAccount = `-- name: ArchiveTenantServiceAccount :one
SELECT app.archive_tenant_service_account_v1(
  $1::uuid,
  $2::integer,
  $3::text,
  $4::uuid,
  $5::uuid,
  $6::inet,
  nullif($7::text, ''),
  $8::text
) AS version
`

type ArchiveTenantServiceAccountParams struct {
	ServiceAccountID     pgtype.UUID `db:"service_account_id" json:"service_account_id"`
	ExpectedVersion      int32       `db:"expected_version" json:"expected_version"`
	Reason               string      `db:"reason" json:"reason"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
}

func (q *Queries) ArchiveTenantServiceAccount(ctx context.Context, arg ArchiveTenantServiceAccountParams) (int32, error) {
	row := q.db.QueryRow(ctx, archiveTenantServiceAccount,
		arg.ServiceAccountID,
		arg.ExpectedVersion,
		arg.Reason,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const createTenantServiceAccount = `-- name: CreateTenantServiceAccount :one
SELECT result.result_resource_id::uuid AS result_resource_id,
       result.result_version::integer AS result_version
FROM app.create_tenant_service_account_v1(
  $1::uuid,
  $2::text,
  $3::text,
  $4::text,
  $5::uuid,
  $6::uuid,
  $7::inet,
  nullif($8::text, ''),
  $9::text
) AS result(result_resource_id, result_version)
`

type CreateTenantServiceAccountParams struct {
	ServiceAccountID     pgtype.UUID `db:"service_account_id" json:"service_account_id"`
	AccountKey           string      `db:"account_key" json:"account_key"`
	DisplayName          string      `db:"display_name" json:"display_name"`
	Description          string      `db:"description" json:"description"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
}

type CreateTenantServiceAccountRow struct {
	ResultResourceID pgtype.UUID `db:"result_resource_id" json:"result_resource_id"`
	ResultVersion    int32       `db:"result_version" json:"result_version"`
}

func (q *Queries) CreateTenantServiceAccount(ctx context.Context, arg CreateTenantServiceAccountParams) (*CreateTenantServiceAccountRow, error) {
	row := q.db.QueryRow(ctx, createTenantServiceAccount,
		arg.ServiceAccountID,
		arg.AccountKey,
		arg.DisplayName,
		arg.Description,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
	)
	var i CreateTenantServiceAccountRow
	err := row.Scan(&i.ResultResourceID, &i.ResultVersion)
	return &i, err
}

const getTenantAPICredential = `-- name: GetTenantAPICredential :one
SELECT credential.credential_id::uuid AS credential_id,
       credential.service_account_id::uuid AS service_account_id,
       credential.label::text AS label,
       credential.format_version::integer AS format_version,
       credential.key_version::integer AS key_version,
       credential.issued_by_membership_id::uuid AS issued_by_membership_id,
       credential.issued_by_user_id::uuid AS issued_by_user_id,
       credential.issued_at::timestamptz AS issued_at,
       credential.expires_at::timestamptz AS expires_at,
       credential.rotated_from_credential_id::uuid AS rotated_from_credential_id,
       credential.revoked_at::timestamptz AS revoked_at,
       credential.revoked_by_membership_id::uuid AS revoked_by_membership_id,
       credential.revoked_by_user_id::uuid AS revoked_by_user_id,
       coalesce(credential.revoke_reason::text, '')::text AS revoke_reason,
       credential.last_used_at::timestamptz AS last_used_at,
       credential.last_used_ip::inet AS last_used_ip,
       CASE
         WHEN credential.revoked_at IS NOT NULL THEN 'revoked'
         WHEN credential.expires_at <= transaction_timestamp() THEN 'expired'
         ELSE 'active'
       END::text AS credential_state,
       credential.version::integer AS version,
       credential.updated_at::timestamptz AS updated_at,
       credential.permission_keys::text[] AS permission_keys,
       credential.permission_scopes::text[] AS permission_scopes,
       credential.networks::cidr[] AS networks
FROM app.get_tenant_api_credential_v1(
  $1::uuid,
  $2::uuid
) AS credential(
  credential_id, service_account_id, label, format_version, key_version,
  issued_by_membership_id, issued_by_user_id, issued_at, expires_at,
  rotated_from_credential_id, revoked_at, revoked_by_membership_id,
  revoked_by_user_id, revoke_reason, last_used_at, last_used_ip, version,
  updated_at, permission_keys, permission_scopes, networks
)
`

type GetTenantAPICredentialParams struct {
	ServiceAccountID pgtype.UUID `db:"service_account_id" json:"service_account_id"`
	CredentialID     pgtype.UUID `db:"credential_id" json:"credential_id"`
}

type GetTenantAPICredentialRow struct {
	CredentialID            pgtype.UUID        `db:"credential_id" json:"credential_id"`
	ServiceAccountID        pgtype.UUID        `db:"service_account_id" json:"service_account_id"`
	Label                   string             `db:"label" json:"label"`
	FormatVersion           int32              `db:"format_version" json:"format_version"`
	KeyVersion              int32              `db:"key_version" json:"key_version"`
	IssuedByMembershipID    pgtype.UUID        `db:"issued_by_membership_id" json:"issued_by_membership_id"`
	IssuedByUserID          pgtype.UUID        `db:"issued_by_user_id" json:"issued_by_user_id"`
	IssuedAt                pgtype.Timestamptz `db:"issued_at" json:"issued_at"`
	ExpiresAt               pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RotatedFromCredentialID pgtype.UUID        `db:"rotated_from_credential_id" json:"rotated_from_credential_id"`
	RevokedAt               pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RevokedByMembershipID   pgtype.UUID        `db:"revoked_by_membership_id" json:"revoked_by_membership_id"`
	RevokedByUserID         pgtype.UUID        `db:"revoked_by_user_id" json:"revoked_by_user_id"`
	RevokeReason            string             `db:"revoke_reason" json:"revoke_reason"`
	LastUsedAt              pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	LastUsedIp              netip.Addr         `db:"last_used_ip" json:"last_used_ip"`
	CredentialState         string             `db:"credential_state" json:"credential_state"`
	Version                 int32              `db:"version" json:"version"`
	UpdatedAt               pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	PermissionKeys          []string           `db:"permission_keys" json:"permission_keys"`
	PermissionScopes        []string           `db:"permission_scopes" json:"permission_scopes"`
	Networks                []netip.Prefix     `db:"networks" json:"networks"`
}

func (q *Queries) GetTenantAPICredential(ctx context.Context, arg GetTenantAPICredentialParams) (*GetTenantAPICredentialRow, error) {
	row := q.db.QueryRow(ctx, getTenantAPICredential, arg.ServiceAccountID, arg.CredentialID)
	var i GetTenantAPICredentialRow
	err := row.Scan(
		&i.CredentialID,
		&i.ServiceAccountID,
		&i.Label,
		&i.FormatVersion,
		&i.KeyVersion,
		&i.IssuedByMembershipID,
		&i.IssuedByUserID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RotatedFromCredentialID,
		&i.RevokedAt,
		&i.RevokedByMembershipID,
		&i.RevokedByUserID,
		&i.RevokeReason,
		&i.LastUsedAt,
		&i.LastUsedIp,
		&i.CredentialState,
		&i.Version,
		&i.UpdatedAt,
		&i.PermissionKeys,
		&i.PermissionScopes,
		&i.Networks,
	)
	return &i, err
}

const getTenantServiceAccount = `-- name: GetTenantServiceAccount :one
SELECT account.service_account_id::uuid AS service_account_id,
       account.account_key::text AS account_key,
       account.display_name::text AS display_name,
       account.description::text AS description,
       account.created_by_membership_id::uuid AS created_by_membership_id,
       account.created_by_user_id::uuid AS created_by_user_id,
       account.archived_at::timestamptz AS archived_at,
       account.archived_by_membership_id::uuid AS archived_by_membership_id,
       account.archived_by_user_id::uuid AS archived_by_user_id,
       coalesce(account.archive_reason::text, '')::text AS archive_reason,
       account.version::integer AS version,
       account.created_at::timestamptz AS created_at,
       account.updated_at::timestamptz AS updated_at
FROM app.get_tenant_service_account_v1(
  $1::uuid
) AS account(
  service_account_id, account_key, display_name, description,
  created_by_membership_id, created_by_user_id, archived_at,
  archived_by_membership_id, archived_by_user_id, archive_reason, version,
  created_at, updated_at
)
`

type GetTenantServiceAccountParams struct {
	ServiceAccountID pgtype.UUID `db:"service_account_id" json:"service_account_id"`
}

type GetTenantServiceAccountRow struct {
	ServiceAccountID       pgtype.UUID        `db:"service_account_id" json:"service_account_id"`
	AccountKey             string             `db:"account_key" json:"account_key"`
	DisplayName            string             `db:"display_name" json:"display_name"`
	Description            string             `db:"description" json:"description"`
	CreatedByMembershipID  pgtype.UUID        `db:"created_by_membership_id" json:"created_by_membership_id"`
	CreatedByUserID        pgtype.UUID        `db:"created_by_user_id" json:"created_by_user_id"`
	ArchivedAt             pgtype.Timestamptz `db:"archived_at" json:"archived_at"`
	ArchivedByMembershipID pgtype.UUID        `db:"archived_by_membership_id" json:"archived_by_membership_id"`
	ArchivedByUserID       pgtype.UUID        `db:"archived_by_user_id" json:"archived_by_user_id"`
	ArchiveReason          string             `db:"archive_reason" json:"archive_reason"`
	Version                int32              `db:"version" json:"version"`
	CreatedAt              pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetTenantServiceAccount(ctx context.Context, arg GetTenantServiceAccountParams) (*GetTenantServiceAccountRow, error) {
	row := q.db.QueryRow(ctx, getTenantServiceAccount, arg.ServiceAccountID)
	var i GetTenantServiceAccountRow
	err := row.Scan(
		&i.ServiceAccountID,
		&i.AccountKey,
		&i.DisplayName,
		&i.Description,
		&i.CreatedByMembershipID,
		&i.CreatedByUserID,
		&i.ArchivedAt,
		&i.ArchivedByMembershipID,
		&i.ArchivedByUserID,
		&i.ArchiveReason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getTenantServiceAccountRoleGrant = `-- name: GetTenantServiceAccountRoleGrant :one
SELECT role_grant.grant_id::uuid AS grant_id,
       role_grant.service_account_id::uuid AS service_account_id,
       role_grant.role_id::uuid AS role_id,
       role_grant.role_key::text AS role_key,
       role_grant.role_display_name::text AS role_display_name,
       role_grant.role_system::boolean AS role_system,
       role_grant.source_id::uuid AS source_id,
       role_grant.source_kind::text AS source_kind,
       role_grant.source_key::text AS source_key,
       role_grant.source_authoritative::boolean AS source_authoritative,
       role_grant.source_retired_at::timestamptz AS source_retired_at,
       role_grant.granted_by_membership_id::uuid AS granted_by_membership_id,
       role_grant.granted_by_user_id::uuid AS granted_by_user_id,
       role_grant.grant_reason::text AS grant_reason,
       role_grant.granted_at::timestamptz AS granted_at,
       role_grant.expires_at::timestamptz AS expires_at,
       role_grant.revoked_at::timestamptz AS revoked_at,
       role_grant.revoked_by_membership_id::uuid AS revoked_by_membership_id,
       role_grant.revoked_by_user_id::uuid AS revoked_by_user_id,
       coalesce(role_grant.revoke_reason::text, '')::text AS revoke_reason,
       role_grant.grant_state::text AS grant_state,
       role_grant.version::integer AS version,
       role_grant.updated_at::timestamptz AS updated_at
FROM app.get_tenant_service_account_role_grant_v1(
  $1::uuid,
  $2::uuid
) AS role_grant(
  grant_id, service_account_id, role_id, role_key, role_display_name,
  role_system, source_id, source_kind, source_key, source_authoritative,
  source_retired_at, granted_by_membership_id, granted_by_user_id,
  grant_reason, granted_at, expires_at, revoked_at,
  revoked_by_membership_id, revoked_by_user_id, revoke_reason, grant_state,
  version, updated_at
)
`

type GetTenantServiceAccountRoleGrantParams struct {
	ServiceAccountID pgtype.UUID `db:"service_account_id" json:"service_account_id"`
	GrantID          pgtype.UUID `db:"grant_id" json:"grant_id"`
}

type GetTenantServiceAccountRoleGrantRow struct {
	GrantID               pgtype.UUID        `db:"grant_id" json:"grant_id"`
	ServiceAccountID      pgtype.UUID        `db:"service_account_id" json:"service_account_id"`
	RoleID                pgtype.UUID        `db:"role_id" json:"role_id"`
	RoleKey               string             `db:"role_key" json:"role_key"`
	RoleDisplayName       string             `db:"role_display_name" json:"role_display_name"`
	RoleSystem            bool               `db:"role_system" json:"role_system"`
	SourceID              pgtype.UUID        `db:"source_id" json:"source_id"`
	SourceKind            string             `db:"source_kind" json:"source_kind"`
	SourceKey             string             `db:"source_key" json:"source_key"`
	SourceAuthoritative   bool               `db:"source_authoritative" json:"source_authoritative"`
	SourceRetiredAt       pgtype.Timestamptz `db:"source_retired_at" json:"source_retired_at"`
	GrantedByMembershipID pgtype.UUID        `db:"granted_by_membership_id" json:"granted_by_membership_id"`
	GrantedByUserID       pgtype.UUID        `db:"granted_by_user_id" json:"granted_by_user_id"`
	GrantReason           string             `db:"grant_reason" json:"grant_reason"`
	GrantedAt             pgtype.Timestamptz `db:"granted_at" json:"granted_at"`
	ExpiresAt             pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt             pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RevokedByMembershipID pgtype.UUID        `db:"revoked_by_membership_id" json:"revoked_by_membership_id"`
	RevokedByUserID       pgtype.UUID        `db:"revoked_by_user_id" json:"revoked_by_user_id"`
	RevokeReason          string             `db:"revoke_reason" json:"revoke_reason"`
	GrantState            string             `db:"grant_state" json:"grant_state"`
	Version               int32              `db:"version" json:"version"`
	UpdatedAt             pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetTenantServiceAccountRoleGrant(ctx context.Context, arg GetTenantServiceAccountRoleGrantParams) (*GetTenantServiceAccountRoleGrantRow, error) {
	row := q.db.QueryRow(ctx, getTenantServiceAccountRoleGrant, arg.ServiceAccountID, arg.GrantID)
	var i GetTenantServiceAccountRoleGrantRow
	err := row.Scan(
		&i.GrantID,
		&i.ServiceAccountID,
		&i.RoleID,
		&i.RoleKey,
		&i.RoleDisplayName,
		&i.RoleSystem,
		&i.SourceID,
		&i.SourceKind,
		&i.SourceKey,
		&i.SourceAuthoritative,
		&i.SourceRetiredAt,
		&i.GrantedByMembershipID,
		&i.GrantedByUserID,
		&i.GrantReason,
		&i.GrantedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedByMembershipID,
		&i.RevokedByUserID,
		&i.RevokeReason,
		&i.GrantState,
		&i.Version,
		&i.UpdatedAt,
	)
	return &i, err
}

const grantTenantServiceAccountRole = `-- name: GrantTenantServiceAccountRole :one
SELECT result.result_resource_id::uuid AS result_resource_id,
       result.result_version::integer AS result_version
FROM app.grant_tenant_service_account_role_v1(
  $1::uuid,
  $2::uuid,
  $3::uuid,
  $4::text,
  $5::timestamptz,
  $6::uuid,
  $7::uuid,
  $8::inet,
  nullif($9::text, ''),
  $10::text
) AS result(result_resource_id, result_version)
`

type GrantTenantServiceAccountRoleParams struct {
	GrantID              pgtype.UUID        `db:"grant_id" json:"grant_id"`
	ServiceAccountID     pgtype.UUID        `db:"service_account_id" json:"service_account_id"`
	RoleID               pgtype.UUID        `db:"role_id" json:"role_id"`
	Reason               string             `db:"reason" json:"reason"`
	ExpiresAt            pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RequestID            pgtype.UUID        `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID        `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr         `db:"ip_address" json:"ip_address"`
	UserAgent            string             `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string             `db:"authentication_method" json:"authentication_method"`
}

type GrantTenantServiceAccountRoleRow struct {
	ResultResourceID pgtype.UUID `db:"result_resource_id" json:"result_resource_id"`
	ResultVersion    int32       `db:"result_version" json:"result_version"`
}

func (q *Queries) GrantTenantServiceAccountRole(ctx context.Context, arg GrantTenantServiceAccountRoleParams) (*GrantTenantServiceAccountRoleRow, error) {
	row := q.db.QueryRow(ctx, grantTenantServiceAccountRole,
		arg.GrantID,
		arg.ServiceAccountID,
		arg.RoleID,
		arg.Reason,
		arg.ExpiresAt,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
	)
	var i GrantTenantServiceAccountRoleRow
	err := row.Scan(&i.ResultResourceID, &i.ResultVersion)
	return &i, err
}

const issueTenantAPICredential = `-- name: IssueTenantAPICredential :one
SELECT result.result_credential_id::uuid AS result_credential_id,
       result.result_version::integer AS result_version,
       result.replayed::boolean AS replayed
FROM app.issue_tenant_api_credential_v1(
  $1::uuid,
  $2::uuid,
  $3::bytea,
  $4::bytea,
  $5::text,
  $6::integer,
  $7::bytea,
  $8::integer,
  $9::bytea,
  $10::timestamptz,
  $11::text[],
  $12::text[]::authorization_scope[],
  $13::cidr[],
  $14::uuid,
  $15::uuid,
  $16::inet,
  nullif($17::text, ''),
  $18::text
) AS result(result_credential_id, result_version, replayed)
`

type IssueTenantAPICredentialParams struct {
	CredentialID         pgtype.UUID        `db:"credential_id" json:"credential_id"`
	ServiceAccountID     pgtype.UUID        `db:"service_account_id" json:"service_account_id"`
	KeyDigest            []byte             `db:"key_digest" json:"key_digest"`
	RequestDigest        []byte             `db:"request_digest" json:"request_digest"`
	Label                string             `db:"label" json:"label"`
	FormatVersion        int32              `db:"format_version" json:"format_version"`
	Locator              []byte             `db:"locator" json:"locator"`
	KeyVersion           int32              `db:"key_version" json:"key_version"`
	SecretDigest         []byte             `db:"secret_digest" json:"secret_digest"`
	ExpiresAt            pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	PermissionKeys       []string           `db:"permission_keys" json:"permission_keys"`
	PermissionScopes     []string           `db:"permission_scopes" json:"permission_scopes"`
	Networks             []netip.Prefix     `db:"networks" json:"networks"`
	RequestID            pgtype.UUID        `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID        `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr         `db:"ip_address" json:"ip_address"`
	UserAgent            string             `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string             `db:"authentication_method" json:"authentication_method"`
}

type IssueTenantAPICredentialRow struct {
	ResultCredentialID pgtype.UUID `db:"result_credential_id" json:"result_credential_id"`
	ResultVersion      int32       `db:"result_version" json:"result_version"`
	Replayed           bool        `db:"replayed" json:"replayed"`
}

func (q *Queries) IssueTenantAPICredential(ctx context.Context, arg IssueTenantAPICredentialParams) (*IssueTenantAPICredentialRow, error) {
	row := q.db.QueryRow(ctx, issueTenantAPICredential,
		arg.CredentialID,
		arg.ServiceAccountID,
		arg.KeyDigest,
		arg.RequestDigest,
		arg.Label,
		arg.FormatVersion,
		arg.Locator,
		arg.KeyVersion,
		arg.SecretDigest,
		arg.ExpiresAt,
		arg.PermissionKeys,
		arg.PermissionScopes,
		arg.Networks,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
	)
	var i IssueTenantAPICredentialRow
	err := row.Scan(&i.ResultCredentialID, &i.ResultVersion, &i.Replayed)
	return &i, err
}

const listLiveAPICredentialKeyVersions = `-- name: ListLiveAPICredentialKeyVersions :many
SELECT inventory.key_version::integer AS key_version
FROM app.list_live_api_credential_key_versions_v1(
  $1::integer
) AS inventory(key_version)
`

type ListLiveAPICredentialKeyVersionsParams struct {
	PageSize int32 `db:"page_size" json:"page_size"`
}

func (q *Queries) ListLiveAPICredentialKeyVersions(ctx context.Context, arg ListLiveAPICredentialKeyVersionsParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, listLiveAPICredentialKeyVersions, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var key_version int32
		if err := rows.Scan(&key_version); err != nil {
			return nil, err
		}
		items = append(items, key_version)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantAPICredentials = `-- name: ListTenantAPICredentials :many
SELECT credential.credential_id::uuid AS credential_id,
       credential.service_account_id::uuid AS service_account_id,
       credential.label::text AS label,
       credential.format_version::integer AS format_version,
       credential.key_version::integer AS key_version,
       credential.issued_by_membership_id::uuid AS issued_by_membership_id,
       credential.issued_by_user_id::uuid AS issued_by_user_id,
       credential.issued_at::timestamptz AS issued_at,
       credential.expires_at::timestamptz AS expires_at,
       credential.rotated_from_credential_id::uuid AS rotated_from_credential_id,
       credential.revoked_at::timestamptz AS revoked_at,
       credential.revoked_by_membership_id::uuid AS revoked_by_membership_id,
       credential.revoked_by_user_id::uuid AS revoked_by_user_id,
       coalesce(credential.revoke_reason::text, '')::text AS revoke_reason,
       credential.last_used_at::timestamptz AS last_used_at,
       credential.last_used_ip::inet AS last_used_ip,
       CASE
         WHEN credential.revoked_at IS NOT NULL THEN 'revoked'
         WHEN credential.expires_at <= transaction_timestamp() THEN 'expired'
         ELSE 'active'
       END::text AS credential_state,
       credential.version::integer AS version,
       credential.updated_at::timestamptz AS updated_at,
       credential.permission_keys::text[] AS permission_keys,
       credential.permission_scopes::text[] AS permission_scopes,
       credential.networks::cidr[] AS networks
FROM app.list_tenant_api_credentials_v1(
  $1::uuid,
  $2::uuid,
  $3::boolean,
  $4::integer
) AS credential(
  credential_id, service_account_id, label, format_version, key_version,
  issued_by_membership_id, issued_by_user_id, issued_at, expires_at,
  rotated_from_credential_id, revoked_at, revoked_by_membership_id,
  revoked_by_user_id, revoke_reason, last_used_at, last_used_ip, version,
  updated_at, permission_keys, permission_scopes, networks
)
`

type ListTenantAPICredentialsParams struct {
	ServiceAccountID pgtype.UUID `db:"service_account_id" json:"service_account_id"`
	AfterID          pgtype.UUID `db:"after_id" json:"after_id"`
	IncludeRevoked   bool        `db:"include_revoked" json:"include_revoked"`
	PageSize         int32       `db:"page_size" json:"page_size"`
}

type ListTenantAPICredentialsRow struct {
	CredentialID            pgtype.UUID        `db:"credential_id" json:"credential_id"`
	ServiceAccountID        pgtype.UUID        `db:"service_account_id" json:"service_account_id"`
	Label                   string             `db:"label" json:"label"`
	FormatVersion           int32              `db:"format_version" json:"format_version"`
	KeyVersion              int32              `db:"key_version" json:"key_version"`
	IssuedByMembershipID    pgtype.UUID        `db:"issued_by_membership_id" json:"issued_by_membership_id"`
	IssuedByUserID          pgtype.UUID        `db:"issued_by_user_id" json:"issued_by_user_id"`
	IssuedAt                pgtype.Timestamptz `db:"issued_at" json:"issued_at"`
	ExpiresAt               pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RotatedFromCredentialID pgtype.UUID        `db:"rotated_from_credential_id" json:"rotated_from_credential_id"`
	RevokedAt               pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RevokedByMembershipID   pgtype.UUID        `db:"revoked_by_membership_id" json:"revoked_by_membership_id"`
	RevokedByUserID         pgtype.UUID        `db:"revoked_by_user_id" json:"revoked_by_user_id"`
	RevokeReason            string             `db:"revoke_reason" json:"revoke_reason"`
	LastUsedAt              pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	LastUsedIp              netip.Addr         `db:"last_used_ip" json:"last_used_ip"`
	CredentialState         string             `db:"credential_state" json:"credential_state"`
	Version                 int32              `db:"version" json:"version"`
	UpdatedAt               pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	PermissionKeys          []string           `db:"permission_keys" json:"permission_keys"`
	PermissionScopes        []string           `db:"permission_scopes" json:"permission_scopes"`
	Networks                []netip.Prefix     `db:"networks" json:"networks"`
}

func (q *Queries) ListTenantAPICredentials(ctx context.Context, arg ListTenantAPICredentialsParams) ([]*ListTenantAPICredentialsRow, error) {
	rows, err := q.db.Query(ctx, listTenantAPICredentials,
		arg.ServiceAccountID,
		arg.AfterID,
		arg.IncludeRevoked,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListTenantAPICredentialsRow
	for rows.Next() {
		var i ListTenantAPICredentialsRow
		if err := rows.Scan(
			&i.CredentialID,
			&i.ServiceAccountID,
			&i.Label,
			&i.FormatVersion,
			&i.KeyVersion,
			&i.IssuedByMembershipID,
			&i.IssuedByUserID,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.RotatedFromCredentialID,
			&i.RevokedAt,
			&i.RevokedByMembershipID,
			&i.RevokedByUserID,
			&i.RevokeReason,
			&i.LastUsedAt,
			&i.LastUsedIp,
			&i.CredentialState,
			&i.Version,
			&i.UpdatedAt,
			&i.PermissionKeys,
			&i.PermissionScopes,
			&i.Networks,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantServiceAccountRoleGrants = `-- name: ListTenantServiceAccountRoleGrants :many
SELECT role_grant.grant_id::uuid AS grant_id,
       role_grant.service_account_id::uuid AS service_account_id,
       role_grant.role_id::uuid AS role_id,
       role_grant.role_key::text AS role_key,
       role_grant.role_display_name::text AS role_display_name,
       role_grant.role_system::boolean AS role_system,
       role_grant.source_id::uuid AS source_id,
       role_grant.source_kind::text AS source_kind,
       role_grant.source_key::text AS source_key,
       role_grant.source_authoritative::boolean AS source_authoritative,
       role_grant.source_retired_at::timestamptz AS source_retired_at,
       role_grant.granted_by_membership_id::uuid AS granted_by_membership_id,
       role_grant.granted_by_user_id::uuid AS granted_by_user_id,
       role_grant.grant_reason::text AS grant_reason,
       role_grant.granted_at::timestamptz AS granted_at,
       role_grant.expires_at::timestamptz AS expires_at,
       role_grant.revoked_at::timestamptz AS revoked_at,
       role_grant.revoked_by_membership_id::uuid AS revoked_by_membership_id,
       role_grant.revoked_by_user_id::uuid AS revoked_by_user_id,
       coalesce(role_grant.revoke_reason::text, '')::text AS revoke_reason,
       role_grant.grant_state::text AS grant_state,
       role_grant.version::integer AS version,
       role_grant.updated_at::timestamptz AS updated_at
FROM app.list_tenant_service_account_role_grants_v1(
  $1::uuid,
  $2::uuid,
  $3::boolean,
  $4::integer
) AS role_grant(
  grant_id, service_account_id, role_id, role_key, role_display_name,
  role_system, source_id, source_kind, source_key, source_authoritative,
  source_retired_at, granted_by_membership_id, granted_by_user_id,
  grant_reason, granted_at, expires_at, revoked_at,
  revoked_by_membership_id, revoked_by_user_id, revoke_reason, grant_state,
  version, updated_at
)
`

type ListTenantServiceAccountRoleGrantsParams struct {
	ServiceAccountID pgtype.UUID `db:"service_account_id" json:"service_account_id"`
	AfterID          pgtype.UUID `db:"after_id" json:"after_id"`
	IncludeRevoked   bool        `db:"include_revoked" json:"include_revoked"`
	PageSize         int32       `db:"page_size" json:"page_size"`
}

type ListTenantServiceAccountRoleGrantsRow struct {
	GrantID               pgtype.UUID        `db:"grant_id" json:"grant_id"`
	ServiceAccountID      pgtype.UUID        `db:"service_account_id" json:"service_account_id"`
	RoleID                pgtype.UUID        `db:"role_id" json:"role_id"`
	RoleKey               string             `db:"role_key" json:"role_key"`
	RoleDisplayName       string             `db:"role_display_name" json:"role_display_name"`
	RoleSystem            bool               `db:"role_system" json:"role_system"`
	SourceID              pgtype.UUID        `db:"source_id" json:"source_id"`
	SourceKind            string             `db:"source_kind" json:"source_kind"`
	SourceKey             string             `db:"source_key" json:"source_key"`
	SourceAuthoritative   bool               `db:"source_authoritative" json:"source_authoritative"`
	SourceRetiredAt       pgtype.Timestamptz `db:"source_retired_at" json:"source_retired_at"`
	GrantedByMembershipID pgtype.UUID        `db:"granted_by_membership_id" json:"granted_by_membership_id"`
	GrantedByUserID       pgtype.UUID        `db:"granted_by_user_id" json:"granted_by_user_id"`
	GrantReason           string             `db:"grant_reason" json:"grant_reason"`
	GrantedAt             pgtype.Timestamptz `db:"granted_at" json:"granted_at"`
	ExpiresAt             pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt             pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RevokedByMembershipID pgtype.UUID        `db:"revoked_by_membership_id" json:"revoked_by_membership_id"`
	RevokedByUserID       pgtype.UUID        `db:"revoked_by_user_id" json:"revoked_by_user_id"`
	RevokeReason          string             `db:"revoke_reason" json:"revoke_reason"`
	GrantState            string             `db:"grant_state" json:"grant_state"`
	Version               int32              `db:"version" json:"version"`
	UpdatedAt             pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListTenantServiceAccountRoleGrants(ctx context.Context, arg ListTenantServiceAccountRoleGrantsParams) ([]*ListTenantServiceAccountRoleGrantsRow, error) {
	rows, err := q.db.Query(ctx, listTenantServiceAccountRoleGrants,
		arg.ServiceAccountID,
		arg.AfterID,
		arg.IncludeRevoked,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListTenantServiceAccountRoleGrantsRow
	for rows.Next() {
		var i ListTenantServiceAccountRoleGrantsRow
		if err := rows.Scan(
			&i.GrantID,
			&i.ServiceAccountID,
			&i.RoleID,
			&i.RoleKey,
			&i.RoleDisplayName,
			&i.RoleSystem,
			&i.SourceID,
			&i.SourceKind,
			&i.SourceKey,
			&i.SourceAuthoritative,
			&i.SourceRetiredAt,
			&i.GrantedByMembershipID,
			&i.GrantedByUserID,
			&i.GrantReason,
			&i.GrantedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RevokedByMembershipID,
			&i.RevokedByUserID,
			&i.RevokeReason,
			&i.GrantState,
			&i.Version,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantServiceAccounts = `-- name: ListTenantServiceAccounts :many
SELECT account.service_account_id::uuid AS service_account_id,
       account.account_key::text AS account_key,
       account.display_name::text AS display_name,
       account.description::text AS description,
       account.created_by_membership_id::uuid AS created_by_membership_id,
       account.created_by_user_id::uuid AS created_by_user_id,
       account.archived_at::timestamptz AS archived_at,
       account.archived_by_membership_id::uuid AS archived_by_membership_id,
       account.archived_by_user_id::uuid AS archived_by_user_id,
       coalesce(account.archive_reason::text, '')::text AS archive_reason,
       account.version::integer AS version,
       account.created_at::timestamptz AS created_at,
       account.updated_at::timestamptz AS updated_at
FROM app.list_tenant_service_accounts_v1(
  $1::uuid,
  $2::boolean,
  $3::integer
) AS account(
  service_account_id, account_key, display_name, description,
  created_by_membership_id, created_by_user_id, archived_at,
  archived_by_membership_id, archived_by_user_id, archive_reason, version,
  created_at, updated_at
)
`

type ListTenantServiceAccountsParams struct {
	AfterID         pgtype.UUID `db:"after_id" json:"after_id"`
	IncludeArchived bool        `db:"include_archived" json:"include_archived"`
	PageSize        int32       `db:"page_size" json:"page_size"`
}

type ListTenantServiceAccountsRow struct {
	ServiceAccountID       pgtype.UUID        `db:"service_account_id" json:"service_account_id"`
	AccountKey             string             `db:"account_key" json:"account_key"`
	DisplayName            string             `db:"display_name" json:"display_name"`
	Description            string             `db:"description" json:"description"`
	CreatedByMembershipID  pgtype.UUID        `db:"created_by_membership_id" json:"created_by_membership_id"`
	CreatedByUserID        pgtype.UUID        `db:"created_by_user_id" json:"created_by_user_id"`
	ArchivedAt             pgtype.Timestamptz `db:"archived_at" json:"archived_at"`
	ArchivedByMembershipID pgtype.UUID        `db:"archived_by_membership_id" json:"archived_by_membership_id"`
	ArchivedByUserID       pgtype.UUID        `db:"archived_by_user_id" json:"archived_by_user_id"`
	ArchiveReason          string             `db:"archive_reason" json:"archive_reason"`
	Version                int32              `db:"version" json:"version"`
	CreatedAt              pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListTenantServiceAccounts(ctx context.Context, arg ListTenantServiceAccountsParams) ([]*ListTenantServiceAccountsRow, error) {
	rows, err := q.db.Query(ctx, listTenantServiceAccounts, arg.AfterID, arg.IncludeArchived, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListTenantServiceAccountsRow
	for rows.Next() {
		var i ListTenantServiceAccountsRow
		if err := rows.Scan(
			&i.ServiceAccountID,
			&i.AccountKey,
			&i.DisplayName,
			&i.Description,
			&i.CreatedByMembershipID,
			&i.CreatedByUserID,
			&i.ArchivedAt,
			&i.ArchivedByMembershipID,
			&i.ArchivedByUserID,
			&i.ArchiveReason,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveTenantServiceAccountAuthority = `-- name: ResolveTenantServiceAccountAuthority :many
SELECT authority.permission_key::text AS permission_key,
       authority.scope::text AS scope,
       authority.effective_expires_at::timestamptz AS effective_expires_at
FROM app.resolve_tenant_service_account_authority_v1(
  $1::uuid,
  $2::integer
) AS authority(permission_key, scope, effective_expires_at)
`

type ResolveTenantServiceAccountAuthorityParams struct {
	ServiceAccountID pgtype.UUID `db:"service_account_id" json:"service_account_id"`
	PageSize         int32       `db:"page_size" json:"page_size"`
}

type ResolveTenantServiceAccountAuthorityRow struct {
	PermissionKey      string             `db:"permission_key" json:"permission_key"`
	Scope              string             `db:"scope" json:"scope"`
	EffectiveExpiresAt pgtype.Timestamptz `db:"effective_expires_at" json:"effective_expires_at"`
}

func (q *Queries) ResolveTenantServiceAccountAuthority(ctx context.Context, arg ResolveTenantServiceAccountAuthorityParams) ([]*ResolveTenantServiceAccountAuthorityRow, error) {
	rows, err := q.db.Query(ctx, resolveTenantServiceAccountAuthority, arg.ServiceAccountID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ResolveTenantServiceAccountAuthorityRow
	for rows.Next() {
		var i ResolveTenantServiceAccountAuthorityRow
		if err := rows.Scan(&i.PermissionKey, &i.Scope, &i.EffectiveExpiresAt); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeTenantAPICredential = `-- name: RevokeTenantAPICredential :one
SELECT app.revoke_tenant_api_credential_v1(
  $1::uuid,
  $2::uuid,
  $3::integer,
  $4::text,
  $5::uuid,
  $6::uuid,
  $7::inet,
  nullif($8::text, ''),
  $9::text
) AS version
`

type RevokeTenantAPICredentialParams struct {
	ServiceAccountID     pgtype.UUID `db:"service_account_id" json:"service_account_id"`
	CredentialID         pgtype.UUID `db:"credential_id" json:"credential_id"`
	ExpectedVersion      int32       `db:"expected_version" json:"expected_version"`
	Reason               string      `db:"reason" json:"reason"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
}

func (q *Queries) RevokeTenantAPICredential(ctx context.Context, arg RevokeTenantAPICredentialParams) (int32, error) {
	row := q.db.QueryRow(ctx, revokeTenantAPICredential,
		arg.ServiceAccountID,
		arg.CredentialID,
		arg.ExpectedVersion,
		arg.Reason,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const revokeTenantServiceAccountRoleGrant = `-- name: RevokeTenantServiceAccountRoleGrant :one
SELECT app.revoke_tenant_service_account_role_grant_v1(
  $1::uuid,
  $2::uuid,
  $3::integer,
  $4::text,
  $5::uuid,
  $6::uuid,
  $7::inet,
  nullif($8::text, ''),
  $9::text
) AS version
`

type RevokeTenantServiceAccountRoleGrantParams struct {
	ServiceAccountID     pgtype.UUID `db:"service_account_id" json:"service_account_id"`
	GrantID              pgtype.UUID `db:"grant_id" json:"grant_id"`
	ExpectedVersion      int32       `db:"expected_version" json:"expected_version"`
	Reason               string      `db:"reason" json:"reason"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
}

func (q *Queries) RevokeTenantServiceAccountRoleGrant(ctx context.Context, arg RevokeTenantServiceAccountRoleGrantParams) (int32, error) {
	row := q.db.QueryRow(ctx, revokeTenantServiceAccountRoleGrant,
		arg.ServiceAccountID,
		arg.GrantID,
		arg.ExpectedVersion,
		arg.Reason,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const rotateTenantAPICredential = `-- name: RotateTenantAPICredential :one
SELECT result.result_credential_id::uuid AS result_credential_id,
       result.result_version::integer AS result_version,
       result.replayed::boolean AS replayed
FROM app.rotate_tenant_api_credential_v1(
  $1::uuid,
  $2::uuid,
  $3::uuid,
  $4::integer,
  $5::bytea,
  $6::bytea,
  $7::text,
  $8::integer,
  $9::bytea,
  $10::integer,
  $11::bytea,
  $12::timestamptz,
  $13::text[],
  $14::text[]::authorization_scope[],
  $15::cidr[],
  $16::text,
  $17::uuid,
  $18::uuid,
  $19::inet,
  nullif($20::text, ''),
  $21::text
) AS result(result_credential_id, result_version, replayed)
`

type RotateTenantAPICredentialParams struct {
	ReplacementCredentialID pgtype.UUID        `db:"replacement_credential_id" json:"replacement_credential_id"`
	ServiceAccountID        pgtype.UUID        `db:"service_account_id" json:"service_account_id"`
	RotatedFromCredentialID pgtype.UUID        `db:"rotated_from_credential_id" json:"rotated_from_credential_id"`
	ExpectedVersion         int32              `db:"expected_version" json:"expected_version"`
	KeyDigest               []byte             `db:"key_digest" json:"key_digest"`
	RequestDigest           []byte             `db:"request_digest" json:"request_digest"`
	Label                   string             `db:"label" json:"label"`
	FormatVersion           int32              `db:"format_version" json:"format_version"`
	Locator                 []byte             `db:"locator" json:"locator"`
	KeyVersion              int32              `db:"key_version" json:"key_version"`
	SecretDigest            []byte             `db:"secret_digest" json:"secret_digest"`
	ExpiresAt               pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	PermissionKeys          []string           `db:"permission_keys" json:"permission_keys"`
	PermissionScopes        []string           `db:"permission_scopes" json:"permission_scopes"`
	Networks                []netip.Prefix     `db:"networks" json:"networks"`
	RotationReason          string             `db:"rotation_reason" json:"rotation_reason"`
	RequestID               pgtype.UUID        `db:"request_id" json:"request_id"`
	CorrelationID           pgtype.UUID        `db:"correlation_id" json:"correlation_id"`
	IpAddress               netip.Addr         `db:"ip_address" json:"ip_address"`
	UserAgent               string             `db:"user_agent" json:"user_agent"`
	AuthenticationMethod    string             `db:"authentication_method" json:"authentication_method"`
}

type RotateTenantAPICredentialRow struct {
	ResultCredentialID pgtype.UUID `db:"result_credential_id" json:"result_credential_id"`
	ResultVersion      int32       `db:"result_version" json:"result_version"`
	Replayed           bool        `db:"replayed" json:"replayed"`
}

func (q *Queries) RotateTenantAPICredential(ctx context.Context, arg RotateTenantAPICredentialParams) (*RotateTenantAPICredentialRow, error) {
	row := q.db.QueryRow(ctx, rotateTenantAPICredential,
		arg.ReplacementCredentialID,
		arg.ServiceAccountID,
		arg.RotatedFromCredentialID,
		arg.ExpectedVersion,
		arg.KeyDigest,
		arg.RequestDigest,
		arg.Label,
		arg.FormatVersion,
		arg.Locator,
		arg.KeyVersion,
		arg.SecretDigest,
		arg.ExpiresAt,
		arg.PermissionKeys,
		arg.PermissionScopes,
		arg.Networks,
		arg.RotationReason,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
	)
	var i RotateTenantAPICredentialRow
	err := row.Scan(&i.ResultCredentialID, &i.ResultVersion, &i.Replayed)
	return &i, err
}

const updateTenantServiceAccount = `-- name: UpdateTenantServiceAccount :one
SELECT app.update_tenant_service_account_v1(
  $1::uuid,
  $2::integer,
  $3::text,
  $4::text,
  $5::uuid,
  $6::uuid,
  $7::inet,
  nullif($8::text, ''),
  $9::text
) AS version
`

type UpdateTenantServiceAccountParams struct {
	ServiceAccountID     pgtype.UUID `db:"service_account_id" json:"service_account_id"`
	ExpectedVersion      int32       `db:"expected_version" json:"expected_version"`
	DisplayName          *string     `db:"display_name" json:"display_name"`
	Description          *string     `db:"description" json:"description"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
}

func (q *Queries) UpdateTenantServiceAccount(ctx context.Context, arg UpdateTenantServiceAccountParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateTenantServiceAccount,
		arg.ServiceAccountID,
		arg.ExpectedVersion,
		arg.DisplayName,
		arg.Description,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
		arg.AuthenticationMethod,
	)
	var version int32
	err := row.Scan(&version)
	return version, err
}
