// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant_settings.sql

package dbsql

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTenantSettings = `-- name: GetTenantSettings :one
SELECT settings.tenant_id::uuid AS tenant_id,
       settings.brand_name::text AS brand_name,
       settings.brand_mark::text AS brand_mark,
       settings.primary_color::text AS primary_color,
       settings.accent_color::text AS accent_color,
       settings.timezone::text AS timezone,
       settings.locale::text AS locale,
       settings.version::integer AS version,
       settings.updated_at::timestamptz AS updated_at
FROM app.get_tenant_settings_v1(
  $1::uuid,
  $2::text
) AS settings(
  tenant_id, brand_name, brand_mark, primary_color, accent_color,
  timezone, locale, version, updated_at
)
`

type GetTenantSettingsParams struct {
	SessionID            pgtype.UUID `db:"session_id" json:"session_id"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
}

type GetTenantSettingsRow struct {
	TenantID     pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	BrandName    string             `db:"brand_name" json:"brand_name"`
	BrandMark    string             `db:"brand_mark" json:"brand_mark"`
	PrimaryColor string             `db:"primary_color" json:"primary_color"`
	AccentColor  string             `db:"accent_color" json:"accent_color"`
	Timezone     string             `db:"timezone" json:"timezone"`
	Locale       string             `db:"locale" json:"locale"`
	Version      int32              `db:"version" json:"version"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetTenantSettings(ctx context.Context, arg GetTenantSettingsParams) (*GetTenantSettingsRow, error) {
	row := q.db.QueryRow(ctx, getTenantSettings, arg.SessionID, arg.AuthenticationMethod)
	var i GetTenantSettingsRow
	err := row.Scan(
		&i.TenantID,
		&i.BrandName,
		&i.BrandMark,
		&i.PrimaryColor,
		&i.AccentColor,
		&i.Timezone,
		&i.Locale,
		&i.Version,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateTenantSettings = `-- name: UpdateTenantSettings :one
SELECT settings.tenant_id::uuid AS tenant_id,
       settings.brand_name::text AS brand_name,
       settings.brand_mark::text AS brand_mark,
       settings.primary_color::text AS primary_color,
       settings.accent_color::text AS accent_color,
       settings.timezone::text AS timezone,
       settings.locale::text AS locale,
       settings.version::integer AS version,
       settings.updated_at::timestamptz AS updated_at
FROM app.update_tenant_settings_v1(
  $1::uuid,
  $2::text,
  $3::integer,
  $4::text,
  $5::text,
  $6::text,
  $7::text,
  $8::text,
  $9::text,
  $10::text,
  $11::uuid,
  $12::uuid,
  $13::uuid,
  $14::inet,
  $15::text
) AS settings(
  tenant_id, brand_name, brand_mark, primary_color, accent_color,
  timezone, locale, version, updated_at
)
`

type UpdateTenantSettingsParams struct {
	SessionID            pgtype.UUID `db:"session_id" json:"session_id"`
	AuthenticationMethod string      `db:"authentication_method" json:"authentication_method"`
	ExpectedVersion      int32       `db:"expected_version" json:"expected_version"`
	BrandName            string      `db:"brand_name" json:"brand_name"`
	BrandMark            string      `db:"brand_mark" json:"brand_mark"`
	PrimaryColor         string      `db:"primary_color" json:"primary_color"`
	AccentColor          string      `db:"accent_color" json:"accent_color"`
	Timezone             string      `db:"timezone" json:"timezone"`
	Locale               string      `db:"locale" json:"locale"`
	Reason               string      `db:"reason" json:"reason"`
	AuditID              pgtype.UUID `db:"audit_id" json:"audit_id"`
	RequestID            pgtype.UUID `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr  `db:"ip_address" json:"ip_address"`
	UserAgent            string      `db:"user_agent" json:"user_agent"`
}

type UpdateTenantSettingsRow struct {
	TenantID     pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	BrandName    string             `db:"brand_name" json:"brand_name"`
	BrandMark    string             `db:"brand_mark" json:"brand_mark"`
	PrimaryColor string             `db:"primary_color" json:"primary_color"`
	AccentColor  string             `db:"accent_color" json:"accent_color"`
	Timezone     string             `db:"timezone" json:"timezone"`
	Locale       string             `db:"locale" json:"locale"`
	Version      int32              `db:"version" json:"version"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateTenantSettings(ctx context.Context, arg UpdateTenantSettingsParams) (*UpdateTenantSettingsRow, error) {
	row := q.db.QueryRow(ctx, updateTenantSettings,
		arg.SessionID,
		arg.AuthenticationMethod,
		arg.ExpectedVersion,
		arg.BrandName,
		arg.BrandMark,
		arg.PrimaryColor,
		arg.AccentColor,
		arg.Timezone,
		arg.Locale,
		arg.Reason,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i UpdateTenantSettingsRow
	err := row.Scan(
		&i.TenantID,
		&i.BrandName,
		&i.BrandMark,
		&i.PrimaryColor,
		&i.AccentColor,
		&i.Timezone,
		&i.Locale,
		&i.Version,
		&i.UpdatedAt,
	)
	return &i, err
}
