// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ticket_numbering.sql

package dbsql

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const commitReplaceTenantTicketNumberingPolicy = `-- name: CommitReplaceTenantTicketNumberingPolicy :one
SELECT policy.version_id::uuid AS version_id,
       policy.tenant_id::uuid AS tenant_id,
       policy.aggregate_kind::text AS aggregate_kind,
       policy.version::integer AS version,
       policy.prefix::text AS prefix,
       policy.separator::text AS separator,
       policy.period::text AS period,
       policy.width::integer AS width,
       policy.start::bigint AS start,
       policy.published_by_membership_id::uuid AS published_by_membership_id,
       policy.published_at::timestamptz AS published_at
FROM app.commit_replace_tenant_ticket_numbering_policy_v1(
  $1::uuid,
  $2::text,
  $3::public.ticket_aggregate_kind,
  $4::integer,
  $5::bytea,
  $6::bytea,
  $7::uuid,
  $8::integer,
  $9::text,
  $10::text,
  $11::public.ticket_numbering_period,
  $12::integer,
  $13::bigint,
  $14::bytea,
  $15::timestamptz,
  $16::text,
  $17::uuid,
  $18::uuid,
  $19::uuid,
  $20::inet,
  $21::text
) AS policy(
  version_id, tenant_id, aggregate_kind, version, prefix, separator,
  period, width, start, published_by_membership_id, published_at
)
`

type CommitReplaceTenantTicketNumberingPolicyParams struct {
	SessionID            pgtype.UUID           `db:"session_id" json:"session_id"`
	AuthenticationMethod string                `db:"authentication_method" json:"authentication_method"`
	AggregateKind        TicketAggregateKind   `db:"aggregate_kind" json:"aggregate_kind"`
	ExpectedVersion      int32                 `db:"expected_version" json:"expected_version"`
	KeyDigest            []byte                `db:"key_digest" json:"key_digest"`
	RequestDigest        []byte                `db:"request_digest" json:"request_digest"`
	VersionID            pgtype.UUID           `db:"version_id" json:"version_id"`
	ResultVersion        int32                 `db:"result_version" json:"result_version"`
	Prefix               string                `db:"prefix" json:"prefix"`
	Separator            string                `db:"separator" json:"separator"`
	Period               TicketNumberingPeriod `db:"period" json:"period"`
	Width                int32                 `db:"width" json:"width"`
	Start                int64                 `db:"start" json:"start"`
	NamespaceDigest      []byte                `db:"namespace_digest" json:"namespace_digest"`
	PublishedAt          pgtype.Timestamptz    `db:"published_at" json:"published_at"`
	Reason               string                `db:"reason" json:"reason"`
	AuditID              pgtype.UUID           `db:"audit_id" json:"audit_id"`
	RequestID            pgtype.UUID           `db:"request_id" json:"request_id"`
	CorrelationID        pgtype.UUID           `db:"correlation_id" json:"correlation_id"`
	IpAddress            netip.Addr            `db:"ip_address" json:"ip_address"`
	UserAgent            string                `db:"user_agent" json:"user_agent"`
}

type CommitReplaceTenantTicketNumberingPolicyRow struct {
	VersionID               pgtype.UUID        `db:"version_id" json:"version_id"`
	TenantID                pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	AggregateKind           string             `db:"aggregate_kind" json:"aggregate_kind"`
	Version                 int32              `db:"version" json:"version"`
	Prefix                  string             `db:"prefix" json:"prefix"`
	Separator               string             `db:"separator" json:"separator"`
	Period                  string             `db:"period" json:"period"`
	Width                   int32              `db:"width" json:"width"`
	Start                   int64              `db:"start" json:"start"`
	PublishedByMembershipID pgtype.UUID        `db:"published_by_membership_id" json:"published_by_membership_id"`
	PublishedAt             pgtype.Timestamptz `db:"published_at" json:"published_at"`
}

func (q *Queries) CommitReplaceTenantTicketNumberingPolicy(ctx context.Context, arg CommitReplaceTenantTicketNumberingPolicyParams) (*CommitReplaceTenantTicketNumberingPolicyRow, error) {
	row := q.db.QueryRow(ctx, commitReplaceTenantTicketNumberingPolicy,
		arg.SessionID,
		arg.AuthenticationMethod,
		arg.AggregateKind,
		arg.ExpectedVersion,
		arg.KeyDigest,
		arg.RequestDigest,
		arg.VersionID,
		arg.ResultVersion,
		arg.Prefix,
		arg.Separator,
		arg.Period,
		arg.Width,
		arg.Start,
		arg.NamespaceDigest,
		arg.PublishedAt,
		arg.Reason,
		arg.AuditID,
		arg.RequestID,
		arg.CorrelationID,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i CommitReplaceTenantTicketNumberingPolicyRow
	err := row.Scan(
		&i.VersionID,
		&i.TenantID,
		&i.AggregateKind,
		&i.Version,
		&i.Prefix,
		&i.Separator,
		&i.Period,
		&i.Width,
		&i.Start,
		&i.PublishedByMembershipID,
		&i.PublishedAt,
	)
	return &i, err
}

const getTenantTicketNumberingPolicy = `-- name: GetTenantTicketNumberingPolicy :one
SELECT policy.version_id::uuid AS version_id,
       policy.tenant_id::uuid AS tenant_id,
       policy.aggregate_kind::text AS aggregate_kind,
       policy.version::integer AS version,
       policy.prefix::text AS prefix,
       policy.separator::text AS separator,
       policy.period::text AS period,
       policy.width::integer AS width,
       policy.start::bigint AS start,
       policy.published_by_membership_id::uuid AS published_by_membership_id,
       policy.published_at::timestamptz AS published_at
FROM app.get_tenant_ticket_numbering_policy_v1(
  $1::uuid,
  $2::text,
  $3::public.ticket_aggregate_kind
) AS policy(
  version_id, tenant_id, aggregate_kind, version, prefix, separator,
  period, width, start, published_by_membership_id, published_at
)
`

type GetTenantTicketNumberingPolicyParams struct {
	SessionID            pgtype.UUID         `db:"session_id" json:"session_id"`
	AuthenticationMethod string              `db:"authentication_method" json:"authentication_method"`
	AggregateKind        TicketAggregateKind `db:"aggregate_kind" json:"aggregate_kind"`
}

type GetTenantTicketNumberingPolicyRow struct {
	VersionID               pgtype.UUID        `db:"version_id" json:"version_id"`
	TenantID                pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	AggregateKind           string             `db:"aggregate_kind" json:"aggregate_kind"`
	Version                 int32              `db:"version" json:"version"`
	Prefix                  string             `db:"prefix" json:"prefix"`
	Separator               string             `db:"separator" json:"separator"`
	Period                  string             `db:"period" json:"period"`
	Width                   int32              `db:"width" json:"width"`
	Start                   int64              `db:"start" json:"start"`
	PublishedByMembershipID pgtype.UUID        `db:"published_by_membership_id" json:"published_by_membership_id"`
	PublishedAt             pgtype.Timestamptz `db:"published_at" json:"published_at"`
}

func (q *Queries) GetTenantTicketNumberingPolicy(ctx context.Context, arg GetTenantTicketNumberingPolicyParams) (*GetTenantTicketNumberingPolicyRow, error) {
	row := q.db.QueryRow(ctx, getTenantTicketNumberingPolicy, arg.SessionID, arg.AuthenticationMethod, arg.AggregateKind)
	var i GetTenantTicketNumberingPolicyRow
	err := row.Scan(
		&i.VersionID,
		&i.TenantID,
		&i.AggregateKind,
		&i.Version,
		&i.Prefix,
		&i.Separator,
		&i.Period,
		&i.Width,
		&i.Start,
		&i.PublishedByMembershipID,
		&i.PublishedAt,
	)
	return &i, err
}

const prepareReplaceTenantTicketNumberingPolicy = `-- name: PrepareReplaceTenantTicketNumberingPolicy :one
SELECT policy.replayed::boolean AS replayed,
       policy.version_id::uuid AS version_id,
       policy.tenant_id::uuid AS tenant_id,
       policy.aggregate_kind::text AS aggregate_kind,
       policy.version::integer AS version,
       policy.prefix::text AS prefix,
       policy.separator::text AS separator,
       policy.period::text AS period,
       policy.width::integer AS width,
       policy.start::bigint AS start,
       policy.published_by_membership_id::uuid AS published_by_membership_id,
       policy.published_at::timestamptz AS published_at
FROM app.prepare_replace_tenant_ticket_numbering_policy_v1(
  $1::uuid,
  $2::text,
  $3::public.ticket_aggregate_kind,
  $4::bytea,
  $5::bytea
) AS policy(
  replayed, version_id, tenant_id, aggregate_kind, version, prefix,
  separator, period, width, start, published_by_membership_id, published_at
)
`

type PrepareReplaceTenantTicketNumberingPolicyParams struct {
	SessionID            pgtype.UUID         `db:"session_id" json:"session_id"`
	AuthenticationMethod string              `db:"authentication_method" json:"authentication_method"`
	AggregateKind        TicketAggregateKind `db:"aggregate_kind" json:"aggregate_kind"`
	KeyDigest            []byte              `db:"key_digest" json:"key_digest"`
	RequestDigest        []byte              `db:"request_digest" json:"request_digest"`
}

type PrepareReplaceTenantTicketNumberingPolicyRow struct {
	Replayed                bool               `db:"replayed" json:"replayed"`
	VersionID               pgtype.UUID        `db:"version_id" json:"version_id"`
	TenantID                pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	AggregateKind           string             `db:"aggregate_kind" json:"aggregate_kind"`
	Version                 int32              `db:"version" json:"version"`
	Prefix                  string             `db:"prefix" json:"prefix"`
	Separator               string             `db:"separator" json:"separator"`
	Period                  string             `db:"period" json:"period"`
	Width                   int32              `db:"width" json:"width"`
	Start                   int64              `db:"start" json:"start"`
	PublishedByMembershipID pgtype.UUID        `db:"published_by_membership_id" json:"published_by_membership_id"`
	PublishedAt             pgtype.Timestamptz `db:"published_at" json:"published_at"`
}

func (q *Queries) PrepareReplaceTenantTicketNumberingPolicy(ctx context.Context, arg PrepareReplaceTenantTicketNumberingPolicyParams) (*PrepareReplaceTenantTicketNumberingPolicyRow, error) {
	row := q.db.QueryRow(ctx, prepareReplaceTenantTicketNumberingPolicy,
		arg.SessionID,
		arg.AuthenticationMethod,
		arg.AggregateKind,
		arg.KeyDigest,
		arg.RequestDigest,
	)
	var i PrepareReplaceTenantTicketNumberingPolicyRow
	err := row.Scan(
		&i.Replayed,
		&i.VersionID,
		&i.TenantID,
		&i.AggregateKind,
		&i.Version,
		&i.Prefix,
		&i.Separator,
		&i.Period,
		&i.Width,
		&i.Start,
		&i.PublishedByMembershipID,
		&i.PublishedAt,
	)
	return &i, err
}
