// Package platformidentityprovider implements the disabled-by-default
// administration boundary for platform-owned LDAP, OIDC, and SAML providers.
package platformidentityprovider

import (
	"fmt"
	"time"

	"github.com/google/uuid"

	identity "github.com/periapsis-im/periapsis/modules/identity"
	"github.com/periapsis-im/periapsis/modules/identity/federatedsaml"
	"github.com/periapsis-im/periapsis/services/api/internal/authentication"
	"github.com/periapsis-im/periapsis/services/api/internal/identityprovider"
)

type ProviderKind string

const (
	ProviderKindLDAP ProviderKind = "ldap"
	ProviderKindOIDC ProviderKind = "oidc"
	ProviderKindSAML ProviderKind = "saml"
)

// LDAPEndpoint is a globally owned directory destination. ID is required in
// read and update projections and is generated by the service during create.
type LDAPEndpoint struct {
	ID              uuid.UUID `json:"id"`
	Priority        int       `json:"priority"`
	Host            string    `json:"host"`
	Port            uint16    `json:"port"`
	Transport       string    `json:"transport"`
	TLSServerName   string    `json:"tlsServerName"`
	ReferralAllowed bool      `json:"referralAllowed"`
	Enabled         bool      `json:"enabled"`
}

// LDAPCreateConfiguration keeps the typed directory policy and its bounded
// endpoints in the protocol-discriminated provider create request.
type LDAPCreateConfiguration struct {
	Configuration identityprovider.Configuration `json:"configuration"`
	Endpoints     []LDAPEndpoint                 `json:"endpoints"`
}

func (LDAPCreateConfiguration) platformIdentityProviderCreateConfiguration() {}
func (LDAPCreateConfiguration) ProviderKind() ProviderKind                   { return ProviderKindLDAP }

type LDAPMapping struct {
	ID                 uuid.UUID                           `json:"id"`
	MatcherType        identityprovider.MappingMatcherType `json:"matcherType"`
	MatcherValue       string                              `json:"matcherValue"`
	CaseSensitive      bool                                `json:"caseSensitive"`
	Priority           int                                 `json:"priority"`
	PlatformRoleID     uuid.UUID                           `json:"platformRoleId"`
	ReconciliationMode identityprovider.ReconciliationMode `json:"reconciliationMode"`
	Enabled            bool                                `json:"enabled"`
	Notes              string                              `json:"notes"`
	LastMatchedAt      *time.Time                          `json:"lastMatchedAt"`
	Version            int64                               `json:"version"`
	ArchivedAt         *time.Time                          `json:"archivedAt"`
}

// LDAPConfiguration is the complete safe platform LDAP read model. Bind
// secret envelopes and passwords never cross this projection.
type LDAPConfiguration struct {
	Configuration identityprovider.Configuration
	Endpoints     []LDAPEndpoint
	Mappings      []LDAPMapping
}

// AccountMode controls how a platform-provider subject may be associated with
// a local User. Provider claims never create platform authority.
type AccountMode string

const (
	AccountModeDisabled         AccountMode = "disabled"
	AccountModeExistingIdentity AccountMode = "existing_identity"
	AccountModeCreate           AccountMode = "create"
)

// OIDCCreateConfiguration is the complete non-secret configuration accepted
// when a disabled platform OIDC provider is created. Client secrets have a
// separate write-only action.
type OIDCCreateConfiguration struct {
	Issuer                string   `json:"issuer"`
	ClientID              string   `json:"clientId"`
	RedirectURI           string   `json:"redirectUri"`
	TenantRedirectURI     string   `json:"tenantRedirectUri"`
	PostLogoutRedirectURI string   `json:"postLogoutRedirectUri"`
	ExtraScopes           []string `json:"extraScopes"`
	AllowRefreshToken     bool     `json:"allowRefreshToken"`
	UseUserInfo           bool     `json:"useUserInfo"`
}

func (OIDCCreateConfiguration) platformIdentityProviderCreateConfiguration() {}
func (OIDCCreateConfiguration) ProviderKind() ProviderKind                   { return ProviderKindOIDC }

// SAMLCreateConfiguration is the complete non-secret configuration accepted
// when a disabled platform SAML provider is created. Service-provider private
// keys are never accepted by this boundary.
type SAMLCreateConfiguration struct {
	ExpectedEntityID           string                                   `json:"expectedEntityId"`
	SPEntityID                 string                                   `json:"spEntityId"`
	ACSURL                     string                                   `json:"acsUrl"`
	RedirectSignatureAlgorithm federatedsaml.RedirectSignatureAlgorithm `json:"redirectSignatureAlgorithm"`
	SignaturePolicy            federatedsaml.SignaturePolicy            `json:"signaturePolicy"`
	EncryptionPolicy           federatedsaml.EncryptionPolicy           `json:"encryptionPolicy"`
	DecryptionKeyVersions      []int16                                  `json:"decryptionKeyVersions"`
	RequestedAuthnContexts     []string                                 `json:"requestedAuthnContexts"`
	SubjectSource              federatedsaml.SubjectSource              `json:"subjectSource"`
	SubjectAttributeName       *string                                  `json:"subjectAttributeName,omitempty"`
	SubjectAttributeNameFormat *string                                  `json:"subjectAttributeNameFormat,omitempty"`
	ClockSkew                  time.Duration                            `json:"clockSkewNanoseconds"`
	MaximumAuthenticationAge   time.Duration                            `json:"maxAuthenticationAgeNanoseconds"`
}

func (SAMLCreateConfiguration) platformIdentityProviderCreateConfiguration() {}
func (SAMLCreateConfiguration) ProviderKind() ProviderKind                   { return ProviderKindSAML }

// CreateConfiguration is a closed, protocol-discriminated creation payload.
// Its unexported marker prevents another package from smuggling an unreviewed
// provider kind across the persistence boundary.
type CreateConfiguration interface {
	platformIdentityProviderCreateConfiguration()
	ProviderKind() ProviderKind
}

type ProviderSummary struct {
	ID                               uuid.UUID
	Key                              string
	DisplayName                      string
	Description                      string
	Kind                             ProviderKind
	Enabled                          bool
	PlatformLoginEnabled             bool
	PlatformLoginActivationAvailable bool
	ActivationAvailable              bool
	Configured                       bool
	SecretPresent                    bool
	ArchivedAt                       *time.Time
	Version                          int64
	CreatedAt                        time.Time
	UpdatedAt                        time.Time
}

// OIDCConfiguration is a safe read model. It exposes only whether a secret is
// present and its revision, never an envelope or plaintext value.
type OIDCConfiguration struct {
	Issuer                string
	ClientID              string
	RedirectURI           string
	TenantRedirectURI     string
	PostLogoutRedirectURI string
	ExtraScopes           []string
	AllowRefreshToken     bool
	UseUserInfo           bool
	ClientSecretRevision  int64
	ClientSecretPresent   bool
	DiscoveryRevision     int64
	JWKSRevision          int64
}

// SAMLConfiguration is a safe read model. SP private keys, metadata bodies,
// assertions, and certificate material are deliberately absent.
type SAMLConfiguration struct {
	ExpectedEntityID           string
	SPEntityID                 string
	ACSURL                     string
	SPKeyRevision              int64
	SPKeyPresent               bool
	MetadataRevision           int64
	RedirectSignatureAlgorithm federatedsaml.RedirectSignatureAlgorithm
	SignaturePolicy            federatedsaml.SignaturePolicy
	EncryptionPolicy           federatedsaml.EncryptionPolicy
	RequestedAuthnContexts     []string
	SubjectSource              federatedsaml.SubjectSource
	SubjectAttributeName       *string
	SubjectAttributeNameFormat *string
	ClockSkew                  time.Duration
	MaximumAuthenticationAge   time.Duration
}

type Provider struct {
	ProviderSummary
	ConfigurationRevision   int64
	SecurityRevision        int64
	PlanRevision            int64
	AssurancePolicyRevision int64
	AccountMode             AccountMode
	LDAP                    *LDAPConfiguration
	OIDC                    *OIDCConfiguration
	SAML                    *SAMLConfiguration
}

type ProviderPage struct {
	Items      []ProviderSummary
	NextCursor *uuid.UUID
}

type ListInput struct {
	After           *uuid.UUID
	Limit           int
	IncludeArchived bool
}

type CreateInput struct {
	Key            string
	DisplayName    string
	Description    string
	Configuration  CreateConfiguration
	Reason         string
	IdempotencyKey string
	Event          authentication.EventContext
}

type UpdateInput struct {
	// Key is repeated for wire compatibility and optimistic validation, but is
	// an immutable public locator. The protected repository rejects a value
	// different from the provider's current key.
	Key               string
	DisplayName       string
	Description       string
	Reason            string
	ExpectedEntityTag *string
	Event             authentication.EventContext
}

type ArchiveInput struct {
	Reason            string
	ExpectedEntityTag *string
	Event             authentication.EventContext
}

type ReplaceOIDCClientSecretInput struct {
	// Secret ownership transfers to ReplaceOIDCClientSecret. Its backing bytes
	// are cleared before that method returns on every path.
	Secret            []byte `json:"-"`
	Reason            string
	ExpectedEntityTag *string
	Event             authentication.EventContext
}

type UpdateLDAPInput struct {
	Key               string
	DisplayName       string
	Description       string
	Configuration     identityprovider.Configuration
	Endpoints         []LDAPEndpoint
	Reason            string
	ExpectedEntityTag *string
	Event             authentication.EventContext
}

type ReplaceLDAPBindSecretInput struct {
	Secret            []byte `json:"-"`
	Reason            string
	ExpectedEntityTag *string
	Event             authentication.EventContext
}

func (input ReplaceLDAPBindSecretInput) String() string {
	return fmt.Sprintf(
		"platformidentityprovider.ReplaceLDAPBindSecretInput{secret_bytes:%d,material:[REDACTED]}",
		len(input.Secret),
	)
}

func (input ReplaceLDAPBindSecretInput) GoString() string { return input.String() }

type PutLDAPMappingInput struct {
	ExpectedVersion    *int64
	MatcherType        identityprovider.MappingMatcherType
	MatcherValue       string
	CaseSensitive      bool
	Priority           int
	PlatformRoleID     uuid.UUID
	ReconciliationMode identityprovider.ReconciliationMode
	Enabled            bool
	Notes              string
	Reason             string
	Event              authentication.EventContext
}

type SetLDAPLoginStateInput struct {
	Enabled           bool
	Reason            string
	ExpectedEntityTag *string
	Event             authentication.EventContext
}

type LDAPTestKind string

const (
	LDAPTestConnection    LDAPTestKind = "connection"
	LDAPTestBind          LDAPTestKind = "bind"
	LDAPTestSearchUser    LDAPTestKind = "search_user"
	LDAPTestFilter        LDAPTestKind = "filter"
	LDAPTestMappingDryRun LDAPTestKind = "mapping_dry_run"
)

type LDAPTestInput struct {
	Kind     LDAPTestKind
	Username *string
	Reason   string
	Event    authentication.EventContext
}

type LDAPDiagnostic struct {
	TestID            uuid.UUID
	Kind              LDAPTestKind
	Outcome           string
	Category          string
	EndpointPriority  *int
	Duration          time.Duration
	MatchedEntryCount *int
	Attributes        []string
}

type ActivateInput struct {
	AccountMode       AccountMode
	Reason            string
	ExpectedEntityTag *string
	Event             authentication.EventContext
}

type DeactivateInput struct {
	Reason            string
	ExpectedEntityTag *string
	Event             authentication.EventContext
}

// DirectLoginInput is the reason-bearing, exact-version command shared by
// the explicit direct platform OIDC login lifecycle actions. The direct
// account mode is deliberately absent: v1 always admits pre-linked existing
// identities and provider claims never create platform authority.
type DirectLoginInput struct {
	Reason            string
	ExpectedEntityTag *string
	Event             authentication.EventContext
}

func (input ReplaceOIDCClientSecretInput) String() string {
	return fmt.Sprintf(
		"platformidentityprovider.ReplaceOIDCClientSecretInput{secret_bytes:%d,material:[REDACTED]}",
		len(input.Secret),
	)
}

func (input ReplaceOIDCClientSecretInput) GoString() string { return input.String() }

// EncryptedOIDCClientSecret is the only secret-bearing representation allowed
// across the repository port.
type EncryptedOIDCClientSecret struct {
	SecretID uuid.UUID
	Envelope identity.OIDCClientSecretEnvelope
}

func (secret EncryptedOIDCClientSecret) String() string {
	return fmt.Sprintf(
		"platformidentityprovider.EncryptedOIDCClientSecret{key_version:%d,ciphertext_bytes:%d,material:[REDACTED]}",
		secret.Envelope.KeyVersion, len(secret.Envelope.Ciphertext),
	)
}

func (secret EncryptedOIDCClientSecret) GoString() string { return secret.String() }
