-- Custom SQL migration file, put your code below! --
-- Custom SQL migration file, put your code below! --
-- Successor ABI for the canonical HTTP POST contract. The binding identifier
-- is generated by PostgreSQL, and exact replays return the current resource
-- version without duplicating the mutation or audit event.
CREATE FUNCTION app.create_tenant_auth_provider_binding_v2(
  p_idempotency_key_digest bytea,
  p_provider_id uuid,
  p_key text,
  p_enabled boolean,
  p_profile_priority integer,
  p_audit_event_id uuid,
  p_request_id uuid,
  p_correlation_id uuid,
  p_ip_address inet,
  p_user_agent text,
  p_authentication_method text
)
RETURNS TABLE (
  result_resource_id uuid,
  result_version integer,
  replayed boolean
)
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = pg_catalog, public, app
AS $function$
DECLARE
  context_tenant uuid := app.context_tenant_id();
  actor_membership uuid;
  canonical_request_digest bytea;
  replay record;
  current_version integer;
  new_binding_id uuid;
  created_version integer;
  new_source_id uuid;
  new_epoch_id uuid;
BEGIN
  PERFORM app.lock_current_tenant_authorization_state();
  actor_membership := app.current_tenant_membership_id();
  IF NOT app.current_tenant_human_has_exact_permission_v3(
    'identity_provider.manage', 'tenant'
  ) THEN
    RAISE EXCEPTION 'identity_provider.manage tenant scope is required'
      USING ERRCODE = '42501';
  END IF;
  IF p_idempotency_key_digest IS NULL
     OR octet_length(p_idempotency_key_digest) <> 32 THEN
    RAISE EXCEPTION 'idempotency key digest must be SHA-256'
      USING ERRCODE = '22023';
  END IF;
  IF p_enabled IS NULL OR p_key IS NULL OR p_key <> lower(btrim(p_key))
     OR p_key !~ '^[a-z][a-z0-9_-]{2,63}$'
     OR p_profile_priority IS NULL
     OR p_profile_priority NOT BETWEEN 0 AND 1000000 THEN
    RAISE EXCEPTION 'tenant auth-provider binding input is invalid'
      USING ERRCODE = '22023';
  END IF;
  SELECT sha256(convert_to(jsonb_build_object(
    'provider_id', p_provider_id,
    'key', p_key,
    'enabled', p_enabled,
    'profile_priority', p_profile_priority
  )::text, 'UTF8')) INTO canonical_request_digest;
  PERFORM pg_advisory_xact_lock(hashtextextended(
    context_tenant::text || actor_membership::text ||
    encode(p_idempotency_key_digest, 'hex'), 0
  ));

  DELETE FROM public.tenant_authorization_commands AS command
  WHERE command.tenant_id = context_tenant
    AND command.actor_membership_id = actor_membership
    AND command.operation = 'identity_provider_binding.create'
    AND command.key_digest = p_idempotency_key_digest
    AND command.expires_at <= transaction_timestamp();
  SELECT command.request_digest, command.result_resource_id
  INTO replay
  FROM public.tenant_authorization_commands AS command
  WHERE command.tenant_id = context_tenant
    AND command.actor_membership_id = actor_membership
    AND command.operation = 'identity_provider_binding.create'
    AND command.key_digest = p_idempotency_key_digest;
  IF FOUND THEN
    IF replay.request_digest <> canonical_request_digest THEN
      RAISE EXCEPTION 'idempotency key was reused with different binding input'
        USING ERRCODE = '23505';
    END IF;
    SELECT binding.version INTO current_version
    FROM public.tenant_auth_provider_bindings AS binding
    WHERE binding.tenant_id = context_tenant
      AND binding.id = replay.result_resource_id;
    IF NOT FOUND THEN
      RAISE EXCEPTION 'idempotent binding result no longer exists'
        USING ERRCODE = '55000';
    END IF;
    RETURN QUERY SELECT replay.result_resource_id::uuid,
                        current_version, true;
    RETURN;
  END IF;

  PERFORM 1 FROM public.tenant_auth_providers AS provider
  WHERE provider.tenant_id = context_tenant AND provider.id = p_provider_id
    AND provider.kind = 'ldap' AND provider.archived_at IS NULL
    AND (NOT p_enabled OR provider.enabled)
  FOR KEY SHARE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'eligible tenant LDAP provider was not found'
      USING ERRCODE = 'P0002';
  END IF;

  new_binding_id := uuidv7();
  created_version := 1;
  INSERT INTO public.tenant_auth_provider_bindings (
    id, tenant_id, provider_id, key, enabled, profile_priority,
    created_by_membership_id, updated_by_membership_id
  ) VALUES (
    new_binding_id, context_tenant, p_provider_id, p_key, false,
    p_profile_priority, actor_membership, actor_membership
  );
  IF p_enabled THEN
    new_source_id := uuidv7();
    new_epoch_id := uuidv7();
    INSERT INTO public.tenant_authorization_sources (
      id, tenant_id, kind, key, authoritative, protected
    ) VALUES (
      new_source_id, context_tenant, 'identity_provider_access',
      format('identity_provider_access:%s:1', new_binding_id), true, false
    );
    INSERT INTO public.tenant_identity_provider_access_epochs (
      id, tenant_id, binding_id, provider_id, source_id, sequence,
      started_by_membership_id
    ) VALUES (
      new_epoch_id, context_tenant, new_binding_id, p_provider_id,
      new_source_id, 1, actor_membership
    );
    UPDATE public.tenant_auth_provider_bindings AS binding
    SET enabled = true, current_access_epoch_id = new_epoch_id
    WHERE binding.tenant_id = context_tenant AND binding.id = new_binding_id;
  END IF;
  INSERT INTO public.tenant_authorization_commands (
    tenant_id, actor_membership_id, operation, key_digest, request_digest,
    result_resource_id, result_version
  ) VALUES (
    context_tenant, actor_membership, 'identity_provider_binding.create',
    p_idempotency_key_digest, canonical_request_digest, new_binding_id,
    created_version
  );

  PERFORM app.append_tenant_authorization_audit(
    p_audit_event_id, 'tenant.identity_provider_binding.created',
    'identity_provider_binding', new_binding_id, p_request_id,
    p_correlation_id, p_ip_address, p_user_agent, p_authentication_method,
    NULL,
    jsonb_build_object(
      'provider_id', p_provider_id, 'key', p_key, 'enabled', p_enabled,
      'profile_priority', p_profile_priority, 'auth_revision', 1,
      'access_epoch_sequence', CASE WHEN p_enabled THEN 1 ELSE NULL END,
      'version', created_version
    ), '{}'::jsonb
  );
  RETURN QUERY SELECT new_binding_id, created_version, false;
END;
$function$;--> statement-breakpoint

ALTER FUNCTION app.create_tenant_auth_provider_binding_v2(bytea, uuid, text, boolean, integer, uuid, uuid, uuid, inet, text, text) OWNER TO periapsis_migrator;--> statement-breakpoint
REVOKE ALL ON FUNCTION app.create_tenant_auth_provider_binding_v2(bytea, uuid, text, boolean, integer, uuid, uuid, uuid, inet, text, text) FROM PUBLIC, periapsis_api, periapsis_worker, periapsis_notifier, periapsis_auditor;--> statement-breakpoint
GRANT EXECUTE ON FUNCTION app.create_tenant_auth_provider_binding_v2(bytea, uuid, text, boolean, integer, uuid, uuid, uuid, inet, text, text) TO periapsis_api;

