ARG OPENSSL_IMAGE=alpine/openssl:3.5.7@sha256:19f8eb9004a1dbaec323eed6094e9b6bcc1dbf2697ecb5fb8d2fad4e3336a8f7

FROM ${OPENSSL_IMAGE}

LABEL org.opencontainers.image.description="Ephemeral local OpenLDAP TLS material generator" \
      org.opencontainers.image.licenses="Apache-2.0" \
      org.opencontainers.image.title="Periapsis LDAP TLS initializer" \
      org.opencontainers.image.version="3.5.7"

USER 0
RUN addgroup -S -g 10001 periapsis \
    && adduser -S -D -H -u 10001 -G periapsis periapsis \
    && install -d -o 10001 -g 10001 -m 0700 /tls

COPY --chown=10001:10001 deploy/compose/auth/generate-openldap-tls.sh /usr/local/bin/generate-openldap-tls

USER 10001:10001
ENTRYPOINT ["/bin/sh", "/usr/local/bin/generate-openldap-tls"]
