ARG KEYCLOAK_IMAGE=quay.io/keycloak/keycloak:26.7.2@sha256:831330513f55695572286e521f94fcd3c7e285250ed5b848090265a33192f669

FROM ${KEYCLOAK_IMAGE} AS build

ENV KC_DB=dev-file \
    KC_HEALTH_ENABLED=true \
    KC_METRICS_ENABLED=true

RUN /opt/keycloak/bin/kc.sh build

FROM ${KEYCLOAK_IMAGE}

LABEL org.opencontainers.image.description="Pre-built local OIDC and SAML test identity provider" \
      org.opencontainers.image.licenses="Apache-2.0" \
      org.opencontainers.image.title="Periapsis Keycloak test provider" \
      org.opencontainers.image.version="26.7.2"

COPY --from=build /opt/keycloak/ /opt/keycloak/

ENV KC_DB=dev-file \
    KC_HEALTH_ENABLED=true \
    KC_METRICS_ENABLED=true

USER 1000
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
