import type { PhaseTwoApi, SessionView } from "../lib/phase-two-types";

export const sessionFixture = {
  absoluteExpiresAt: "2026-08-24T12:00:00Z",
  csrfToken: "csrf-memory-only-test-value-000000000000000000000",
  id: "0198c97d-cf4f-7000-8000-000000000002",
  idleExpiresAt: "2026-08-23T12:00:00Z",
  permissions: ["platform.tenant.read", "platform.tenant.create"],
  user: {
    displayName: "Ada Analyst",
    email: "ada@example.invalid",
    id: "0198c97d-cf4f-7000-8000-000000000001",
  },
} satisfies SessionView;

const unsupported = async (): Promise<never> => {
  throw new Error("Unexpected PhaseTwoApi call in test");
};

export function createPhaseTwoApi(
  overrides: Partial<PhaseTwoApi> = {},
): PhaseTwoApi {
  return {
    activatePlatformLocalAccount: unsupported,
    activatePlatformOidcDirectLogin: unsupported,
    activatePlatformAuthProvider: unsupported,
    activatePlatformAuthProviderTenantBinding: unsupported,
    addOperatorTeamRosterEntry: unsupported,
    archivePlatformAuthProvider: unsupported,
    archivePlatformAuthProviderTenantBinding: unsupported,
    archivePlatformOperatorTeam: unsupported,
    archiveTenantSecurityGroup: unsupported,
    archiveTenantRole: unsupported,
    archiveTenantServiceAccount: unsupported,
    archiveTenantLdapAuthProvider: unsupported,
    archiveTenantLdapAuthProviderBinding: unsupported,
    archiveTenantLdapMapping: unsupported,
    authorizePlatformTenantAccess: unsupported,
    completeMfa: unsupported,
    confirmBootstrap: unsupported,
    createPlatformOperatorTeam: unsupported,
    createPlatformAuthProvider: unsupported,
    createPlatformAuthProviderTenantBinding: unsupported,
    createTenant: unsupported,
    createTenantSecurityGroup: unsupported,
    createTenantSecurityGroupMembership: unsupported,
    createTenantRole: unsupported,
    createTenantServiceAccount: unsupported,
    createTenantLdapAuthProvider: unsupported,
    createTenantLdapAuthProviderBinding: unsupported,
    createTenantLdapMapping: unsupported,
    deactivatePlatformAuthProvider: unsupported,
    deactivatePlatformOidcDirectLogin: unsupported,
    deactivatePlatformAuthProviderTenantBinding: unsupported,
    disablePlatformLocalAccount: unsupported,
    dryRunTenantLdapMappings: unsupported,
    enablePlatformLocalAccount: unsupported,
    enrollBootstrap: unsupported,
    getBootstrapStatus: unsupported,
    getOperatorTeamAssignmentEpoch: unsupported,
    getPlatformOperatorTeam: unsupported,
    getPlatformAuthProvider: unsupported,
    getPlatformAuthProviderAccount: unsupported,
    getPlatformAuthProviderTenantBinding: unsupported,
    getPlatformLocalAccount: unsupported,
    getSession: unsupported,
    getTenantAuthority: unsupported,
    getTenantSecurityGroup: unsupported,
    getTenantRole: unsupported,
    getTenantServiceAccount: unsupported,
    getTenantServiceAccountCredential: unsupported,
    getTenantLdapAuthProvider: unsupported,
    getTenantLdapAuthProviderBinding: unsupported,
    getTenantLdapMapping: unsupported,
    getTenantLdapSyncRun: unsupported,
    getTenantLdapSyncStatus: unsupported,
    grantTenantSecurityGroupRole: unsupported,
    grantTenantServiceAccountRole: unsupported,
    grantUserRole: unsupported,
    listOperatorTeamRosterEntries: unsupported,
    listPlatformOperatorTeams: unsupported,
    listPlatformAuthProviderAccounts: unsupported,
    listPlatformAuthProviders: unsupported,
    listPlatformAuthProviderTenantBindings: unsupported,
    listPlatformLocalAccounts: unsupported,
    listMemberships: unsupported,
    listSessions: unsupported,
    listTenantPermissions: unsupported,
    listTenantOperatorTeamAssignmentEpochs: unsupported,
    listTenantRoles: unsupported,
    listTenantSecurityGroupMemberships: unsupported,
    listTenantSecurityGroupRoleGrants: unsupported,
    listTenantSecurityGroups: unsupported,
    listTenantServiceAccountCredentials: unsupported,
    listTenantServiceAccountRoleGrants: unsupported,
    listTenantServiceAccounts: unsupported,
    listTenantLdapAuthProviders: unsupported,
    listTenantLdapAuthProviderBindings: unsupported,
    listTenantLdapMappings: unsupported,
    listTenantLdapSyncRuns: unsupported,
    listTenantUsers: unsupported,
    listTenants: unsupported,
    listUserRoleGrants: unsupported,
    login: unsupported,
    logout: unsupported,
    issueTenantServiceAccountCredential: unsupported,
    invitePlatformLocalAccount: unsupported,
    replaceTenantRolePolicy: unsupported,
    replacePlatformLdapBindSecret: unsupported,
    replacePlatformOidcAuthProviderClientSecret: unsupported,
    replacePlatformSamlMetadata: unsupported,
    replacePlatformSamlSpKey: unsupported,
    clearPlatformSamlSpKey: unsupported,
    prelinkPlatformAuthProviderAccount: unsupported,
    reactivateTenant: unsupported,
    recoverPlatformLocalAccount: unsupported,
    retirePlatformAuthProviderAccount: unsupported,
    revokeOperatorTeamRosterEntry: unsupported,
    revokeRoleGrant: unsupported,
    revokeSession: unsupported,
    revokeTenantSecurityGroupMembership: unsupported,
    revokeTenantSecurityGroupRoleGrant: unsupported,
    revokeTenantServiceAccountCredential: unsupported,
    revokeTenantServiceAccountRoleGrant: unsupported,
    rotateTenantServiceAccountCredential: unsupported,
    rotatePlatformLocalAccountPassword: unsupported,
    startOperatorTeamAssignmentEpoch: unsupported,
    endOperatorTeamAssignmentEpoch: unsupported,
    switchTenant: unsupported,
    suspendTenant: unsupported,
    setTenantLdapAuthProviderBindSecret: unsupported,
    searchTenantLdapAuthProviderUser: unsupported,
    setPlatformLdapLoginState: unsupported,
    clearTenantLdapAuthProviderBindSecret: unsupported,
    changeTenantMembershipLifecycle: unsupported,
    testTenantLdapAuthProviderBind: unsupported,
    testPlatformLdapProvider: unsupported,
    testTenantLdapAuthProviderConnection: unsupported,
    testTenantLdapAuthProviderFilter: unsupported,
    startTenantLdapManualSync: unsupported,
    updateTenantRole: unsupported,
    updatePlatformOperatorTeam: unsupported,
    updatePlatformAuthProvider: unsupported,
    updatePlatformLdapAuthProvider: unsupported,
    putPlatformLdapMapping: unsupported,
    updatePlatformAuthProviderTenantBinding: unsupported,
    updateTenantSecurityGroup: unsupported,
    updateTenantServiceAccount: unsupported,
    updateTenantLdapAuthProvider: unsupported,
    updateTenantLdapAuthProviderBinding: unsupported,
    updateTenantLdapMapping: unsupported,
    ...overrides,
  };
}
