DatabaseDirectory /var/lib/clamav
DatabaseOwner clamav
DatabaseMirror database.clamav.net
Checks 12
TestDatabases yes
ScriptedUpdates yes
CompressLocalDatabase no
ConnectTimeout 30
ReceiveTimeout 120
NotifyClamd /etc/clamav/clamd.conf
