-- name: GetAlert :one
SELECT
  id,
  tenant_id,
  external_id,
  title,
  description,
  status,
  severity,
  created_by,
  created_at,
  updated_at,
  version
FROM alerts
WHERE tenant_id = sqlc.arg(tenant_id)::uuid
  AND id = sqlc.arg(id)::uuid
  AND deleted_at IS NULL;

-- name: ListAlerts :many
SELECT
  id,
  tenant_id,
  external_id,
  title,
  description,
  status,
  severity,
  created_by,
  created_at,
  updated_at,
  version
FROM alerts
WHERE tenant_id = sqlc.arg(tenant_id)::uuid
  AND deleted_at IS NULL
  AND (
    sqlc.narg(after_id)::uuid IS NULL
    OR id > sqlc.narg(after_id)::uuid
  )
ORDER BY id ASC
LIMIT sqlc.arg(page_size);

-- name: CreateTenantAlertAsHuman :one
SELECT created.id::uuid AS id,
       created.number::text AS number,
       created.workflow_id::uuid AS workflow_id,
       created.workflow_version::integer AS workflow_version,
       created.state_key::text AS state_key,
       created.customer_visible::boolean AS customer_visible,
       (created.external_id IS NOT NULL)::boolean AS has_external_id,
       coalesce(created.external_id::text, '')::text AS external_id,
       (created.deduplication_key IS NOT NULL)::boolean AS has_deduplication_key,
       coalesce(created.deduplication_key::text, '')::text AS deduplication_key,
       created.title::text AS title,
       (created.description IS NOT NULL)::boolean AS has_description,
       coalesce(created.description::text, '')::text AS description,
       created.status::text AS status,
       created.severity::text AS severity,
       created.priority::text AS priority,
       created.category::text AS category,
       (created.classification IS NOT NULL)::boolean AS has_classification,
       coalesce(created.classification::text, '')::text AS classification,
       created.source::text AS source,
       created.source_type::text AS source_type,
       created.tags::text[] AS tags,
       created.custom_fields::jsonb AS custom_fields,
       created.customer_custom_fields::jsonb AS customer_custom_fields,
       created.raw_payload::jsonb AS raw_payload,
       created.assigned_team_id::uuid AS assigned_team_id,
       created.assignee_user_id::uuid AS assignee_user_id,
       created.claimed_by_user_id::uuid AS claimed_by_user_id,
       created.created_by_user_id::uuid AS created_by_user_id,
       created.created_by_membership_id::uuid AS created_by_membership_id,
       created.created_by_service_account_id::uuid AS created_by_service_account_id,
       created.detected_at::timestamptz AS detected_at,
       created.received_at::timestamptz AS received_at,
       created.acknowledged_at::timestamptz AS acknowledged_at,
       created.closed_at::timestamptz AS closed_at,
       created.assigned_at::timestamptz AS assigned_at,
       created.first_response_at::timestamptz AS first_response_at,
       created.resolved_at::timestamptz AS resolved_at,
       created.claimed_at::timestamptz AS claimed_at,
       created.created_at::timestamptz AS created_at,
       created.updated_at::timestamptz AS updated_at,
       created.version::integer AS version,
       created.replayed::boolean AS replayed
FROM app.create_tenant_alert_as_human_v3(
  sqlc.arg(title)::text,
  sqlc.narg(description)::text,
  sqlc.narg(external_id)::text,
  sqlc.arg(severity)::alert_severity,
  sqlc.arg(source)::text,
  sqlc.arg(source_type)::text,
  sqlc.narg(deduplication_key)::text,
  sqlc.arg(raw_payload)::jsonb,
  sqlc.arg(priority)::text,
  sqlc.arg(category)::text,
  sqlc.narg(classification)::text,
  sqlc.narg(detected_at)::timestamptz,
  sqlc.arg(customer_visible)::boolean,
  sqlc.arg(tags)::text[],
  sqlc.arg(custom_fields)::jsonb,
  sqlc.narg(workflow_id)::uuid,
  sqlc.narg(assigned_team_id)::uuid,
  sqlc.narg(assignee_user_id)::uuid,
  sqlc.arg(key_digest)::bytea,
  sqlc.arg(request_digest)::bytea,
  sqlc.arg(request_id)::uuid,
  sqlc.arg(correlation_id)::uuid,
  sqlc.arg(ip_address)::inet,
  nullif(sqlc.arg(user_agent)::text, ''),
  sqlc.arg(authentication_method)::text,
  sqlc.narg(traceparent)::text,
  sqlc.narg(tracestate)::text
) AS created(
  id, number, workflow_id, workflow_version, state_key, customer_visible,
  external_id, deduplication_key, title, description, status, severity,
  priority, category, classification, source, source_type, tags, custom_fields,
  customer_custom_fields, raw_payload, assigned_team_id, assignee_user_id,
  claimed_by_user_id, created_by_user_id, created_by_membership_id,
  created_by_service_account_id, detected_at, received_at, acknowledged_at,
  closed_at, assigned_at, first_response_at, resolved_at, claimed_at,
  created_at, updated_at, version, replayed
);

-- name: CreateTenantAlertAsServiceAccount :one
SELECT created.id::uuid AS id,
       created.number::text AS number,
       created.workflow_id::uuid AS workflow_id,
       created.workflow_version::integer AS workflow_version,
       created.state_key::text AS state_key,
       created.customer_visible::boolean AS customer_visible,
       (created.external_id IS NOT NULL)::boolean AS has_external_id,
       coalesce(created.external_id::text, '')::text AS external_id,
       (created.deduplication_key IS NOT NULL)::boolean AS has_deduplication_key,
       coalesce(created.deduplication_key::text, '')::text AS deduplication_key,
       created.title::text AS title,
       (created.description IS NOT NULL)::boolean AS has_description,
       coalesce(created.description::text, '')::text AS description,
       created.status::text AS status,
       created.severity::text AS severity,
       created.priority::text AS priority,
       created.category::text AS category,
       (created.classification IS NOT NULL)::boolean AS has_classification,
       coalesce(created.classification::text, '')::text AS classification,
       created.source::text AS source,
       created.source_type::text AS source_type,
       created.tags::text[] AS tags,
       created.custom_fields::jsonb AS custom_fields,
       created.customer_custom_fields::jsonb AS customer_custom_fields,
       created.raw_payload::jsonb AS raw_payload,
       created.assigned_team_id::uuid AS assigned_team_id,
       created.assignee_user_id::uuid AS assignee_user_id,
       created.claimed_by_user_id::uuid AS claimed_by_user_id,
       created.created_by_user_id::uuid AS created_by_user_id,
       created.created_by_membership_id::uuid AS created_by_membership_id,
       created.created_by_service_account_id::uuid AS created_by_service_account_id,
       created.detected_at::timestamptz AS detected_at,
       created.received_at::timestamptz AS received_at,
       created.acknowledged_at::timestamptz AS acknowledged_at,
       created.closed_at::timestamptz AS closed_at,
       created.assigned_at::timestamptz AS assigned_at,
       created.first_response_at::timestamptz AS first_response_at,
       created.resolved_at::timestamptz AS resolved_at,
       created.claimed_at::timestamptz AS claimed_at,
       created.created_at::timestamptz AS created_at,
       created.updated_at::timestamptz AS updated_at,
       created.version::integer AS version,
       created.replayed::boolean AS replayed
FROM app.create_tenant_alert_as_service_account_v3(
  sqlc.arg(tenant_id)::uuid,
  sqlc.arg(locator)::bytea,
  sqlc.arg(envelope_key_version)::integer,
  sqlc.arg(secret_digest)::bytea,
  sqlc.arg(client_address)::inet,
  sqlc.arg(title)::text,
  sqlc.narg(description)::text,
  sqlc.narg(external_id)::text,
  sqlc.arg(severity)::alert_severity,
  sqlc.arg(source)::text,
  sqlc.arg(source_type)::text,
  sqlc.narg(deduplication_key)::text,
  sqlc.arg(raw_payload)::jsonb,
  sqlc.arg(priority)::text,
  sqlc.arg(category)::text,
  sqlc.narg(classification)::text,
  sqlc.narg(detected_at)::timestamptz,
  sqlc.arg(customer_visible)::boolean,
  sqlc.arg(tags)::text[],
  sqlc.arg(custom_fields)::jsonb,
  sqlc.narg(workflow_id)::uuid,
  sqlc.narg(assigned_team_id)::uuid,
  sqlc.narg(assignee_user_id)::uuid,
  sqlc.arg(key_digest)::bytea,
  sqlc.arg(request_digest)::bytea,
  sqlc.arg(request_id)::uuid,
  sqlc.arg(correlation_id)::uuid,
  nullif(sqlc.arg(user_agent)::text, ''),
  sqlc.narg(traceparent)::text,
  sqlc.narg(tracestate)::text
) AS created(
  id, number, workflow_id, workflow_version, state_key, customer_visible,
  external_id, deduplication_key, title, description, status, severity,
  priority, category, classification, source, source_type, tags, custom_fields,
  customer_custom_fields, raw_payload, assigned_team_id, assignee_user_id,
  claimed_by_user_id, created_by_user_id, created_by_membership_id,
  created_by_service_account_id, detected_at, received_at, acknowledged_at,
  closed_at, assigned_at, first_response_at, resolved_at, claimed_at,
  created_at, updated_at, version, replayed
);
