-- name: BeginTenantLDAPAdministrativeDirectoryInspection :one
SELECT snapshot.operation_run_id::uuid AS operation_run_id,
       snapshot.tenant_id::uuid AS tenant_id,
       snapshot.provider_id::uuid AS provider_id,
       snapshot.provider_version::integer AS provider_version,
       snapshot.configuration_version::integer AS configuration_version,
       snapshot.endpoint_snapshot_digest::bytea AS endpoint_snapshot_digest,
       snapshot.configuration::jsonb AS configuration,
       snapshot.endpoints::jsonb AS endpoints,
       snapshot.bind_secret_id::uuid AS bind_secret_id,
       snapshot.bind_secret_ciphertext::bytea AS bind_secret_ciphertext,
       snapshot.bind_secret_nonce::bytea AS bind_secret_nonce,
       snapshot.bind_secret_version::integer AS bind_secret_version,
       snapshot.bind_secret_key_version::integer AS bind_secret_key_version,
       snapshot.bind_secret_algorithm::text AS bind_secret_algorithm,
       snapshot.started_at::timestamptz AS started_at,
       snapshot.expires_at::timestamptz AS expires_at
FROM app.begin_tenant_ldap_administrative_search_v1(
  sqlc.arg(operation_run_id)::uuid,
  sqlc.arg(provider_id)::uuid,
  sqlc.arg(operation_kind)::text::ldap_directory_operation_kind,
  sqlc.arg(reason)::text,
  sqlc.arg(audit_event_id)::uuid,
  sqlc.arg(request_id)::uuid,
  sqlc.arg(correlation_id)::uuid,
  sqlc.arg(ip_address)::inet,
  nullif(sqlc.arg(user_agent)::text, ''),
  sqlc.arg(authentication_method)::text
) AS snapshot;

-- name: BeginTenantLDAPMappingDryRun :one
SELECT snapshot.operation_run_id::uuid AS operation_run_id,
       snapshot.tenant_id::uuid AS tenant_id,
       snapshot.provider_id::uuid AS provider_id,
       snapshot.provider_version::integer AS provider_version,
       snapshot.configuration_version::integer AS configuration_version,
       snapshot.endpoint_snapshot_digest::bytea AS endpoint_snapshot_digest,
       snapshot.configuration::jsonb AS configuration,
       snapshot.endpoints::jsonb AS endpoints,
       snapshot.bind_secret_id::uuid AS bind_secret_id,
       snapshot.bind_secret_ciphertext::bytea AS bind_secret_ciphertext,
       snapshot.bind_secret_nonce::bytea AS bind_secret_nonce,
       snapshot.bind_secret_version::integer AS bind_secret_version,
       snapshot.bind_secret_key_version::integer AS bind_secret_key_version,
       snapshot.bind_secret_algorithm::text AS bind_secret_algorithm,
       snapshot.binding_id::uuid AS binding_id,
       snapshot.binding_version::integer AS binding_version,
       snapshot.binding_auth_revision::integer AS binding_auth_revision,
       snapshot.binding_access_epoch_id::uuid AS binding_access_epoch_id,
       snapshot.rule_set_revision::bigint AS rule_set_revision,
       snapshot.authorization_revision::bigint AS authorization_revision,
       snapshot.mapping_revisions::jsonb AS mapping_revisions,
       snapshot.started_at::timestamptz AS started_at,
       snapshot.expires_at::timestamptz AS expires_at
FROM app.begin_tenant_ldap_mapping_dry_run_v1(
  sqlc.arg(operation_run_id)::uuid,
  sqlc.arg(binding_id)::uuid,
  sqlc.arg(include_disabled_mapping_ids)::uuid[],
  sqlc.arg(reason)::text,
  sqlc.arg(audit_event_id)::uuid,
  sqlc.arg(request_id)::uuid,
  sqlc.arg(correlation_id)::uuid,
  sqlc.arg(ip_address)::inet,
  nullif(sqlc.arg(user_agent)::text, ''),
  sqlc.arg(authentication_method)::text
) AS snapshot;

-- name: GetTenantLDAPMappingDryRunPlanningSnapshot :one
SELECT snapshot.operation_run_id::uuid AS operation_run_id,
       snapshot.tenant_id::uuid AS tenant_id,
       snapshot.provider_id::uuid AS provider_id,
       snapshot.provider_version::integer AS provider_version,
       snapshot.binding_id::uuid AS binding_id,
       snapshot.binding_version::integer AS binding_version,
       snapshot.binding_auth_revision::integer AS binding_auth_revision,
       snapshot.binding_access_epoch_id::uuid AS binding_access_epoch_id,
       snapshot.configuration_revision::integer AS configuration_revision,
       snapshot.rule_set_revision::bigint AS rule_set_revision,
       snapshot.authorization_revision::bigint AS authorization_revision,
       snapshot.jit_mode::text AS jit_mode,
       snapshot.no_match_policy::text AS no_match_policy,
       snapshot.effective_until::timestamptz AS effective_until,
       snapshot.provider_access_source_id::uuid AS provider_access_source_id,
       snapshot.provider_access_epoch_id::uuid AS provider_access_epoch_id,
       snapshot.external_identity_id::uuid AS external_identity_id,
       snapshot.user_id::uuid AS user_id,
       snapshot.membership_id::uuid AS membership_id,
       snapshot.external_identity_exists::boolean AS external_identity_exists,
       snapshot.user_active::boolean AS user_active,
       snapshot.tenant_membership_exists::boolean AS tenant_membership_exists,
       snapshot.tenant_membership_active::boolean AS tenant_membership_active,
       snapshot.access_grant_live::boolean AS access_grant_live,
       snapshot.rules::jsonb AS rules,
       snapshot.security_groups::jsonb AS security_groups,
       snapshot.live_assignments::jsonb AS live_assignments,
       snapshot.role_policies::jsonb AS role_policies,
       snapshot.existing_effective_role_ids::uuid[] AS existing_effective_role_ids,
       snapshot.delegation::jsonb AS delegation,
       snapshot.live_owned_edges::jsonb AS live_owned_edges
FROM app.get_tenant_ldap_dry_run_planning_snapshot_v1(
  sqlc.arg(operation_run_id)::uuid,
  sqlc.arg(digest_key_versions)::integer[],
  sqlc.arg(subject_digests)::bytea[]
) AS snapshot;

-- name: CompleteTenantLDAPDirectoryInspection :one
SELECT result.operation_run_id::uuid AS operation_run_id,
       result.outcome::text AS outcome,
       result.category::text AS category,
       coalesce(result.endpoint_priority, 0)::integer AS endpoint_priority,
       result.duration_ms::integer AS duration_ms,
       result.matched_entry_count::integer AS matched_entry_count,
       result.truncated::boolean AS truncated,
       result.stale::boolean AS stale,
       result.completed_at::timestamptz AS completed_at
FROM app.complete_tenant_ldap_directory_operation_v1(
  sqlc.arg(operation_run_id)::uuid,
  sqlc.arg(reported_outcome)::text::ldap_provider_test_outcome,
  sqlc.arg(reported_category)::text::ldap_provider_test_category,
  sqlc.narg(endpoint_priority)::integer,
  sqlc.arg(duration_ms)::integer,
  sqlc.arg(matched_entry_count)::integer,
  sqlc.arg(truncated)::boolean,
  sqlc.arg(audit_event_id)::uuid,
  sqlc.arg(request_id)::uuid,
  sqlc.arg(correlation_id)::uuid,
  sqlc.arg(ip_address)::inet,
  nullif(sqlc.arg(user_agent)::text, ''),
  sqlc.arg(authentication_method)::text
) AS result;
